fix(k8s): fix some issues with KinD and add integ test
garden-io/garden pull request #1751
Opened 2020-03-30 11:14 UTC by edvald

**What this PR does / why we need it**:

Found a few issues when setting up and using KinD. For one, installing nginx was not working, and some things needed explanation in the docs. 

Plus I've been wanting to set up an integ test for a while, having a crack at that now.

2020-03-31 04:06 UTC, eysi09 commented on garden-service/src/plugins/kubernetes/local/config.ts
> +const supportedContexts = ["docker-for-desktop", "docker-desktop", "microk8s", "minikube", "kind-kind"]
Is there a better way around this? The order of preference feels very arbitrary. At the very least it feels like we should log it at the `info` level if there are multiple supported contexts found and Garden picks the first one. You can e.g. have multiple `kind` contexts. 

See also this issue: https://github.com/garden-io/garden/issues/1708

This issue acknowledges that it's not easy to get around this so perhaps logging and documenting this is our best bet for now.

2020-03-31 04:09 UTC, eysi09 commented on garden-service/src/plugins/kubernetes/local/config.ts
> +  return supportedContexts.includes(context) || context.startsWith("kind-")
Same for this one. Users can easily rename their contexts and it isn't super obvious that this is what Garden is doing. Perhaps we could include this in the docs for these tools. For example that Garden expects Kind contexts to begin with `kind-` and that it'll pick the first one it finds.

2020-03-31 04:14 UTC, eysi09 commented on garden-service/src/plugins/kubernetes/local/config.ts
> +const supportedContexts = ["docker-for-desktop", "docker-desktop", "microk8s", "minikube", "kind-kind"]
One simple idea for teams with different local clusters (and that can't depend on the order of contexts above) would be to just use local env vars: `context: ${local.env.LOCAL_CONTEXT}`  or similar. Perhaps we could document that as a workaround.

2020-03-31 04:16 UTC, eysi09 commented on garden-service/src/plugins/kubernetes/local/config.ts
>  import { isClusterKind } from "./kind"
Not part of the PR per se but it would be nice to refactor the `configureProvider` function at some point. A lot of ifs and buts.

2020-03-31 04:17 UTC, eysi09 commented on garden-service/src/plugins/kubernetes/local/config.ts
> +      remove(_systemServices, (s) => nginxServices.includes(s))
Would it make sense to refactor this into its own function since it's used in three places?

2020-04-04 13:04 UTC, edvald commented on garden-service/src/plugins/kubernetes/local/config.ts
> +      remove(_systemServices, (s) => nginxServices.includes(s))
I don't think it matters tbh.

2020-04-04 13:06 UTC, edvald commented on garden-service/src/plugins/kubernetes/local/config.ts
> +const supportedContexts = ["docker-for-desktop", "docker-desktop", "microk8s", "minikube", "kind-kind"]
Yes, I actually put in a TODO the code below. Thing is, any behavior change we make here is essentially a breaking change. So all I did here was to augment the behavior to explicitly account for kind, with a mind to address this better in a breaking release.

Agreed on documentation though, perhaps coupled with making the `clusterType` config variable public and documented.

2020-04-07 04:12 UTC, eysi09 commented
LGTM. Notice that the integ test is failing and the PR is still flagged as WIP.

2021-01-18 12:01 UTC, edvald commented
@eysi09 this is now good to go.

2021-02-03 12:27 UTC, thsig requested changes
Noticed a typo there, otherwise I think this is good to go.

2021-02-03 12:27 UTC, thsig commented on docs/guides/local-kubernetes.md
> +For kind installation instruction, see the [official docs](https://kind.sigs.k8s.io/docs/user/quick-start/).
"instruction" -> "instructions"

2021-02-03 15:57 UTC, edvald commented
Rebased and updated @thsig

2021-02-03 17:28 UTC, thsig approved these changes

2021-02-03 22:37 UTC, merged