feat(dashboard): add octant provider and dashboard integration
garden-io/garden pull request #2006
Opened 2020-08-14 15:31 UTC by edvald

**What this PR does / why we need it**:

This adds an `octant` provider, that you can drop into any Garden
project that includes a `kubernetes`/`local-kubernetes` provider:

```
...
providers
  - name: octant
...
```

This will add an Octant tab to your dashboard, which will be loaded
on-demand, pointed at the context and namespace of your project.
You also get a `garden tools octant` command if you'd like to run it
standalone.

Most of the work in the PR is to do with the mechanism for providers to
add dashboard pages, which is now easy to do and can be done in a
dynamic fashion.

I also added a toggle for provider tools, to indicate whether they
should be pre-fetched as part of our container builds.

**Special notes for your reviewer**:

Please test the dashboard itself, see if it all works as expected.

2020-08-19 14:50 UTC, eysi09 requested changes
Had a few question / comments, otherwise looks good.

2020-08-19 14:50 UTC, eysi09 commented on core/src/commands/util/fetch-tools.ts
> +  "prefetch-only": new BooleanParameter({
Wouldn't `--only-prefetch` be more idiomatic?

I actually think either option name is a little confusing in this context (although it's mainly used internally). I would expect `garden util fetch-tools --all` to basically prefetch tools, so it's not clear what `--prefetch-only | --only-prefetch` adds to it.

Can we think of a better flag than `prefetch=true` for these tools? Perhaps `builtIn`? Or something more explicit like `includeInImage` / `addToImage` (or some version of that).

2020-08-19 14:50 UTC, eysi09 commented on core/src/plugins/octant/octant.ts
> +            !resolved && reject(err)
Why do we need to check for `!resolved` here?

2020-08-19 14:50 UTC, eysi09 commented on core/src/config-store.ts
> +  linkedModuleSources: () => joiArray(linkedSourceSchema()),
Why are we making the value a function?

2020-08-19 14:50 UTC, eysi09 commented on core/test/unit/src/server/server.ts
> +    // await request(server)
Should this be commented out?

2020-08-19 14:50 UTC, eysi09 commented on dashboard/src/api/actions.ts
> +    draft.environmentStatuses = status.providers
Why this change?

2020-08-19 14:50 UTC, eysi09 commented on dashboard/src/components/provider.tsx
> +class ProviderPageFrame extends React.Component<ProviderPageProps, ProviderPageState> {
Any reason you didn't go for a functional component here? It would probably be a bit simpler and more consistent with the rest of the components.

2020-08-19 14:50 UTC, eysi09 commented on dashboard/src/components/provider.tsx
> +    this.state = {
For some reason the spinner isn't visible when fetching Octant, during the very first load which is also the longest one.

2020-08-19 14:59 UTC, edvald commented on core/src/plugins/octant/octant.ts
> +            !resolved && reject(err)
It's possible that the proc emits an error after the promise is resolved, in which case calling reject is basically an error.

2020-08-19 15:02 UTC, edvald commented on core/src/commands/util/fetch-tools.ts
> +  "prefetch-only": new BooleanParameter({
Yeah I don't feel strongly about this. It's _only_ used internally and is hidden from any docs. The flag will also not be a part of any external APIs. That said, it's fine to rename them for clarity, make it a little more verbose and obvious.

2020-08-19 15:03 UTC, edvald commented on core/src/config-store.ts
> +  linkedModuleSources: () => joiArray(linkedSourceSchema()),
To avoid circular import issues, which tend to come up if the values are resolved at module resolution time. Most schemas are now defined like this, and otherwise I tend to fix it if I come across it.

2020-08-19 15:03 UTC, edvald commented on core/test/unit/src/server/server.ts
> +    // await request(server)
Nope, will fix.

2020-08-19 15:07 UTC, edvald commented on dashboard/src/components/provider.tsx
> +class ProviderPageFrame extends React.Component<ProviderPageProps, ProviderPageState> {
Yes. I could not find a way to make functional components persist, i.e. not unmount, on route change. The slight added complexity means that the iframe is hidden/shown on route changes after it's first created.

2020-08-19 15:08 UTC, edvald commented on dashboard/src/components/provider.tsx
> +    this.state = {
Hmm. But only in that specific first case?

2020-08-19 15:16 UTC, edvald commented on core/src/commands/util/fetch-tools.ts
> +  "prefetch-only": new BooleanParameter({
Changed in added TBS commit

2020-08-19 15:30 UTC, eysi09 commented on dashboard/src/components/provider.tsx
> +    this.state = {
I'd guess it's because we're not mounting this component until the API call returns. And it's only really noticeable if Garden has to actually fetch the tool as part of the API call.

2020-08-19 15:31 UTC, eysi09 commented on dashboard/src/components/provider.tsx
> +class ProviderPageFrame extends React.Component<ProviderPageProps, ProviderPageState> {
Hmm ok.

2020-08-19 15:33 UTC, edvald commented on dashboard/src/components/provider.tsx
> +class ProviderPageFrame extends React.Component<ProviderPageProps, ProviderPageState> {
Maybe I'm out of my depth here in React land, open to a different solution if you have one.

2020-08-19 15:34 UTC, eysi09 commented on dashboard/src/api/actions.ts
> +    draft.environmentStatuses = status.providers
Ok makes sense. So it was basically broken before since we were overriding the providers with environment statuses. But doesn't appear to be used anywhere.

2020-08-19 15:36 UTC, eysi09 commented on dashboard/src/components/provider.tsx
> +  // componentDidUpdate(prevProps, prevState) {
Also forgot mention this in my first pass. Do we need that?

2020-08-19 15:37 UTC, eysi09 commented on dashboard/src/components/provider.tsx
> +class ProviderPageFrame extends React.Component<ProviderPageProps, ProviderPageState> {
This is fine IMO. But perhaps add a comment explaining why, so some wise-guy/gal won't come along and refactor this to a functional component.

2020-08-19 15:41 UTC, edvald commented on dashboard/src/components/provider.tsx
> +    this.state = {
Gotcha. I can take another look, and test it with a sleep to make sure it works as expected.

2020-08-19 15:41 UTC, edvald commented on dashboard/src/components/provider.tsx
> +  // componentDidUpdate(prevProps, prevState) {
Nope, just needs a cleanup.

2020-08-19 16:04 UTC, edvald commented on dashboard/src/components/provider.tsx
> +    this.state = {
> I'd guess it's because we're not mounting this component until the API call returns.

That's not correct though. We mount the component immediately, the iframe just gets the URL that eventually redirects (no separate API call performed), in this particular case after the octant tool is fetched. 

And it looks to work fine for me, I get the pink spinner immediately 🤷‍♂️. Can you give another... _spin_?

2020-08-19 16:06 UTC, edvald commented on dashboard/src/api/actions.ts
> +    draft.environmentStatuses = status.providers
I think it worked as it was, but we have since moved the `dashboardPages` key from the environment status to the provider definition. And yeah I suppose it's no longer used then, but I'm quite sure we will have some use for this later, so I'll just leave it.

2020-08-19 16:16 UTC, edvald commented on dashboard/src/components/provider.tsx
> +class ProviderPageFrame extends React.Component<ProviderPageProps, ProviderPageState> {
Turns out I could use a function component. Indeed, much more elegant. The problem I previously had turned out to be solved in the router setup. See the updated TBS commit.

2020-08-19 18:12 UTC, eysi09 commented on dashboard/src/components/provider.tsx
> +    this.state = {
Hehe. But yeah ok, this only happens if you navigate to the Octant tab from another tab. So if I go straight to the Octant page via `/providers/octant` I see this spinner. But if I start at the Overview page and navigate my way towards the Octant page, I don't see the spinner.

2020-08-19 21:02 UTC, edvald commented on dashboard/src/components/provider.tsx
> +    this.state = {
For whatever reason, I don't get the same result :/ Works in either case for me.

2020-08-20 10:26 UTC, edvald commented on dashboard/src/components/provider.tsx
> +    this.state = {
Updated with your suggested fix. Can you give it a ~spin~ another go to confirm that it works?

2020-08-20 11:50 UTC, eysi09 commented on dashboard/src/components/provider.tsx
> +    this.state = {
Works now. But boy, did we have to go round and round on this one.

2020-08-20 11:50 UTC, eysi09 approved these changes

2020-08-20 12:00 UTC, merged