feat(container): add deployment-image-id module output key
garden-io/garden pull request #2031
Opened 2020-09-02 10:06 UTC by edvald

Adding a new `deployment-image-id` module output key, as well as a 
corresponding `local-image-id` key.

This will seem like a large commit for a small feature, but this
involved adding a new plugin handler to allow referencing the module
version in module outputs, which was previously not possible.

We add a new getModuleOutputs plugin handler, and no longer return
outputs in the configureModule handler.

2020-09-04 08:00 UTC, eysi09 commented
First question, what do we need this for?

2020-09-04 08:53 UTC, edvald commented on docs/using-garden/variables-and-templating.md
> +  image: `${modules.my-image.outputs.deployment-image-id}`
Here's a good example of why this is useful.

That aside, we'll need to the added flexibility with respect to module outputs for some upcoming features, in particular relating to custom container builders.

2020-09-04 10:42 UTC, eysi09 commented on docs/using-garden/variables-and-templating.md
> +  image: `${modules.my-image.outputs.deployment-image-id}`
Yeah I figured that workaround above was acceptable if a little ugly. Didn't realise we had upcoming features depending on this.

2020-09-04 10:47 UTC, edvald commented on docs/using-garden/variables-and-templating.md
> +  image: `${modules.my-image.outputs.deployment-image-id}`
Just to elaborate a little, what I'm doing is defining a standard `oci-image` interface (and starting with a `docker-image` module implementation of that interface), and for that it's quite clumsy to not have these added fields as part of the interface. Different implementations may choose different ways to tag images, so we'd quickly run into interoperability problems.

2020-09-08 11:21 UTC, thsig requested changes
Looks good! Only had a couple of minor comments there.

2020-09-08 11:52 UTC, edvald commented on core/src/config/module.ts
> +  kind?: "Module"
Yeah. Otherwise we'd have broken a huge number of type checks, mostly in tests. The value is redundant basically, we just want to allow for it to be specified, but there isn't a good reason to require it to be set.

2020-09-08 11:53 UTC, edvald commented on core/src/plugins/container/container.ts
> +          const deploymentImageName = await containerHelpers.getDeploymentImageName(moduleConfig, undefined)
That could be true. Probably used to be necessary but no longer after a refactor. Could change it now that we're poking at this code anyway.

2020-09-08 11:53 UTC, edvald commented on core/src/config/config-context.ts
>    public version: string | undefined
Yeah I think so

2020-09-08 11:55 UTC, thsig commented on core/src/config/module.ts
> +  kind?: "Module"
Ok, gotcha.

2020-09-08 12:59 UTC, edvald commented on core/src/plugins/container/container.ts
> +          const deploymentImageName = await containerHelpers.getDeploymentImageName(moduleConfig, undefined)
Updated.

2020-09-08 13:02 UTC, thsig approved these changes

2020-09-08 18:29 UTC, merged