fix(k8s): handle undefined properly
garden-io/garden pull request #2036
Opened 2020-09-04 09:14 UTC by solomonope

**What this PR does / why we need it**:
When we have environment variables  in nature below 
```
VAULT_APPROLE_SECRET_ID: ${var.vault-approle-secret-id}?
VAULT_APPROLE_ROLE_ID: ${var.vault-approle-role-id}?
```
They are conditional and can be `undefined`, `null` check involving `===` does not handle the case of it being `undefined`

This PR adds an explicit `undefined` check
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2020-09-04 10:02 UTC, edvald requested changes

2020-09-04 10:02 UTC, edvald commented on core/src/plugins/kubernetes/util.ts
> +    if (value === null || value === undefined) {
Good catch! But I'd prefer to do this differently, by basically filtering out undefined values in the object, instead of implicitly casting to null. So basically adding a `.filter(...)` before the `.map(...)` instead.

2020-09-04 10:03 UTC, edvald commented on core/src/plugins/kubernetes/util.ts
> +    if (value === null || value === undefined) {
I'd also suggest updating the commit message accordingly :)

2020-09-04 13:04 UTC, solomonope commented on core/src/plugins/kubernetes/util.ts
> +    if (value === null || value === undefined) {
I have done the update

2020-09-07 15:49 UTC, edvald approved these changes

2020-09-07 16:32 UTC, merged