feat(cli): add `get module(s)` command
garden-io/garden pull request #2046
Opened 2020-09-09 11:52 UTC by edvald

Closes #2038

2020-09-09 14:46 UTC, thsig requested changes
Looks good! Only had one comment (relating to the docstrings and generated docs).

2020-09-09 14:46 UTC, thsig commented on core/src/commands/get/get-modules.ts
> +    Examples:
The examples string should be put under the `description` field (e.g. to avoid cluttering up the subcommand listing that shows up when you run `garden get`).

2020-09-09 14:46 UTC, edvald commented on core/src/commands/get/get-modules.ts
> +    Examples:
Ah yes, will fix.

2020-09-09 14:49 UTC, edvald commented on core/src/commands/get/get-modules.ts
> +    Examples:
Fixed

2020-09-09 15:36 UTC, merged

2020-09-11 13:38 UTC, lucas-sonnabend commented
Thanks a lot for the quick turnaround!