Bundles (Module Templates)
garden-io/garden pull request #2089
Opened 2020-10-02 16:29 UTC by edvald

Here's an incomplete draft of a new feature, submitted for early review and feedback. From the added docs:

> You can create customized templates for modules or sets of modules, called _bundles_. These templates allow you to define your own schemas and abstractions, that are then translated at runtime to one or more modules, even including any supporting files (such as Kubernetes manifests, common configuration files, Dockerfiles etc.).
> 
> This provides a powerful yet easy-to-use mechanism to tailor Garden's functionality to your needs, improve governance, reduce boilerplate, and to provide higher-level abstractions to application developers.
> 
> These templates can be defined within a project, or in a separate repository that can be shared across multiple projects (using remote sources).

2020-10-06 16:27 UTC, thsig requested changes
Looks great! Had a few minor comments / suggestions.

2020-10-06 16:27 UTC, thsig commented on core/src/garden.ts
>          Bluebird.map(rawModuleConfigs, async (config) => this.addModuleConfig(config)),
How about including the source bundle template name in the error message for duplicate module names (in `addModuleConfig` below)? Might help users pinpoint the problem in their config more quickly.

Then again, it might already be obvious enough from the generated module path.

Just a thought.

2020-10-07 17:35 UTC, edvald commented on core/src/garden.ts
>          Bluebird.map(rawModuleConfigs, async (config) => this.addModuleConfig(config)),
Fair point, but I think it's clear enough from the config paths

2020-10-08 08:02 UTC, thsig approved these changes

2020-10-08 13:47 UTC, merged