feat(k8s): enable hot reloading for kubernetes modules
garden-io/garden pull request #2099
Opened 2020-10-08 18:34 UTC by eysi09

**What this PR does / why we need it**:

Enables hot reloading for the `kubernetes-module` module type.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

I lumped the hot reload handler for the `kubernetes-module` and for the `helm` module into a single handler and as result had to move some files around. Concretely, we now have all the K8s related hot reload logic in `kubernetes/hot-reload/hot-reload.ts` and `kubernetes/hot-reload/hot-reload.ts` instead of being split up between module types.

2020-10-08 18:36 UTC, eysi09 commented on core/src/plugins/kubernetes/kubernetes-module/handlers.ts
> -    await waitForResources({
This was being called after applying namespaces, again here, and finally once more below, for good measure I suppose.

Now it's only called once after all the `apply` calls. Does that make sense or where we doing all the waiting for resources for a reason?

2020-10-08 18:39 UTC, eysi09 commented on core/test/integ/src/plugins/kubernetes/hot-reload.ts
>  describe("getHotReloadSpec", () => {
This tests the functions in `kubernetes/hot-reload` for the a helm module. I could duplicate them for a K8s module but the code paths are almost identical so I figured it wasn't needed.

2020-10-12 19:10 UTC, thsig requested changes
Looks good! Only had a couple of minor comments.

2020-10-12 19:10 UTC, thsig commented on core/test/setup.ts
> +  // console.log(getDefaultProfiler().report())
Remove comment.

2020-10-12 19:10 UTC, thsig commented on examples/hot-reload/README.md
> +---
Just curious—is there a reason we're changing from `...` to `---` here to indicate "more above/below"?

2020-10-12 20:32 UTC, eysi09 commented on examples/hot-reload/README.md
> +---
Nope, not sure how that happened. I'll revert it.

2020-10-12 20:34 UTC, eysi09 commented on core/src/plugins/kubernetes/kubernetes-module/handlers.ts
> -    await waitForResources({
Could I get a second opinion from @edvald on this one? In the previous implementation we had three `waitForResources` calls, was that just a mistake? I removed two of them but just want to make sure I'm not missing something.

2020-10-13 06:39 UTC, thsig commented on core/src/plugins/kubernetes/kubernetes-module/handlers.ts
> -    await waitForResources({
Ah, this one slipped past me. It was a bit late when I read through it.

The thing is, the non-namespace resources could very well belong inside the namespaces being created. So we should be waiting for the namespaces to be up first (like we were doing before this change), to ensure that the namespaces exist before applying the non-namespace resources.

The third `waitForResources` call was probably unnecessary though. I think it's a leftover from this PR: https://github.com/garden-io/garden/pull/1942/files.

2020-10-13 06:46 UTC, thsig commented on core/src/plugins/kubernetes/kubernetes-module/handlers.ts
> -    await waitForResources({
One other question: Have we verified that deploying a `kubernetes` service with/without hot reloading and then redeploying it with the opposite setting (without/with hot reloading) results in a redeploy, as expected?

2020-10-13 09:28 UTC, eysi09 commented on examples/hot-reload/README.md
> +---
...I think this was my YAML formatter fixing it on autosave.

2020-10-13 09:42 UTC, eysi09 commented
@thsig, I addressed the PR comments in a separate commit.

2020-10-13 09:45 UTC, eysi09 commented on core/src/plugins/kubernetes/kubernetes-module/handlers.ts
> -    await waitForResources({
Good catch! It does not. How are we doing this for Helm?

2020-10-14 11:31 UTC, eysi09 commented
@thsig, I've addressed the issue with redeploys not working in a new commit on top of the others.

2020-10-14 11:38 UTC, thsig approved these changes

2020-10-14 16:48 UTC, merged