fix(core): create artifact placeholder in a world-readable place
garden-io/garden pull request #2105
Opened 2020-10-13 08:52 UTC by wyrie

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2020-10-14 12:36 UTC, edvald requested changes

2020-10-14 12:36 UTC, edvald commented on core/src/plugins/kubernetes/run.ts
> +                command: ["sh", "-c", "cd /tmp && touch .DS_Store && " + tarCmd.join(" ")],
This approach should work, but you do need to `cd` back to the root before the tar command. After that it should be fine, as far as I can tell.

2020-10-14 12:46 UTC, edvald commented on core/src/plugins/kubernetes/run.ts
> +                command: ["sh", "-c", "cd /tmp && touch .DS_Store && " + tarCmd.join(" ")],
Or just change it to `touch /tmp/.DS_Store`. I'll later modify the code to make it a bit more obvious what's going on there, instead of using this particular filename that might be a source of confusion.

2020-10-15 09:17 UTC, wyrie commented on core/src/plugins/kubernetes/run.ts
> +                command: ["sh", "-c", "cd /tmp && touch .DS_Store && " + tarCmd.join(" ")],
That works now, thanks.

2020-10-15 09:21 UTC, wyrie reviewed
https://github.com/garden-io/garden/pull/2105/commits/ee236aa75114ccee159e7bd6325b6cea7529425d

2020-10-19 15:49 UTC, edvald approved these changes

2020-10-19 15:49 UTC, merged