fix(core): prohibit templates in workflow name
garden-io/garden pull request #2158
Opened 2020-12-01 09:51 UTC by thsig

**What this PR does / why we need it**:

We don't want to allow template strings in workflow names or trigger specs.

2020-12-03 12:08 UTC, eysi09 approved these changes

2020-12-03 12:08 UTC, eysi09 commented on core/src/config/workflow.ts
> +  // {
Remove comment?

2020-12-03 12:09 UTC, eysi09 requested changes
One comment, otherwise looks good.

2020-12-10 10:51 UTC, thsig commented on core/src/config/workflow.ts
> +  // {
Done!

2020-12-11 10:42 UTC, eysi09 approved these changes

2020-12-11 10:42 UTC, merged