docs(faq): update section on out-of-scope Dockerfiles
garden-io/garden pull request #2230
Opened 2021-01-25 21:11 UTC by eysi09

**What this PR does / why we need it**:

Update FAQ question on out-of-scope Dockerfiles.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-02-03 23:06 UTC, edvald requested changes

2021-02-03 23:06 UTC, edvald commented on docs/misc/faq.md
> +If you go for this approach, you might want to set `GARDEN_EXPERIMENTAL_BUILD_STAGE=true`. This will become the default behaviour in a future release and speeds up build staging for projects structur
We just merged a change that makes this the default, so we can remove this. Besides that, LGTM 👍

2021-02-07 13:42 UTC, eysi09 commented on docs/misc/faq.md
> +If you go for this approach, you might want to set `GARDEN_EXPERIMENTAL_BUILD_STAGE=true`. This will become the default behaviour in a future release and speeds up build staging for projects structur
I've updated the PR.

2021-02-07 22:55 UTC, edvald approved these changes

2021-02-07 22:55 UTC, merged