test(workflows): add workflow smoke-test in pre-release script
garden-io/garden pull request #2232
Opened 2021-01-29 15:38 UTC by 10ko

**What this PR does / why we need it**:
Add a sanity check for the `run workflow` command in order to avoid future regressions.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-01-29 15:49 UTC, edvald commented
Ugh, I think GitBook messed up our docs folder (again). I can fix that.

2021-01-29 15:50 UTC, 10ko commented
Uh, I was wondering what was the issue. Thanks @edvald

2021-01-29 15:52 UTC, thsig commented
Looks good to me, do you have any comments @edvald?

The main point is to test the "outer" part, the CLI/command init etc. (similarly to how we're testing the other commands here), and for that, I think the test case is sufficient as written.

The unit tests should cover the details of the command's execution pretty well.

2021-01-29 15:56 UTC, edvald commented
It occurs to me that we should do this in a specific testing project, outside of our example projects. Either that or make the workflow somehow more organically included in the example, it's kinda just lumped in there without a purpose or further explanation at the moment, which we could address in the example README or comments in the added workflow config.

2021-01-29 16:11 UTC, 10ko commented
Makes sense, I will make some changes to make it look more "useful" under that example and add a bit of explanation in the README of the project.
The reason is there is because we use this project in demos and it would have been handy to have an example of a workflow.

2021-02-03 10:31 UTC, thsig submitted a review, later dismissed

2021-02-03 15:38 UTC, 10ko commented
Added few lines to the README of the example, made the workflow a "full-test" and fixed the `clear-db` task which was broken.

2021-02-03 16:05 UTC, edvald requested changes
Super minor stuff, mostly just the db-init step that felt superfluous.

2021-02-03 16:05 UTC, edvald commented on examples/vote/workflows.garden.yml
> +  - command: [run, task, db-init]
This task is implicitly run in the test command, so that seems sorta superfluous. But it makes sense to clear the db after.

2021-02-03 16:05 UTC, edvald commented on examples/vote/workflows.garden.yml
> +  - script: echo "Greetings $USER, your full-test script run succesfully."
Could use `${local.username}` just to illustrate the templating, just a thought.

2021-02-03 16:05 UTC, edvald commented on examples/vote/README.md
> +This example includes a usage example for Garden workflows. The `workflows.garden.yml` file contains the configuration for a sample workflow called `full-test` which initilizes the `db`, runs the tes
"initilizes" -> "initializes"
"cleanups at the end" -> "and cleans up the database afterwards"

2021-02-03 21:29 UTC, 10ko commented
Thanks @edvald, addressed all the last requests.

2021-02-03 23:20 UTC, edvald approved these changes

2021-02-04 09:55 UTC, merged