feat(workflows): only resolve config being run
garden-io/garden pull request #2345
Opened 2021-04-14 07:53 UTC by thsig

**What this PR does / why we need it**:

In the `run workflow` command, we now only resolve the workflow config being run.

This adds flexibility when some workflows reference e.g. secrets that are created by other workflows.

2021-04-16 08:32 UTC, thsig commented
This should be good to go now (the `validate` command resolves all workflow configs).

2021-04-19 19:10 UTC, eysi09 requested changes
A test is being skipped, otherwise looks good.

2021-04-19 19:10 UTC, eysi09 commented on core/test/unit/src/garden.ts
> +    it.skip("should throw an error if an invalid workflow config is present", async () => {
Did you forget this?

2021-04-20 09:01 UTC, thsig commented on core/test/unit/src/garden.ts
> +    it.skip("should throw an error if an invalid workflow config is present", async () => {
No, actually—we don't want to throw an error here if an invalid workflow config is present (since that would imply resolving all workflow configs during the scan).

I've removed this test case now, that should be clearer.

2021-04-21 17:55 UTC, eysi09 approved these changes

2021-04-22 07:25 UTC, merged