feat(template): add liveness and readiness timeout definitions for co…
garden-io/garden pull request #2364
Opened 2021-04-26 11:56 UTC by tvollstaedt

**What this PR does / why we need it**:

The `container` module abstracts many kubernetes internals by providing a simple template syntax. It allows to define health checks to make sure our service are in a proper state when deployed. Garden sets sensible defaults for timeout values for those health checks. 
However, sometimes it may be necessary to adjust these timeouts because services need more time for initial startup or similar. It's currently not possible to adjust these values within the container module, one would need to switch over to the `kubernetes`-module to gain full control over deployment, but also has to have deeper knowledge about Kubernetes for that.

This PR adds control over liveness and readiness timouts through templating to avoid the mentioned workaround.

2021-04-26 13:44 UTC, thsig requested changes
Many thanks for the contribution here! Had a couple of minor comments.

Once we've addressed those squashed everything into one commit, we should be ready to merge this.

2021-04-26 13:44 UTC, thsig commented on core/src/plugins/container/config.ts
> +      readinessTimeout: joi
Let's rename these to `readinessTimeoutSeconds` and `livenessTimeoutSeconds`, just to be extra obvious to the end-user.

2021-04-26 13:44 UTC, thsig commented on core/src/plugins/container/config.ts
> +        .description("The maximum amount of seconds to wait until the readiness check counts as failed."),
"amount of" -> "number of"

2021-04-26 14:36 UTC, tvollstaedt commented
Not quite sure what happened to the docs, just re-ran the script 😨

2021-04-26 19:36 UTC, tvollstaedt commented
Should be ready now.

2021-04-28 07:52 UTC, tvollstaedt commented
@thsig Is there anything else you would like me to change?

2021-05-03 11:52 UTC, thsig approved these changes

2021-05-04 08:35 UTC, merged