improvement(k8s): get rid of NFS when using kaniko build mode
garden-io/garden pull request #2372
Opened 2021-05-03 23:06 UTC by edvald

I'm sure this'll be a big relief for many users. This is a drop-in upgrade that removes the need for NFS, `build-sync` and other cluster-wide services when using the `kaniko` build mode.

Additionally, users can set `kaniko.namespace: null` in their `kubernetes` provider configs to run the Kaniko pods in the project namespace instead of `garden-system`, which will be helpful in scenarios where it's problematic to allow users to run pods in a shared namespace.

It's also no longer necessary to run `garden plugins kubernetes cluster-init` when using Kaniko, except to install unrelated services (like an ingress controller etc.).

I've updated the documentation and examples to default to Kaniko, and updated the in-cluster building guide and recommendations therein to reflect the changes.

2021-05-04 09:08 UTC, edvald commented
Looking at the failing tests, will ping you once it's cleaned up @thsig

2021-05-04 09:17 UTC, thsig commented
Cool, thanks!

2021-05-04 09:43 UTC, eysi09 commented
Just out of curiosity, is there a trade-off here? Like, was there any particular benefit to NFS to begin with that we'll now need to do without it?

2021-05-04 09:58 UTC, edvald commented
Good question. There is a slight efficiency loss in that the build context does need to be copied to the Kaniko Pod, instead of just mounted. But I think that's outweighed by the operational simplicity and the instability (and sometimes slow performance) of NFS.

The reason NFS was picked in the first place was for performance but at the time we didn't suspect it would have the myriad operational issues we've found along the way.

2021-05-04 11:04 UTC, thsig requested changes
Looks good! Only had a few text-related comments.

2021-05-04 11:04 UTC, thsig commented on docs/guides/in-cluster-building.md
> +Generally we recommend picking either `kaniko` or `cluster-buildkit`, based on your usage patterns and scalability requirements. For ephemeral namespaces, `kaniko` is generally the better option, sin
"long-running namespaces" -> "long-lived namespaces"

2021-05-04 14:08 UTC, edvald commented
Running into issues with CI atm (not related to this PR), but this should be all set for final review.

2021-05-04 14:34 UTC, edvald commented
Actually I have found one legitimate issue, with different Kaniko build flows stepping over each other in shared namespaces. I'll need to fix that before we wrap this up.

2021-05-05 16:25 UTC, edvald commented
@thsig this should be all good to go now. I'd suggest doing a second code review, since I had to shuffle a couple of things around.

2021-05-12 12:59 UTC, thsig requested changes
Looks good! Had a couple of minor comments there.

2021-05-12 12:59 UTC, thsig commented on core/src/plugins/kubernetes/container/build/buildkit.ts
> +        await sleep(5)
Is 5ms enough here? Or was this meant to be 5 seconds?

2021-05-12 12:59 UTC, thsig commented on core/src/plugins/kubernetes/container/build/kaniko.ts
> +    remove: false, // TODO
Should this be left here as is?

2021-05-12 13:52 UTC, edvald commented
@thsig comments resolved!

2021-05-12 13:57 UTC, thsig approved these changes

2021-05-12 15:06 UTC, merged

2021-05-13 08:29 UTC, marcelloromani commented
Great news! Looking forward to download the next release which includes these changes :)

2021-05-17 18:11 UTC, ArnaudRinquin commented
Congrats! Has this been shiped with 0.15?