fix(k8s): automatic retry for failed API requests
garden-io/garden pull request #2386
Opened 2021-05-12 12:32 UTC by thsig

**What this PR does / why we need it**:

We now automatically retry failed Kubernetes API requests if the reason for the failure matches certain conditions.

For example, timeouts or DNS-related errors will result in retries, but not 404/not found errors (and so forth), which will be thrown without retrying.

We can easily add more error codes and/or conditions to this logic if we discover further error cases that should result in retries.

**Which issue(s) this PR fixes**:

Fixes #2255.

Should also fix the sporadic API timeouts that some users have been encountering in day-to-day usage.

**Special notes for your reviewer**:

Do we want to include any more status codes and/or error messages in the `shouldRetry` helper? Are there other kinds of conditions for which we want to retry?

Also, feel free to comment on the general approach here.

2021-05-12 12:34 UTC, thsig commented
Note: I didn't use `p-retry` here, since it doesn't play nice with our custom error classes (which include extra fields in addition to the message).

2021-05-13 09:35 UTC, eysi09 commented
I think @edvald is best suited to review this one. I'll take a look but un-assign myself.

2021-05-13 13:25 UTC, edvald requested changes
Couple of small comments there, otherwise seems solid!

2021-05-13 13:25 UTC, edvald commented on core/src/plugins/kubernetes/api.ts
> +        if (log) {
I'd prefer to go directly for the root logger as a fallback. Also, I think this should be a warn log. This is a bit too hidden atm.

2021-05-13 13:25 UTC, edvald commented on core/src/plugins/kubernetes/api.ts
> +            log.debug(`Kubernetes API: Maximum retry count exceeded, throwing error`)
"throwing error" is maybe a bit odd for a user-facing message :)

2021-05-13 13:25 UTC, edvald commented on core/src/plugins/kubernetes/api.ts
> +const errorMessageRegexesForRetry = [/getaddrinfo ENOTFOUND/, /getaddrinfo EAI_AGAIN/]
Isn't this available on the error object in a more structured form?

2021-05-17 09:57 UTC, thsig commented on core/src/plugins/kubernetes/api.ts
> +            log.debug(`Kubernetes API: Maximum retry count exceeded, throwing error`)
Haha yeah, good point—I've removed that text.

2021-05-17 09:59 UTC, thsig commented on core/src/plugins/kubernetes/api.ts
> +        if (log) {
I refactored this so that the wrapped API has access to the log entry passed to the `KubeApi.factory` method.

I also added a description parameter to the `requestWithRetry` function for including in the warning messages, which should add a bit of clarity to the log output.

2021-05-17 10:04 UTC, thsig commented on core/src/plugins/kubernetes/api.ts
> +const errorMessageRegexesForRetry = [/getaddrinfo ENOTFOUND/, /getaddrinfo EAI_AGAIN/]
It might be, but the `wrapError` helper we're using doesn't include those fields (since they're not part of the `KubernetesError` class).

I thought matching against the error message was neater than adding several optional fields to the `KubernetesError` class, since we'd probably end up adding more and more of those fields going forward as we handle more of these cases.

I haven't reproduced it on my end, but here's an example of these error objects ([from here](https://github.com/nodejs/node/issues/5436)):
``` 
{ [Error: getaddrinfo ENOTFOUND host]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'host' }
```
That said, I'm totally open to adding more fields to the wrapped error (or maybe putting them all in an `inheritedFields` field with type `any`).

2021-05-17 10:06 UTC, edvald commented on core/src/plugins/kubernetes/api.ts
> +const errorMessageRegexesForRetry = [/getaddrinfo ENOTFOUND/, /getaddrinfo EAI_AGAIN/]
Let's not overthink it, no worries. I take it you tested this to make sure it works?

2021-05-17 10:10 UTC, thsig commented on core/src/plugins/kubernetes/api.ts
> +const errorMessageRegexesForRetry = [/getaddrinfo ENOTFOUND/, /getaddrinfo EAI_AGAIN/]
Yeah, I did—I had the logic throw errors and verified that the logging/retrying worked as expected.

The logging could be a bit nicer, but I think addressing that would require a bit of a refactor.

Here's a brief example snippet (where I hardcoded a `throw` with a `getaddrinfo ENOTFOUND` error, which matches the retry criteria):
```
✔ backend                   → Syncing module sources (2 files)... → Done (took 0 sec)
⠦ frontend                  → Getting build status for v-a57012fdb5...
⠼ backend                   → Getting build status for v-6fbe386fc0...
Kubernetes API: listNamespace failed with error test error: getaddrinfo ENOTFOUND, sleeping for 4000ms and retrying (#1/5)
Kubernetes API: /api/v1 failed with error test error: getaddrinfo ENOTFOUND, sleeping for 4000ms and retrying (#1/5)
Kubernetes API: /api/v1/namespaces/demo-project-testing-ths/secrets/garden-docker-auth-41e2da failed with error test error: getaddrinfo ENOTFOUND, sleeping
for 4000ms and retrying (#1/5)
Kubernetes API: patchNamespace failed with error test error: getaddrinfo ENOTFOUND, sleeping for 4000ms and retrying (#1/5)
```

2021-05-17 14:34 UTC, edvald commented on core/src/plugins/kubernetes/api.ts
> +const errorMessageRegexesForRetry = [/getaddrinfo ENOTFOUND/, /getaddrinfo EAI_AGAIN/]
Ok cool. I'd suggest "sleeping for 4000ms and retrying" -> "retrying in 4000ms", otherwise looks good.

Also, is 4000ms the value for the first retry? Seems a touch high, no?

2021-05-17 14:51 UTC, thsig commented on core/src/plugins/kubernetes/api.ts
> +const errorMessageRegexesForRetry = [/getaddrinfo ENOTFOUND/, /getaddrinfo EAI_AGAIN/]
> Ok cool. I'd suggest "sleeping for 4000ms and retrying" -> "retrying in 4000ms", otherwise looks good.

Yeah, that's better—will make that change.

> Also, is 4000ms the value for the first retry? Seems a touch high, no?

It's 2000ms for the first retry, actually (`2000 + 2000 * retries`)—this should say "#2/5".

Should we go for `500 + 500 * retries` instead?

2021-05-17 16:44 UTC, edvald approved these changes

2021-05-17 16:45 UTC, merged