improvement(core): better logs command
garden-io/garden pull request #2390
Opened 2021-05-13 11:07 UTC by eysi09

**What this PR does / why we need it**:

This PR makes some improvements to the logs stream. E.g.:

- More resilient logs follow mode
- Color code logs
- Add --since flag
- Interleave logs when not in follow mode

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-05-13 13:50 UTC, edvald requested changes
This is great! Solid improvement, and much needed. Had a few comments but overall looks like a good implementation.

2021-05-13 13:50 UTC, edvald commented on core/src/commands/logs.ts
> +        garden logs --original-color      # interaleaves logs from all services and prints the original output color
Typo: interaleaves

2021-05-13 13:50 UTC, edvald commented on core/src/commands/logs.ts
> +        garden logs --since 2d            # interleaves color coded logs from all services from the last 2 days
Typo: "color coded" -> "color-coded"

2021-05-13 13:50 UTC, edvald commented on core/src/commands/logs.ts
> +        originalColor ? (hasAnsi(serviceLog) ? serviceLog : chalk.white(serviceLog)) : style(serviceLog),
This is very difficult to parse imo

2021-05-13 13:50 UTC, edvald commented on core/src/cli/params.ts
> +export function convertDurationToSeconds(duration: string) {
This could really use some unit tests.

2021-05-13 13:50 UTC, edvald commented on core/src/cli/params.ts
> +export function convertDurationToSeconds(duration: string) {
Or, just use something like this: https://www.npmjs.com/package/parse-duration

2021-05-13 13:50 UTC, edvald commented on core/src/commands/logs.ts
> -  // since: new MomentParameter({ help: "Retrieve logs from the specified point onwards" }),
This should just be removed, right?

2021-05-13 13:50 UTC, edvald commented on core/src/commands/logs.ts
> +    log.info(chalk.white("-------------------------------------"))
This doesn't quite look nice imo. I suggest using this: https://github.com/garden-io/garden/blob/65303d41b0f132393e344d080f0fa2b8dfb088b7/core/src/logger/util.ts#L210

Also, maybe make the divider and the text above it bold?

2021-05-13 13:50 UTC, edvald commented on core/src/plugins/kubernetes/logs.ts
> +      this.write({
Somehow this state didn't come up in my testing. When re-deploying I just got this as part of the logs:

`api    → error: code = Unknown desc = Error: No such container: 390fd1ba5565f66189a4e31d5f0872cd1979d57bfdfa6652abf64c2b1deca234`

Which is sort of fine. Do you know if that's something we're printing ourselves from our error handling, or if this just comes over the wire from k8s?

2021-05-13 14:08 UTC, eysi09 commented on core/src/plugins/kubernetes/logs.ts
> +      this.write({
This came from over the wire.

2021-05-13 15:39 UTC, eysi09 commented on core/src/commands/logs.ts
> +        originalColor ? (hasAnsi(serviceLog) ? serviceLog : chalk.white(serviceLog)) : style(serviceLog),
The last part with the double ternary, or just the whole thing?

2021-05-13 16:01 UTC, eysi09 commented on core/src/commands/logs.ts
> -  // since: new MomentParameter({ help: "Retrieve logs from the specified point onwards" }),
It is removed, it's red :)

2021-05-13 16:05 UTC, eysi09 commented on core/src/commands/logs.ts
> +    log.info(chalk.white("-------------------------------------"))
Good suggestion, looks good imo:
![Screenshot 2021-05-13 at 18 04 27](https://user-images.githubusercontent.com/5373776/118153023-b6da3a00-b415-11eb-82dc-a58a2b75f4f0.png)

2021-05-13 16:05 UTC, edvald commented on core/src/commands/logs.ts
> -  // since: new MomentParameter({ help: "Retrieve logs from the specified point onwards" }),
![image](https://user-images.githubusercontent.com/155684/118153071-c063a200-b415-11eb-9587-8110bf00571c.png)

2021-05-13 16:06 UTC, edvald commented on core/src/commands/logs.ts
> -  // since: new MomentParameter({ help: "Retrieve logs from the specified point onwards" }),
![](https://i.imgur.com/zGHQb4O.gif)

2021-05-13 16:08 UTC, eysi09 commented on core/src/plugins/kubernetes/logs.ts
> +      this.write({
I've seen this happen on occasion, and on other occasions it's more graceful. For example here I delete a service mid log stream:

```
result     → Checking for updates { }...
result     → <Lost connection to container "result" in Pod "result-58fb4d74cb-c82nt". Reason: Request closed. Will retry in background... >
result     → <No running containers found for service. W {ill retry in 10s
```

2021-05-13 16:15 UTC, eysi09 commented
Thanks for the review! I've addressed all the comments. 

There's one outstanding question: This thing with the initial request "ending" when streaming 100+ log lines in follow mode (see the 3rd bullet in "notes for reviewer" above). 

If for example I log a tick every second and then run `garden logs --follow --since 500s`, I get something like:

```
tick 1
tick 2
...
tick 100
tick 101 <--- Around here the connection ends. The logs follower attempts to reconnect but doesn't know the correct position so just gets the logs from the last 10 seconds
tick 489
tick 490
tick 491
...
```

Currently we default to `--since 10m` in follow mode. Perhaps we should rather default to `--tail 10` or similar. Or maybe even enforce it?

2021-05-14 12:38 UTC, edvald commented
One other suggestion: Could we bold the service name, and maybe make the timestamp gray (or something like that, haven't actually tried it myself) to make the different parts more visually distinct? Feels a little hard to parse the output atm.

2021-05-15 09:44 UTC, eysi09 commented
Making the service name bold makes the rest of text feel a little greyed out somehow (it was italic previously):

<img width="894" alt="Screenshot 2021-05-15 at 11 42 32" src="https://user-images.githubusercontent.com/5373776/118355880-cae77e00-b572-11eb-8d79-da63f95fe889.png">

One thing that's a little annoying also is that we don't know the lengths of the container names. So we can't easily align them like we do services. Although we can adjust the alignment as new logs come in.

2021-05-15 09:46 UTC, eysi09 commented
We could also pad the log lines so that they don't break under the service names and timestamps, but then copying them wouldn't be nice.

2021-05-18 10:34 UTC, edvald commented on core/src/commands/logs.ts
> +      since = "10m"
I was just testing this and noticed I could get a _lot_ of logs since this is uncapped. Would it maybe make more sense to default to tail?

2021-05-18 10:38 UTC, eysi09 commented on core/src/commands/logs.ts
> +      since = "10m"
Ah whoops, this is suppose to be "1m". It was originally "10m" but I decided to change it because of this very reason. 

I kind of like the idea of using a duration here, since the idea is you get new logs and just a little bit of context with it if applicable. As opposed to always getting, say, the last 10 lines which may be way old. 

But of course `--since 1m` can still turn up a lot of logs. So no strong opinions really either way.

2021-05-18 15:12 UTC, edvald approved these changes

2021-05-18 20:25 UTC, merged