feat(k8s): resolve template strings in kubernetes module manifest files
garden-io/garden pull request #2399
Opened 2021-05-19 10:32 UTC by edvald

Previously, you could only use template strings when inlining
manifests using the `manifests` field. Now, template strings are also
resolved in the files referenced in the `files` key.

Internally, we now make a `ctx.resolveTemplateStrings()` for all
plugin handlers, so this will be easy to do in other scenarios as well.

Also added a commit to allow referencing service or task versions via e.g.
`${runtime.services.my-service.version}` or
`${runtime.tasks.my-task.version}`.

2021-05-19 18:49 UTC, eysi09 commented
@tvollstaedt, this might be of interest to you.

2021-05-21 11:28 UTC, thsig requested changes
Looks great! Had one text-related comment there.

2021-05-21 11:28 UTC, thsig commented on core/src/plugins/kubernetes/kubernetes-module/config.ts
> +      "POSIX-style paths to YAML files to load manifests from. Each can contain multiple manifests, and can include any Garden template string, which will be resolved before applying the manifests."
"template string" -> "template strings"

2021-05-21 11:43 UTC, edvald commented
Rebased and ready @thsig!

2021-05-21 12:16 UTC, thsig approved these changes

2021-05-21 12:40 UTC, merged