improvement(cloud): better secrets errors
garden-io/garden pull request #2413
Opened 2021-05-27 11:34 UTC by thsig

**What this PR does / why we need it**:

We now log more informative error messages when a missing secret is referenced, and when trying to fetch secrets for an environment that doesn't exist on the backend.

2021-06-01 08:16 UTC, eysi09 requested changes
Had few comments/questions/suggestions on the text but overall looks great.

2021-06-01 08:16 UTC, eysi09 commented on core/src/config/template-contexts/project.ts
> +        Note: An empty set of secrets was fetched. If you have defined secrets for the current project and environment in Garden
Isn't it most likely that this happens simply when the secrets haven't been created at all? If that's the case, shouldn't the suggestion be similar to below? Maybe with a bit more colour since it looks the user hasn't created secrets at all.

Something like: "Looks like no secrets have been created for this environment in Garden Cloud. To create secrets click the following link ${linkToProjectSecretsPageForGivenEnterpriseDomain}`.

2021-06-01 08:16 UTC, eysi09 commented on core/src/enterprise/api.ts
> +        `Received a null/empty client auth token while logging in. Please contact your system administrator.`,
"Please contact your system administrator" is probably my least favourite error message. Especially when there's a chance that the person seeing this message is the system administrator. 

When is this likely to happen? Can give more actionable suggestions based on that?

2021-06-01 09:02 UTC, thsig commented on core/src/enterprise/api.ts
> +        `Received a null/empty client auth token while logging in. Please contact your system administrator.`,
> "Please contact your system administrator" is probably my least favourite error message. Especially when there's a chance that the person seeing this message is the system administrator.

Haha yeah, true that.

> When is this likely to happen? Can give more actionable suggestions based on that?

How about: "This may indicate a problem with your VCS provider setup."?

2021-06-07 07:39 UTC, thsig commented
I think this should be good to go now, @eysi09.

If we're OK with this, I'll fold the TBS commit into the first one before merging.

2021-06-08 15:16 UTC, merged