feat(core): local targets for build dependencies
garden-io/garden pull request #2444
Opened 2021-06-18 09:19 UTC by thsig

**What this PR does / why we need it**:

Added an optional `localTarget` flag to `build.dependencies[].copy[]`.

When used, build dependencies are copied to the module (source) directory of the dependant module instead of the build directory.

This is useful for many flows, especially when using the `exec` module for custom build flows, and has been indirectly requested by many of our users.

2021-06-18 10:58 UTC, edvald commented
Seems good at a glance, although I'm unsure about the `localTarget` name. When seeing it next to `target`, it doesn't feel clear that this will be a boolean flag, and feels opaque. How about something a little more verbose (and helpful), like `copyToSourceDir`?

2021-06-22 14:23 UTC, thsig commented
Yeah, good point—`copyToSourceDir` is clearer. Should be good to go now.

2021-07-05 14:51 UTC, thsig commented
How do we feel about this one? Any further comments?

2021-07-05 18:25 UTC, edvald commented
I think we need more complete tests for this. What we need to test for is whether the files are copied _before_ the module version is computed. If it isn't, this won't have the desired effect, and may trigger some awkward version re-computes mid-process (which is a big part of why we stage builds in the first place).

2021-07-05 18:25 UTC, edvald requested changes
See comment above.

2023-03-23 10:42 UTC, closed without merging