feat(config): add support for module-level variables
garden-io/garden pull request #2454
Opened 2021-06-24 17:40 UTC by edvald

This introduces _module variables_ to help make configurations cleaner
and easier to manage, especially for larger projects.

From the added docs:

--

## Module variables

Each Garden module can specify its own set of variables, that can be
re-used within the module, as well as referenced by other dependant
modules.

Simply specify the `variables` field on the module, same as in the
project configuration. For example:

```yaml
# my-service/garden.yml
kind: Module
name: my-service
variables:
  # This overrides the project-level hostname variable
  hostname: my-service.${var.hostname}
  # You can specify maps or lists as variables
  envVars:
    LOG_LEVEL: debug
    DATABASE_PASSWORD: ${var.database-password}
services:
  - name: my-service
    ...
    ingresses:
      - path: /
        port: http
        # This resolved to the hostname variable set above,
        # not the project-level one
        hostname: ${var.hostname}
    # Referencing the above envVar module variable
    env: ${var.envVars}
tests:
  - name: my-test
    ...
    # Re-using the envVar module variable
    env: ${var.envVars}
```

Notice that you can override variables defined at the project-level,
and even reference project-scoped variables when defining the module
variables.

Also notice the generally handy use-case of re-using a common value (in
this case a map of environment variables) in multiple spots in the
module configuration.

### Referencing module variables

On top of that, you can reference the resolved module variables in
other modules. With the above example, another module might for example
reference `${modules.my-service.var.hostname}`. For larger projects
this can be much cleaner than, say, hoisting a lot of variables up to
the project level.

**Special notes for your reviewer**:

Please give it a quick spin, see if it works alright outside of unit/functional tests.

2021-07-05 19:57 UTC, thsig requested changes
Looks great! This will be a very welcome feature for our users.

Only had a few test/documentation-related comments there.

2021-07-05 19:57 UTC, thsig commented on core/src/config/module.ts
> +  variables: joiVariables().default(() => undefined).description(dedent`
Minor question: Is there a reason we don't default to `{}` here?

2021-07-05 19:57 UTC, thsig commented on docs/using-garden/variables-and-templating.md
> +Each Garden module can specify its own set of variables, that can be re-used within the module, as well as referenced by other dependant modules.
"set of variables, that" -> "set of variables that"

Also, for added clarity, I think we should expand this: "as well as referenced by other dependant modules"

to something like "The variables defined in a module can be reused in modules that have build or runtime dependencies on it."

Btw, are those the semantics? Just making sure I read the resolution flow right.

Also, if a user makes a mistake there (e.g. expects a variable to be available, but didn't get the dependency structure right), will they get an informative error message (or will the origin of the mistake generally be obvious from the usage context)?

2021-07-05 19:57 UTC, thsig commented on docs/using-garden/variables-and-templating.md
> +        # This resolved to the hostname variable set above, not the project-level one
"resolved" -> "resolves"

"not the project level one" -> "not the project-level hostname variable"

2021-07-06 14:31 UTC, edvald commented on core/src/config/module.ts
> +  variables: joiVariables().default(() => undefined).description(dedent`
This is to avoid introducing unnecessary changes to version hashes, and breaking a bunch of tests along the way.

2021-07-06 14:33 UTC, edvald commented on docs/using-garden/variables-and-templating.md
> +Each Garden module can specify its own set of variables, that can be re-used within the module, as well as referenced by other dependant modules.
Actually that's not the case—a module can implicitly depend on another by way of template string reference without including an explicit build/runtime reference. So I think this copy (save for the typo) is fine.

2021-07-06 16:11 UTC, thsig approved these changes

2021-07-08 08:48 UTC, merged