chore: add more logging to GitHandler (tracking down a user issue)
garden-io/garden pull request #2465
Opened 2021-07-01 11:59 UTC by edvald

2021-07-05 20:16 UTC, thsig requested changes
Looks good! Had a few minor comments there.

2021-07-05 20:16 UTC, thsig commented on core/src/vcs/git.ts
> +    log.debug(`Scanning ${pathDescription} at ${path}\nIncludes: ${include}\nExcludes:${exclude}`)
Maybe this should be at the `silly` level (like the other new log statement at line 160 below)?

2021-07-05 20:16 UTC, thsig commented on core/src/vcs/git.ts
> + * Given a list of POSIX-style globs
Unfinished comment?

Also, maybe it would be cleaner to explicitly return `undefined` on line 540 below.

2021-07-05 20:16 UTC, thsig commented on core/test/unit/src/vcs/git.ts
> +    it("should include a directory that's explicitly included its exact name", async () => {
"included its" -> "included by its"

2021-07-06 14:24 UTC, edvald commented on core/src/vcs/git.ts
> +    log.debug(`Scanning ${pathDescription} at ${path}\nIncludes: ${include}\nExcludes:${exclude}`)
Felt like this could be at a higher level, because it's not called as frequently and is broadly useful to know when debugging.

2021-07-06 14:31 UTC, edvald commented
@thsig comments addressed (and linting errors fixed)

2021-07-06 16:13 UTC, thsig approved these changes

2021-07-08 15:49 UTC, edvald commented
The failing unit test seems to be down to a behavior difference in git versions. Which is annoying. I'm seeing about how best to fix it.

2021-07-09 12:41 UTC, merged