feat(core): stream build statuses
garden-io/garden pull request #2470
Opened 2021-07-07 15:56 UTC by thsig

**What this PR does / why we need it**:

We now stream build status events, similarly to how we've been streaming service, test and task status events.

2021-07-07 15:58 UTC, edvald approved these changes

2021-07-08 12:39 UTC, edvald commented on core/src/types/plugin/module/build.ts
> +export type BuildState = "fetched" | "building" | "built" | "error"
Maybe "failed" is more consistent in terms of phrasing, rather than "error"?

2021-07-08 15:12 UTC, thsig commented on core/src/types/plugin/module/build.ts
> +export type BuildState = "fetched" | "building" | "built" | "error"
Yeah, that's better.

2021-07-14 12:03 UTC, thsig commented
@edvald: I've made the changes we talked about, could you have another look?

2021-07-14 12:23 UTC, edvald requested changes
Had some field naming comments, otherwise looks good!

2021-07-14 12:23 UTC, edvald commented on core/src/actions.ts
> +      testConfigVersion,
I think it's clearer to just call this `testVersion`. The test version isn't _just_ the test config version, but rather the whole chain including the module version, dependencies etc.

2021-07-14 12:23 UTC, edvald commented on core/src/actions.ts
> +      serviceConfigVersion,
Same goes here, just call this `serviceVersion` imo.

2021-07-14 12:23 UTC, edvald commented on core/src/actions.ts
> +      taskConfigVersion,
And here as well, of course .)

2021-07-14 13:10 UTC, thsig commented
Thanks for the suggestions! The fields have been renamed now.

2021-07-14 13:21 UTC, edvald approved these changes

2021-07-14 13:46 UTC, thsig commented
@10ko: I've added `moduleName` to the `serviceStatus` and `taskStatus` events as you requested. Will merge this once CI is passing.

2021-07-15 14:26 UTC, merged