chore: Update azure.Docker file to work with Azure DevOps Pipelines
garden-io/garden pull request #2509
Opened 2021-07-26 23:13 UTC by ITHedgeHog

**What this PR does / why we need it**:

Adds the correct items needed for this Docker image to run on Azure DevOps

**Which issue(s) this PR fixes**:
Fixes 2502

**Special notes for your reviewer**:

@edvald I checked the code I copied from Stack Overflow, it was in fact all needed -  I purposely chose to add the extra bits for Azure DevOps in a second run command so that it creates a separate layer for reuse in other images as necessary. I'm pretty sure this can all be collapsed in to a single run command if you prefer.

The Endpoint and label are both required by Azure DevOps for the image to run.

I've deployed this image to our internal registry and updated our CI/CD pipeline to use it.

2021-07-27 14:01 UTC, edvald requested changes
Thanks @ITHedgeHog! Maybe being a bit nitpicky, but I had a couple of small comments, should be quick to address .)

2021-07-27 21:55 UTC, ITHedgeHog commented on support/azure.Dockerfile
> +ENV KUBELOGIN_VERSION="v0.0.9"
I've moved this.

2021-07-27 21:55 UTC, ITHedgeHog commented on support/azure.Dockerfile
> +LABEL "com.azure.dev.pipelines.agent.handler.node.path"="/usr/local/bin/node"
Comment added

2021-07-27 21:56 UTC, ITHedgeHog commented on support/azure.Dockerfile
> +  && apk add bash sudo shadow \
I've merged the two run statements. I tried building it without adding readline and linux-pam however without those I could not add bash sudo or shadow.

2021-08-05 15:52 UTC, edvald approved these changes

2021-08-05 15:52 UTC, merged