For loops and list concatenation
garden-io/garden pull request #2654
Opened 2021-11-09 08:29 UTC by edvald

This PR includes two major templating improvements:
- Any list/array value now supports a special kind of value, which is an object with a single `$concat` key. This allows you to easily concatenate multiple arrays.
- You can now map through a list of values by using the special `$forEach/$return` object.

Here's an example where we concatenate the same templated value into
two arrays of test arguments:

```yaml
kind: Module
...
variables:
  commonArgs:
    - yarn
    - test
    - -g
tests:
  - name: test-a
    # resolves to [yarn, test, -g, suite-a]
    args:
      - $concat: ${var.commonArgs}
      - suite-a
  - name: test-b
    # resolves to [yarn, test, -g, suite-b]
    args:
      - $concat: ${var.commonArgs}
      - suite-b
```

To perform a for-each loop, you specify an object with two keys, `$forEach: <some list>` and
`$return: <any value>`. You can also optionally add a
`$filter: <expression>` key, which if evaluates to `false` or `null`
for a particular value, it will be omitted.

Template strings in the `$return` and `$filter` fields are resolved
with the same template context as what's available when resolving the
for-loop, in addition to `${item.value}` which resolves to the list
item being processed, and `${item.index}` which is the index number
(starting with 0) of the item in the list.

Here's an example where we kebab-case a list of string values:

```yaml
kind: Module
...
variables:
  values:
    - some_name
    - AnotherName
    - __YET_ANOTHER_NAME__
tasks:
  - name: my-task
    # resolves to [some-name, another-name, yet-another-name]
    args:
      $forEach: ${var.values}
      $return: ${kebabCase(item.value)}
```

Here's another example, where we create an object for each value in a
list and skip certain values:

```yaml
kind: Module
...
variables:
  ports:
    - 80
    - 8000
    - 8100
    - 8200
services:
  - name: my-service
    ports:
      # loop through the ports list declared above
      $forEach: ${var.ports}
      # only use values higher than 1000
      $filter: ${item.value > 1000}
      # for each port number, create an object with a name and port keys
      $return:
        name: port-${item.index}  # item.index is the array index
        port: ${item.value}
```

2021-11-09 19:12 UTC, thsig commented on core/src/config/common.ts
> +      [arrayConcatKey]: joi.alternatives(joi.array(), joi.string()),
Is the `joi.string()` option to account for partial/unresolved values?

2021-11-10 13:01 UTC, thsig requested changes
Looks great! Had one suggestion for an added test case (but we can also add that later if we want to get this merged fast).

2021-11-10 13:02 UTC, edvald commented on core/test/unit/src/template-string.ts
> +  context("$concat", () => {
Good idea, I'll add that

2021-11-10 13:03 UTC, edvald commented on core/src/config/common.ts
> +      [arrayConcatKey]: joi.alternatives(joi.array(), joi.string()),
Yep exactly. I can add a comment.

2021-11-10 13:48 UTC, thsig approved these changes

2021-11-17 12:25 UTC, merged