feat(core): module varfiles
garden-io/garden pull request #2701
Opened 2021-12-14 12:05 UTC by thsig

**What this PR does / why we need it**:

Added support for module varfiles. These are located at or under the module root, and take precedence over module variables (thus having the second-highest precedence behind CLI vars).

The path to the module varfile is set via the optional `module.varfile` field.

Also fixed an issue where CLI variables were overridden by module variables. CLI variables now correctly have the highest precedence.

**Which issue(s) this PR fixes**:

Fixes #2687 and #2676.

2021-12-20 14:22 UTC, edvald requested changes
Looks good! Just some super minor things I noticed, otherwise seems solid 👌

2021-12-20 14:22 UTC, edvald commented on core/src/config/project.ts
> +  defaultPath: string | undefined
I'd suggest deconstructing this, best to avoid consecutive optional args.

2021-12-20 14:22 UTC, edvald commented on core/src/resolve-module.ts
> +      // console.log(`rawConfig: ${JSON.tringify(rawConfig, null, 2)}`)
🧹

2021-12-21 13:24 UTC, thsig commented
@edvald: This should be good to go now.

2021-12-21 18:49 UTC, merged