fix(core): properly handle sparse build deps
garden-io/garden pull request #2719
Opened 2022-01-11 11:50 UTC by thsig

**What this PR does / why we need it**:

Previously, adding an optional build dependency via a template string that sometimes resolves to null would throw an error when the string resolved to null.

The build dependencies array was always intended to be a sparse array, but due to the special handling we have to support both the shorthand (module name only) and the full (a map with the module name and other fields) formats, we needed to add a bit of extra logic to account for this use case.

**Which issue(s) this PR fixes**:

Fixes #2685.

**Special notes for your reviewer**:

It's a bit awkward that we have to normalize / clean up the shape of the build dependencies array in two separate places, but it's perhaps acceptable given the incremental nature of the module resolution flow.

2022-01-11 12:15 UTC, edvald commented on core/src/config/base.ts
> +    })
This is quite difficult to parse. Would it not be simpler to first map to the canonical form and then filter based on whether the name is empty or not..?

2022-01-11 15:44 UTC, thsig commented on core/src/config/base.ts
> +    })
Yeah, good point—I'll make that change.

2022-01-12 08:57 UTC, thsig commented on core/src/config/base.ts
> +    })
How about now?

2022-01-12 09:01 UTC, edvald commented on core/src/config/base.ts
> +    })
Hmm, let's see. If `dep` is a template string that resolves later to null, this won't work as expected. I think the filtering may need to happen quite a bit later, on reflection. That is, when the list is actually used.

2022-01-12 09:47 UTC, thsig commented on core/src/config/base.ts
> +    })
It's not quite obvious, but it does work because of the re-filtering I added in line 335 in `core/src/resolve-module.ts`. I could add another test case to explicitly check for that (I manually verified that part).

2022-01-13 17:48 UTC, edvald commented on core/src/config/base.ts
> +    })
That would be good to verify, I could totally see that break at a later point.

2022-01-14 12:07 UTC, thsig commented on core/src/config/base.ts
> +    })
I've added a test case for this now (good thing that I did, it revealed a bug that I fixed). So I think we should be good.

2022-01-15 10:25 UTC, edvald requested changes

2022-01-15 10:25 UTC, edvald commented on core/test/unit/src/garden.ts
> +    it.only("should filter out null build dependencies after resolving template strings", async () => {
Left `it.only` in there. Seems fine otherwise.

2022-01-15 14:35 UTC, thsig commented on core/test/unit/src/garden.ts
> +    it.only("should filter out null build dependencies after resolving template strings", async () => {
Thanks! I've removed it now.

2022-01-15 14:45 UTC, merged