feat(template): add indent helper function
garden-io/garden pull request #2725
Opened 2022-01-13 16:15 UTC by edvald

This is useful for indenting YAML strings, for example:

`${indent("some: multiline\nyaml: document", 2)}`

 ->

```
  some: multiline
  yaml: document
```

Closes #2659

2022-01-13 21:14 UTC, thsig requested changes
Looks good! Had one comment there (there's a constant that should probably be a variable/argument).

2022-01-13 21:14 UTC, thsig commented on core/src/template-string/functions.ts
> +    fn: (str: string) => indentString(str, 2),
Shouldn't the indent be a variable here?

2022-01-15 10:26 UTC, edvald commented on core/src/template-string/functions.ts
> +    fn: (str: string) => indentString(str, 2),
Indeed!

2022-01-15 12:39 UTC, edvald commented on core/src/template-string/functions.ts
> +    fn: (str: string) => indentString(str, 2),
Fixed + improved the testing setup for all the helpers.

2022-01-15 14:32 UTC, thsig approved these changes

2022-01-15 14:32 UTC, merged