feat(core): debug & silly-level logfiles
garden-io/garden pull request #2752
Opened 2022-01-31 09:42 UTC by thsig

**What this PR does / why we need it**:

We now output all debug-level and silly-level logs into logfiles in the project's `.garden/logs` directory.

The names of these logfiles include the command name, log level and the time the command was executed (as an ISO timestamp).

Logfiles older than 7 days are also automatically cleaned up by this logic.

This will be useful for gathering debug information when something goes wrong in a Garden command that was run at a lower (less verbose) log level.

2022-02-15 08:48 UTC, eysi09 reviewed
I had one suggestion (that we can mostly implement in a follow up PR).

2022-02-15 08:48 UTC, eysi09 commented on core/src/cli/cli.ts
> +      {
Why not just have a single silly log file and a built-in Garden command for getting debug logs, filtering on the correct level and either write to the terminal or to a file. 

So you can essentially "replay" a Garden command at any log level. (We could even store output from the last "n" commands and have a drop down list in the TUI with a command + timestamp that you can pick from). 

So as not to block the this PR though, we could skip the debug file for now and implement the built-in command in a follow up PR.

2022-02-15 08:48 UTC, eysi09 commented on core/src/cli/cli.ts
> +      {
In any case it feels odd to have two create two files where once is a strict subset of the other.

2022-02-16 13:04 UTC, edvald commented on core/src/cli/cli.ts
> +      {
This is pretty hidden debug "feature", I don't exactly mind a slightly-less-than-ideal implementation and just getting it done. We can make this nicer later.

Does the log level on each line get printed as part of the logfile output?

2022-02-17 09:55 UTC, thsig commented on core/src/cli/cli.ts
> +      {
> a built-in Garden command for getting debug logs, filtering on the correct level and either write to the terminal or to a file.
>
> So you can essentially "replay" a Garden command at any log level. (We could even store output from the last "n" commands and have a drop down list in the TUI with a command + timestamp that you can pick from).

I like this feature idea. In the meantime, I think the debug-level logfile would be good to have in there, since the silly-level one is uncomfortably verbose for the user.

Once we get rid of the debug-level logfiles, they'll be automatically cleaned up by the pruning logic anyway.

What do you think, @edvald? Should we merge this one as is or should we get rid of the debug-level logfile first?

2022-02-17 17:43 UTC, thsig commented on core/src/cli/cli.ts
> +      {
> Does the log level on each line get printed as part of the logfile output?

Not currently, no.

2022-02-21 12:00 UTC, thsig commented on core/src/cli/cli.ts
> +      {
I replaced the silly-level logfile with a JSONL-formatted logfile (using a new `JsonFileWriter` for the log rendering), so I think we should be good to go here now.

2022-02-21 13:48 UTC, eysi09 requested changes
One tiny comment, otherwise looks good.

2022-02-21 13:48 UTC, eysi09 commented on core/src/cli/debug-logs.ts
> +  return `${commandFullName.replace(" ", "-")}.${logLevel}.${new Date().toISOString()}.log`
For the JSON file the log level should still be silly and the file extension should be `jsonl`.

2022-02-22 19:15 UTC, thsig commented on core/src/cli/debug-logs.ts
> +  return `${commandFullName.replace(" ", "-")}.${logLevel}.${new Date().toISOString()}.log`
Yeah, agreed. I'll make that change.

2022-02-23 15:51 UTC, thsig commented on core/src/cli/debug-logs.ts
> +  return `${commandFullName.replace(" ", "-")}.${logLevel}.${new Date().toISOString()}.log`
Ok, should be good to go now. Any further comments here?

2022-02-23 16:05 UTC, eysi09 approved these changes

2022-02-23 16:08 UTC, merged