improvement(cloud): handle AEC for Helm services
garden-io/garden pull request #2758
Opened 2022-02-03 14:41 UTC by 10ko

**What this PR does / why we need it**:
This PR changes the status check for the Helm plugin to mark resources that have been deployed via Helm and paused by Garden Cloud AEC functionality as `outdated`.
This is needed because when we scale down Helm workload resources from the CleanupRunners, Helm stays unaware of those changes and always returns the `ready` status.

Note: I might need help with testing this @thsig and we were also wondering how to pass a `gardenCloudContext` to plugin handlers in order to call this logic only if the user is logged in Garden Cloud and avoid unnecessary checks otherwise.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
cc @twelvemo

2022-02-04 09:31 UTC, thsig commented on core/src/plugins/kubernetes/helm/deployment.ts
> +      Bluebird.all(
Aren't we missing an `await` here?

2022-02-04 09:33 UTC, thsig commented on core/src/plugins/kubernetes/helm/deployment.ts
> +      Bluebird.all(
We should either `await` here or make sure to handle promise rejections (if the idea is to not wait for the `annotateResource` calls to finish, for performance reasons).

2022-02-04 12:48 UTC, 10ko commented on core/src/plugins/kubernetes/helm/deployment.ts
> +      Bluebird.all(
Oops, this is a mistake, we should `await` there. Good catch!

2022-02-15 09:44 UTC, thsig commented on core/src/plugins/kubernetes/helm/deployment.ts
> +        Bluebird.all(
Missing `await` here.

2022-02-15 12:41 UTC, thsig requested changes
Had a few minor comments there, looks great otherwise!

2022-02-15 12:41 UTC, thsig commented on core/src/plugins/kubernetes/helm/deployment.ts
> +    // that could have been paused by Garden Cloud AEC functionality. We therefore make sure to cleanup any
"by Garden Cloud" -> "by Garden Cloud's"

"cleanup" -> "clean up"

"annotation" -> "annotations"

2022-02-15 12:41 UTC, thsig commented on core/src/plugins/kubernetes/helm/deployment.ts
> +        const errorMsg = `Failed to remove Garden Cloud AEC annotations for module: ${module.name}.`
While the service name and module name are the same for Helm modules, we should use the service name here (and say "annotations for service" in the error message), since services are the thing that's deployed (in Garden parlance).

2022-02-15 12:41 UTC, thsig commented on core/src/plugins/kubernetes/helm/status.ts
> +  log.info("checking status")
I think this should be at the verbose or debug level.

2022-02-15 12:41 UTC, thsig commented on core/src/plugins/kubernetes/helm/status.ts
> +      // that could have been paused by Garden Cloud AEC functionality. We therefore make sure to check for
"Garden Cloud" -> "Garden Cloud's"

2022-02-15 12:41 UTC, thsig commented on core/src/plugins/kubernetes/helm/status.ts
> +      // the annotations Garden Cloud adds to Helm deployments and statefulsets when pausing an environment.
"deployments and statefulsets" -> "Deployments and StatefulSets"

2022-02-15 12:41 UTC, thsig commented on core/src/plugins/kubernetes/helm/status.ts
> + *  Returns Helm workload resources that have been marked as "paused" by the Garden Cloud AEC functionality
"by the Garden Cloud" -> "by Garden Cloud's"

2022-02-15 14:20 UTC, 10ko commented on core/src/plugins/kubernetes/helm/status.ts
> +  log.info("checking status")
I think this should be removed altogether, I added it while debugging.

2022-02-15 14:24 UTC, 10ko commented
@thsig thanks, I made the changes you requested.

2022-02-16 10:46 UTC, thsig approved these changes

2022-02-16 10:48 UTC, merged