feat: pulumi provider
garden-io/garden pull request #2835
Opened 2022-03-03 21:52 UTC by thsig

**What this PR does / why we need it**:

The pulumi provider wraps the pulumi CLI for deploying and destroying pulumi stacks.

The pulumi module type supports merging variables and varfiles with pulumi configs (via the `pulumiVariables` and `pulumiVarfiles` config fields). Pulumi modules that deploy sensitive resources can be protected by setting `autoApply: false` and/or `allowDestroy: false`.

When the `planPath` config variable is provided, the stack will be deployed with the provided pre-generated plan, which is useful for two-phase CI flows (where the proposed plans can be reviewed and then passed to the deployment pipeline).

Also included are plugin commands for cancelling, refreshing, and reimporting stacks (in dependency order, when called for more than one service).

Finally, we've also moved the terraform plugin out of the Core package into the `plugins` directory.

**TODO**
[ ] Write integration tests.
[ ] Write guide.

2022-05-10 21:04 UTC, tedchang77 commented on docs/advanced/pulumi.md
> +pulumiVarfiles: [my-default-varfile.yaml, dev.yaml]
For simple pulumi programs, you many not need or want the additional flexibility (and complexity) that pulumiVarfiles and pulumiVars provide. You should have the ability to opt out and use a hand crafted Pulumi.<stack>.yaml that is not generated. if both of these directories are not set, we shouldn't generate an empty Pulumi.<stack>.yaml.

2022-05-11 10:13 UTC, vvagaytsev requested changes
LGTM. I left a couple of comments. By the way, it would be nice to add `tslint.json` to `pulumi` and `terraform` plugins now and apply the linter's suggested changes in this PR.

If it's too time consuming now, let's then do it in a separate PR. I can do that.

2022-05-11 10:17 UTC, thsig commented on plugins/pulumi/config.ts
> +  orgName?: string | null
Yeah, it has different semantics than `undefined` (i.e. not providing a value at all). See:
https://github.com/garden-io/garden/blob/pulumi/plugins/pulumi/config.ts#L125-L126

2022-05-11 10:32 UTC, vvagaytsev submitted a review, later dismissed

2022-05-11 11:56 UTC, vvagaytsev approved these changes

2022-05-11 11:56 UTC, vvagaytsev commented on plugins/pulumi/handlers.ts
> +  const { autoApply, deployFromPreview, cacheStatus } = pulumiModule.spec
Variable `cacheStatus` is unused here.

2022-05-11 11:56 UTC, vvagaytsev commented on plugins/pulumi/handlers.ts
> +  const { autoApply, deployFromPreview, cacheStatus } = pulumiModule.spec
I'll fix it in another PR with linters config.

2022-05-11 14:09 UTC, merged