WIP: Docs: updated release instructions
garden-io/garden pull request #2868
Opened 2022-03-28 08:37 UTC by vvagaytsev

**What this PR does / why we need it**:
This PR adds some release-related corrections to the contributing guide.

This is still a WIP PR.

2022-03-30 08:51 UTC, vvagaytsev commented
This is ready for review now.

2022-04-05 06:44 UTC, thsig requested changes
Thanks for the edits! Had a few text-related comments there.

2022-04-05 06:44 UTC, thsig commented on CONTRIBUTING.md
> +        2. Run `git log` to make sure that the latest commit is the expected one and there are no unwanted changes from master included into the release.
"included into" -> "included in"

2022-04-05 06:44 UTC, thsig commented on CONTRIBUTING.md
> +        * If there are any issues with syncing, consider changing the `services[].devMode.sync[].mode` value(s) to `one-way-replica` and restart the Garden.
"restart the" -> "restart"

2022-04-05 06:44 UTC, thsig commented on CONTRIBUTING.md
> +    * On **macOS** or **Linux**, run the `./scripts/test-release.sh <version>` script, where the `<version>` should be in the format of `<major>.<minor>.<patch>-<preReleaseCounter>`, e.g. `0.12.38-0`
"where the" -> "where"

"be in the format of" -> "have the format"

2022-04-05 08:09 UTC, vvagaytsev commented
CR-based fixes have been done, @thsig could you review it again, please?

2022-04-05 08:34 UTC, thsig approved these changes

2022-04-05 08:39 UTC, merged