docs: add namespace guide
garden-io/garden pull request #2873
Opened 2022-03-29 06:03 UTC by sixhobbits

**What this PR does / why we need it**:

- adds a guide on how to use namespaces

**Which issue(s) this PR fixes**:

- n/a

**Special notes for your reviewer**:

2022-04-20 14:29 UTC, eysi09 requested changes
Great work @sixhobbits! Just had a few suggestions but overall looks good.

2022-04-20 14:29 UTC, eysi09 commented on docs/guides/namespaces.md
> +To specify which Garden Namespace to use, you can use either of the following:
All references to Garden namespaces should be lower case. So change "Namespace" to "namespace" here and below. 

However, a Kubernetes "Namespace" resource is capitalised :)

2022-04-20 14:29 UTC, eysi09 commented on docs/guides/namespaces.md
> +		defaultNamespace: my-project
These white spaces look odd.

2022-04-20 14:29 UTC, eysi09 commented on docs/guides/namespaces.md
> +* This namespace is set at a provider level, so Garden will always deploy the project to that namespace when that developer runs `garden deploy`.
I think we can skip this point.

2022-04-20 14:29 UTC, eysi09 commented on docs/guides/namespaces.md
> +- Specify the default Namespace in your Garden configuration file, using the `defaultNamespace` field under the `environments` specification.
Can you add a link to the `defaultNamespace`, like so:

using the \[\`defaultNamespace\`\](https://docs.garden.io/reference/project-config#environments-.defaultnamespace) field under the...

2022-04-20 14:29 UTC, eysi09 commented on docs/guides/namespaces.md
> +* The `base-hostname` variable gives a unique hostname per project and per developer too. For example, if Jane Doe is working on a project called "Phoenix Project" at a company called Acme, her hostn
Change to:

The `hostname` variable can be re-used in the module configuration. When using the `container` module type, you can e.g. set `hostname: my-service.${var.hostname}` under the [`services.ingress`](https://docs.garden.io/reference/module-types/container#services-.ingresses) field. A similar approach can be used for other module types.

2022-04-20 14:29 UTC, eysi09 commented on docs/guides/namespaces.md
> +* This can also be used in the container module, to add another level of subdomains for individual services. So if the "Phoenix Project" includes a Redis database, the hostname could be `redis.phoeni
Skip this.

2022-04-22 13:12 UTC, sixhobbits commented
@eysi09 - changes are done

2022-04-26 21:03 UTC, eysi09 approved these changes
Great work @sixhobbits! 🚀

2022-05-03 18:32 UTC, merged