Feat: local mode with reverse k8s proxy
garden-io/garden pull request #2949
Opened 2022-05-11 15:36 UTC by vvagaytsev

**What this PR does / why we need it**:
This PR implements a "replacement"  of a Garden service (or a few services) running in a k8s cluster with a locally deployed application (or a few applications).

In order to achieve this, the target container in the k8s cluster is replaced with a proxy container that runs an ssh server. First, the Garden app starts an SSH tunnel between the local service and the proxy container using `kubectl port-forward` command. Next, it starts a reverse-port-forwarding with `ssh` between the remote proxy container's exposed port and the local app's port with `ssh` command.

The Garden supports the new `local-mode` option in `deploy` command and the new `localMode` configuration entry. It allows running a Garden service in "local mode". It means running the application locally and connecting it to the k8s cluster via a proxy container.

See [running-service-in-local-mode.md](https://github.com/garden-io/garden/blob/feat/local-mode-with-reverse-k8s-proxy/docs/guides/running-service-in-local-mode.md) for more details.

2022-05-11 15:41 UTC, Orzelius approved these changes
Note: this is same as https://github.com/garden-io/garden/pull/2880

2022-05-24 08:15 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +export class LocalModeSshPortRegistry {
Good point, I've found [this article](https://www.digitalocean.com/community/tutorials/js-js-singletons) after a quick googling. it looks like we can use something like `SingletonFactory` function. I'll try it out soon.

2022-05-25 08:47 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +export class LocalModeSshPortRegistry {
Hmm... I assumed we would be able to parameterize the singleton factory function and pass the actual instance-producing function as an argument. That looks a bit complicated.

I don't think a generic class can help here. A decorator can be a nice solution, I've found one here: https://github.com/tkuminecz/singleton-decorator
But there are no official releases of that library. Another solution is suggested [here](https://stackoverflow.com/a/40062227/2753863), but there are some typing-related issues.

We can get back to it later, now the boilerplate part of the code is not that huge.

2022-05-31 11:29 UTC, edvald commented on core/src/commands/deploy.ts
> +  "local-mode": new StringsParameter({
I think it's also okay to have it as an alias, same as `--dev/--dev-mode`. I don't mind having multi-character aliases, just as long as the docs look right.

2022-05-31 12:17 UTC, edvald requested changes
Here's a preliminary review, still wanted to poke around a bit more but figured I'd share these comments to start.

2022-05-31 12:17 UTC, edvald commented on core/src/plugins/kubernetes/local-mode.ts
> +      log.debug("Cleaning up .ssh/known_hosts file...")
This message would kinda freak me out, thinking the known_hosts file might have been wiped out. Perhaps something like

```suggestion
      log.debug("Cleaning temporary entries from .ssh/known_hosts file...")
```

2022-05-31 12:17 UTC, edvald commented on core/src/plugins/kubernetes/local-mode.ts
> +      log.warn(`Error cleaning up .ssh/known_hosts file: ${err}`)
```suggestion
      log.warn(`Unable to clean temporary entries from .ssh/known_hosts file: ${err}`)
```

2022-05-31 12:17 UTC, edvald commented on core/src/plugins/kubernetes/local-mode.ts
> +    return []
What is the rationale here? Wouldn't it make more sense to name the injected SSH port something more unique, e.g. `garden-ssh` and always inject it?

2022-05-31 12:17 UTC, edvald commented on docs/guides/running-service-in-local-mode.md
> +TODO: not supported yet
Let's remember to remove this if we're not doing it in the same PR.

2022-05-31 12:17 UTC, edvald commented on core/src/util/retriable-process.ts
> + * The tree data structure reflects the parent-child relationships between the processes.
Could you maybe add some explanation of _why_ this is needed and how it's meant to be used?

2022-05-31 12:28 UTC, edvald commented on core/src/plugins/container/config.ts
> +    containerName: joi.string().optional().description("The k8s name of the remote container (optional)."),
I would suggest omitting this for the container module type, and only using it for kubernetes/helm modules.

2022-05-31 13:06 UTC, vvagaytsev commented on core/src/plugins/container/config.ts
> +    Specifies necessary configuration details of the local application which will replace a target remote service in the k8s cluster.
Removed in https://github.com/garden-io/garden/commit/ceb00d6725de3b8751800565fc9247b63b43a22a

2022-05-31 13:08 UTC, vvagaytsev commented on core/src/plugins/container/config.ts
> +    The target service in the k8s cluster will be replaced by a proxy container with an ssh server running,
Done in https://github.com/garden-io/garden/commit/ceb00d6725de3b8751800565fc9247b63b43a22a

2022-05-31 13:10 UTC, vvagaytsev commented on docs/guides/running-service-in-local-mode.md
> +TODO: not supported yet
Done in https://github.com/garden-io/garden/commit/9c1d0d792225cd7f6038757531d5c8e6c1578ea9

2022-05-31 13:10 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +      log.debug("Cleaned up .ssh/known_hosts successfully!")
Done in https://github.com/garden-io/garden/commit/11a35b8f266ee3a32bf4a7f7bfaab10dd87c3e9f

2022-05-31 13:15 UTC, vvagaytsev commented on core/src/plugins/container/config.ts
> +    Those can be disabled by setting \`services[].localMode.enableLivenessProbe: false\`.
Yes, it does not make sense to restart a proxy container. Also, a user might not want to receive health check requests as noisy traffic while debugging the local service.

I think the good enough default behavior would be to just disable health checks.

2022-05-31 13:21 UTC, vvagaytsev commented on core/src/plugins/kubernetes/container/deployment.ts
> +          "but doesn't have a devMode configuration section! Please check its garden.yml config file."
I think the same is applicable to the `--local-mode` flag. We can run `garden deploy --local` and get lots of noisy warnings too.

2022-05-31 13:55 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +    await pRetry(() => execSync(sshKeyGenCmd, { shell: "/bin/sh" }), {
Good point, I think we do not really need to retry here. I'll also change this to use async execution.

2022-05-31 14:10 UTC, vvagaytsev commented on core/src/plugins/kubernetes/container/deployment.ts
> +    const mode = enableHotReload || enableDevMode ? "dev" : enableLocalMode ? "local" : "normal"
Changed in https://github.com/garden-io/garden/commit/91b2d9a30ef0489ea0c24e2a760366a026dc95f4 :)

2022-05-31 14:11 UTC, vvagaytsev commented on core/src/plugins/container/config.ts
> +    Those can be disabled by setting \`services[].localMode.enableLivenessProbe: false\`.
Updated the docs and removed this unnecessary config entry in https://github.com/garden-io/garden/commit/8526ff7f68754b3f7a3dfd35bfb8aa81c4e84cb9

2022-05-31 14:12 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +      throw new ConfigurationError(`Could not read public key file from path ${filePath}; cause: ${message}`, err)
Done in https://github.com/garden-io/garden/commit/74b774cda45c13a4ebf4013ddd0c5189861cd21c

2022-05-31 14:55 UTC, vvagaytsev commented on core/src/plugins/kubernetes/container/deployment.ts
> +    log.warn({
Done in https://github.com/garden-io/garden/commit/4fa51d41b4736ecc96342a34adc4a8ab77773577

2022-05-31 14:58 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +    return []
Right, let's use own unambiguous port name.

2022-05-31 15:04 UTC, edvald commented on core/src/plugins/kubernetes/container/deployment.ts
> +  if (enableLocalMode && localModeSpec) {
How about when we do something like `garden deploy --dev --local`? Another case could be `garden dev --local=api`, in which case `api` is implicitly in both dev and local mode. Perhaps it makes sense to have local mode take precedence over dev mode?

2022-05-31 16:07 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +    return []
Changed in https://github.com/garden-io/garden/commit/8980c17057caf56b1b4c719e9fbfe29e53a56acf

2022-05-31 16:37 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +    const serviceDirPath = resolve(moduleDirPath, service.name)
Right, simplified in https://github.com/garden-io/garden/commit/3fd0eed31aea2d3e7ad5e8585886d9da525018e8

2022-05-31 16:37 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +      return readFileSync(filePath).toString("utf-8")
Changed to async in https://github.com/garden-io/garden/commit/440ad3e053aaf2626305cb6a1e1449d3fd2d6f22

2022-05-31 16:38 UTC, vvagaytsev commented on core/src/plugins/kubernetes/constants.ts
> +export const reverseProxyImageName = "gardendev/k8s-reverse-proxy:0.0.1-amd64"
Changed in https://github.com/garden-io/garden/commit/93d6756cc3447ea958c9beeb27d5ecb597a4e1c5

2022-05-31 16:52 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +    await pRetry(() => execSync(sshKeyGenCmd, { shell: "/bin/sh" }), {
What is an async alternative here? We need to be sure the process has been completed. Doing it in an async way assumes the implementation of some event handlers for the spawned process, which looks more verbose and cluttered. Any elegant way (or utility method) to await the command execution completion?

2022-06-01 09:19 UTC, vvagaytsev commented on core/src/util/retriable-process.ts
> + * The tree data structure reflects the parent-child relationships between the processes.
Added some explanation in https://github.com/garden-io/garden/pull/2949/commits/5cf1f176cb2aa770d2a262a669c6c49b18ff87f1

2022-06-01 09:29 UTC, vvagaytsev commented
@wojciechka thank you so much for testing this and sharing the feedback! I'll take a closer look at the issue you encountered. I'll also change the code to use `UserKnownHostsFile` - that's a very good point!

2022-06-01 09:42 UTC, vvagaytsev commented on core/src/plugins/container/config.ts
> +    The \`command\` should not depend on the current service or module path.
Actually, this makes no sense. The working directory is the module root, you're right. And it's ok to use both relative and absolute paths. I'll remove this confusing section.

2022-06-01 09:54 UTC, vvagaytsev commented on core/src/plugins/container/config.ts
> +    The \`command\` should not depend on the current service or module path.
Removed this section in https://github.com/garden-io/garden/pull/2949/commits/09c9bc82e23225a345128ce224422cb0fdc6bd7a

2022-06-01 11:52 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +    const serviceDirPath = resolve(moduleDirPath, service.name)
And flattened in https://github.com/garden-io/garden/pull/2949/commits/2254ecbaafcc093b299ef60ed7466271ca531e6f

2022-06-01 12:10 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +    await pRetry(() => execSync(sshKeyGenCmd, { shell: "/bin/sh" }), {
Removed retries in https://github.com/garden-io/garden/pull/2949/commits/df967adba63a371896fb54e2922a5605fdceade0.
Still looking for a better way to execute it with async. Maybe sync exec is just fine here? We cannot proceed until the key pair is generated.

2022-06-01 13:52 UTC, edvald commented on core/src/plugins/kubernetes/local-mode.ts
> +    return []
I would suggest to include a `garden-` prefix for this and most things we inject automatically, makes it a little more clear and lowers risk of conflict.

2022-06-01 13:55 UTC, edvald commented on core/src/plugins/kubernetes/local-mode.ts
> +    const sshDirPath = service.module.localModeSshKeystorePath
What was the reason for adding a property on the GardenModule interface, instead of just computing the value here?

2022-06-01 14:03 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +    return []
Changed in https://github.com/garden-io/garden/pull/2949/commits/09673f6973b7989bab343175d96b17fbcd90ba9c

2022-06-01 14:09 UTC, edvald commented on core/src/plugins/kubernetes/local-mode.ts
> +    await pRetry(() => execSync(sshKeyGenCmd, { shell: "/bin/sh" }), {
The surrounding async method/function won't resolve anyway until the exec is done, just the same with `await exec(...)` and `execSync(...)`.

2022-06-01 14:13 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +    const sshDirPath = service.module.localModeSshKeystorePath
That's a leftover from the initial implementation. Actually, we need a reference to the `.garden` dir here. Looks like it's not available in the current context. We can store `localModeSshKeystorePath` in the `Garden` class and declare it like this: `this.localModeSshKeystorePath = join(this.gardenDirPath, PROXY_CONTAINER_SSH_DIR)`.

How can we easily get access to a `Garden` instance here? One way is to pass `ctx: PluginContext` to the function `createWorkloadManifest`.

2022-06-01 14:22 UTC, edvald commented on core/src/plugins/kubernetes/local-mode.ts
> +    const sshKeygenOutput = execSync(sshKeyGenCmd, { shell: "/bin/sh" }).toString()
Yeah we should make a note of that, and maybe a GitHub issue to follow it up.

2022-06-01 14:23 UTC, edvald commented on core/src/plugins/kubernetes/local-mode.ts
> +    const sshDirPath = service.module.localModeSshKeystorePath
Yeah I see no reason to make a new property to drag along with every Garden class. Just pass `ctx` along as needed and derive the value with `join(ctx.gardenDirPath, PROXY_CONTAINER_SSH_DIR)`.

2022-06-01 15:45 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +    const sshDirPath = service.module.localModeSshKeystorePath
Done in https://github.com/garden-io/garden/pull/2949/commits/50aa66637f3197a8f6ea5b708988d8a4e24ecb01 and https://github.com/garden-io/garden/pull/2949/commits/3128dc5ed353dd30676748b8e26b5e48a3d110f0

2022-06-03 14:10 UTC, vvagaytsev commented
@wojciechka huge thanks for your recent feedback. I've made some new changes and want to share a short update.

> * I did not try to break networking / put computer to sleep and see recovery

I added `-oServerAliveInterval=60` to the ssh command. I tested the recovery by killing kubectl port-forward and ssh reverse port-forward processes. The local mode was able to recover in both cases.

> * I have started UI in separate process and ran sleep 999d as command for localMode as the webpack dev server startup is quite long, but that should not have affected the outcome

Currently, the command is a part of the recoverable process tree `local app -> kubectl port-forward -> ssh reverse port-forward`. So, if the command is provided in the config, then it will be restarted automatically every time the local app dies/stops. Every failure of a process in the tree causes restarting of the process itself and its sub-tree.

Perhaps, we don't this behavior. We can detach the local app command from the recoverable process tree and run it only once if the command is defined in the local mode config. @edvald wdyt?
In the future, we might want to make it more interactive and support manual stopping/starting of the port-forwarding.

> * local mode support for kubernetes module would be great, even if not in first version of this change - I had to delete existing Kubernetes deployment and service in order to use the container Garden module as the garden-generated label selectors were different

We'll consider implementing kubernetes and helm modules support in the first version.

> * The ssh process is modifying ~/.ssh/known_hosts; this is not a major issue, but passing UserKnownHostsFile option to ssh command to store it in ./.garden/ would make it less intrusive

Now it's fixed with `-oUserKnownHostsFile` as you suggested, thank you!

> * I ran into an issue where just running .../garden/bin/garden deploy --local-mode failed to port-forward; see below for more details

I haven't looked into it in detail yet. I will have a closer look next week. I've made some minor which may affect this. So if you have a chance to test it again, that would be great!

2022-06-03 15:18 UTC, edvald commented
> Currently, the command is a part of the recoverable process tree local app -> kubectl port-forward -> ssh reverse port-forward. So, if the command is provided in the config, then it will be restarted automatically every time the local app dies/stops. Every failure of a process in the tree causes restarting of the process itself and its sub-tree.

> Perhaps, we don't this behavior. We can detach the local app command from the recoverable process tree and run it only once if the command is defined in the local mode config. @edvald wdyt?
In the future, we might want to make it more interactive and support manual stopping/starting of the port-forwarding.

Are we restarting the port forward and tunnel when the local app restarts? If so, that does strike me as unnecessary, unless I'm missing something?

2022-06-08 16:23 UTC, vvagaytsev commented on core/src/plugins/kubernetes/container/deployment.ts
> +  if (enableLocalMode && localModeSpec) {
Maybe it makes sense to always prefer the local mode over the dev one.

It looks quite natural to prefer explicitly mentioned service over the match-all flags. For example, if we have a command like
```
garden deploy --dev --local=backend
# or 
```
then it makes sense

2022-06-09 08:21 UTC, vvagaytsev commented
> > Currently, the command is a part of the recoverable process tree local app -> kubectl port-forward -> ssh reverse port-forward. So, if the command is provided in the config, then it will be restarted automatically every time the local app dies/stops. Every failure of a process in the tree causes restarting of the process itself and its sub-tree.
> 
> > Perhaps, we don't this behavior. We can detach the local app command from the recoverable process tree and run it only once if the command is defined in the local mode config. @edvald wdyt?
> > In the future, we might want to make it more interactive and support manual stopping/starting of the port-forwarding.
> 
> Are we restarting the port forward and tunnel when the local app restarts? If so, that does strike me as unnecessary, unless I'm missing something?

Yes, we are. We have the process tree: `local app -> kubectl port-forward -> reverse port-forward`. If any node of the tree dies, then it and all its siblings get restarted. This is ok.

The question is should we keep the local app in that recoverable process tree? I assume we should. Of course, the local app lifecycle can be controlled by a user. So, there is a scenario when the user needs to stop the local app, rebuild it, and rerun it. But in that case, it's better to omit the local app startup command in the local mode config. Otherwise, the local app command will be re-executed by Garden once the app has stopped.

2022-06-09 08:25 UTC, wojciechka commented
> Yes, we are. We have the process tree: `local app -> kubectl port-forward -> reverse port-forward`. If any node of the tree dies, then it and all its siblings get restarted. This is ok.
> 
> The question is should we keep the local app in that recoverable process tree? I assume we should. Of course, the local app lifecycle can be controlled by a user. So, there is a scenario when the user needs to stop the local app, rebuild it, and rerun it. But in that case, it's better to omit the local app startup command in the local mode config. Otherwise, the local app command will be re-executed by Garden once the app has stopped.

@vvagaytsev Wanted to share my perspective on this. Startup of the app may be significant, like 60s or even more. In my case it's webpack dev server that also fetches OpenAPIs and generates code from those and initial generation and compilation of all code is around 1-2 minutes.

So from my perspective it would be great if the app could stay running even if port forwarding gets restarted. However, that's only the one use case I am thinking about, you may be aware of others.

2022-06-09 10:14 UTC, edvald commented
Hmm yeah I'm struggling to think of a good reason to keep the local app in that restartable process tree, and telling people to run the process separately seems counterintuitive to me. Seems the tunnel can live independently and tolerate local app restarts or crashes so there isn't a practical reason to restart the tunnel processes along with the app.

2022-06-09 12:23 UTC, thsig commented on core/src/plugins/kubernetes/container/deployment.ts
> +  if (enableLocalMode && localModeSpec) {
I think we should have local mode take precedence over dev mode.
```
# 1.1 Deploy backend in local mode, all other services in dev mode
garden deploy --dev --local=backend

# 1.2 Deploy all services in local mode (or throw an error)
garden deploy --dev=backend --local

# 2.1 Deploy backend in dev mode, frontend in local mode
garden deploy --dev=backend --local=frontend

# 2.2 Deploy backend and frontend in local mode (or throw an error)
garden deploy --dev=backend --local=backend,frontend

# 3.1 Deploy all services in local mode (or throw an error)
garden deploy --dev --local

# 3.2 Deploy backend and frontend in local mode (or throw an error)
garden deploy --dev=backend,frontend --local=backend,frontend
```
In the cases above labelled with "or throw an error", I could go either way on whether to throw an error or simply make local mode take precedence.

It partly depends on which behaviou is nicer in custom commands, or where a list of service names is generated dynamically. Because of those use-cases, I'm leaning slightly more towards not throwing an error and just making local mode take precendence (the result will be clear to the user once the deploy logs show up).

2022-06-09 14:04 UTC, vvagaytsev commented on core/src/plugins/kubernetes/container/deployment.ts
> +  if (enableLocalMode && localModeSpec) {
Agree, let's always prefer local mode over dev mode in case there are any conflicts. This definitely keeps things simple. Fixed it in https://github.com/garden-io/garden/pull/2949/commits/b66e6dc075ea7511a5912b8961a9045dbd4cf975

2022-06-09 15:32 UTC, edvald commented on core/src/plugins/kubernetes/container/deployment.ts
> +  if (enableLocalMode && localModeSpec) {
👍  all set then!

2022-06-16 14:24 UTC, edvald commented on core/src/plugins/kubernetes/local-mode.ts
> +  export const USER_NAME = "USER_NAME"
I'm not convinced these env var names are sensible. Would it not make sense to prefix things we inject with `GARDEN_`? And perhaps make them more verbose/descriptive. Was there a specific reason for passing the username+ssh public key as an env var?

2022-06-17 08:03 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +  export const USER_NAME = "USER_NAME"
Agree, let's add the `GARDEN_` prefix. I'll rename those and will add some comments.
We generate an SSH key for every local mode service on every Garden run. So we need to pass the public key and the user name to the proxy container to make it accept the connections.

2022-06-17 08:34 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +  export const USER_NAME = "USER_NAME"
Actually, `USER_NAME` and `PUBLIC_KEY` are the standard env vars supported by the [openssh-server](https://docs.linuxserver.io/images/docker-openssh-server). So, we can't rename them.

2022-06-17 12:42 UTC, edvald commented on core/src/plugins/kubernetes/local-mode.ts
> +  const logsPath = join(service.module.path, ".garden", "logs")
I think it's generally better to use a path under `<project root>/.garden`. I actually thought that was already where the logs were going? Also, some duplication of this specific line in the commit, maybe nice to add a little helper, or a property on `ctx`.

2022-06-17 12:50 UTC, edvald commented on core/src/plugins/kubernetes/local-mode.ts
> +    commandString = `${service.module.path}/${commandString}`
Couple of notes here:
1. It's generally preferable to leave the command as an array, instead of stringifying. Making it into a single string can cause issues with argument handling. Sorry I didn't catch that earlier.
2. We shouldn't prefix the path anyway here. We should rather exec with `command[0]` as the _command_, `command.slice(1)` as the _arguments_, and `service.module.path` as the working directory (cwd) for execution.

2022-06-17 13:41 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +  const logsPath = join(service.module.path, ".garden", "logs")
Yes, that's right, `<project root>/.garden/logs` is the correct location.

2022-06-17 13:52 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +  const logsPath = join(service.module.path, ".garden", "logs")
Fixed in https://github.com/garden-io/garden/pull/2949/commits/ec39784ae6a314e024e9e9be8a545489708c2541

2022-06-17 14:33 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local-mode.ts
> +    commandString = `${service.module.path}/${commandString}`
Done in https://github.com/garden-io/garden/pull/2949/commits/3d3a9a968297e0585a40d92f00da524ced48e882

2022-06-20 23:37 UTC, edvald submitted a review, later dismissed

2022-06-21 09:21 UTC, vvagaytsev commented
Thanks for the review @edvald!
There is one more fresh commit to be reviewed: https://github.com/garden-io/garden/pull/2949/commits/18e3e4fac4b2ab367393fc7094c7093c5db502e7
It's about post-rebase corrections for compatibility with core-cloud interactivity.

2022-06-21 10:18 UTC, edvald approved these changes

2022-06-21 12:50 UTC, edvald approved these changes

2022-06-21 12:52 UTC, merged