fix: git repository ownership issue
garden-io/garden pull request #3012
Opened 2022-06-17 10:06 UTC by vvagaytsev

**What this PR does / why we need it**:
This is an additional fix for #2905. The same issue happened with some sub-folder of the git repo in the Garden Cloud testing.

The suggested solution is to always consider any working directory in a git repository as a safe one.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2022-06-17 10:07 UTC, Orzelius approved these changes

2022-06-17 10:25 UTC, thsig requested changes
Good stuff!

While the logic itself looks fine, we're now performing two extra git CLI calls every time we call `vcs.getFiles` (which can happen once for each module when a command is first run).

How about reading the contents of the `safe.directory` block in the git config the first time this method is called, and initialising `this.gitSafeDirs` using the entries from there?

That should mean that after the path is added (e.g. the first time `ensureSafeDirGitRepo` is called on the path) we can almost always return semi-instantly from `ensureSafeGitDirRepo` without having to call git.

I'm mostly mentioning this because we recently became aware that the time/resource cost of all these git CLI calls really adds up for large projects with lots of modules.

2022-06-20 18:41 UTC, eysi09 approved these changes

2022-06-20 18:43 UTC, merged

2022-06-20 18:50 UTC, edvald commented on core/src/vcs/git.ts
> +    await this.ensureSafeDirGitRepo(log, path)
Sorry I'm late to the party here, but I should note that this will add up to hundreds of git calls for certain large projects. I wonder if this could be done more optimally, but maybe that could be included along with other optimizations.

2022-06-21 07:29 UTC, vvagaytsev commented on core/src/vcs/git.ts
> +    await this.ensureSafeDirGitRepo(log, path)
Yes, we can do further optimizations later. Now we read all safe directories from the `.gitconfig` file, this will allow us to avoid extra `git status` calls for the directories which are explicitly marked as safe ones in the `.gitconfig`.

But `git status` will be executed for "normal" repos, i.e. the repos that do not have any ownership issues and should not be marked as safe ones.

We can simply cache the successful git status check results in memory, I did it in https://github.com/garden-io/garden/pull/3014

Of course, if there are any repo ownership changes done while a Garden CLI is running, then we might get the issue again. But restarting the Garden CLI will solve the issue.

2022-06-21 07:54 UTC, vvagaytsev commented on core/src/vcs/git.ts
> +    await this.ensureSafeDirGitRepo(log, path)
One more idea on optimizing this. We can keep the git safe directories in a singleton object. In such case, all `GitHandler` instances will share the same in-memory cache with known safe directories.