fix(core): delete services in reverse dep order
garden-io/garden pull request #3034
Opened 2022-07-05 11:44 UTC by thsig

**What this PR does / why we need it**:

Delete services in reverse dependency order (that is, dependants first) when calling the `delete service` and `delete environment` commands.

**Which issue(s) this PR fixes**:

Fixes #2782.

**Special notes for your reviewer**:

We had previously implemented logic for this in the `resolveDependencies` method of `DeleteServiceTask`, but that code path was never taken (since it was only triggered when a certain CLI option was passed, but for some reason that CLI option was never implemented—this has been cleaned up here).

Also note that the dependency logic here only uses service dependencies and doesn't traverse task dependencies to find transitive service dependencies.

This means that e.g. in the vote project, the `result` service won't be deleted before the `postgres` service, even though `result` transitively depends on `postgres` via the `db-init` task. Adding an explicit service dependency on `postgres` to the `result` service would change this.

If we want to fully replicate the dependency behavior of `DeployTask` in reverse, we'd have to modify the dependency calculation logic there (which wouldn't be a big deal to implement either). Which do we think is the right approach here?

2022-07-05 12:06 UTC, Orzelius commented on core/src/tasks/delete-service.ts
> +  constructor({ garden, graph, log, service, deleteServiceNames }: DeleteServiceTaskParams) {
why even have the `service` parameter here any more if all of them will be deleted anyway?

2022-07-05 12:06 UTC, Orzelius commented on core/src/commands/delete.ts
> +      return new DeleteServiceTask({ garden, graph, log, service, deleteServiceNames })
This can also be taken out of the map I think, (if not I need an explanation on what's going on :small_airplane: )

2022-07-06 11:57 UTC, thsig commented
@edvald: The changes we talked about yesterday have been applied here, so I think we should be good to go.

2022-07-12 07:31 UTC, vvagaytsev approved these changes

2022-07-12 07:32 UTC, vvagaytsev requested changes
Looks like there are some test failures: https://app.circleci.com/pipelines/github/garden-io/garden/12296/workflows/eac4a57b-75e9-40a5-acbd-4eeb83c13b56/jobs/201243

2022-07-12 11:27 UTC, vvagaytsev commented on core/src/actions.ts
> +          deleteServiceNames,
Should the `dependantsFirst` flag be propagated to the action router too?

2022-07-12 11:29 UTC, vvagaytsev commented on core/test/unit/src/commands/delete.ts
> +    expect(deleteOrder).to.eql(["service-a", "service-b", "service-c", "service-d"])
I think this condition is not stable enough. If the services are deleted simultaneously, the final deletion order cannot be predicted. We can use something like this here:
```
const expectedDeletedServices = shuffle(["service-a", "service-b", "service-c", "service-d"])
expect(new Set<string>(deleteOrder)).to.eql(new Set<string>(expectedDeletedServices))
``` 

But that would look redundant as it's equivalent to L152:
```
expect(deletedServices.sort()).to.eql(["service-a", "service-b", "service-c", "service-d"])
```

2022-07-12 11:58 UTC, vvagaytsev commented on core/test/unit/src/commands/delete.ts
> +      expect(deleteOrder).to.eql(["service-c", "service-d", "service-b", "service-a"])
Sometimes this fails with actual value `["service-b", "service-a", "service-c", "service-d"]`.
The dependency graph here looks like this (I omitted `service-` prefix):
```
c -> |
        | -> b -> a
d -> |
```

So, the deletion order would look like this: `((c, d), (b), (a))`. We mocked `deleteService` handler in the test to just write the service name to the list. but `deleteService` handler is called asynchronously, so the completion order might still be unstable.

2022-07-14 08:57 UTC, thsig commented on core/test/unit/src/commands/delete.ts
> +      expect(deleteOrder).to.eql(["service-c", "service-d", "service-b", "service-a"])
I've fixed this now—I had originally intended to use the handwritten module configs for the `DeleteEnvironment` tests too, but was still using the modules from `projectRootB`.

To be extra sure, I ran these on a loop for ~30 repetitions, and never got a test failure. So I think we should be good to go now.

2022-07-14 13:02 UTC, vvagaytsev approved these changes

2022-07-14 13:19 UTC, merged