docs: update with commonly asked questions
garden-io/garden pull request #3045
Opened 2022-07-07 23:13 UTC by thelongshanx

This PR adds/updates guides on how to add permissions for clusters and container registries, and how to templatize DNS records for namespaces

2022-07-08 09:27 UTC, Orzelius approved these changes

2022-07-08 09:27 UTC, Orzelius commented on docs/guides/in-cluster-building.md
> +                    "arn:aws:iam::account-id:role/<k8s_worker_iam_role>"                ]
the formatting is funny on the bracket here and probably the account-id should also be in the carrot parenthesis `<>`

2022-07-08 16:33 UTC, twelvemo requested changes
This is great stuff! I had a couple of comments, but overall love these additional docs!

2022-07-08 16:33 UTC, twelvemo commented on docs/using-garden/iam-permissions.md
> +            "Resource": "<arn identifier>"
Also in full knowledge that this was my code snippet, but i think it would be a bit clearer to put `<arn of the eks cluster>` here.

2022-07-12 01:22 UTC, thelongshanx commented
@twelvemo I've pulled in your changes - thank you so much!

2022-08-01 15:34 UTC, twelvemo commented
Hi @thelongshanx , sorry for the vacation caused delay in the re-review :-) I think there might be some rebase issue here, as there are quite a lot of unrelated changes in the PR now. Can you rebase and push again?

2022-08-22 18:24 UTC, thelongshanx commented
This is a hot git mess, so I'm just gonna make a new branch without the rebase disaster

2022-08-22 18:24 UTC, closed without merging