Remove commented fields from create command outputs
garden-io/garden pull request #3068
Opened 2022-07-22 08:06 UTC by Orzelius

with this addition I'm undoing my very first contribution to garden (as an employee). #2904

* create commands no longer add empty commented fields
* remove `--skip-comments` flag
* update getting-started docs accordingly
* add links do docs on top of generated docs

![image](https://user-images.githubusercontent.com/33936483/180393342-fa55842b-1c37-48e8-82bd-f36a6dd4e9cb.png)

2022-07-22 14:20 UTC, edvald requested changes
Some minor comments, otherwise 👍

2022-07-22 14:20 UTC, edvald commented on core/src/commands/create/create-project.ts
> +    yaml = `# More info and documentation at ${projectDocURL}\n\n${yaml}`
Maybe add a link to the reference docs as well.

2022-07-22 14:20 UTC, edvald commented on core/src/commands/create/create-module.ts
> +    yaml = `# Documentation about ${type} modules at ${moduleTypeUrl}\n\n${yaml}`
```suggestion
    yaml = `# See the documentation and reference for ${type} modules at ${moduleTypeUrl}\n\n${yaml}`
```

2022-07-22 14:20 UTC, edvald commented on core/src/commands/create/create-project.ts
> -    const formattedIgnoreName = chalk.bold.white(".gardenignore")
I still think mentioning the .gardenignore file is good.

2022-07-25 10:27 UTC, Orzelius commented on core/src/commands/create/create-project.ts
> -    const formattedIgnoreName = chalk.bold.white(".gardenignore")
It is still mentioned. You can see from the first few lines in the picture in the pr

2022-07-25 10:58 UTC, Orzelius commented on core/src/commands/create/create-project.ts
> +    yaml = `# More info and documentation at ${projectDocURL}\n\n${yaml}`
sure, why not. Added in [59c0199](https://github.com/garden-io/garden/pull/3068/commits/59c0199a4f5d31df088f3e1c1905176176c449c4)

2022-07-28 08:36 UTC, vvagaytsev approved these changes
LGTM!

2022-07-29 10:57 UTC, edvald approved these changes

2022-07-29 10:57 UTC, merged