support only single dotIgnoreFile
garden-io/garden pull request #3069
Opened 2022-07-22 09:07 UTC by vvagaytsev

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2022-07-22 13:04 UTC, vvagaytsev commented on core/src/vcs/vcs.ts
> +    protected ignoreFile: string,
Should we make this optional `protected ignoreFile?: string`?

2022-07-22 13:07 UTC, vvagaytsev commented on core/src/vcs/git.ts
>      // TODO: change in 0.13 to no longer exclude these
Was this comment about executing `git` command for multiple files? If yes, then we can remove this TODO now.

2022-07-22 13:44 UTC, vvagaytsev commented on core/test/unit/src/garden.ts
> +      const projectRoot = getDataDir("test-projects", "dotignore-custom")
Project `"dotignore-custom"` has been unused, and this case case has been equivalent to the one above (`should respect .gitignore and .gardenignore files`).

Now, this test uses the right project and has the corrected assertions.

2022-07-22 14:21 UTC, edvald commented on core/src/vcs/git.ts
>      // TODO: change in 0.13 to no longer exclude these
Actually this comment can be removed. We no longer plan on changing this behavior.

2022-07-22 14:37 UTC, edvald requested changes
Looks good! It does occur to me though that we should ease the migration here.

Maybe we could add something here: https://github.com/garden-io/garden/blob/9f639397050f1277c93502572ee9c5bcda9ccfb8/core/src/config/base.ts#L117

Basically if we find a Project kind, we do some similar pre-processing as we do with Module kinds. If `dotIgnoreFiles` is set with exactly one value, we print a yellow deprecation warning but map it to the new `dotIgnoreFile` field. If there's more than one value, we throw an error and tell people should specify only one file with the `dotIgnoreFile` field.

2022-07-22 14:37 UTC, edvald commented on core/src/config/project.ts
> +        .example(".gardenignore"),
Maybe the example could be `.gitignore`?

2022-07-22 14:39 UTC, edvald commented
Also, please make sure to add a `BREAKING CHANGE:` clause to the commit, so that we get it in the changelogs later.

2022-07-22 14:48 UTC, vvagaytsev commented on core/src/config/project.ts
> +        .example(".gardenignore"),
Yes, makes sense.

2022-07-25 12:26 UTC, vvagaytsev commented on core/src/vcs/vcs.ts
> +    protected ignoreFile: string,
Actually, it's better to keep it non-optional and supply a default value.

2022-07-25 13:25 UTC, vvagaytsev commented
@edvald I've implemented automated migration, see the latest commits:
* https://github.com/garden-io/garden/pull/3069/commits/3f26eebaa22ba1ce077c62d0c252c505a4fed227 - restored old config field `dotIgnoreFiles`
* https://github.com/garden-io/garden/pull/3069/commits/f9701fb2a7945041adca8d3d61609a9c9de4b07c - implemented automatic remapping + unit test
* https://github.com/garden-io/garden/pull/3069/commits/4aa80578e6e5d9123b957ca56cc22a8410239dd2 - excessive integration tests

What is a good place to print a warning in case if `dotIgnoreFiles` array contains a single value? Function [`prepareResource`](https://github.com/garden-io/garden/blob/9f639397050f1277c93502572ee9c5bcda9ccfb8/core/src/config/base.ts#L117) does not have a logger in its context.

2022-07-25 15:41 UTC, edvald commented
I think it's sensible to pass `log` to the `prepareResource` function, might as well just do that imo.

2022-07-26 10:48 UTC, vvagaytsev commented
@edvald now the deprecation warning is there:
* https://github.com/garden-io/garden/pull/3069/commits/4d13dc7fc3911173283435f2b2bb1f0eea8b7a91 - print the warninig
* https://github.com/garden-io/garden/pull/3069/commits/d0f643c2780b9c7f5958cab4cf208818522addc4 - deduplicate the warning

2022-07-28 11:01 UTC, Orzelius approved these changes
approve for merge permission (I didn't take a look myself, trusting Jon's review)

2022-07-29 10:30 UTC, vvagaytsev commented on core/src/vcs/git.ts
> +        : await git("ls-files", "--ignored", ...lsFilesCommonArgs, "--exclude-per-directory", this.ignoreFile)
@edvald I wanna double-check the old comment "TODO: change in 0.13 to no longer exclude these". Did it mean that we want Git to track the files listed in a .ignore-file?

If yes, then we need to remove this statement.

2022-07-29 10:54 UTC, edvald commented on core/src/vcs/git.ts
> +        : await git("ls-files", "--ignored", ...lsFilesCommonArgs, "--exclude-per-directory", this.ignoreFile)
That TODO no longer applies. We should retain the current behavior and simply remove the TODO comment itself.

2022-08-02 08:57 UTC, vvagaytsev commented
@edvald this is ready for review. If we're fine with the in-memory warnings tracking implemented in https://github.com/garden-io/garden/pull/3069/commits/7a4ca0ff518c031881241407e44a9d99669e3a39, then we can merge it. Please re-review once you have time.

2022-08-02 11:17 UTC, edvald approved these changes

2022-08-02 11:18 UTC, edvald commented
Approved. Please make sure there's a `BREAKING CHANGE` clause in the squashed commit 🙏

2022-08-02 11:27 UTC, merged