WIP: single image docker with many tags
garden-io/garden pull request #3089
Opened 2022-08-02 12:18 UTC by Orzelius

this is WIP

2022-08-02 15:01 UTC, vvagaytsev approved these changes
LGTM, please remember to put a `BREAKING CHANGE` label in the commit message description.

2022-08-02 15:27 UTC, edvald requested changes
Existing changes are good, but you're missing changes to `scripts/push-containers.sh`. That script is run in the release process (as opposed to on every build).

2022-08-02 17:45 UTC, Orzelius commented
> Existing changes are good, but you're missing changes to `scripts/push-containers.sh`. That script is run in the release process (as opposed to on every build). Oh and `scripts/build-containers.sh`, which the former calls.

aha, silly miss from my part. Updated in [edd3193](https://github.com/garden-io/garden/pull/3089/commits/edd31936a55b8bd3f149e63e6de28ae883e1b791).

2022-08-09 12:42 UTC, edvald approved these changes

2022-08-09 12:45 UTC, merged