Graph v2 build tests albert
garden-io/garden pull request #3120
Opened 2022-08-23 15:11 UTC by Orzelius

fix build issues in a couple of unit test modules.

2022-08-23 15:29 UTC, vvagaytsev requested changes
Left a comment, please check it.

2022-08-23 15:29 UTC, vvagaytsev commented on core/test/unit/src/enterprise/event-handlers.ts
> -      expect(deployTask.service.name).to.eql("service-a")
I think it's better to preserve this condition. Otherwise, we'll weaken the test semantics. It can be commented out with a todo-label, or rewritten like `expect(deployTask["service"].name).to.eql("service-a")`

Now the method `cloudEventHandlers.deployRequested(..,)` returns an array of `DeployTask` instead of a single task. So, in future, this will likely be fixed with `expect(deployTask[0].action.name).to.eql("service-a")`.

2022-08-24 06:14 UTC, Orzelius commented on core/test/unit/src/enterprise/event-handlers.ts
> -      expect(deployTask.service.name).to.eql("service-a")
Good catch, fixed in [200a3d4](https://github.com/garden-io/garden/pull/3120/commits/200a3d4496da7dd5d539a8e5b77ef14ee61491d7). I'm actually not sure why I had removed this line originally, probably by accident or it was just lost in the work progress.

2022-08-24 08:03 UTC, vvagaytsev commented on core/test/unit/src/config/template-contexts/module.ts
> +      buildA = graph.getBuild("build-a")
I think we should preserve the dependencies between the actions here. I did something similar in https://github.com/garden-io/garden/pull/3121/files#diff-7dd75283963156981c657ddf2fcaed7827d6a421a11e33f46619c71dfe295e30R76 -- the missing part there is the `graphResult.setResult()` invocation. That will be fixed in the next iteration.

Let's comment out the old code to keep the past context visible. Afaiui, `getService(...)` should be mapped to `getDeploy(...)`.

2022-08-24 08:29 UTC, Orzelius commented on core/test/unit/src/config/template-contexts/module.ts
> +      buildA = graph.getBuild("build-a")
I see, kinda like this c3b401a72a01e9ee1382aa91ec792f16313f117a then?

2022-08-24 09:16 UTC, vvagaytsev commented on core/test/unit/src/config/template-contexts/module.ts
> +      buildA = graph.getBuild("build-a")
Yep, I think so :)

2022-08-24 09:16 UTC, vvagaytsev approved these changes

2022-08-24 10:43 UTC, merged

2022-08-24 10:44 UTC, Orzelius commented
rebased as there's some useful info in the commits and we can squash the collector branch later if we so wish