Fix more action things
garden-io/garden pull request #3264
Opened 2022-09-29 12:43 UTC by Orzelius

Fix some logic and some tests, mostly related to actions and module resolution

Please see individual commits for more detail.

2022-09-30 10:58 UTC, vvagaytsev commented on core/src/graph/actions.ts
> +  return <Executed<T>>(<unknown>results.results.getResult(task)!.result!.executedAction)
I'm not that deep into actions router yet, but should the same fi be applied to `resolveAction(s)` functions in https://github.com/garden-io/garden/blob/graph-v2/core/src/graph/actions.ts#L209 and https://github.com/garden-io/garden/blob/graph-v2/core/src/graph/actions.ts#L248?

2022-09-30 11:04 UTC, vvagaytsev commented on core/test/unit/src/actions.ts
> +      const all = graph.getActions()
Unused variable declaration

2022-09-30 11:05 UTC, vvagaytsev requested changes
Looks good, but I left a couple of comments. Please check.

2022-09-30 11:09 UTC, Orzelius commented on core/test/unit/src/actions.ts
> +      const all = graph.getActions()
good catch, had this left from debugging. [addea3b](https://github.com/garden-io/garden/pull/3264/commits/addea3bace2ad5bd63a7194112487af8725dca9a)

2022-10-06 12:44 UTC, vvagaytsev approved these changes

2022-10-06 12:49 UTC, merged