fix(cloud): fix duplicate event emission
garden-io/garden pull request #3310
Opened 2022-10-19 01:03 UTC by thsig

**What this PR does / why we need it**:

**fix(cloud): fix duplicate event emission**

Before this fix, we were sending each event twice to websocket subscribers in live Cloud sessions.

This is because the `ignoreHost` logic in `DashboardEventStream` expected a `serverHost` without an auth token appended, which was broken when the dashboard auth tokens were introduced a while back. The fix was to simply compare the base server URLs.

**chore(cloud): don't emit client requests as events**

Previously, we were emitting build, test, deploy and task requests on the event bus and handling    them in `processModules`.

This was unnecessarily complicated, and resulted in requests from Cloud being emitted back to it as events (which wasn't the desired behavior for our event logging).

**Which issue(s) this PR fixes**:

Fixes duplicate event logging in the Cloud UI.

**Special notes for your reviewer**:

Both the dashboard and Cloud's logging interface (also when used with interactivity) seem to be working as desired after these changes.

2022-10-19 01:06 UTC, thsig commented on core/src/server/client-router.ts
> +      case "build":
We should get rid of `buildRequested` etc. here eventually—that will require changes on the Cloud side too, though.

So I'm keeping both names (`build` + `buildRequested` etc.) here for compatibility until we've implemented & rolled this out on the Cloud side.

2022-10-19 01:09 UTC, thsig commented on core/src/tasks/test.ts
> +  @pMemoizeDecorator()
This fixes an issue in Cloud where "test X has already passed" would appear twice when running tests via the command palette (since `getTestResult` was being called in `resolveDependencies` and in `process`, resulting in two test status events being emitted).

This only happens when using the command palette, since we call `garden.clearCaches()` in the Cloud request handlers, which clears the task graph cache (that cache prevents the event from getting emitted twice).

Note that we're doing away with a lot of these extra caching layers in 0.13 anyway.

2022-10-19 09:22 UTC, eysi09 commented on core/src/server/client-router.ts
> +        // This will result in a type error if one or more event types is forgotten above.
Nice.

2022-10-19 11:21 UTC, eysi09 requested changes
Awesome! Thanks so much for looking into this.

2022-10-21 09:11 UTC, vvagaytsev commented on core/src/events.ts
>    // Cloud UI events
```suggestion
```

2022-10-21 09:11 UTC, vvagaytsev commented on core/src/events.ts
>    // Cloud UI events
This looks like a dangling comment that can be removed.

2022-10-21 09:59 UTC, vvagaytsev commented on core/src/server/server.ts
> +      // Pipe everything from the event bus to the socket.
How do we define listeners for `this.incomingEvents` now? I can see that we emit some events to that bus, but it looks like we do not have any listeners defined.

2022-10-21 10:36 UTC, vvagaytsev commented on core/src/server/server.ts
> +      // Pipe everything from the event bus to the socket.
The `ClientRouter` is a functional replacement for the `incomingEvents` event bus, isn't it? The `ClientRouter` is called from `addWebsocketEndpoint()` method which, in turn, is called from `/events` endpoint handler.

It looks like `this.incomingEvents` bus can be safely removed.

2022-10-21 10:44 UTC, vvagaytsev commented on core/src/server/server.ts
> +    this.clientRouter = new ClientRouter(this.garden, this.log)
Sounds reasonable. This looks a bit like [feature envy](https://refactoring.guru/smells/feature-envy). Otoh, we have the Cloud requests handling logic placed in a separate component. In some sense that fits the SRP over low-granular composition.

We can leave it as it is now, but attempt to do a bigger refactoring later. I'd like to submit a separate PR for that with some ideas.

There are more places to be refactored in the `GardenServer` class itself. Some methods seem to be too long and hard to read. We can decompose it by splitting the effective request-handling logic and the app/endpoint creation machinery.

2022-10-21 10:45 UTC, vvagaytsev submitted a review, later dismissed
Looks good 👍 I left a few comments, please check :) Let's try to get it merged by Monday. it will be included in `0.12.46` then.

2022-10-25 19:09 UTC, eysi09 submitted a review, later dismissed

2022-10-25 19:59 UTC, thsig commented
We noticed a regression in one place, marking this as a draft until I've had time to look into it.

2022-10-25 22:54 UTC, eysi09 commented on core/src/server/server.ts
> +      // Pipe everything from the event bus to the socket.
I think we actually still need the incoming events bus to handle events from other Garden processes.

2022-10-25 22:55 UTC, eysi09 approved these changes

2022-10-25 22:55 UTC, merged