Graph v2 use exec handlers for test plugin + some Build command fixes
garden-io/garden pull request #3319
Opened 2022-10-21 16:47 UTC by vvagaytsev

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2022-11-10 15:49 UTC, thsig requested changes
Looks good! Had a few suggestions there.

2022-11-10 15:49 UTC, thsig commented on core/test/helpers.ts
> +            // const execBuildAction = prepareExecBuildAction(params)
Delete commented-out stuff here.

2022-11-10 15:49 UTC, thsig commented on core/test/unit/src/commands/build.ts
> +    const buildModuleResult = buildActionResults[`build.${moduleName}`]
Maybe there's a helper somewhere that we can use instead of `build.${moduleName}`? No big deal if not, imho.

2022-11-10 15:49 UTC, thsig commented on core/test/unit/src/commands/build.ts
> +    // TODO-G2: need to check if results.graphResults["build.module-a"]?.outputs still makes any sense.
It does still make sense, but only some plugins make use of it (so I think we can delete this comment).

The `exec` plugin's build action's output type is `{}` (and that's the type of this test case's build action). See:

https://github.com/garden-io/garden/blob/graph-v2/core/src/plugins/exec/config.ts#L30

In contrast, the output type of `container` builds has a bunch of fields:

https://github.com/garden-io/garden/blob/graph-v2/core/src/plugins/container/config.ts#L871-L883

These outputs are available in template strings via `ActionResultContext`, similarly to how module outputs were used in 0.12 for stuff like this:

https://github.com/garden-io/garden/blob/main/examples/vote-helm/vote/garden.yml#L17

2022-11-11 07:58 UTC, vvagaytsev commented on core/test/helpers.ts
>              // and all the other actions from the container conversion.
I updated the comments in the rewritten commit https://github.com/garden-io/garden/pull/3319/commits/bf00343e01547f04b5e9e382e40e2cd7205a1116

2022-11-11 07:58 UTC, vvagaytsev commented on core/test/helpers.ts
> +            // const execBuildAction = prepareExecBuildAction(params)
Done in https://github.com/garden-io/garden/pull/3319/commits/bf00343e01547f04b5e9e382e40e2cd7205a1116

2022-11-11 08:02 UTC, vvagaytsev commented on core/test/unit/src/commands/build.ts
> +    const buildModuleResult = buildActionResults[`build.${moduleName}`]
Good point, done in https://github.com/garden-io/garden/pull/3319/commits/13baeee7b22d6b1bae7c9c68a7f87494f96c7759

2022-11-11 08:04 UTC, vvagaytsev commented on core/test/unit/src/commands/build.ts
> +    // TODO-G2: fix versions
I've updated this comment in https://github.com/garden-io/garden/pull/3319/commits/2bebf83911b9541e0c1c501b6d98bd73661860b4. The version assertions still fail, I'm wondering if it's a bug or some new semantics. I need to dig into that, will do it in the next iteration.

2022-11-11 08:04 UTC, vvagaytsev commented on core/test/unit/src/commands/build.ts
> +    // TODO-G2: need to check if results.graphResults["build.module-a"]?.outputs still makes any sense.
Good to know, thank you! I updated the TODO-comments in https://github.com/garden-io/garden/pull/3319/commits/2bebf83911b9541e0c1c501b6d98bd73661860b4

2022-11-11 08:12 UTC, vvagaytsev commented on core/test/unit/src/commands/build.ts
> +    // TODO-G2: need to check if results.graphResults["build.module-a"]?.outputs still makes any sense.
And how about outputs from `result`? See `results.graphResults["build.module-a"]?.result?.outputs` - could it be different from `results.graphResults["build.module-a"]?.outputs`?

2022-11-11 08:27 UTC, thsig commented on core/test/unit/src/commands/build.ts
> +    // TODO-G2: need to check if results.graphResults["build.module-a"]?.outputs still makes any sense.
The `GraphResult.outputs` field is always initialized from `GraphResult.result.outputs`. It has the same type:

https://github.com/garden-io/garden/blob/graph-v2/core/src/graph/results.ts#L30

And (as far as I can tell) is only initialized here:

https://github.com/garden-io/garden/blob/graph-v2/core/src/graph/nodes.ts#L133

I think the reason this field is here is simply to avoid the awkwardness of `result.result.outputs` when getting at the outputs from a `GraphResult` object.

Maybe @edvald can confirm that was the intent behind copying/duplicating the data here?

2022-11-11 08:28 UTC, thsig approved these changes

2022-11-11 08:43 UTC, merged