WIP: Separate util cfg
garden-io/garden pull request #3357
Opened 2022-11-17 09:33 UTC by Orzelius

2022-11-17 13:30 UTC, stefreak commented on core/src/plugins/kubernetes/config.ts
> +        util: resourceSchema(defaultResources.util, false).description(dedent`
joi allows to pass a function to the `default` method with a `parent` argument like this:

```
   .default((parent) => parent.kaniko)
```

Here it seems to be complicated as we use the `resourceSchema` function, but in general this can be useful to avoid if statements later in the code.
```

2022-11-17 13:35 UTC, Orzelius commented on core/src/plugins/kubernetes/config.ts
> +        util: resourceSchema(defaultResources.util, false).description(dedent`
I think I prefer to keep my schema stupid and account for logic behavior in code. In general that seems to be the pattern in garden.

2022-11-17 13:40 UTC, stefreak commented on core/src/plugins/kubernetes/container/build/common.ts
> +        cpu: millicpuToString(provider.config.resources.util.limits.cpu),
maybe transforming the limits / request config to pod spec could be done in a helper function, as it's repeated

2022-11-17 13:43 UTC, stefreak commented on core/src/plugins/kubernetes/config.ts
> +      cpu: 256,
in the old util pod spec, we only specified limits bot no requests. 

Specifying requests leads to scheduling problems for our customers, the scheduler will reserve this amount of cpu and memory for the util pod (that doesn't need much) even when there is ample space available for other services.

2022-11-17 13:46 UTC, stefreak requested changes
Everything looks good to me, except for introducing requests for the util pod; I think limits are enough, so we don't hog customer's resources

Great stuff! 👍 🥳

2022-11-17 13:53 UTC, Orzelius commented on core/src/plugins/kubernetes/config.ts
> +      cpu: 256,
From the kuberetes doc: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

> If you specify a limit for a resource, but do not specify any request, and no admission-time mechanism has applied a default request for that resource, then Kubernetes copies the limit you specified and uses it as the requested value for the resource.

so it seems people should just set the request to a low value if they want to save on resources

2022-11-17 13:59 UTC, srihas-g commented on core/src/plugins/kubernetes/config.ts
> +      cpu: 256,
I agree with @Orzelius if we don't specify `requests` we can't ensure if util pod can even be scheduled or not. Also specifying `requests` will help our service avoid being throttled on CPU since minimum requested CPU is always made sure to be available for our service, for e.g.

2022-11-17 14:14 UTC, stefreak commented on core/src/plugins/kubernetes/config.ts
> +      cpu: 256,
Ah, I didn't know that, thanks @Orzelius

2022-11-17 14:20 UTC, stefreak approved these changes
Thanks for clarifying that when you don't specify a request, kubernetes will use the limits as requests. I learned something today :)

looks good to me

2022-11-17 14:24 UTC, vvagaytsev commented on core/test/unit/src/plugins/kubernetes/container/build/common.ts
> +                    image: "gardendev/k8s-util:0.5.4",
This value can be replaced with the named constant `k8sUtilImageName` from `core/src/plugins/kubernetes/constants.ts`. Otherwise, the test will get broken on every k8s util image version update.

2022-11-18 09:11 UTC, Orzelius commented on core/src/plugins/kubernetes/container/build/common.ts
> +        cpu: millicpuToString(provider.config.resources.util.limits.cpu),
Good idea [787cd1a](https://github.com/garden-io/garden/pull/3357/commits/787cd1a8b36f3872f1e10f736afb20531ed9f1c9)

2022-11-18 09:20 UTC, Orzelius commented on core/src/plugins/kubernetes/container/build/common.ts
> +        cpu: millicpuToString(provider.config.resources.util.limits.cpu),
I just read your comment again and realized you probably meant this [88bbd59](https://github.com/garden-io/garden/pull/3357/commits/88bbd590b21b40dcbf1988b0535e6d58c9939bcd), but some extra cleanup never hurts

2022-11-18 10:34 UTC, vvagaytsev approved these changes

2022-11-21 08:57 UTC, stefreak approved these changes
🚢 👍

2022-11-21 09:02 UTC, srihas-g commented
Would we also want to enable `[ephemeral-storage](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#configurations-for-local-ephemeral-storage)` as a variable so we satisfy all existing fields for resource requests/limits? 
I don't really know that we need it for this particular case or not though.

2022-11-21 09:26 UTC, stefreak commented on core/src/plugins/kubernetes/container/build/common.ts
> +        cpu: millicpuToString(provider.config.resources.util.limits.cpu),
looks much better now 👍

2022-11-21 11:10 UTC, Orzelius commented
Approve plz, I just squashed the fixup commit

2022-11-21 11:20 UTC, vvagaytsev approved these changes

2022-11-21 11:37 UTC, merged