chore(core): add 'isRecurringUser' to analytics payload + refactor
garden-io/garden pull request #3360
Opened 2022-11-19 10:31 UTC by eysi09

**What this PR does / why we need it**:

This commit adds a 'isRecurringUser' field to the analytics event payload.

I also used the chance to refactor some of the code since it was quite old and had become difficult to maintain and test. Namely:

- Have the factory function initialize the class as opposed to running it after initialisation.
- Simplify the logic around initializing and saving the config.
- Rename types and remove unneeded type casts.
- Add more tests.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2022-11-21 08:27 UTC, mkhq approved these changes
Have a small comment on a left-over TODO (not blocking), otherwise great improvement to this code and tests.

2022-11-21 08:27 UTC, mkhq commented on core/src/analytics/analytics.ts
> +  private segment: any // TODO
Do you want to leave this TODO for later?

2022-12-01 07:46 UTC, eysi09 commented
Depends on #3394

2022-12-01 12:05 UTC, vvagaytsev requested changes
Nice job!  But there are some test failures: https://app.circleci.com/pipelines/github/garden-io/garden/13869/workflows/b7a83b1e-7921-47fa-b33e-9cc446bc572d/jobs/232164
Please, take a look :)

2022-12-01 18:16 UTC, eysi09 commented
> Nice job! But there are some test failures: https://app.circleci.com/pipelines/github/garden-io/garden/13869/workflows/b7a83b1e-7921-47fa-b33e-9cc446bc572d/jobs/232164 Please, take a look :)

Haha, I see what it is. 

The `isCi` flag is returning true because, well, it is CI.

2022-12-02 10:40 UTC, vvagaytsev approved these changes
🚀

2022-12-02 10:40 UTC, merged