feat(jib-container): add maven daemon support as project type
garden-io/garden pull request #3361
Opened 2022-11-21 04:22 UTC by ishantagarwal-x213235

**What this PR does / why we need it**:
Added one more build option in `type:jib-container` to use [Mavend](https://github.com/apache/maven-mvnd#introduction) for faster build processes of maven projects.

User can now use `mavend` to specify in `projectType` for `jib-container` modules.

Eg.
`kind: Module
type: jib-container
name: spring-boot
build:
  projectType: mavend
`

This is useful for maven based projects and aims at providing faster Maven builds, when using jib container module.

2022-11-21 12:47 UTC, vvagaytsev commented
Huge thanks for implementing this @ishantagarwal-x213235! 👍

2022-11-21 12:53 UTC, vvagaytsev requested changes
Great job, thank you so much! 🚀 
I left a comment about `sha256` hashes, please check.

2022-11-21 12:53 UTC, vvagaytsev commented on plugins/jib/mavend.ts
> +    sha256: "0949505fcf42a1765558048451bb2a22e84b3635b1a31dd6191780eeccaa4ada",
Hashes for `darwin_aarch64` and `darwin_amd64` are the same. How did you compute those? There is a [script](https://github.com/garden-io/garden/blob/main/scripts/compute-ext-tool-binary-shas.sh) to compute the sha256 hashes. I got the different values with that script. could you double-check, please?

2022-11-21 14:28 UTC, ishantagarwal-x213235 commented on plugins/jib/mavend.ts
> +    sha256: "0949505fcf42a1765558048451bb2a22e84b3635b1a31dd6191780eeccaa4ada",
you are right `darwin_aarch64 `and `darwin_amd64` should not have same `sha256` . I was actually looking that script to generate `sha256`. 
Thank you so much @vvagaytsev

2022-11-21 16:31 UTC, ishantagarwal-x213235 commented on plugins/jib/mavend.ts
> +    sha256: "0949505fcf42a1765558048451bb2a22e84b3635b1a31dd6191780eeccaa4ada",
@vvagaytsev I have changed the sha256 for all platforms. Could you please check and let me know in case of any issue/concern.

2022-11-22 13:02 UTC, vvagaytsev requested changes
Thanks for updating this @ishantagarwal-x213235!
I've left a few more comments and suggestions. Please take a look.

2022-11-22 13:02 UTC, vvagaytsev commented on plugins/jib/mavend.ts
> +  windows: {
SHA computation script gave me a different value for Windows:
```
./compute-ext-tool-binary-shas.sh https://github.com/apache/maven-mvnd/releases/download/0.8.2/maven-mvnd-0.8.2-windows-amd64.zip
```
printed
`bfe6115b643ecb54b52a46df9e5b790035e54e67e21c10f964c7d58f633b7f22`

2022-11-22 13:02 UTC, vvagaytsev commented on plugins/jib/mavend.ts
> +    sha256: "1991f977d9f73b8fa13a21c062e0fa3bd850e874f2f5682dca1f567548024bc6",
```suggestion
    sha256: "bfe6115b643ecb54b52a46df9e5b790035e54e67e21c10f964c7d58f633b7f22",
```

2022-11-23 07:24 UTC, ishantagarwal-x213235 commented on plugins/jib/mavend.ts
> +    sha256: "1991f977d9f73b8fa13a21c062e0fa3bd850e874f2f5682dca1f567548024bc6",
@vvagaytsev Thank you so much for your feedback. Your suggestion has been incorporated.

2022-11-23 08:21 UTC, vvagaytsev approved these changes

2022-11-23 08:23 UTC, merged

2022-11-23 08:24 UTC, vvagaytsev commented
Looks good! 🚀 Great job, @ishantagarwal-x213235! Thanks for your contribution!