irsa
garden-io/garden pull request #3384
Opened 2022-11-25 17:57 UTC by stefreak

- fix(k8s): make getRolloutStatus work with 0 replicas
- fix(k8s): compareDeployedResources should not ignore manifest hash
- fix(k8s): add manifest-hash annotations also for upsert operations
- feat(k8s): add service account and irsa support for in-cluster-builder

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2022-12-15 12:09 UTC, vvagaytsev requested changes
Thanks, great job! 💪  I've left a few comments and questions, please check.

2022-12-15 12:09 UTC, vvagaytsev commented on core/src/plugins/kubernetes/container/build/buildkit.ts
> +    if (status.remoteResources.length && serviceAccountChanged) {
Minor nit-pick :) Here and in [L413](https://github.com/garden-io/garden/pull/3384/files#diff-e7c65544747fe8f12648a5aa212bca83e7ebb6636cefb76985963f26015b035dR413) we use `.length` as a `boolean` condition, and in [L344](https://github.com/garden-io/garden/pull/3384/files#diff-e7c65544747fe8f12648a5aa212bca83e7ebb6636cefb76985963f26015b035dR344) we use explicit `.length > 0`. I think those checks are equivalent, because `0` is falsey in JS/TS and the `length` property cannot be negative.

I'm just wondering what is the most typescriptic way of writing such expressions. Is there any convention or recommended style?

2022-12-15 12:15 UTC, stefreak commented on core/src/plugins/kubernetes/container/build/common.ts
> +      status.remoteResources.length > 0 && !isEqualAnnotations(serviceAccount, status.remoteResources[0])
No, it's 0 or 1 (depending on wether this is a fresh deployment or updating an existing one).
We only want to cycle the deployment if it's existing, to get the fresh credentials via IRSA.

2022-12-15 12:16 UTC, stefreak commented on core/src/plugins/kubernetes/container/build/common.ts
> +    // `compareDeployedResources` as of today only checks wether the manifest is a subset of the deployed manifest.
```suggestion
    // `compareDeployedResources` as of today only checks whether the manifest is a subset of the deployed manifest.
```

2022-12-15 12:20 UTC, twelvemo requested changes
Reviewed the docs! Thanks for implementing this, this is super useful!
I have two suggestions concerning the structure of the docs as they contain significantly more content now than before:
1. Split into documentation about pulling images and pushing images.
2. For pushing images, keep the existing docs on how to allow all nodes to push to ECR and display using IRSA as an improved and recommended alternative.

2022-12-15 12:20 UTC, twelvemo commented on docs/guides/in-cluster-building.md
> +1. Create an IAM policy that allows your Kubernetes worker nodes to pull images from the ECR registry
```suggestion
1. Create an IAM policy that allows your Kubernetes worker nodes to pull images from the ECR registry. Depending on how you deployed your EKS cluster this might not be necessary, as this policy is attached to the worker nodes by default in some scenarios. For more info please check [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_on_EKS.html).
```

2022-12-15 12:20 UTC, twelvemo commented on docs/guides/in-cluster-building.md
> +2. Create a [web identity IAM role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp_oidc.html), allowing the `garden-in-cluster-builder` service accounts managed by Garden to
I think we should keep the current documentation on how to add a policy to ECR that allows the worker nodes role push access to ECR. IRSA is another, more secure way of handling this, but the original option is still feasible especially for AWS accounts only used for development. What do you think?

2022-12-15 12:20 UTC, twelvemo commented on docs/guides/in-cluster-building.md
> +Create this IAM policy to allow the Kubernetes nodes to pull images from your ECR repositories:
```suggestion
If not already present, create this IAM policy to allow the Kubernetes nodes to pull images from your ECR repositories:
```

2022-12-15 12:20 UTC, twelvemo commented on docs/guides/in-cluster-building.md
> +        eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/<web-identity-role-name>
So nice 🎉

2022-12-15 12:23 UTC, stefreak commented on docs/guides/in-cluster-building.md
> +2. Create a [web identity IAM role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp_oidc.html), allowing the `garden-in-cluster-builder` service accounts managed by Garden to
OK, I'll create a new guide for IRSA then.

I decided against that initially as almost always the ECR registry will be used for production deployments.

But at the same time I acknowledge that there is a trade off between ease of setup and security here.

2022-12-15 12:28 UTC, twelvemo commented on docs/guides/in-cluster-building.md
> +2. Create a [web identity IAM role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp_oidc.html), allowing the `garden-in-cluster-builder` service accounts managed by Garden to
But since we are suggesting IAM resource based policies in ECR we are only allowing push access to specific repositories. And the production ECR registry could also be in another account.

2022-12-15 13:30 UTC, stefreak commented on core/src/plugins/kubernetes/container/build/common.ts
> +  return JSON.stringify(a1) === JSON.stringify(a2)
good point, using lowdash's `isEqual` now

2022-12-16 17:54 UTC, stefreak commented on docs/guides/in-cluster-building.md
> +2. Create a [web identity IAM role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp_oidc.html), allowing the `garden-in-cluster-builder` service accounts managed by Garden to
changed this

2022-12-16 17:58 UTC, stefreak commented on docs/guides/in-cluster-building.md
> +1. Create an IAM policy that allows your Kubernetes worker nodes to pull images from the ECR registry
Added a link to these docs. thanks for the good feedback!

2022-12-18 14:09 UTC, srihas-g commented on core/src/plugins/kubernetes/container/build/common.ts
> +    // if the service account changed, all pods part of the deployment must be restarted
what does `changed` mean here, name of the service account or the metadata associated to it?



Aren't credentials mounted via serviceAccount tokens in pods which are projected volumes? which means changing annotations doesn't need to restart pods to apply changes I believe.

I think Secret token was removed from serviceAccount object to make it dynamic since tokens are static and don't have a TTL.

source: https://kubernetes.io/docs/concepts/storage/projected-volumes/#serviceaccounttoken

2022-12-20 09:03 UTC, stefreak commented on core/src/plugins/kubernetes/container/build/common.ts
> +    // if the service account changed, all pods part of the deployment must be restarted
@srihas-g yes that's right. But this is specific to make IRSA work; if you change or add the IRSA annotation on the service account the pods need to be re-created to receive updated `AWS_*` environment variables.

2023-05-04 22:50 UTC, jamesloosli commented
This PR solves an issue we're having as well.

Any chance this will make the next release?

2023-05-05 15:03 UTC, stefreak commented
@jamesloosli I absolutely want to finish this but we won't make it before the 0.13 release (will happen this month).

2023-05-22 17:42 UTC, stefreak commented
Changed the base back to main, as this would need to land in main and not 0.12

2023-08-04 23:12 UTC, highb commented
@stefreak @twelvemo Any ideas of when this PR will land and ship? This would be a massive improvement for our security posture during in-cluster builds.

2023-08-07 07:34 UTC, stefreak commented
@highb right now we are focused on bug fixes and stability improvements– but this is definitely something I want to look back into in the coming months.
Sorry for the delay here.

2023-11-01 17:22 UTC, twelvemo commented
Picking this up again now and also making sure this works with GCP workload identity for the in-cluster builders as well.

2023-11-14 10:12 UTC, stefreak commented on core/test/integ/src/plugins/kubernetes/container/build/build.ts
> +      expect(isEqualAnnotations(originalServiceAccount, status.remoteResources[0]))
I'm not sure if expect will actually fail if you do not explicitly assert for true 
```suggestion
      expect(isEqualAnnotations(originalServiceAccount, status.remoteResources[0])).to.be.true
```

2023-11-14 10:32 UTC, stefreak reviewed
Looks good to me 👍

2023-11-14 10:32 UTC, stefreak commented on images/skopeo/garden.yml
> +image: gardendev/skopeo:1.41.0-4
We do not seem to reference this image from Garden, but this can be cleaned up in a separate PR

2023-11-14 10:32 UTC, stefreak commented on core/test/integ/src/plugins/kubernetes/container/build/build.ts
> +      expect(isEqualAnnotations(originalServiceAccount, status.remoteResources[0]))
We should install https://www.npmjs.com/package/eslint-plugin-chai-expect

2023-11-14 12:28 UTC, twelvemo commented on core/test/integ/src/plugins/kubernetes/container/build/build.ts
> +      expect(isEqualAnnotations(originalServiceAccount, status.remoteResources[0]))
Will create a new PR because some existing tests fail the new linter rules.

2023-11-14 12:45 UTC, stefreak commented on core/test/integ/src/plugins/kubernetes/container/build/build.ts
> +      expect(isEqualAnnotations(originalServiceAccount, status.remoteResources[0])).to.be.true
I'm ok with this, but if the test fails this will give a better error message with the actual difference:
```suggestion
      expect(isEqualAnnotations(originalServiceAccount)).to.equal(status.remoteResources[0])
```

2023-11-14 15:19 UTC, TimBeyer commented on core/test/integ/src/plugins/kubernetes/container/build/build.ts
> +      expect(isEqualAnnotations(originalServiceAccount, status.remoteResources[0])).to.be.true
This doesn't really work like that since `isEqualAnnotations` is a function that takes two parameters, and it checks the following
```
  const a1 = r1.metadata.annotations !== undefined ? r1.metadata.annotations : {}
  const a2 = r2.metadata.annotations !== undefined ? r2.metadata.annotations : {}
  return isEqual(a1, a2)
```

So I think what would be needed is 
```
expect(originalServiceAccount.metadata.annotations).to.eql(status.removeResources[0].metadata.annotations)
```

`to.equal` is strict equality btw so not a good match here.

2023-11-14 15:20 UTC, TimBeyer commented on core/test/integ/src/plugins/kubernetes/container/build/build.ts
> +      expect(isEqualAnnotations(originalServiceAccount, status.remoteResources[0])).to.be.true
I see that change was already fixed so I'll go ahead and resolve that now :)

2023-11-14 15:46 UTC, vvagaytsev approved these changes

2023-11-14 16:13 UTC, merged

2023-11-15 09:37 UTC, stefreak commented on core/test/integ/src/plugins/kubernetes/container/build/build.ts
> +      expect(isEqualAnnotations(originalServiceAccount, status.remoteResources[0])).to.be.true
Ah yes, my snippet was flawed but anna correctly used deep.equal on just the annotations; That should work fine 👍