feat(k8s): custom nodeSelector for util pods
garden-io/garden pull request #3391
Opened 2022-11-29 13:56 UTC by Walther

**What this PR does / why we need it**:

Enables customizing `nodeSelector` requirements for the `garden-util` pods when using `kaniko` in kubernetes.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2022-11-29 14:12 UTC, Walther commented on core/src/plugins/kubernetes/container/build/common.ts
>    }
Do you think it is okay to keep this here as it has been so far, or should we refactor this to `kaniko.ts` specifically?

2022-11-29 14:13 UTC, Walther commented on core/test/unit/src/plugins/kubernetes/container/build/common.ts
> +    })
related to above; if we want to refactor the configuration from `common.ts` to `kaniko.ts`, we could also move these tests respectively

2022-11-30 09:03 UTC, stefreak requested changes
Thanks for the good work, only had some minor comments 👍

2022-11-30 09:03 UTC, stefreak commented on docs/reference/providers/kubernetes.md
> +      # certain components, for example autoscalers. Same annotations will be used for each util pod unless they are
👍

2022-11-30 09:03 UTC, stefreak commented on core/src/plugins/kubernetes/config.ts
> +          nodeSelector: joiStringMap(joi.string()).description(
maybe let's add a hint to the other `nodeSelector` config flag, that `kaniko.nodeSelector` will be applied to the util container unless the `kaniko.util.nodeSelector` is specified (Similar to the description of `tolerations` and `annotations`).

2022-11-30 10:44 UTC, Orzelius reviewed
I have nothing to add to @stefreak review. I'm really impressed with how fast you got this done

2022-11-30 11:45 UTC, Walther commented on core/src/plugins/kubernetes/config.ts
> +          nodeSelector: joiStringMap(joi.string()).description(
Added! Unified some of the wording while at it.

2022-11-30 12:02 UTC, Orzelius approved these changes

2022-11-30 12:06 UTC, stefreak approved these changes
🥳

2022-11-30 12:08 UTC, Walther commented on core/src/plugins/kubernetes/container/build/common.ts
>    }
Based on slack conversations, let's do the refactor later so we can get this feature into the next release window quickly.

2022-11-30 15:29 UTC, merged