WIP: fix: send a periodic ping over the websocket for exec
garden-io/garden pull request #3395
Opened 2022-12-01 14:15 UTC by TimBeyer

**What this PR does / why we need it**:

Currently it can happen that the websocket connection is timed out somewhere in the network, and no error event is triggered. Garden believes something is still executing, and never receives the information about completion or failure. This sends a periodic ping so that hopefully the connection stays alive.

As an extra step we could implement the full timeout logic in https://github.com/websockets/ws#how-to-detect-and-close-broken-connections

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2022-12-01 15:02 UTC, agates4 commented
I've ran our long build command with this version of Garden and I've confirmed it results in accurately reporting the results back to our shell! 
LGTM, as far as fixing the issue in https://github.com/garden-io/garden/issues/3324

2022-12-05 11:38 UTC, vvagaytsev approved these changes

2022-12-05 12:06 UTC, vvagaytsev requested changes
Looks good! I left a couple of comments/questions, please take a look.

2022-12-05 12:06 UTC, vvagaytsev commented on core/src/plugins/kubernetes/api.ts
> +      ws.emit("error", new Error("Lost connection to the Kubernetes WebSocket API (Timed out)"))
Should we include the timeout value in the error message?

2022-12-05 12:06 UTC, vvagaytsev commented on core/src/plugins/kubernetes/api.ts
> +        reject(err)
Should `done` get any value here?

2022-12-05 12:41 UTC, TimBeyer commented on core/src/plugins/kubernetes/api.ts
> +        reject(err)
It did not previously and I think that's fine.
`done` is only relevant once the `execHandler` is running and different callbacks might get called that only need to resolve once.
In this `try/catch` block, the only way we throw is if the initialization of the `exec` was interrupted and once that is the case, none of the other completion handlers will be triggered anymore.

2022-12-05 12:45 UTC, vvagaytsev commented on core/src/plugins/kubernetes/api.ts
> +      ws.emit("error", new Error("Lost connection to the Kubernetes WebSocket API (Timed out)"))
Yes, let's add it.

2022-12-05 13:22 UTC, TimBeyer commented on core/src/plugins/kubernetes/api.ts
> +      ws.emit("error", new Error("Lost connection to the Kubernetes WebSocket API (Timed out)"))
Done

2022-12-05 13:24 UTC, vvagaytsev approved these changes

2022-12-05 13:28 UTC, merged

2022-12-07 16:50 UTC, agates4 commented
Thanks for the really quick turnaround on this fix. Is this something that would be released in `0.12.48`? This currently **blocks** our ability to build our production images