chore: upgrade gcloud cli and install gke auth plugin
garden-io/garden pull request #3431
Opened 2022-12-09 14:55 UTC by Walther

**What this PR does / why we need it**:
Related to changes outlined in https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

**Which issue(s) this PR fixes**:

More task details in Asana.

**Special notes for your reviewer**:

2022-12-12 17:29 UTC, stefreak approved these changes
👍

2022-12-12 17:42 UTC, stefreak commented on images/circleci-runner/Dockerfile
> -FROM google/cloud-sdk:390.0.0 as gcloud
I think this one needs a tag bump in `images/circleci-runner/garden.yml` and then also in the `.circleci/config.yml`

2022-12-12 17:43 UTC, stefreak requested changes
`images/circleci-runner` needs a version bump (see comment) and for the other images I'm not 100% sure if there are additional, similar TODOs

2022-12-15 09:42 UTC, vvagaytsev commented
I've made some extra changes:
* bumped `circleci-runner` image version in https://github.com/garden-io/garden/pull/3431/commits/ad0302fa443bc1a8779758034b3277ba48f4ca38, built and pushed the new image to the Docker hub
* Updated the CircleCI config to use the new image in https://github.com/garden-io/garden/pull/3431/commits/c0995d22672fdb01a37d708f4ee99e45820f2e75
* Updated GCloud SDK version in the CircleCI config in https://github.com/garden-io/garden/pull/3431/commits/ae0da5bb5a1887db6ebe7e7d82067fda36831fc1

A similar GCloud SDK version update was done in #3013 and in its patch PR #3037.

2022-12-15 09:44 UTC, stefreak approved these changes
LGTM 👍

2022-12-15 10:21 UTC, merged