improvement(cloud): automate remote project creation
garden-io/garden pull request #3462
Opened 2022-12-20 19:34 UTC by mkhq

**What this PR does / why we need it**:

This is an experimental integration with Garden Cloud that automates cloud project creation for a signed-in user.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2022-12-21 10:29 UTC, eysi09 requested changes

2022-12-21 10:29 UTC, eysi09 commented on core/src/cloud/api.ts
> +    if (response.status === "error" || (response.status === "success" && response.data.length !== 1)) {
Only check: `if (response.data.length !== 1` and log an informative and actionable error.

2022-12-21 10:29 UTC, eysi09 commented on core/src/commands/cloud/secrets/secrets-list.ts
> +      throw new EnterpriseApiError(`Project ${garden.projectName} is not a Garden Cloud project`, {})
Replace "Garden Cloud" with `${getCloudDistributionName(domain}`. Also in other places.

2022-12-21 10:29 UTC, eysi09 commented on core/src/commands/cloud/users/users-list.ts
> +      throw new EnterpriseApiError(`Project ${garden.projectName} is not a Garden Cloud project`, {})
Also update string.

2022-12-21 10:29 UTC, eysi09 commented on core/src/cloud/api.ts
> +    if (response.status === "error" || (response.status === "success" && response.data.length !== 1)) {
Where we catch the error in the Garden class we need to check if it's a "duplicate project error", and if so, fail hard with, again, an actionable message for the user. 

This is what happened, this is what you need to do.

2022-12-21 21:42 UTC, mkhq commented on core/src/cloud/api.ts
> +    if (response.status === "error" || (response.status === "success" && response.data.length !== 1)) {
Opted for a warning message instead and continuing without a project configured since that's how other errors are handled when we cannot use a project.

2022-12-22 10:34 UTC, eysi09 approved these changes

2022-12-22 10:36 UTC, merged