Run and Test command rework
garden-io/garden pull request #3505
Opened 2023-01-12 12:54 UTC by edvald

This makes several changes to commands and fixes related issues uncovered in the process. The idea is for `garden run ...` to no longer be a category of commands, and instead we get `garden run` as a command of its own, analogous to the build, deploy and test commands.

Individual commits reveal more detail but here's a summary of changes:

* The `run service/deploy` command has been removed.
* The `run module/build` command has been removed.
* The `run workflow` command has been renamed to `run-workflow` (note the dash).
* The `run test` command has been removed and its specific functionality moved to the `test` command (mainly the `--interactive` flag).
* The `run task` command is now simply `run`.
* Fixed several issues related to the `test` command. It now works properly for e.g. the `demo-project` example.

There's more work to be done around unit tests and updating the Run command, but it'd be good to get this checkpoint merged.

2023-01-13 14:30 UTC, thsig requested changes
Great stuff! Feels good to see the command list tidied up.

Had a few minor comments there (mostly text-related).

2023-01-13 14:30 UTC, thsig commented on core/src/commands/get/get-test-result.ts
> +      "The test to run. If using modules, specify the module name here and the test name from the module in the second argument",
```suggestion
      "The name of the test. If this test belongs to a module, specify the module name here instead, and specify the test name from the module in the second argument.",
```
Suggesting this change since here we're fetching the result, not running the test.

2023-01-13 14:30 UTC, thsig commented on core/src/commands/get/get-test-result.ts
> +    help: "The name of the test to run in a module.",
```suggestion
    help: "When the test belongs to a module, specify its name here (i.e. as the second argument).",
```

2023-01-13 14:30 UTC, thsig commented on core/src/commands/run.ts
> +    // if (opts.interactive && opts.watch) {
Remove commented-out code.

2023-01-13 14:30 UTC, thsig commented on core/src/config/task.ts
> +    Set to false if you don't want the task's result to be cached. Use this if the task needs to be run any time your project (or one or more of the task's dependants) is deployed. Otherwise the task
Out of scope for this PR, but since the line appears in the diff I thought I'd ask the question:

Should we start referring to tasks as Runs and services as Deploys in the docstrings for the old module-related schemas that use the old nomenclature?

I think it may be clearer for the user to just always say Deploys and Runs, and to speak of "tasks" and "services" as deprecated aliases for Deploys / Runs.

2023-01-13 14:30 UTC, thsig commented on core/src/plugin/base.ts
> +    success: joi.boolean().required().description("Whether the module was successfully run."),
```suggestion
    success: joi.boolean().required().description("Whether the Run was successful."),
```
Also: We should probably override the description strings in `testResultSchema` to refer to Tests instead of Runs, right?

2023-01-13 14:30 UTC, thsig commented on core/src/plugin/base.ts
> +    startedAt: joi.date().required().description("When the module run was started."),
```suggestion
    startedAt: joi.date().required().description("When the Run was started."),
```

2023-01-13 14:30 UTC, thsig commented on core/src/plugin/base.ts
> +    completedAt: joi.date().required().description("When the module run was completed."),
```suggestion
    completedAt: joi.date().required().description("When the Run was completed."),
```

2023-01-13 14:30 UTC, thsig commented on core/src/plugin/base.ts
> +    log: joi.string().allow("").default("").description("The output log from the run."),
```suggestion
    log: joi.string().allow("").default("").description("The output log from the Run."),
```

2023-01-13 14:30 UTC, thsig commented on core/src/commands/run.ts
> +    // if (opts.interactive && initialTasks.length !== 1) {
Remove commented-out code.

2023-01-16 13:25 UTC, edvald commented on core/src/commands/run.ts
> +  // "interactive": new BooleanParameter({
I'd actually like to keep this. It related to a TODO comment above.

2023-01-16 13:26 UTC, edvald commented on core/src/commands/run.ts
> +    // if (opts.interactive && opts.watch) {
Same as last comment, keeping it around.

2023-01-16 13:28 UTC, edvald commented on core/src/config/task.ts
> +    Set to false if you don't want the task's result to be cached. Use this if the task needs to be run any time your project (or one or more of the task's dependants) is deployed. Otherwise the task
I agree with that. I haven't been chasing everything as I go, more opportunistically. I figure it's best if we starting tracking this down more deliberately once most changes are settled down.

2023-01-16 13:31 UTC, edvald commented on core/src/plugin/base.ts
> +    success: joi.boolean().required().description("Whether the module was successfully run."),
This schema doesn't actually refer specifically or only to the `Run` action type. It is also used for Test actions.

2023-01-16 13:31 UTC, edvald commented on core/src/plugin/base.ts
> +    log: joi.string().allow("").default("").description("The output log from the run."),
This is fine as-is (see prior comment).

2023-01-16 13:38 UTC, thsig approved these changes

2023-01-16 13:39 UTC, merged

2023-01-16 14:02 UTC, Orzelius commented on core/src/commands/test.ts
> +
should probably delete this