fix(kubernetes): fix bugs #3331 and #3535
garden-io/garden pull request #3537
Opened 2023-01-17 17:37 UTC by stefreak

For #3331:
- Stream logs to CLI to make them visible in verbose log level (`-l3`).

For #3535:
- Detect that pod has been killed by listing Pod events after the Pod
  has completed, and throwing an exception when the Pod has been killed
  to prevent reporting successful status in case the tests did not
  actually run to completion.

For #3331, #3535:
- improve the error message to be more on-point and convey more
  contextual information

co-authored-by: eysi09 <eysi09@users.noreply.github.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-01-17 17:38 UTC, stefreak commented on core/src/plugins/kubernetes/run.ts
> +    const { log, remove, tty, events } = params
```suggestion
    const { log, remove, tty } = params
```

2023-01-17 17:46 UTC, stefreak commented on core/src/plugins/kubernetes/run.ts
> +      }
```suggestion
      if (some(events.items, (event) => event.reason === "Killing")) {
        const details: PodErrorDetails = { podEvents: events }
        throw new NotFoundError("Pod has been killed or evicted.", details)
      }
```

2023-01-17 17:47 UTC, stefreak commented on core/src/plugins/kubernetes/run.ts
> +async getPodEvents(): Promise<CoreV1EventList | undefined> {
```suggestion
async getPodEvents(): Promise<CoreV1EventList> {
```

2023-01-18 10:01 UTC, eysi09 requested changes
Great job! This is an awesome improvement. 

Had a handful of minor comments.

2023-01-18 10:01 UTC, eysi09 commented on core/src/plugins/kubernetes/run.ts
> +          // TODO: Add section about how to prevent this by using the annotation
Feels like we should either add this now or remove the comment.

2023-01-18 10:56 UTC, stefreak commented on core/src/plugins/kubernetes/run.ts
> +        statusLine.setState(renderOutputStream(msg, `${this.podName}.${this.getMainContainerName()}`))
the command could be the same for multiple test tasks (e.g. integ and unit tests would both have the command `npm`). maybe the name of the test / the task would be best, what do you think? that would be `integ` or `unit`, or it could be `type.name`, e.g. `test.integ`

2023-01-18 11:15 UTC, eysi09 commented on core/src/plugins/kubernetes/run.ts
> +        statusLine.setState(renderOutputStream(msg, `${this.podName}.${this.getMainContainerName()}`))
We'll make `type.name` the section name with #3254.

So something like:

```
 ℹ test.e2e [verbose]      → [test-e2e-runner-e2e-1415ec.main]: > node_modules/mocha/bin/mocha tests/integ/test.js
 ```
 
In general we'll have information about the Garden action to the left of the arrow output from the underlying process to the right. 

But for this case, we could just leave it empty. We already print the following before starting the test:

```
ℹ e2e-runner [verbose]      → Starting Pod test-e2e-runner-e2e-1415ec with command 'npm run test:integ'
```

2023-01-18 11:20 UTC, eysi09 commented on core/src/plugins/kubernetes/run.ts
> +        statusLine.setState(renderOutputStream(msg, `${this.podName}.${this.getMainContainerName()}`))
IMO these are our options:

**1: Print pod name and container name**

``` 
ℹ e2e-runner [verbose]      → [test-e2e-runner-e2e-1415ec.main]: Test 0
```

**2: Print nothing**

``` 
ℹ e2e-runner [verbose]      → Test 0
```

**3: Print command**

``` 
ℹ e2e-runner [verbose]      → [npm]: Test 0
```

**3: Print full command**

``` 
ℹ e2e-runner [verbose]      → [npm run test:integ]: Test 0
```

**4: Print how it's execute**

``` 
ℹ e2e-runner [verbose]      → [kubectl exec]: Test 0
```

**5: Print how it's executed and command**

``` 
ℹ e2e-runner [verbose]      → [kubectl exec 'npm run test:integ']: Test 0
```

I think I'm leaning towards 2. (we already print the "Starting Pod...") line above or 3. 

What do you think?

2023-01-18 13:54 UTC, stefreak commented on core/src/plugins/kubernetes/util.ts
> +  return events
I discovered that there is already some code to fetch and display events in an error message.

This code can be found in `getResourceEvents` of `core/src/plugins/kubernetes/status/workload.ts`.

Will change this PR to share the same code

2023-01-19 11:49 UTC, stefreak commented on core/src/plugins/kubernetes/run.ts
> +          if (logs !== undefined && logs.length > 0) {
I felt like changing it because `!!""` gives true and `!![]` gives false. I think using `!!` can be really confusing, for subtle things like that. As the double-not operators are used in several places in this file, I decided nowo to keep it though. But IMO we should avoid using it if possible and go with a more explicit variant

2023-01-19 14:58 UTC, stefreak commented on core/src/plugins/kubernetes/run.ts
> +        statusLine.setState(renderOutputStream(msg, `${this.podName}.${this.getMainContainerName()}`))
At the moment, we do not print the task type and name, but only the module name on the left side.

I think optimal would be to log something like 
```
ℹ module [verbose]      → [test.name]: node_modules/mocha/bin/mocha tests/integ/test.js
```

for now, until #3254 is implemented and it looks like

```
ℹ test.name [verbose]      → > node_modules/mocha/bin/mocha tests/integ/test.js
```

But it is difficult to achieve, as we do not have the type of the task nor the name of the task in the location we are processing the logs.

This would be really easy to achieve when implemented in the `ActionRouter`, which I'll try next because then we can have the best log message and it's consitent between all modules.

2023-01-19 15:41 UTC, stefreak commented on core/src/plugins/kubernetes/run.ts
> +        process.stdout.write(`${msg}\n`)
In https://github.com/garden-io/garden/commit/15e8acedf9267c2f0960154b32ae3dde224a9b40 I've moved the code that calls `statusLine.setState` to the `ActionRouter`, which makes this much more clear so I think a comment is not necessary anymore, at least not here

That is, as long you find the change in this commit good – otherwise we might need a comment after all 👍

2023-01-19 16:01 UTC, stefreak commented on core/src/plugins/kubernetes/container/build/kaniko.ts
> -    statusLine.setState(renderOutputStream(line.toString(), "kaniko"))
In Kaniko, sending logs to CLI never worked apparently, as outputStream was unused.

2023-01-19 18:25 UTC, stefreak commented on plugins/jib/index.ts
> +              ctx.events.emit("log", { timestamp: new Date().getTime(), data: line })
`jib` plugin logs apparently were apparently never sent to garden cloud, if I didn't overlook something

2023-01-20 12:23 UTC, Orzelius commented
This is the most beautiful pr and discussion I've seen on garden project to date

2023-01-21 12:58 UTC, eysi09 commented on core/src/plugins/kubernetes/run.ts
> +          if (logs !== undefined && logs.length > 0) {
Yeah it's a pattern we use quite frequently and feels safe when we know the types. 

Another alternative is to use something like lodash' `isEmpty` which works consistently across types.

2023-01-21 14:14 UTC, eysi09 commented on core/src/plugins/kubernetes/run.ts
> +        statusLine.setState(renderOutputStream(msg, `${this.podName}.${this.getMainContainerName()}`))
I absolutely agree that we should show the action type but let's stick with introducing that in #3254. 

I personally think the latest version is less informative. The whole idea is to show users what's happening under the hood when using the `verbose` log level. 

The format should be:

```console
<Garden concepts, e.g. module name> → [information about tool being used]: <output from tool being used>
```

When going from `info` to `verbose` level, I find it useful to know that e.g. local Docker is being used to run a given build, rather than, say, Kaniko.

This is more informative:

```console
frontend [verbose]        → [local-docker]: #1 [internal] load build definition from Dockerfile
```

...than this:

```console
frontend [verbose]        → [build]: #1 [internal] load build definition from Dockerfile
```

And again, we want to show the action type as well, and we will with #3254 which we've already started hacking on:

```console
build.frontend [verbose]        → [local-docker]: #1 [internal] load build definition from Dockerfile
```

I don't think it makes sense to change the current behaviour, which is based on user feedback, and then undo that again in a few weeks.

Note that I'm only talking about the log output here. I agree that at the code level the current implementation isn't great and it's awkward to have to remember to set the status line everywhere in the plugin handlers. We can definitely fix that, but it shouldn't be at the cost of making `verbose` logs less informative.

2023-01-22 16:21 UTC, edvald commented on core/src/plugins/kubernetes/run.ts
> +        statusLine.setState(renderOutputStream(msg, `${this.podName}.${this.getMainContainerName()}`))
Just to further this point, I actually think `[local-docker]` isn't the best prefix. I'd much rather see something like `[docker build]` because that's actually what's running and is less ambiguous.

2023-01-23 12:27 UTC, stefreak commented on core/src/plugins/kubernetes/run.ts
> +        statusLine.setState(renderOutputStream(msg, `${this.podName}.${this.getMainContainerName()}`))
I think I need a pairing session with someone who's into the logging so we come to an okay solution here more quickly.

2023-01-23 14:16 UTC, stefreak commented on core/src/plugins/kubernetes/container/build/kaniko.ts
> -    statusLine.setState(renderOutputStream(line.toString(), "kaniko"))
With this PR merged as-is, the kaniko logs would appear in `-l3` logs as `sh`, as the kaniko build command begins with `sh -c`. To fix that, we'd need to pass some parameter down to `runAndWait`, so it can set the `implementation` parameter of the log event correctly to `kaniko`.

2023-01-23 17:09 UTC, edvald commented on core/src/plugins/kubernetes/run.ts
> +        statusLine.setState(renderOutputStream(msg, `${this.podName}.${this.getMainContainerName()}`))
I'm not actually suggesting displaying the _full_ command as a prefix in general. I literally meant just the words `[docker build]` in the specific context where it now says `[local-docker]`.

Regarding ambiguity with multiple tests in a module, I think that's a non-issue because of the changes in 0.13. Instead of the module name (e.g. `frontend`), you'll always see the action key, e.g. `test.frontend-integ`. We can live with the  occasional bit of ambiguity in the meantime :)

2023-01-23 17:23 UTC, stefreak commented on core/src/plugins/kubernetes/run.ts
> +        statusLine.setState(renderOutputStream(msg, `${this.podName}.${this.getMainContainerName()}`))
👍  Yes, eysi and me had a quick sync today and came to the same conclusion essentially. I'm personally not super happy with it, as it makes streaming the logs in the forthcoming 0.12 releases a less useful for people who have more than 1 test per module. But I am ok with this if you think that's the best choice for now.

I'll resolve this discussion because the code has been changed according to @eysi09 s suggestions (I'm working on the final touches)

2023-01-23 17:24 UTC, stefreak commented on core/src/plugin-context.ts
> +  implementation: string
`origin` is probably what we'll go for

2023-01-24 03:14 UTC, eysi09 commented on core/src/actions.ts
> +    const statusLine = params.log.placeholder({ level: LogLevel.verbose })
I'm think that setting a status line at the action level won't work. 

We're basically creating a node in the log graph that's in the wrong place. 

Since we don't use the "fancy" logger with the verbose level we don't notice, but if you were to change the level to info you'd likely see the log update in the wrong place. 

So this works now, but that's almost by chance and in general this break some invariants. There's also a chance that the logs could be rendered in the wrong place in Garden Cloud. 

Since the logger is a graph that can be updated in place—as opposed to a list—we need to create and update the nodes in the right place.

Again, we'll address this by making the logger append-only in #3254, but here we're just not using it as intended.

2023-01-24 18:11 UTC, stefreak commented
Close in favor of https://github.com/garden-io/garden/pull/3576 and https://github.com/garden-io/garden/pull/3571

2023-01-24 18:11 UTC, closed without merging