fix(k8s): fix Helm Tests, Runs and dev mode specs
garden-io/garden pull request #3539
Opened 2023-01-17 20:44 UTC by thsig

**What this PR does / why we need it**:

Fixed various schema / data shape errors that only surfaced when actually running `garden deploy`, `garden test` and `garden deploy --dev` in the `vote-helm` project.

After this fix, Tests and Runs are now working for `helm` modules.

Also fixed some other issues and cleaned things up along the way.

**IMPORTANT NOTE**

Runs and Tests generated from `helm` modules all have the `kubernetes-pod` type, and don't use the `podSpec` field. Therefore, they include a runtime dependency on their parent module's Deploy. This means that the `helm` Deploy is executed first, and the pod spec for the Test/Run pod runner is read from the cluster.

This behavior is different from 0.12, where the pod spec was read from the output of a dry-run deploy using the `helm` CLI (and did thus not require the deploy to take place first).

**Special notes for your reviewer**:

I did notice a few more problems with dev mode along the way, but those aren't `helm`-specific and should be addressed in a separate PR (mostly to do with log formatting, and then an issue with `actionSourcesChanged` events being handled even though the source belongs to a Build that's referenced by a dev-mode Deploy).

2023-01-18 10:40 UTC, vvagaytsev approved these changes
LGTM 🚀 Thank you! 👍

2023-01-18 11:08 UTC, edvald commented
It appears you have an import loop, causing the build to fail.

What you can do to track that down:

```
npm i detect-circular-deps -g
cd <repo root>/core
detect-circular-deps build/src/cli/cli.js
```

Commonly you can address these loops by changing imports to `import type` where possible, and moving exported zero/low-dependency functions to different or separate files.

2023-01-18 11:10 UTC, edvald commented on core/src/plugins/kubernetes/helm/exec.ts
> +    throw new ConfigurationError(`${action.longDescription()} does not specify a defaultTarget.`, {
I suspect this may be a very opaque error message in some scenarios. I think the original text ended with "... hot reloading" or something similar. Might be good to see what the relevant usages are here post refactor.

2023-01-18 11:15 UTC, edvald requested changes
Some small things I caught (beyond the import loop)

2023-01-18 11:15 UTC, edvald commented on core/src/plugins/kubernetes/helm/handlers.ts
> +      actions.push(makeDummyBuild({ module, copyFrom: undefined, dependencies: undefined }))
This is not necessary. There is no notion of a base `helm` Deploy (the `base` feature is only in modules now).

2023-01-18 11:27 UTC, thsig commented on core/src/plugins/kubernetes/helm/handlers.ts
> +      actions.push(makeDummyBuild({ module, copyFrom: undefined, dependencies: undefined }))
The `vote-helm` project fails to deploy if I remove this line (which triggers this exception: https://github.com/garden-io/garden/blob/51d027d2ff9db399e8a45106123ec17c26e5bdd2/core/src/graph/actions.ts#L422).

Was the idea instead to ask users to manually migrate their base chart-based modules, and to change the `vote-helm` project to no longer use the `base-chart` structure?

2023-01-18 13:43 UTC, edvald commented on core/src/plugins/kubernetes/helm/handlers.ts
> +      actions.push(makeDummyBuild({ module, copyFrom: undefined, dependencies: undefined }))
Then the issue is something more subtle, likely something very specifically to do with the base chart thing. Perhaps the dummy build needs to be injected specifically for that scenario (as opposed to always, which feels excessive to me).

The base chart mechanic should only be in `helm` _modules_ but should still be supported there. Users anyway need to manually migrate from modules to actions, and there is a straightforward alternative approach to "base charts" that doesn't need specific semantics at the action-type level. Namely, you just create multiple `helm` Deploy actions with the same chart path.

2023-01-22 16:27 UTC, edvald approved these changes

2023-01-22 16:27 UTC, merged