refactor(core): get rid of sqlite and just use file-backed config stores
garden-io/garden pull request #3619
Opened 2023-01-29 12:07 UTC by edvald

This substantially cuts down on startup time and general build complexity.

Along the way, we make sure users can have a cloud auth token for each
Garden Cloud domain, which will if nothing else simplify development.

Best to look at the individual commits to dig into the refactors.

2023-01-31 08:55 UTC, thsig commented on core/src/process.ts
> +  const record: GardenProcess = {
Maybe we should use `processInfo` instead of `processRecord`/`record`? Similar to the naming of the `CommandInfo` interface (and associated local variables).

2023-01-31 09:17 UTC, mkhq commented on core/src/config-store/base.ts
> +    await writeFile(this.getConfigPath(), JSON.stringify(config))
I think this could result in a partial/corrupted config file if there is some error while writing. `writeFile` potentially calls `write` multiple times with the buffer and is not guaranteed to be atomic. One way to work around this and make it more safe would be to first write the data in a temp file and then use `mv` which is atomic on posix filesystems.

2023-02-01 03:49 UTC, edvald commented on core/src/process.ts
> +  const record: GardenProcess = {
I mean, it's still a record of a process. Don't think it matters too much what this is called in internal interfaces :P

2023-02-01 03:56 UTC, edvald commented on core/src/config-store/base.ts
> +    await writeFile(this.getConfigPath(), JSON.stringify(config))
I don't believe that's true, given that there is a file lock placed around every execution of this. The lock is intentionally not placed inside this particular method because the lock needs to encapsulate the read and the write at the same time.

2023-02-01 03:58 UTC, edvald commented on core/src/config-store/base.ts
> +    await writeFile(this.getConfigPath(), JSON.stringify(config))
Ah I may have jumped the gun there, I suppose that is indeed possible (if highly unlikely). I don't mind addressing that, to err on the side of caution. My hunch is that there's a library for that .)

2023-02-01 04:07 UTC, edvald commented on core/src/config-store/base.ts
> +    await writeFile(this.getConfigPath(), JSON.stringify(config))
Did that, and added a stricter file mode on the global config to boot, since it will contain auth tokens.

2023-02-01 04:07 UTC, edvald commented on core/src/config-store/base.ts
> +    await writeFile(this.getConfigPath(), JSON.stringify(config))
For future reference: https://github.com/npm/write-file-atomic

2023-02-01 04:33 UTC, eysi09 commented on core/src/cloud/api.ts
> +    return globalConfigStore.get("clientAuthTokens", domain)
Nice :)

2023-02-01 04:43 UTC, eysi09 requested changes
Looks good but noticed a couple of unfinished tests in there.

2023-02-01 04:43 UTC, eysi09 commented on core/test/unit/src/process.ts
> +describe("registerProcess", () => {
Remove or update?

2023-02-01 04:57 UTC, edvald commented on core/test/unit/src/process.ts
> +describe("registerProcess", () => {
Good catch, added the implementations.

2023-02-01 04:57 UTC, eysi09 approved these changes

2023-02-01 04:57 UTC, merged

2023-02-03 15:55 UTC, vvagaytsev commented
It looks like this affected the [`HideWarninigCommand`](https://github.com/garden-io/garden/blob/main/core/src/commands/util/hide-warning.ts).

So, we should also store warnings in the new FS-based store now. Is that correct, @edvald?

2023-02-03 16:51 UTC, edvald commented
We actually do, yes. Let me know if you noticed something wrong about the implementation, perfectly possible I missed something :)