Interactive dev command (WIP)
garden-io/garden pull request #3671
Opened 2023-02-03 23:56 UTC by edvald

Ah, it's finally taking shape! Plenty to do still, but the basic mechanics are there, including type-ahead, autocomplete, and the ability to run basically any Garden command.

TODO:

- [ ] Handle multiple watch/dev/sync commands concurrently (i.e. move that logic to the Garden instance)
- [ ] Gracefully handle global options
- [ ] Print nice intro message on start
- [ ] Add reload command to reload config
- [ ] Notify when config changes are detected

2023-02-05 23:04 UTC, eysi09 commented
Can we get a screen cap plz? 🙏

2023-02-08 11:27 UTC, Orzelius reviewed
This is very cool but I wonder how big the downside of us having to emulate a terminal like this is. Many users have their own preferences and plugins for their shell and will miss them in our solution. I guess it's a necessary evil.

2023-02-08 11:27 UTC, Orzelius commented on core/src/commands/base.ts
> +export abstract class InteractiveCommand<A extends Parameters = {}, O extends Parameters = {}, R = any> extends Command<
Shouldn't this be parameters and options instead of two parameters? Also, what does `R` stand for?

2023-02-08 11:27 UTC, Orzelius commented on core/src/commands/dev.tsx
> +      const configDump = await garden.dumpConfig({ log })
Shouldn't this also grab the config dump from the new garden?

2023-02-08 11:27 UTC, Orzelius commented on core/src/commands/serve.ts
> +      const configDump = await garden.dumpConfig({ log })
Same dump config comment here

2023-02-08 11:27 UTC, Orzelius commented on core/src/cli/command-line.ts
> +        this.flashError(`Logs cannot currently be followed in the dev console. Please use a separate sheterminalll.`)
```suggestion
        this.flashError(`Logs cannot currently be followed in the dev console. Please use a separate terminal.`)
```

2023-02-09 13:58 UTC, vvagaytsev commented on core/src/logger/writers/file-writer.ts
> +    super({ level: config.level })
This can be simplified. There is a duplicate assignment of `this.level` here and in L62.
The following changes can be done:
1. `FileWriterConfig` can extend `BaseWriterParams`
2. This line can be changed to `super(config)` (no need to create one more object)
3. assignment `this.level = level` can be removed

2023-02-10 18:15 UTC, edvald commented on core/src/cli/command-line.ts
> +    })
Yeah I've had the same thought 👍

2023-02-10 18:16 UTC, edvald commented on core/src/commands/base.ts
> +export abstract class InteractiveCommand<A extends Parameters = {}, O extends Parameters = {}, R = any> extends Command<
No, this is correct. See the Command class that's being extended.

2023-02-10 18:17 UTC, edvald commented on core/src/commands/dev.tsx
> +      const configDump = await garden.dumpConfig({ log })
It should, yes.

2023-02-10 18:18 UTC, edvald commented on core/src/cli/command-line.ts
> +    this.setKeyHandler("downArrow", () => {
Yeah that'd be nice, but left out of scope.

2023-02-10 19:36 UTC, edvald commented
> This is very cool but I wonder how big the downside of us having to emulate a terminal like this is. Many users have their own preferences and plugins for their shell and will miss them in our solution. I guess it's a necessary evil.

I do agree, but this is the only viable way to achieve the desired effect. There may be some maintenance to do, hardening etc. but honestly I think the biggest downside was kinda having to make all that low-level stuff in the first place. But now that's done, so... 🤷 

Obviously this is not at all meant to be a full terminal emulation. It is just a single-line command line. Kinda like how you don't expect Spotlight on macOS to be a full-fledged pluggable thing, or the Cmd+K command palette in webapps etc etc.

2023-02-10 19:49 UTC, edvald commented
@Orzelius @vvagaytsev updated after review, hoping this is good to go now.

2023-02-11 17:53 UTC, eysi09 requested changes
Awesome work! 🚀 

Can't wait to start using it day-to-day. 

Left a handful of comments but the only change I would request is supporting comma so you can type `deploy api,web`. 

Also, some other things I noticed that I'll just add here. But all of this can be flagged as future work.

- I hadn't started local K8s when testing things and got an error resolving providers. There was no real actionable hint and I couldn't use a reload command. Wasn't clear whether I should e.g. kill the process or try again, or just start K8s and carry on.  

- Sometimes the suggestion highlights blue, sometimes it doesn't and I don't understand the difference between the states. See screenshot.

<img width="228" alt="Screenshot 2023-02-11 at 09 47 13" src="https://user-images.githubusercontent.com/5373776/218273095-8ebc464a-6f56-4816-b407-7605c5e4b770.png">
<img width="188" alt="Screenshot 2023-02-11 at 09 47 18" src="https://user-images.githubusercontent.com/5373776/218273096-ebb36bca-1562-4de1-a50f-066fc209f12f.png">

- Process crashes if typing a bad command:

```
 🌼  > <enter command> (enter help for more info)


/Users/eysi/code/garden-io/garden/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

ParameterError: Unexpected positional argument "backend" (expected only names)
    at processCliArgs (/Users/eysi/code/garden-io/garden/core/src/cli/helpers.ts:277:13)
    at CommandLine.handleReturn (/Users/eysi/code/garden-io/garden/core/src/cli/command-line.ts:491:42)
    at /Users/eysi/code/garden-io/garden/core/src/cli/command-line.ts:256:45
    at CommandLine.keyStroke (/Users/eysi/code/garden-io/garden/core/src/cli/command-line.ts:183:7)
    at /Users/eysi/code/garden-io/garden/core/src/commands/dev.tsx:94:21
    at ReadStream.handleData (/Users/eysi/code/garden-io/garden/node_modules/ink/src/hooks/use-input.ts:185:5)
    at ReadStream.emit (node:events:525:35)
    at ReadStream.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at ReadStream.Readable.push (node:internal/streams/readable:234:10)
    at TTY.onStreamRead (node:internal/stream_base_commons:190:23) {
  detail: { expectedKeys: [ 'names' ], extraValue: 'backend' },
  type: 'parameter'
}

Node.js v18.13.0
```

- The old dev command obviously did too much. I think this one may do too little. The majority of our users who use Garden for inner loop dev start the day by running a single command, e.g. `garden deploy --dev`. With this change it's going to be two commands. I think we should support the former workflow. E.g. by deploying by default and adding an option to skip it or allowing users to configure some initial action. 

---

Again, all of this can be addressed later and I'm sure we'll bump into more things around the "unhappy path" that we can fix in follow-up PRs.

2023-02-11 17:53 UTC, eysi09 commented on core/src/cli/command-line.ts
> +const inputChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789- _*!@$%&/="
Looks like `,` is missing here. I wasn't to run e.g. `deploy backend,frontend`

2023-02-11 17:53 UTC, eysi09 commented on core/src/cli/autocomplete.ts
> +  configDump?: ConfigDump
Would it make sense to use something more lightweight here in a future version? The config dump can potentially be quite large and clients would need to first obtain it over the network and then send it back, right?

2023-02-11 17:53 UTC, eysi09 commented on core/src/cli/command-line.ts
> +      this.cursorPosition = this.currentCommand.length
Should this be: `this.currentCommand.length + 1`?

That way you don't need to hit space after autocompleting to add options or arguments.

2023-02-11 17:53 UTC, eysi09 commented on core/src/cli/command-line.ts
> +      const msg = `Running ${chalk.white.bold(command.getFullName())}...`
Nitpick but it's a little odd how it first prints "Running X..." and then "Running X command...".

<img width="191" alt="Screenshot 2023-02-11 at 09 08 56" src="https://user-images.githubusercontent.com/5373776/218272093-5d90dac2-3b23-462a-8c0d-def3cec96232.png">
<img width="301" alt="Screenshot 2023-02-11 at 09 08 59" src="https://user-images.githubusercontent.com/5373776/218272095-97ce1eac-6c70-45fa-b992-6028479fe674.png">

2023-02-11 17:53 UTC, eysi09 commented on core/src/commands/cloud/secrets/secrets-create.ts
> +  help = "Create secrets in Garden Cloud."
Is this needed since the command name is `garden cloud secrets create`? 

I'm asking because so far we've been setting this dynamically depending on the distro name (i.e. Garden Cloud / Garden Enterprise / Cloud Dashboard).

2023-02-11 17:53 UTC, eysi09 commented on core/src/commands/dev.tsx
> +class QuitCommand extends InteractiveCommand {
My first reaction was to type "exit". Should we allow that alias as well?

2023-02-11 17:53 UTC, eysi09 commented on core/src/commands/exec.ts
> +    help: "The Deploy to exec the command in.",
This does read a little awkward :) 

Was the decision to always refer to "Deploys" as the subject to the "Deploy" verb, as opposed to "Service" or "Deployment"?

2023-02-11 17:53 UTC, eysi09 commented on core/src/commands/run-workflow.ts
> +export async function runStepCommand(params: RunStepCommandParams): Promise<CommandResult<any>> {
These changes look good at a glance but we need to make sure we test this properly with Cloud. In particular that logs works as expected.

2023-02-11 17:53 UTC, eysi09 commented on core/src/cli/autocomplete.ts
> +    const argSuggestions = argSpec.getSuggestions({ configDump })
I'm not getting arg suggestions when testing on my end. E.g. if I type `deploy` I don't get suggestions with deploy action names. Is that expected?

2023-02-11 17:55 UTC, eysi09 commented on core/src/cli/autocomplete.ts
> +    const argSuggestions = argSpec.getSuggestions({ configDump })
Ah right, this happened because resolving the providers failed. See my review comment. 

Feels like we should either exit the process in that case or keep track of the fact that some config hasn't been resolved and try again. 

Or offer a "reload" option.

2023-02-11 17:57 UTC, eysi09 commented on core/src/cli/autocomplete.ts
> +    const argSuggestions = argSpec.getSuggestions({ configDump })
...I suppose if we can ensure the "reload" option works even if provider resolution fails, this is a non issue.

2023-02-11 20:44 UTC, eysi09 commented
One other thing I just noticed (which we can also fix in a follow-up):

If I stop the command with a SIGINT signal (e.g. ctrl+c) I get the following error:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Dev (/Users/eysi/code/garden-io/garden/core/build/src/commands/dev.js:91:22)
    at App (/Users/eysi/code/garden-io/garden/node_modules/ink/build/components/App.js:42:9)
```

2023-02-12 06:23 UTC, edvald commented on core/src/cli/autocomplete.ts
> +  configDump?: ConfigDump
For now this doesn't go over the wire, but yes, we can make a much more trimmed down requirement later.

2023-02-12 06:24 UTC, edvald commented on core/src/cli/command-line.ts
> +      this.cursorPosition = this.currentCommand.length
I get your point but we'd also need to add that space, and I'd want more testing to make sure there aren't unexpected effects. Saving that for later.

2023-02-12 06:24 UTC, edvald commented on core/src/cli/command-line.ts
> +      const msg = `Running ${chalk.white.bold(command.getFullName())}...`
Yeah I agree, let's iterate in a future PR.

2023-02-12 06:26 UTC, edvald commented on core/src/commands/cloud/secrets/secrets-create.ts
> +  help = "Create secrets in Garden Cloud."
Point taken, but I felt this is important just when looking at the command list when running `help` in the dev CLI.

2023-02-12 06:26 UTC, edvald commented on core/src/commands/dev.tsx
> +class QuitCommand extends InteractiveCommand {
Good call. Done.

2023-02-12 06:29 UTC, edvald commented on core/src/cli/autocomplete.ts
> +    const argSuggestions = argSpec.getSuggestions({ configDump })
I've fixed the reload command not showing up or working if initial load fails. But we should definitely give more guidance to the user. Filing that under "a lot of logging improvements to make".

2023-02-12 06:32 UTC, eysi09 approved these changes

2023-02-12 06:34 UTC, merged