fix(k8s): more efficient runner pod log streaming
garden-io/garden pull request #3730
Opened 2023-02-09 18:31 UTC by thsig

**What this PR does / why we need it**:

Fixes an issue with very high upload bandwidth use when running Kubernetes based tests/tasks that produce a lot of log output.

Co-written with @stefreak.

We had previously used a very short retry interval for the logs follower when running one-off pods (e.g. for tests and tasks for our Kubernetes-based module types).

This was fixed by:

* Lengthening the retry interval from 10 milliseconds to 4 seconds.

* Fetching and streaming the last several seconds of pod logs before closing the logs follower, in case any logs were missing (or in case the logs follower hadn't had time to connect to the runner pod before it finished execution).

* Replacing the old, buffer-based deduplication logic with a simpler, more lightweight approach based on comparing the last streamed entry's timestamp and message to the entries considered for deduplication.

**Which issue(s) this PR fixes**:

Fixes #3586.

2023-02-09 21:09 UTC, edvald commented
Nice 👍  Looks good at a glance, but I'll leave a full review to others.

One thing we should do is to get those we know to have had issues with log outputs to test the edge build, after this is merged.

2023-02-10 08:33 UTC, thsig commented
> One thing we should do is to get those we know to have had issues with log outputs to test the edge build, after this is merged.

Definitely!

I'm also not 100% certain that this will fix the issue in question (although I think it's likely)—it's a solid improvement at any rate.

2023-02-10 13:41 UTC, stefreak requested changes
Awesome, this os definitely an improvement 👍 

I had a couple of comments, what do you think about those ideas and thoughts?

2023-02-10 13:41 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +          if (!timestamp || _self.deduplicate({ podName, containerName, timestamp, msg })) {
In my testing, if the timestamp is missing then the message was not part of the Pod's log output, but an error message from the Kubernetes API.

This is how I tested this:
1. modify modify the vote integ test to run longer and log some output
2. run `gdev test -l3 -f vote` in the vote example.
3. delete the test pod

Output:
```diff
ℹ vote [verbose]            → [npm]: test
ℹ vote [verbose]            → [npm]: test
ℹ vote [verbose]            → [npm]: test
ℹ vote [verbose]            → [npm]: test
+ℹ vote [verbose]            → [npm]: error: code = Unknown desc = Error: No such container: 1e5ca22496f210e089ebda21c160e69c14ee17ec639b176f1916b8b7d1fc5c22
✖ vote                      → Running integ tests → Failed! (took 31.6 sec)

Failed running integ tests in module vote. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Could not find Pod while waiting for it to complete. The Pod might have been evicted or deleted.
There are several different possible causes for Pod disruptions.

You can read more about the topic in the Kubernetes documentation:
https://kubernetes.io/docs/concepts/workloads/pods/disruptions/

━━━ Events ━━━
Pod test-vote-integ-86ac3d: Scheduled - Successfully assigned vote-default/test-vote-integ-86ac3d to docker-desktop
Pod test-vote-integ-86ac3d: Pulled - Container image "vote:v-6639ee3d75" already present on machine
Pod test-vote-integ-86ac3d: Created - Created container main
Pod test-vote-integ-86ac3d: Started - Started container main
Pod test-vote-integ-86ac3d: Killing - Stopping container main
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1 test action(s) failed!
```

If I change the code to ignore messages without a timestamp I get the correct result:

```
ℹ vote [verbose]            → [npm]: test
ℹ vote [verbose]            → [npm]: test
ℹ vote [verbose]            → [npm]: test
✖ vote                      → Running integ tests → Failed! (took 24.2 sec)

Failed running integ tests in module vote. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Could not find Pod while waiting for it to complete. The Pod might have been evicted or deleted.
There are several different possible causes for Pod disruptions.

You can read more about the topic in the Kubernetes documentation:
https://kubernetes.io/docs/concepts/workloads/pods/disruptions/

━━━ Events ━━━
Pod test-vote-integ-31d558: Scheduled - Successfully assigned vote-default/test-vote-integ-31d558 to docker-desktop
Pod test-vote-integ-31d558: Pulled - Container image "vote:v-6639ee3d75" already present on machine
Pod test-vote-integ-31d558: Created - Created container main
Pod test-vote-integ-31d558: Started - Started container main
Pod test-vote-integ-31d558: Killing - Stopping container main
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1 test action(s) failed!
```

Also, if we change the types so that we always receive a timestamp in the events down the line, some code can be simplified in the PodRunner (`prepareLogsFollower`).

I think instead of including log lines without a timestamp into the application logs, we should emit a warning or a debug message that we received this log line. This also might help reduce some confusion of developers, who might think that this (or a different) error has been emitted by their app, but it actually originates from kubernetes.

2023-02-10 13:41 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +          return false
With this logic we might get duplicates if an application outputs multiple different lines of output at the very same time.

Could we change the `deduplicate` function so it takes an array of messages as the first parameter, and returns an array of messages that should be written? Then we could make it more robust:

First, it would filter all the messages that have an older timestamp than the one we remembered in lastLogEntries.

Then it would need to find the index of the message that we remembered in the lastLogEntries. If it doesn't find this message in the array, we remember the last entry of the array as `lastLogEntry` and return the filtered array.

If it finds the message, it removes all the entries before the index of the found message, remembers the new `lastLogEntry` and returns the filtered + deduplicated array.

2023-02-10 13:41 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +          return false
Also it might simplify the calling code as it doesn't need to loop through the log entries

2023-02-10 13:41 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
>            since: isRetry ? "10s" : since,
To make it more robust: What if we never send a `since` argument. Then we would always fetch all the logs on retry, but that's fine because retries are rare and the deduplication logic would now be able to deal with any amount of messages.

2023-02-10 13:46 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
>            since: isRetry ? "10s" : since,
Consider this one optional, it might not be worth it to be that "paranoid" about missing out on some messages

2023-02-10 13:58 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
>    const logs = await getPodLogs({
this function calls an imported `getPodLogs` function, while we also have a `getPodLogs` function defined here in this file (could be called with `this.getPodLogs` – why are we using two different mechanisms of fetching logs in the LogsFollower? Might be confusing for other people reading this code

2023-02-10 14:01 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
>            since: isRetry ? "10s" : since,
Best would be of course, to pass a `sinceTime` argument to kubernetes, based on the last log message that we remembered. 

I did a little experiment, and kubernetes seems to adhere to the `sinceTime` argument, and even typescript doesn't complain:

```
diff --git a/core/src/plugins/kubernetes/logs.ts b/core/src/plugins/kubernetes/logs.ts
--- a/core/src/plugins/kubernetes/logs.ts
+++ b/core/src/plugins/kubernetes/logs.ts
@@ -443,13 +443,12 @@ export class K8sLogFollower<T extends LogEntryBase> {
     since?: string
   }) {
     const logger = this.k8sApi.getLogger()
-    const sinceSeconds = since ? parseDuration(since, "s") || undefined : undefined

     const opts = {
       follow: true,
       pretty: false,
       previous: false,
-      sinceSeconds,
+      sinceTime: "2024-02-07T14:44:14.054636925Z",
       tailLines: tail,
       timestamps,
     }
```

2023-02-11 13:58 UTC, thsig commented on core/src/plugins/kubernetes/logs.ts
> +          if (!timestamp || _self.deduplicate({ podName, containerName, timestamp, msg })) {
> In my testing, if the timestamp is missing then the message was not part of the Pod's log output, but an error message from the Kubernetes API.

Yeah, good point. I hadn't noticed this—I'll change the logic to skip logging entries with missing timestamps (but log those messages as debug-level logger messages).

2023-02-11 14:00 UTC, thsig commented on core/src/plugins/kubernetes/logs.ts
> +          return false
Makes sense—could you have a go at making that change and see whether the results look promising, since you've almost written it out in pseudocode here?

2023-02-11 14:06 UTC, thsig commented on core/src/plugins/kubernetes/logs.ts
>    const logs = await getPodLogs({
Yeah, good point. We should rename the private method here to `streamPodLogs`, since it uses the streaming logs k8s API.

The other one (in `status/pod.ts`) calls the old-fashioned `readNamespacedPodLogs` k8s API endpoint: https://github.com/garden-io/garden/blob/98aeba2b65817c99b1019c25debddeb9a41f005e/core/src/plugins/kubernetes/status/pod.ts#L73.

2023-02-11 14:13 UTC, thsig commented on core/src/plugins/kubernetes/logs.ts
>            since: isRetry ? "10s" : since,
> To make it more robust: What if we never send a since argument. Then we would always fetch all the logs on retry, but that's fine because retries are rare and the deduplication logic would now be able to deal with any amount of messages.

Yeah, maybe that would be better—my thinking was to avoid fetching all the logs when there's a lot of them (e.g. for very verbose, long-running test suites and the like).

> Should we maybe use sinceTime after all, to only fetch exactly the logs that we need?

Since the k8s Node client library doesn't allow for a `sinceTime` parameter, we'd have to write our own helper to prepare the request parameters directly.

That's totally doable (and not a lot of effort either), but not necessary if we're thinking about just fetching all the pod logs anyway.

I'll have a look at that, and if it ends up looking like too much work, we can keep the current approach (or just fetch all the pod logs as you suggested above).

2023-02-13 07:09 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
>            since: isRetry ? "10s" : since,
> Since the k8s Node client library doesn't allow for a sinceTime parameter, we'd have to write our own helper to prepare the request parameters directly.

In my testing (see the diff above) adding the sinceTime parameter to opts in `getPodLogs` just works

2023-02-18 20:06 UTC, eysi09 commented on core/src/plugins/kubernetes/logs.ts
> +  return pod.spec!.containers.map((c) => c.name).filter((n) => !n.match(/garden-/))
...I don't think we have containers that match the regex but I wonder if we can make the name of the sidecar containers more specific. Something like `garden-injected-sidecar_mutagen` or similar.

2023-02-18 20:06 UTC, eysi09 commented on core/src/plugins/kubernetes/run.ts
> +      retryIntervalMs: 4000,
Any specific reason for picking this exact number? 

If so it could be good to add it as a comment.

2023-02-18 20:06 UTC, eysi09 commented on core/test/integ/src/plugins/kubernetes/container/logs.ts
> +      afterEach(async () => {
Doesn't look like this needs to be async.

2023-02-20 07:56 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +  private lastLogEntries: { [containerKey: string]: { msg: string; timestamp: Date } }
I was trying to change the types (I wanted to be timestamps to be non-optional everywhere in the kubernetes module) But it was a big type mess, as the Stream object with these types is handed in from the framework into the plugin. 

I wonder if timestamp really needs to be optional for some plugins? For the kubernetes plugin it definitely must not...

2023-02-20 16:02 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +      this.lastLogEntries[key].messages.push(msg)
```suggestion
      lastMessages.push(msg)
```

2023-02-20 17:15 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +    this.log.debug("Failed to flush final logs: Timed out after 20 seconds")
Should this be warning or error level?

2023-02-20 17:16 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +        throw new Error("No connections")
This is more or less a sanity-check assertion; Should we remove this so it doesn't cause weird looking error messages some point in the future? (Maybe we convert it to a debug level message)

2023-02-20 17:18 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +      const pod = await this.k8sApi.core.readNamespacedPodStatus(conn.pod.metadata.name, conn.namespace)
When I test this using Network Link conditioner, we will not see the "Connection timed out" message because readNamespacedPodStatus will re-try effectively forever. Can we somehow disable retry?

Alternatively we could move the decision wether to re-try or not into the createConnections function. That would have the benefit that handleConnectionClose wouldn't need to be async, which is kind of weird.

2023-02-20 17:20 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
>            if (!line) {
TODO: Do we have to call next() in this case?

2023-02-20 17:23 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
>            since: isRetry ? "10s" : since,
Absolutely, this is a very valid point.

In the current version of the PR, we handle this by enforcing `maxLogLinesInMemory` also for the LogFollower.
@eysi09 Do you think that suffices?

2023-02-20 17:30 UTC, stefreak commented on core/src/plugins/kubernetes/run.ts
> +      retryIntervalMs: 1000,
Should we also hardcode the retry interval, instead of parametrizing?

2023-02-20 20:14 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +    Object.values(conns).forEach((conn) => {
`Object.values(Object.values(this.connections))` seems like a bug / mistake

2023-02-21 05:42 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +          } else if (_self.deduplicate({ podName, containerName, timestamp, msg })) {
Add a debug log message when messages have been discarded due to being a duplicate (it should now be rare, usually one message per reconnect)

2023-02-21 09:18 UTC, thsig commented on core/src/plugins/kubernetes/logs.ts
> +    Object.values(conns).forEach((conn) => {
Yeah, that's unnecessary. The second call to `Object.values` is a no-op there (it will return the same array).

2023-02-21 09:19 UTC, thsig commented on core/src/plugins/kubernetes/logs.ts
> +        throw new Error("No connections")
I think converting it to a debug-level log message makes sense.

2023-02-21 09:19 UTC, thsig commented on core/src/plugins/kubernetes/logs.ts
> +    this.log.debug("Failed to flush final logs: Timed out after 20 seconds")
Warning, I'd say.

2023-02-21 09:28 UTC, thsig commented on core/src/plugins/kubernetes/logs.ts
> +      const allConnections = Object.keys(this.connections).map((c) => this.connections[c])
This can be replaced with `Object.values(this.connections)`.

2023-02-21 09:52 UTC, thsig commented on core/src/plugins/kubernetes/logs.ts
> +      const pod = await this.k8sApi.core.readNamespacedPodStatus(conn.pod.metadata.name, conn.namespace)
> Can we somehow disable retry?

We could do that, e.g. by adding a new method to our `KubeApi` class that allows for optional request parameters (and adding support for a `retry: boolean` option there).

Should we do that, or do you think it could be cleaner to do this in `createConnections`? I'd he happy to make the required changes to `KubeApi` if we'd rather go that route, though.

2023-02-21 14:00 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +      const allConnections = Object.keys(this.connections).map((c) => this.connections[c])
```suggestion
      const allConnections = Object.values(this.connections)
```

2023-02-21 14:01 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +        throw new Error("No connections")
```suggestion
        this.log.debug("flushFinalLogs: unexpectedly encountered empty list of connections")
```

2023-02-21 14:02 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +    this.log.debug("Failed to flush final logs: Timed out after 20 seconds")
```suggestion
    this.log.warning("Failed to finish streaming logs: Timed out after 20 seconds. Some logs might be missing in the verbose log output, or in Garden Cloud.")
```

2023-02-21 14:03 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +      const pod = await this.k8sApi.core.readNamespacedPodStatus(conn.pod.metadata.name, conn.namespace)
After giving it another thought, I think it's not strictly necessary as the behaviour is fine with or without the retry. Just the debug log is strange, but we can live with that.

2023-02-21 14:07 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +          } else if (_self.deduplicate({ podName, containerName, timestamp, msg })) {
```suggestion
          } else if (!_self.deduplicate({ podName, containerName, timestamp, msg })) {
              _self.log.debug(`Dropping duplicate log message: ${line}`)
          } else {
```

2023-02-21 14:08 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
>            if (!line) {
```suggestion
          if (!line) {
```

2023-02-21 14:08 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
>            if (!line) {
```suggestion
          if (!line) {
              next()
```

2023-02-21 14:09 UTC, stefreak commented on core/test/integ/src/plugins/kubernetes/container/logs.ts
> +      afterEach(async () => {
```suggestion
      afterEach(() => {
```

2023-02-21 14:59 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +    }
Let's keep this DRY
```suggestion
    this.close()
```

2023-02-22 10:49 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +  return pod.spec!.containers.map((c) => c.name).filter((n) => !n.match(/garden-/))
Let's at least narrow it down to container names starting with `garden-` for now

```suggestion
  return pod.spec!.containers.map((c) => c.name).filter((n) => !n.match(/^garden-/))
```

2023-02-22 10:58 UTC, stefreak commented on core/src/plugins/kubernetes/run.ts
> +      retryIntervalMs: 1000,
```suggestion
      # We use 1 second in the PodRunner, because the task / test will only finish once the LogFollower finished.
      # If this is too low, we waste resources (network/cpu) – if it's too high we add extra time to the run execution.
      retryIntervalMs: 1000,
```

2023-02-22 11:40 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +  private lastLogEntries: { [containerKey: string]: { msg: string; timestamp: Date } }
My suggestion, after multiple attempts of changing this: Let's keep this as-is for now

We might want to add this to the 0.13 TODO-list or have another go at this once 0.13 is finished.

2023-02-22 11:57 UTC, thsig commented
@eysi09: This is ready for final review now.

2023-02-24 17:09 UTC, eysi09 requested changes
Had a couple of comments. Thanks so much for all the attention to detail on this one!

2023-02-24 17:09 UTC, eysi09 commented on core/src/plugins/kubernetes/logs.ts
> +  return pod.spec!.containers.map((c) => c.name).filter((n) => !n.match(/^garden-/))
Nice to add the `^`

2023-02-27 06:21 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +      if (podStatus === "missing" && !wasError) {
No, this wouldn't break that, because every second we are calling `createConnections`, which would call `pods = await getAllPods(this.k8sApi, this.defaultNamespace, this.resources)` (`this.resources` would be, for example, the service resource), and find the new Pod for the service once it's there.

We are just stopping to retry connecting to the old Pod, which doesn't exist anymore and will also never exist again

2023-02-27 06:26 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
>  const maxLogLinesInMemory = 100000
So the garden logs --helps describes the tail option like this:

```
  -t, --tail         Number of lines to show for each service. Defaults to showing all log lines (up to a
                     certain limit). Takes precedence over the `--since` flag if both are set. Note that we
                     don't recommend using a large value here when in follow mode.
```

So if the user calls `garden logs` without the `--tail` option, we'll process up to 100K log lines on startup. Wouldn't it be also okay then to process 100K logs again when we resume the connections, if it was fine on startup?
If the user adds the `--tail` option it will also be honored on the reconnect.

Do you think we should change the limit also for startup, or only for the retry case? if so, why is it okay for startup but not the reconnect case?

2023-02-27 06:33 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +        req = await this.streamPodLogs({
If we can't fix the behaviour, I'd like to add a few comment before we merge this that explains that this function might hang forever sometimes, which is why we are not waiting for pending connections to fail but re-try connecting anyway. I think this is extremely confusing behaviour, and if we can't fix it we should at least try to document it

2023-02-27 16:59 UTC, eysi09 commented on core/src/plugins/kubernetes/logs.ts
> +      if (podStatus === "missing" && !wasError) {
Ah ok, thanks!

2023-02-28 09:48 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +      if (podStatus === "missing" && !wasError) {
Maybe I can add a comment to the code to clarify that

2023-02-28 09:59 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
>  const maxLogLinesInMemory = 100000
Yes, I was also talking about the follow case, but now I got lost completely. 

I think you're right and we don't have a problem with memory at all (at least when we're not streaming logs to Cloud), especially now that we eliminated the deduplication buffer. We should therefore rename the misleading `maxLogLinesInMemory` constant.

I think it's more a problem with the amount of work (=time) that is necessary to download millions of lines of logs and print them to the terminal. I think for this reason, the limit definitely makes sense to set a default tail number for both with and without `--follow`.

I have the feeling that as this is nuanced and complicated enough it will be hard to get to a result quickly using the GitHub comments. Do you have time to pair on this?

2023-03-06 18:32 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +        this.timeoutId = setTimeout(followLoop, this.retryIntervalMs)
if `close()` is called while `createConnections` is still running, the `clearTimeout` in `close()` has no effect. We need to add an `if (this.timeoutId) {` here, to prevent continuation even though close has been called.

2023-03-07 12:24 UTC, stefreak commented on core/src/plugins/kubernetes/logs.ts
> +    return await logger.log({
return is enough

2023-03-07 14:51 UTC, eysi09 approved these changes
Whoop whoop 🚀

2023-03-07 15:46 UTC, merged