feat(examples): add GitOps example based on ArgoCD
garden-io/garden pull request #3762
Opened 2023-02-14 18:37 UTC by srihas-g

**What this PR does / why we need it**:
Adding an example for GitOps based on top of ArgoCD.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

we can run commands `init-db` task manually to create the votes table, probably it can be part of a migration in a real prod app. I think that's fine.

2023-02-14 18:39 UTC, srihas-g commented on examples/argocd/LICENSE
> +MIT License
Not sure if we need in every example, just moved it since it was there with the other example.
CC: @eysi09

2023-02-14 18:39 UTC, srihas-g commented on examples/argocd/project.garden.yml
> +      namespace: srihasg
I am using `srihasg` dockerhub repo and referring it in other places as well, is that fine?

2023-02-20 20:11 UTC, edvald commented on examples/argocd/postgres/garden.yml
> +    # The postgres health check appears to go through before the server accepts remote connections, so we need to
I wonder if this is actually necessary anymore

2023-02-20 20:14 UTC, edvald commented on examples/argocd/api/chart/.argocd-source-api.yaml
> +    value: srihasg/api-image
Does this actually work? Also the version tag below, not sure if we're okay to hardcode it like that.

2023-02-20 20:15 UTC, edvald commented on examples/argocd/api/chart/.argocd-source-api.yaml
> +    value: srihasg/api-image
Hmm wait, I _think_ I get it now. But this could definitely use more commenting and explanation in the docs.

2023-02-21 15:57 UTC, srihas-g commented on examples/argocd/postgres/garden.yml
> +    # The postgres health check appears to go through before the server accepts remote connections, so we need to
<img width="518" alt="image" src="https://user-images.githubusercontent.com/115004077/220395312-1b341f4d-946d-4066-909c-3f6e96fa6993.png">


Just checked, looks like it's okay to remove it.
Pod is reported as READY after like 12s which seems safe. Because I believe there will be a delay until we run `garden run task db-init` anyways.

2023-02-21 15:58 UTC, srihas-g commented on examples/argocd/api/chart/.argocd-source-api.yaml
> +    value: srihasg/api-image
noted, I'll update the README, thanks.

2023-02-23 12:06 UTC, eysi09 requested changes
Fantastic work @srihas-g! 🎉

Had a few comments but otherwise looks great.

2023-02-23 12:06 UTC, eysi09 commented on examples/argocd/README.md
> +This implementation requires two k8s clusters; one of which is a Dev/CI cluster while the other is a Prod cluster. Purpose of Dev/CI cluster is to have resources deployed via `garden` during developm
Change "k8s" to "K8s" or "Kubernetes". 

Change Purpose of... to:

Garden is used to start development environments and trigger CI jobs in the Dev/CI cluster while ArgoCD is used for production deployments in the Prod cluster. Container images are built via Garden's in-cluster building functionality in the Dev/CI cluster and pushed to the respective container repository. In this example we're using Dockerhub.

2023-02-23 12:06 UTC, eysi09 commented on examples/argocd/README.md
> +Argocd image updater helps with actively watching the container repos for new image builds and then creates a commit back to the GitHub repo with the image tag. Image tags are filtered based on `upda
will have below annotations => will have the annotations referenced below

2023-02-23 12:06 UTC, eysi09 commented on examples/argocd/README.md
> +ArgoCD image updater by default uses the same repo credential, that ArgoCD would use, to commit above changes. We use a GitHub App that has been installed on the repo.
Remove comma after repo credential.

2023-02-23 12:06 UTC, eysi09 commented on examples/argocd/README.md
> +## Setup
Would be good to link to the [Getting started with remote K8s](https://docs.garden.io/kubernetes-plugins/remote-k8s) section of our docs here.

2023-02-23 12:06 UTC, eysi09 commented on examples/argocd/api/garden.yml
> +# base: base-chart
Remove the commented out code if it's not supposed to be used.

2023-02-23 12:06 UTC, eysi09 commented on examples/argocd/web/README.md
> +# hello-world
I don't think this file is needed.

2023-02-25 16:30 UTC, srihas-g commented on examples/argocd/README.md
> +1. Dev uses garden in the development environment and is happy with the changes made to the `api` service. Commits changes to GitHub repo.
This framing is actually nice and close to what's in the blog article, I will update the README here too, thanks.

2023-02-27 15:21 UTC, eysi09 commented on examples/argocd/project.garden.yml
> +      namespace: srihasg
Whoops, I misse this comment. But I think it would make more sense to just use our Dockerhub org. The name is `gardendev`.

2023-03-13 09:11 UTC, eysi09 approved these changes

2023-03-13 09:26 UTC, merged