refactor: rename "dev mode" to just sync or "sync mode"
garden-io/garden pull request #3794
Opened 2023-02-17 01:14 UTC by edvald

In the spirit of simplifying terminology and preferring transparent over opaque (or overloaded) phrasing, we've opted to drop the "dev mode" concept in favor of simply "sync". This more directly describes the functionality and should be easier to grok.

Specifically, these are the user-facing changes:
1. Users should now use `--sync` instead of `--dev` in the command line.
2. The `devMode` configuration fields are now called `sync`.
3. The `devMode.sync` and `devMode.syncs` fields are now simply `sync.paths`.

All these changes are backwards compatible.

2023-02-17 08:38 UTC, vvagaytsev commented on core/src/server/client-router.ts
> +      } else if (req.syncMode) {
Prefix name in [L84](https://github.com/garden-io/garden/pull/3794/files#diff-f7b95937d4de3e54e49cc926d17554146d48d8b40f6abcef474f9902c7f449eaR84) can be changed to avoid the old-fashioned "dev-mode" term :)

2023-02-17 08:42 UTC, vvagaytsev commented on core/src/plugins/container/config.ts
> +      See the [Code Synchronization guide](${syncGuideLink}) for more information.
The [L186](https://github.com/garden-io/garden/blob/1934e459dbc09e9477754a124dd8ef25f33dbec8/core/src/plugins/container/config.ts#L186) in this file can also use the `${syncGuideLink}` instead of hard-coded url.

2023-02-17 09:05 UTC, vvagaytsev commented
Looks good! There are still some usages of the old term "dev mode" in the code. I've made more renamings in #3795, feel free to merge/cherry-pick.

Also, some interface names still use `DevMode` in the names. I'm not sure if we want to rename all of those. If any of them are now deprecated, it's better to keep old names (to identify them easily in the future) and add some comments about the deprecation.

2023-02-17 09:05 UTC, vvagaytsev approved these changes

2023-02-17 10:26 UTC, vvagaytsev requested changes
Left one more comment about the help command rendering, please check.

2023-02-17 10:26 UTC, vvagaytsev commented on core/src/cli/helpers.ts
> +    const renderedAlias = renderAlias(param.aliases?.[0])
I'm not sure if this is the relevant piece of code, but now we have a slight regression in the `help` command rendering. I tried the deploy command with the wrong alias `garden deploy -f`  and got the options concatenated with the aliases in the help console output:
```
--local--local-mode
```

In `0.13` it's rendered as follows:
```
--local, --local-mode
```

2023-02-17 10:34 UTC, vvagaytsev commented on core/src/cli/helpers.ts
> +    const renderedAlias = renderAlias(param.aliases?.[0])
It looks like we need to restore `, ` in [L436](https://github.com/garden-io/garden/pull/3794/files#diff-9027ac4fe91c5cce8cef2b1fbd2cdb794283f8188c1ab1ea4199ec2ebddd18f8R436)

2023-02-17 10:44 UTC, vvagaytsev commented on examples/gatsby-dev-mode/src/pages/index.js
> +    <h1 style={{ color: "#000000" }}>Hot reload demo</h1>
It looks like this example has only `index.js` file. Wasn't it superseded by `gatsby-code-sync`. I guess we can remove `gatsby-dev-mode` folder completely.

2023-02-17 17:09 UTC, edvald commented
@vvagaytsev I've updated to address your comments, and pulled your commit over as well.

2023-02-20 13:20 UTC, vvagaytsev approved these changes
🚀

2023-02-20 13:31 UTC, merged