0.13 more integ stuff
garden-io/garden pull request #3798
Opened 2023-02-17 09:45 UTC by Orzelius

wip

2023-02-21 12:20 UTC, vvagaytsev commented on core/test/helpers.ts
> + * Recursively remove null on undefined values from an object (inluding arrays).
Typo? on -> or

2023-02-21 12:21 UTC, vvagaytsev approved these changes
Great job! 🚀 Thank you! I've left one minor non-blocking comment :)

2023-02-21 12:44 UTC, Orzelius commented on core/test/helpers.ts
> + * Recursively remove null on undefined values from an object (inluding arrays).
good catch [578faf9](https://github.com/garden-io/garden/pull/3798/commits/578faf93acd77df7ade0964fd481e6cb8c4b2723)

2023-02-21 13:09 UTC, Orzelius commented
Also took the chance to push [78efe83](https://github.com/garden-io/garden/pull/3798/commits/78efe8304edc44aad5ea0b25a5e1653516a22d69) which fixes all the tests other than the two volume one's failing for what seems internal solver issues

2023-02-21 13:54 UTC, edvald requested changes

2023-02-21 13:54 UTC, edvald commented on core/src/plugins/kubernetes/volumes/configmap.ts
> -                accessModes: module.spec.accessModes,
This seems incorrect. The issue is rather that [this](https://github.com/garden-io/garden/blob/33bef2a49828022ed8fed84a51823b3fd4d2c360/core/src/plugins/base-volume.ts#L20) is missing from [this](https://github.com/garden-io/garden/blob/212bbd3434d02b433cd078e32fb5ae668fbaff8a/core/src/plugins/kubernetes/volumes/configmap.ts#L33).

2023-02-21 13:54 UTC, edvald commented on core/test/integ/src/plugins/kubernetes/container/deployment.ts
> +            },
This doesn't seem right... I think the code being tested is wrong. Notice that we're validating a k8s Deployment resource, and there's definitely no place for `kind: "Deploy"` in there.

2023-02-21 13:54 UTC, edvald commented on core/test/integ/src/plugins/kubernetes/container/deployment.ts
> +      await executeAction({ garden, graph, log: garden.log, action })
This shouldn't be necessary... What error came up without this?

2023-02-22 07:49 UTC, Orzelius commented on core/src/plugins/kubernetes/volumes/configmap.ts
> -                accessModes: module.spec.accessModes,
I don't get it. There seems to be no such field on 0.12 and no logic to do anything if it's set, it also doesn't exist on the spec ts type. Am I missing something obvious?

2023-02-22 08:06 UTC, Orzelius commented on core/test/integ/src/plugins/kubernetes/container/deployment.ts
> +            },
Good catch, fixed in [161d97f](https://github.com/garden-io/garden/pull/3798/commits/161d97f6706772aa76e15482e1a28b9f43586bb9)

2023-02-22 08:17 UTC, Orzelius commented on core/test/integ/src/plugins/kubernetes/container/deployment.ts
> +      await executeAction({ garden, graph, log: garden.log, action })
You're right. Removed in [ddf2bc4](https://github.com/garden-io/garden/pull/3798/commits/ddf2bc4e54678da25a6e52f026c4dc36e1091227).

2023-02-22 08:24 UTC, edvald commented on core/src/plugins/kubernetes/volumes/configmap.ts
> -                accessModes: module.spec.accessModes,
I'm not sure what to tell you... I linked to the field in my comment (also see BaseVolumeSpec), and I'm fairly sure I did not add this post 0.12 🤷‍♂️

2023-02-22 08:51 UTC, Orzelius commented on core/src/plugins/kubernetes/volumes/configmap.ts
> -                accessModes: module.spec.accessModes,
Restored the field and added schema extension in [4ffd0e2](https://github.com/garden-io/garden/pull/3798/commits/4ffd0e232e8faed9869e5ee72383aa6915a43248)

2023-02-27 09:52 UTC, vvagaytsev approved these changes

2023-02-27 10:30 UTC, Orzelius commented
merging as all comments were addressed

2023-02-27 11:56 UTC, Orzelius commented
dead link fix: https://github.com/garden-io/garden/pull/3851

2023-02-27 11:56 UTC, merged