improvement: track the command run result and duration
garden-io/garden pull request #3837
Opened 2023-02-23 14:42 UTC by mkhq

**What this PR does / why we need it**:

When the anonymous analytics is enabled, we currently track that a command is run, but not the actual outcome of the command. With this PR, we add an analytics event after a command has finished including the result as success/failure, error type and command duration. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-02-24 14:55 UTC, eysi09 requested changes
Nice!

2023-02-24 14:55 UTC, eysi09 commented on core/src/analytics/analytics-types.ts
> +  COMMAND_RESULT = "Run Command Result",
This could also just be called "Command Result" imo. Slightly easier to read on Amplitude.

2023-02-24 14:55 UTC, eysi09 commented on core/src/analytics/analytics-types.ts
> +export enum AnalyticsCommandResult {
Can we make this a union type instead of a union? In general we should prefer unions.

2023-02-24 14:55 UTC, eysi09 commented on core/src/analytics/analytics.ts
> +    durationMsec: number
Nice!

2023-02-27 19:04 UTC, mkhq commented
These events will only be sent if the analytics handler has been initialized, which in turn depends on a garden instance. We would need a refactor of the init flow to make sure we can catch all potential error cases.

2023-03-14 09:30 UTC, eysi09 approved these changes

2023-03-15 09:08 UTC, merged