cherry-pick for 0.13: fix(framework): omit detail property of errors
garden-io/garden pull request #3879
Opened 2023-03-03 11:45 UTC by vvagaytsev

**What this PR does / why we need it**:
This cherry-picks https://github.com/garden-io/garden/commit/24f32fad to `0.13`.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-03-03 12:59 UTC, stefreak requested changes

2023-03-03 12:59 UTC, stefreak commented on core/src/events.ts
> +    error: result.error ? String(omit(result.error, "detail")) : null,
I think with `String()` the omit of detail is not necessary anymore.

```
String(new Error("foo"))
'Error: foo'
```

2023-03-03 13:29 UTC, stefreak commented
@vvagaytsev I think we can close this PR

2023-03-03 14:31 UTC, stefreak commented on core/src/events.ts
> +    error: result.error ? String(omit(result.error, "detail")) : null,
In my experiments, for an object like `String({})` yields `[Object object]` and `String(new Error("message"))` yields `Error: message`

2023-03-03 14:33 UTC, stefreak commented on core/src/events.ts
> +    error: result.error ? String(omit(result.error, "detail")) : null,
In the original commit, it was assigned directly without `String`: https://github.com/garden-io/garden/pull/3623/files – so the change became obsolete

2023-03-06 08:47 UTC, vvagaytsev commented on core/src/events.ts
> +    error: result.error ? String(omit(result.error, "detail")) : null,
Ok, thanks!

2023-03-06 08:47 UTC, closed without merging