feat(config): add ${this.mode} template variable to action spec context
garden-io/garden pull request #3913
Opened 2023-03-08 21:43 UTC by edvald

This allows much easier and cleaner templating around whether an action is in sync or local modes.

Also refactored such that action modes are attached to Action instances as part of config graph resolution, as opposed to dragging along `syncModeDeployNames` etc. arrays.

2023-03-09 11:09 UTC, thsig requested changes
Great stuff! This is a lot cleaner than the old way.

Only had a few cleanup-related comments in there. There are also a bunch of newlines added in object literals (didn't want to leave ~20 comments about those), maybe we'd want to clean those up as well.

2023-03-09 11:09 UTC, thsig commented on core/src/plugins/kubernetes/helm/common.ts
> +  const args = flatten(valueFiles.map((f) => ["--values", f])).concat()
Remove `.concat()`.

2023-03-09 11:09 UTC, thsig commented on core/src/garden.ts
> +        // actionConfigs[key] = config
Delete comment.

2023-03-09 11:09 UTC, thsig commented on core/test/unit/src/commands/helpers.ts
> -
Let's just delete this file.

2023-03-09 11:09 UTC, thsig commented on core/test/unit/src/vcs/git.ts
> +        console.log(error)
Delete `console.log`.

2023-03-13 15:08 UTC, edvald commented on core/src/commands/build.ts
> +
I can do this in some scenarios but I _really_ don't want to chase all these down. We can clean that up gradually as we happen upon it.

2023-03-13 16:16 UTC, Walther commented on core/test/unit/src/vcs/git.ts
> +        console.log(error)
PR made https://github.com/garden-io/garden/pull/3938

2023-03-13 16:17 UTC, thsig commented on core/src/commands/build.ts
> +
Yeah, good point.

2023-03-13 16:59 UTC, edvald commented
@thsig should be good to go now.

2023-03-13 17:21 UTC, thsig approved these changes

2023-03-13 17:21 UTC, merged