docs(k8s): ext dns and cert manager example
garden-io/garden pull request #3988
Opened 2023-03-23 13:38 UTC by ShankyJS

- ExternalDns and Cert-manager working
- Update Ingress, DNS and TLS certificate
- Add a new example for Cert-Manager and ExternalDNS

**What this PR does / why we need it**:

Documentation for a new example for cert-manager. We need it as the current integration with cert-manager is deprecated.

**Which issue(s) this PR fixes**:

Creates documentation tackling #2551 

**Special notes for your reviewer**:

2023-03-24 09:11 UTC, stefreak requested changes
Hey @ShankyJS thank you so much for the great work.

I have a couple more comments for you; Really sorry that I'm sprinkling these comments so slowly. But I feel really confident that I will approve this in the next iteration :)

In general I would recommend having a look at the excellent Google Developer documentation styleguide, following the rules from there can help using just the right language to make the documentation easier to read for folks around the world: https://developers.google.com/style
– At the same time, let's not go crazy with it– I just want to share this great resource with you that was of great help for me when I discovered it.

But It's already pretty great, keep up the good work! 🌱 

Please reach out if you have questions / disagree on something 👍

2023-03-24 09:11 UTC, stefreak commented on docs/advanced/cert-manager-integration.md
> +type: helm
this tutorial contains a lot of text, and a lot of yaml code. I think it will be hard to maintain and test, and the document might degrade over time and stop being helpful as it becomes outdated, and at the same time it's hard to maintain because it can't be tested by running a few commands.

I think there is some duplication between the example and this tutorial. How about walking the user through using the example, instead of reproducing the example completely in the form of a tutorial? 

This would get users up to speed more quickly, and make this guide easier to maintain.

2023-03-24 09:11 UTC, stefreak commented on examples/cert-manager-ext-dns/charts/cluster-issuers/README.md
> +With this files ready, our Helm Chart is now available to be deployed with Garden. 🪴
I think it's lovely that you explain these things with such detail– but reproducing the whole code of the helm chart in the readme makes it harder to maintain, and will result with outdated documentation after months and years of changes.

I would suggest you add a couple of comments to the helm chart templates themselves, instead of reproducing the code in the readme.

2023-03-24 09:13 UTC, stefreak commented
@ShankyJS Can you also squash all the commits, and start the commit message with `docs(k8s):`?

2023-03-24 10:31 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +type: helm
I suggested Shanky in-line code for readability. I agree the document is lengthy because we set up both ExternalDNS and cert-manager but I don't want to risk users losing context. An alternative could be to split the guides so that ExternalDNS is set up in another section from cert-manager and they reference each other.

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +Note: *If you are using Dockerhub*, --docker-server should be: `https://index.docker.io/v1/`
```suggestion
Note: *If you are using Docker Hub*, `--docker-server` should be: `https://index.docker.io/v1/`
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +If you decide to setup the secret with a different name make sure to update it in the `imagePullSecrets` configuration.
```suggestion
If you decide to set up the secret with a different name make sure to update it in the `imagePullSecrets` configuration.
```

Setup is a noun as in, "look at my sick setup!"
"Set up" is your action if you want to set something up

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +Now let's add some variables to the `project.garden.yml` that we are going to be using across our configuration in the project.
```suggestion
Now let's add some variables to the `project.garden.yml` that we are going to be using across our configuration.
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +The variables that are required to be modified according to your environment are:
```suggestion
The variables that require modification are:
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +The other variables *should* be set with the values we are providing at this stage as they will configure the project preventing errors to happen, most of them are extra configuration to add another
```suggestion
Keep the other variables set to default: they will smooth out the deployment process and prevent errors.
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +**Note:** Variables are going to be start to make sense after we start building our Helm Modules for `cert-manager` and `external-dns`.
```suggestion
**Note:** Variables are going to start to make sense after we build our Helm modules for `cert-manager` and `external-dns`.
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +For this Helm Chart we only require setting 1 value, `installCRDs`, in charge of installing the [Custom Resource Definitions](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custo
```suggestion
For this Helm chart we only require setting 1 value, `installCRDs`, in charge of installing the [Custom Resource Definitions](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) in our Kubernetes Cluster.
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +The combination of ExternalDNS + Cert-Manager is a powerful and production ready solution to manage and deploy certificates. 🚀
```suggestion
The combination of ExternalDNS + cert-manager is a powerful and production ready solution to manage and deploy certificates. 🚀
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +This Helm module is going to be different than the others we previously configured, because this Helm chart is intended to deploy the Custom Resources that we are going to need in order to interact w
```suggestion
This Helm module is going to be different than the others we previously configured, because this Helm chart is intended to deploy the Custom Resources that we are going to need in order to interact with this demo, and the Helm chart is going to be living in the same repository we are executing this demo from.
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +At this point we are just going to add the configuration of the Helm Module for Garden, we will create the chart in the next section of this tutorial.
```suggestion
At this point we are just going to add the configuration of the Helm module for Garden: we will create the chart in the next section of this tutorial.
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +Now that we have ExternalDNS and Cert-manager charts configured, we still have to configure our Cert-manager Custom Resources.
```suggestion
Now that we have ExternalDNS and cert-manager charts configured, we still have to configure our cert-manager Custom Resources.
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +In order to generate our certificates we need some components from cert-manager applied into our Kubernetes Cluster, these components are the following:
```suggestion
In order to generate our certificates we need some components from cert-manager applied into our Kubernetes cluster:
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +To install those components you can either follow [this guide](https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/) from cert-manager to create the ClusterIssuer and needed secrets.
```suggestion
To install those components you can follow [this guide](https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/) from cert-manager to create the ClusterIssuer and needed secrets.
```

When you use "either" in a sentence you must offer the alternative inside the same sentence.

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +If you want to have this fully automated with Garden you'll need to create a Helm Chart (or any sort of manifest applying mechanism like Kustomize) to create and apply those manifests to your cluster
```suggestion
To fully automate certificate issuance and manage cert-manager with Garden, you'll need to create a Helm chart to create and apply those manifests to your cluster.
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +If you decide to go with the automated way we created a custom Helm Chart that is stored in our [cert-manager-ext-dns](https://github.com/garden-io/garden/tree/main/examples/cert-manager-ext-dns/char
```suggestion
If you decide to go with the automated way we created a custom Helm chart that is stored in our [cert-manager-ext-dns](https://github.com/garden-io/garden/tree/main/examples/cert-manager-ext-dns/charts/cluster-issuers) example folder.
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +To use it just proceed to clone the repository and move the charts folder into your own repository
```suggestion
To use it, clone the repository and move the charts folder into your own repository.
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +To showcase our certificates we decided to use a sample react-application, the code for that React Application is hosted in our examples folder in the main `Garden` repository [cert-manager-ext-dns](
```suggestion
To showcase our certificates we use a simple React application. The code for that React application is hosted in our `examples` folder in the main Garden repository [cert-manager-ext-dns](https://github.com/garden-io/garden/tree/main/examples/cert-manager-ext-dns/frontend).
```

`examples` refers to a file path so that is surrounded by backticks. Garden, when capitalized refers to Garden the software tool, company and ecosystem and is not backticked. Sometimes we wish to refer to `garden` the binary or when instructing users to e.g. `garden deploy`: that's a good place to format `garden` as code.

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +The most important part of this configuration is the ingresses block, as it's where we set the hostname for the application `Ex. react.shankyjs.com`.
```suggestion
The most important part of this configuration is the ingresses block, as it's where we set the hostname for the application `e.g. react.shankyjs.com`.
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +Our website is now up, but without a certificate; because ExternalDNS already provisioned our DNS records, but we still haven't generated any Certificate for our frontend application.
```suggestion
ExternalDNS already provisioned our DNS records but we still haven't generated any certificate for our frontend application. Let's issue those now.
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +In order to generate our first staging-certificate we need to do the following:
```suggestion
In order to generate our first staging certificate, we need to do the following:
```

2023-03-24 11:50 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +This is the last part of this demo: run this part after you've finished your experiments with staging. Remember that the API Limits and Quotas from Production Let's Encrypt are lower so you shouldn't
```suggestion
This is the last part of this demo: run this part after you've finished your experiments with staging. Remember that the API limits and quotas from production Let's Encrypt are lower so you shouldn't be generating excessive amounts of certificates in a short-span of time.
```

Why was Limits and Quota capitalized?

2023-03-24 11:58 UTC, worldofgeese commented on docs/advanced/cert-manager-integration.md
> +type: helm
I'm also confused by the two documents under `docs/k8s-plugins/remote-k8s/ingress-and-dns.md` and `docs/advanced/cert-manager-integration.md`: a quick glance tells me there is a lot of duplication as @stefreak suggests. I suggest just a quick mention on the ingress and TLS page that points to where the cert-manager guide is located so users can "Choose Their Own Adventure" whether they proceed with the documentation on cloud cert provisioning or manage it themselves using the cert-manager guide.

2023-03-24 12:13 UTC, stefreak commented on docs/advanced/cert-manager-integration.md
> +type: helm
I would try to avoid inline code that might get outdated, e.g. due to new helm chart versions that break backwards compatibility. 
Can we also explain the high level concepts and the steps required without too much inline code?

I'm afraid that the tutorial and the example diverge as the code evolve, leaving users who follow the tutorial a potential bad user experience because we weren't able to continuously test the snippets carefully.

For example, what will happen pretty soon is we'll need to port this example to 0.13.

If some snippets are required, that's fine– but I feel right now almost all the code is duplicated across the tutorial and the example.

2023-03-24 12:13 UTC, worldofgeese commented
First of all, let me just apologize @ShankyJS for how long this PR has taken: if I had a genie in a bottle my first wish would be for more time.

I take responsibility as I believe we could have saved a lot of time with smaller, more focused PRs.

We already corresponded privately but I am repeating it here: let's shift left on grammar linting with ChatGPT and tools like Grammarly (or its open source cousin LanguageTool). I've also heard good things about [Hemingway](https://hemingwayapp.com/ ) though it may not handle technical content well.

2023-03-28 13:02 UTC, stefreak requested changes
@ShankyJS starting to look real good 👍 

Thanks for creating multiple smaller PRs. That makes reviewing them much easier 👍 

I still had a couple of comments. Sorry that I didn't catch these earlier.

2023-03-28 14:03 UTC, ShankyJS commented on examples/cert-manager-ext-dns/README.md
> +Deploy again to generate the staging certificates with `garden deploy --yes`.
If you don't have the Certificate and update the tlsSecretRef Garden will error out, that's why 2 deployments are needed.

1. For creating the certificate and making sure it's available.
2. To reference the certificate in the project.garden.yml file which adds the cert to the Ingress!

2023-03-28 14:08 UTC, ShankyJS commented on examples/cert-manager-ext-dns/README.md
> +Note: *If you are using Docker Hub*, `--docker-server` should be: `https://index.docker.io/v1/`
In my experience it failed when I did docker.io, it defaulted to /v2/ which failed when Garden pushed the images to the registry,

I think is good that we recommend the one that works for now (also did for Tao I believe).

2023-03-28 14:08 UTC, ShankyJS commented on examples/cert-manager-ext-dns/README.md
> +To generate the production certificates, turn `GENERATE_PROD_CERTS` to true and re-deploy the example, waiting for the new certificate to be ready.
Fair, doing the change. Thanks!

2023-03-28 14:10 UTC, stefreak commented on examples/cert-manager-ext-dns/README.md
> +Note: *If you are using Docker Hub*, `--docker-server` should be: `https://index.docker.io/v1/`
Makes sense, good to know – there seems to be an issue then with the API compatibility in the garden image build process? Thanks for sharing this with me

2023-03-28 14:29 UTC, ShankyJS commented on examples/cert-manager-ext-dns/README.md
> +Deploy again to generate the staging certificates with `garden deploy --yes`.
1. First deployment deploys the site without using any certificate and GENERATE_STG_CERTIFICATES is false, so no certificates were generated (Doing this to make sure we demonstrate how the flags work).
2. Second deployment deploys  GENERATE_STG_CERTIFICATES to true which creates the Secret needed for the third deployment (unfortunately they cannot be in the same deploy or Garden fails :().
3. Third deployment is actually adding the tlsCertificates (uncommenting it) which adds the certificate to your ingress.

````
tlsCertificates:
  - name: staging-cert
    secretRef:
      name: staging-cert
````

The only way we could make it more efficient is telling the user to do step 1 and 2 combined, but not sure how to feel about that one, what do you think?

2023-03-28 14:33 UTC, stefreak commented on examples/cert-manager-ext-dns/README.md
> +Deploy again to generate the staging certificates with `garden deploy --yes`.
I think you're right and it is fine like it is.

2023-03-28 14:38 UTC, ShankyJS commented on examples/cert-manager-ext-dns/README.md
> +Note: *If you are using Docker Hub*, `--docker-server` should be: `https://index.docker.io/v1/`
It seems like it does, I had a lot of pains when trying to use /v2/, please try to replicate it whenever you have a chance so we can discard compatibility issues!

2023-03-28 14:56 UTC, stefreak approved these changes
Thank you for the awesome work 🥇

2023-03-28 15:05 UTC, merged