Fix mutating action versions
garden-io/garden pull request #4040
Opened 2023-04-03 22:27 UTC by edvald

Plus some other minor issues discovered in the process.

cc @Orzelius

2023-04-04 07:43 UTC, Orzelius approved these changes
Had some non-blocking comments

2023-04-04 07:43 UTC, Orzelius commented on core/src/plugins/kubernetes/container/exec.ts
> +  if (!status.detail?.detail.workload || !includes(["ready", "outdated"], status.detail.state)) {
Could we maybe rename the `detail.state` to something else to reduce confusion, for example `serviceStatus`?

2023-04-04 07:43 UTC, Orzelius commented on core/src/actions/base.ts
> +    return cloneDeep(key ? this._config[key] : this._config)
Some integration tests used the return to modify action configs, how would this be done now?

2023-04-04 07:45 UTC, thsig commented on core/src/actions/base.ts
> +    return cloneDeep(key ? this._config[key] : this._config)
Maybe we'll need to override these methods in the test setup, then?

2023-04-04 07:53 UTC, Orzelius commented on core/src/plugins/kubernetes/container/exec.ts
> +  if (!status.detail?.detail.workload || !includes(["ready", "outdated"], status.detail.state)) {
Also probably the status two lines below should be changed as well

2023-04-04 16:34 UTC, edvald commented on core/src/plugins/kubernetes/container/exec.ts
> +  if (!status.detail?.detail.workload || !includes(["ready", "outdated"], status.detail.state)) {
Yeah, I have that rename on the TODO. Also getting rid of `.detail.detail` :P

2023-04-04 16:43 UTC, edvald commented on core/src/actions/base.ts
> +    return cloneDeep(key ? this._config[key] : this._config)
For testing purposes it's also possible to directly manipulate the config on the action object, instead of after retrieving via `getConfig()`.

2023-04-05 08:32 UTC, vvagaytsev commented on core/src/actions/base.ts
> +    return cloneDeep(key ? this._config[key] : this._config)
We also got [one unit test failure](https://app.circleci.com/pipelines/github/garden-io/garden/16332/workflows/70782cff-e9a4-4b79-a33e-2f08afd500a0/jobs/275027) because of this.

We have a similar test case for the `Test` action [here](https://github.com/garden-io/garden/blob/0.13/core/test/unit/src/router/test.ts#L114). It looks like rewriting the `Run` action test, in the same way, will fix the problem.

Also, (not urgent), it might be nice to refactor the [`run.ts`](https://github.com/garden-io/garden/blob/0.13/core/test/unit/src/router/run.ts) and [`test.ts`](https://github.com/garden-io/garden/blob/0.13/core/test/unit/src/router/test.ts) to have the same approach of creating test actions, and, maybe, extract some shared helpers.

2023-04-05 09:18 UTC, vvagaytsev requested changes

2023-04-05 09:18 UTC, vvagaytsev commented on core/src/plugins/kubernetes/container/exec.ts
> +  if (!status.detail?.detail.workload || !includes(["ready", "outdated"], status.detail.state)) {
@edvald should the same fix been applied to [`helm exec`](https://github.com/garden-io/garden/blob/0.13/core/src/plugins/kubernetes/helm/exec.ts#L61) and [`kubernetes-type exec`](https://github.com/garden-io/garden/blob/0.13/core/src/plugins/kubernetes/kubernetes-type/exec.ts#L52)?

2023-04-06 00:41 UTC, edvald commented
Updated, should be good now @vvagaytsev

2023-04-06 08:18 UTC, vvagaytsev approved these changes
Thanks, @edvald! 👍 
I updated the docs in https://github.com/garden-io/garden/pull/4040/commits/74de54d07f8067b6902b2c9dd6cd20bdf65d1d50

Now it's ready to go! 🚀

2023-04-06 09:42 UTC, merged