fix: login/logout using the configured domain
garden-io/garden pull request #4050
Opened 2023-04-05 12:11 UTC by mkhq

**What this PR does / why we need it**:

Ensures that the login/logout commands uses the cloud domain in the project config. Both have the `noProject` flag set which leads to the garden instance not being initialized with a project config.  

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

@edvald There was an earlier commit which reverted this behavior because of the dev command, https://github.com/garden-io/garden/commit/7f93b90830e1968526fa7f748e6f195c9a6e4421. Could you give some more context on how this relates?

2023-04-05 12:13 UTC, edvald requested changes

2023-04-05 12:13 UTC, edvald commented on core/src/commands/login.ts
> +    const projectConfig: ProjectResource | undefined = await cli!.getProjectConfig(log, garden.projectRoot)
There was a reason for changing this. The `cli` parameter is not populated when running from the dev command. This will need to be fixed differently, with that in mind.

2023-04-05 12:16 UTC, mkhq commented on core/src/commands/login.ts
> +    const projectConfig: ProjectResource | undefined = await cli!.getProjectConfig(log, garden.projectRoot)
`login` and `logout` are currently not listed as commands in the `garden dev` help. Should we make that possible?

2023-04-05 12:18 UTC, edvald commented on core/src/commands/login.ts
> +    const projectConfig: ProjectResource | undefined = await cli!.getProjectConfig(log, garden.projectRoot)
They should be listed imo. I think it's a reasonable thing to do in the console.

2023-04-05 14:28 UTC, edvald commented on core/src/cli/command-line.ts
> +const overrideHiddenCommands = ["login", "logout"]
A simpler approach would be to just remove the `hidden` flag from the commands :P I don't see any reason not to.

2023-04-05 14:29 UTC, edvald commented
One last comment, otherwise seems good to me. Did you test it in the dev command?

2023-04-05 15:57 UTC, mkhq commented on core/src/cli/command-line.ts
> +const overrideHiddenCommands = ["login", "logout"]
Yeah, this is a bit clunky... I looked into where `hidden` is used and found this for the reference docs: https://github.com/garden-io/garden/blob/0.13/core/src/docs/commands.ts#L26.

2023-04-05 15:57 UTC, mkhq commented
> One last comment, otherwise seems good to me. Did you test it in the dev command?

Yes a couple of times :)

2023-04-06 00:51 UTC, edvald commented on core/src/cli/command-line.ts
> +const overrideHiddenCommands = ["login", "logout"]
Oh I meant specifically for the login/logout commands. The flag is not necessary on them, and I'm not even sure why it's there in the first place.

2023-04-06 12:00 UTC, vvagaytsev commented
@edvald is this ready to go?

2023-04-11 17:20 UTC, edvald approved these changes

2023-04-11 19:14 UTC, merged