0.13 fix: use default target in sync overrides
garden-io/garden pull request #4075
Opened 2023-04-13 08:28 UTC by Orzelius

If a target is not specified for a sync override the default target is used.

Also unified the schema and types between targets for sync and sync overrides.

Changed the behavior to throw if target is not set instead of a warning. I don't think it makes sense to just warn here.

2023-04-14 07:56 UTC, vvagaytsev commented on core/src/plugins/kubernetes/sync.ts
> +        .description("Overrides for the container command and/or arguments for when in sync mode"),
```suggestion
        .description("Overrides for the container command and/or arguments for when in sync mode"),
        .description("Overrides for the container command and/or arguments when in sync mode."),
```

2023-04-14 07:57 UTC, vvagaytsev commented on core/src/plugins/kubernetes/sync.ts
> +        .description("Overrides for the container command and/or arguments for when in sync mode"),
Nit: the period is missing at the end of the sentence :) To sure about "for", maybe it's fine to have it there.

2023-04-14 08:00 UTC, vvagaytsev commented on core/src/plugins/kubernetes/commands/sync.ts
> -        Garden needs to be running in dev mode in this project for sync statuses to
I'm not sure if we should remove this completely. Maybe, we should just replace "dev mode" with "sync mode"

2023-04-19 13:56 UTC, edvald commented on core/src/plugins/kubernetes/commands/sync.ts
> -        Garden needs to be running in dev mode in this project for sync statuses to
I think this is fine actually.

2023-04-19 13:58 UTC, edvald requested changes
Suggested improving the error message, otherwise looks good!

2023-04-19 13:58 UTC, edvald commented on core/src/plugins/kubernetes/sync.ts
> +        .description("Overrides for the container command and/or arguments for when in sync mode"),
👍

2023-04-19 13:58 UTC, edvald commented on core/src/plugins/kubernetes/sync.ts
> +        `Sync override configuration on ${action.longDescription()} doesn't specify a target, and none is set as a default.`,
Maybe we can provide more clear instructions here, i.e. which field needs to be filled in.

2023-04-20 09:22 UTC, vvagaytsev commented
The [check-docs](https://app.circleci.com/pipelines/github/garden-io/garden/16517/workflows/9e77eead-2805-4403-98b5-3bae6d39fd2c/jobs/279717) step failed. Please, re-generate the docs.

2023-04-20 10:11 UTC, vvagaytsev approved these changes

2023-04-20 11:06 UTC, merged