0.13: some updated in "Using Garden" guide series
garden-io/garden pull request #4105
Opened 2023-04-20 13:28 UTC by vvagaytsev

**What this PR does / why we need it**:
This PR updates some guides from the "Using Garden" series. The new `actions.md` guide has been created on the basis of `modules.md`.

**Which issue(s) this PR fixes**:

Partially addresses #4067

**Special notes for your reviewer**:
Feel free to create commit suggestions or push some commits on top of the branch. Especially, for the new `actions.md` guide - it's very first version, so any improvements are highly appreciated :)

2023-04-20 15:25 UTC, Orzelius requested changes
Like in the other pr, please remove mentions of "service" unless talking about the k8s resource

2023-04-20 15:25 UTC, Orzelius commented on docs/using-garden/README.md
> +Prior to Garden `0.13`, modules had been the basic unit of _building_ in Garden. In this guide you'll learn how to split your project into modules that Garden can build.
```suggestion
Prior to Garden `0.13`, modules had been the unit of _building_ in Garden. In this guide you'll learn how to split your project into modules that Garden can build.
```

2023-04-20 16:29 UTC, vvagaytsev commented on docs/using-garden/README.md
> +Prior to Garden `0.13`, modules had been the basic unit of _building_ in Garden. In this guide you'll learn how to split your project into modules that Garden can build.
How critical is this? I just used the wording from the previous edition. It was
> Modules are the basic unit of _building_ in Garden.

2023-04-20 16:30 UTC, vvagaytsev commented on docs/using-garden/README.md
> +Since Garden `0.13`, actions have become the basic **unit of work** in Garden.
Same question as in https://github.com/garden-io/garden/pull/4105/files#r1172836850

2023-04-20 16:34 UTC, vvagaytsev commented on docs/using-garden/modules.md
> +
Added in https://github.com/garden-io/garden/pull/4105/commits/4913a290eef0c71235e84cfd1b92ee24ed51a941

2023-04-21 09:03 UTC, Orzelius commented on docs/using-garden/README.md
> +Since Garden `0.13`, actions have become the basic **unit of work** in Garden.
"basic" sounds like there is a more complex better building block but that's not the case

2023-04-24 08:17 UTC, vvagaytsev commented
I did some amendments and squashes, let's have one more review round @Orzelius @Walther @thsig

2023-04-24 09:22 UTC, Orzelius commented on docs/using-garden/actions.md
> +the [`demo-project`](../../examples/demo-project) example project):
I'm not 100% sure if this will work with gitbook. All other examples are marked with absolute github links. If it does that would be great though.

2023-04-24 09:23 UTC, Orzelius commented on docs/using-garden/actions.md
> +A Garden project is usually split up into the project-level configuration file, and several action-level configuration
```suggestion
A Garden project is usually split up into the project-level configuration file and several action-level configuration
```

2023-04-24 09:25 UTC, Orzelius commented on docs/using-garden/actions.md
> +You can also choose any `*.garden.yml` filename for each configuration file.
"choose any" sounds like there's a limited selection to choose from. I'd recommend to rewording to something like this
```suggestion
Filenames ending with`.garden.yml` will be picked up by Garden.
```

2023-04-24 09:29 UTC, Orzelius commented on docs/using-garden/actions.md
> +local `Dockerfile` or pulled from a remote repository.
This line is false. A build action is not needed if an already built image from a repository is used.

2023-04-24 09:34 UTC, Orzelius commented on docs/using-garden/actions.md
> +The `include` and `exclude` fields are a simple way to explicitly specify which sources should belong to a particular
```suggestion
The `include` and `exclude` fields are used to explicitly specify which sources should belong to a particular
```

We try to avoid words as "easy" or "simple" as for the user it might not seem that way

2023-04-24 09:35 UTC, Orzelius commented on docs/using-garden/actions.md
> +action. They both accept a list of POSIX-style paths or globs. For example:
```suggestion
action. Both accept a list of POSIX-style paths or globs. For example:
```
or
```suggestion
action. Both of them accept a list of POSIX-style paths or globs. For example:
```

2023-04-24 09:36 UTC, Orzelius commented on docs/using-garden/actions.md
> +Here, we only include the `Dockerfile` and all the `.py` files under `my-sources/`, but exclude the `my-sources/tmp`
```suggestion
Here we only include the `Dockerfile` and all the `.py` files under `my-sources/`, but exclude the `my-sources/tmp`
```

2023-04-24 09:38 UTC, Orzelius commented on docs/using-garden/actions.md
> +Sometimes, it's useful to define several actions in the same `garden.yml` file. One common situation is where more than
```suggestion
Sometimes it's useful to define several actions in the same `garden.yml` file. One common situation is where more than
```

2023-04-24 09:39 UTC, Orzelius commented on docs/using-garden/actions.md
> +It also might be better for maintainability to have multiple actions of the same `kind` in the same configuration file,
This point is repeated on L99

2023-04-24 09:41 UTC, Orzelius commented on docs/using-garden/actions.md
> +### Multiple actions in the same directory
I'm not sure if this section is needed. All the necessary info was already [written earlier](https://github.com/garden-io/garden/pull/4105/files#diff-778425512afdaa87f3cc1f68b8dd4053c2efc6a6ac0e5da6c1940cbc5251babdR99-R103)

2023-04-24 09:42 UTC, Orzelius commented on docs/using-garden/actions.md
> +## Examples
maybe add a section about example projects here as well.

2023-04-24 12:06 UTC, vvagaytsev commented on docs/using-garden/actions.md
> +the [`demo-project`](../../examples/demo-project) example project):
This should work fine. I used relative links in the local mode guide, and it worked well in docs.garden.io.

2023-04-24 12:18 UTC, vvagaytsev commented on docs/using-garden/actions.md
> +### Multiple actions in the same directory
Agree, I was thinking about combining those sections. I got both of them from the original modules guide. I'll change this soon.

2023-04-24 12:22 UTC, vvagaytsev commented on docs/using-garden/actions.md
> +### Multiple actions in the same directory
Remove the section in https://github.com/garden-io/garden/pull/4105/commits/f3f67ef67abd6d15974599d158ab1be1b9438081 as it didn't add anything new.

2023-04-25 05:51 UTC, vvagaytsev commented on docs/using-garden/actions.md
> +It also might be better for maintainability to have multiple actions of the same `kind` in the same configuration file,
Removed it

2023-04-25 06:13 UTC, vvagaytsev commented on docs/using-garden/actions.md
> +local `Dockerfile` or pulled from a remote repository.
So, does it behave anyhow differently from module-based builds?

What the line above says is that the image can be either built locally or pulled from a remote repository. The `Build` action declaration is still necessary, isn't it? 

Let's consider an example:
```yaml
kind: Build
name: postgres-db
description: Postgres DB container
type: container
image: postgres:12 # pulls the image from a remote Docker repo, no local build happens

---

kind: Deploy
name: postgres-db
build: postgres-db # refers to the name of the Build action above
...
```

We can't use `build: postgres:12` in the `Deploy` action above because there is no `Build` action named `postgres:12` defined in the config, can we? Please, correct me if I'm wrong.

Thus, there is nothing to build locally, but the `Build` action is still executed - it either finds an already existing pulled image in the local Docker registry (and this is a pure no-op "build") or pulls a new one from the remote repository.

2023-04-25 08:14 UTC, Orzelius commented on docs/using-garden/actions.md
> +local `Dockerfile` or pulled from a remote repository.
There's no `image` field on a container build action. If you want to deploy an existing image you set it under the `spec.image` field of a container deploy. In that case a build does not have to be specified. https://github.com/garden-io/garden/blob/0.13/docs/reference/action-types/Deploy/container.md#specimage

2023-04-25 08:18 UTC, Orzelius approved these changes
🚀

2023-04-25 08:18 UTC, Orzelius commented on docs/using-garden/actions.md
> +See more examples in the [examples on our GitHut repository](../../examples).
```suggestion
See more [examples on our GitHut repository](../../examples).
```

2023-04-25 08:32 UTC, vvagaytsev commented on docs/using-garden/actions.md
> +local `Dockerfile` or pulled from a remote repository.
Ah, right! Thank you! 👍 I'll fix this.

2023-04-25 08:45 UTC, vvagaytsev commented on docs/using-garden/actions.md
> +local `Dockerfile` or pulled from a remote repository.
Deleted that obsolete snippet in https://github.com/garden-io/garden/pull/4105/commits/1097e3a9917466e6ee754a26f464d34a0b384635

We have a reference to the action types page.

2023-04-25 08:52 UTC, merged