docs: update local mode guide to use `0.13` terms
garden-io/garden pull request #4106
Opened 2023-04-20 13:46 UTC by vvagaytsev

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-04-20 15:07 UTC, Orzelius requested changes
Can you remove all mentions of "service". I think we just call all of them deploys now unless specifically talking about the k8s services.

2023-04-20 15:07 UTC, Orzelius commented on docs/guides/running-service-in-local-mode.md
>  type: container
I don't think the build is needed here

2023-04-20 15:07 UTC, Orzelius commented on docs/guides/running-service-in-local-mode.md
> +type: container
I don't think the build is needed here

2023-04-20 15:27 UTC, vvagaytsev commented on docs/guides/running-service-in-local-mode.md
> +or [`helm`](../reference/action-types/Deploy/helm.md) service. This limitation is planned to be removed in Garden
Right, it should be "`Deploy` action".

2023-04-20 16:26 UTC, vvagaytsev commented
@Orzelius thanks for the comments! I've pushed 2 new commits with the requested changes addressed. Please, take a look.

2023-04-21 08:54 UTC, Orzelius approved these changes
Some more suggestions

2023-04-21 08:54 UTC, Orzelius commented on docs/guides/running-service-in-local-mode.md
> +  _local mode_ and deployed in a target k8s cluster.
```suggestion
* **Target k8s workload** -
  a [Kubernetes Workload](https://kubernetes.io/docs/concepts/workloads/) produced from a `Deploy` action with a 
  _local mode_ configuration that's deployed to the target kubernetes cluster.
```

2023-04-21 08:54 UTC, Orzelius commented on docs/guides/running-service-in-local-mode.md
> +local app.
```suggestion
A local application can be used instead of a kubernetes workload by adding a _local mode_ configuration 
to the `Deploy action`
```

I don't like the k8s abbreviation, we don't use it elsewhere and it sounds too slangy for my liking.
Also I think this reads a bit clearer.

2023-04-21 09:26 UTC, merged