0.13: update docs, examples and some code
garden-io/garden pull request #4119
Opened 2023-04-24 14:25 UTC by Orzelius

Please make your way to the commits

2023-04-25 06:45 UTC, vvagaytsev commented on docs/k8s-plugins/action-types/container.md
> +The `container` action type is an abstraction that can be used with multiple plugins. [See here](../../other-plugins/container.md) for an in-depth guide on the action type itself. Continue reading fo
A minor nit :) We use the `fixed width` style when we refer to the `container` build action type later in the doc. Would it be nicer to use it here as well?

2023-04-25 06:55 UTC, vvagaytsev commented on docs/k8s-plugins/action-types/helm.md
> +Here's a test action from the [vote-helm example](https://github.com/garden-io/garden/tree/0.12.51/examples/vote-helm/vote/garden.yml.
This link points to the `0.12.51` tag of the `main` branch. That code revision has a module-based configuration. We can replace it with a relative link, it should also work fine with the GitBook.

2023-04-25 06:56 UTC, vvagaytsev commented on docs/k8s-plugins/action-types/helm.md
> +You can define a remote environment as a `production` environment by setting the [production flag](../../reference/project-config.md#environmentsproduction) to `true`. This affects some default behav
```suggestion
You can define a remote environment as a `production` environment by setting the [production flag](../../reference/project-config.md#environmentsproduction) to `true`. This affects some default behavior when working with `helm`  actions. See the [Deploying to production](../advanced/deploying-to-production.md) guide for details.
You can define a remote environment as a `production` environment by setting the [production flag](../../reference/project-config.md#environmentsproduction) to `true`. This affects some default behavior when working with `helm` actions. See the [Deploying to production](../advanced/deploying-to-production.md) guide for details.
```

2023-04-25 06:57 UTC, vvagaytsev commented on docs/k8s-plugins/action-types/helm.md
> +You can define a remote environment as a `production` environment by setting the [production flag](../../reference/project-config.md#environmentsproduction) to `true`. This affects some default behav
Nit: extra space between `helm` and actions

2023-04-25 06:58 UTC, vvagaytsev commented on docs/k8s-plugins/action-types/helm.md
> +and the [vote-helm](https://github.com/garden-io/garden/tree/0.12.51/examples/vote-helm) example project for a full project
Same as in https://github.com/garden-io/garden/pull/4119/commits/a894ebf941599cac7498ded9bd5c281a3e9a4ce1#r1176082959

The link points to the example with the module-based config.

2023-04-25 07:04 UTC, vvagaytsev requested changes
Looks good, but some example link should be double-checked.
Also left a few non-blocking comments.

One more general note. We do not have any strong convention for spelling action kinds. Should we spell those like `Kind` (e.g. `Build`, `Deploy`, etc.)? Just to make a clear difference between the normal verbs and the action kinds we refer to. I'm not sure if this is necessary. In the most cases the meaning is clear enough from the context. It's more about having a unified spelling style.

2023-04-25 13:44 UTC, vvagaytsev commented
@Orzelius I've removed the blocking changes request. Please check the links to the examples and update those to relative ones if necessary. Otherwise, it's good to go! 👍 

Thanks for a great job! 🚀 Let's get his merged.

2023-04-26 07:34 UTC, Orzelius commented on docs/k8s-plugins/action-types/helm.md
> +You can define a remote environment as a `production` environment by setting the [production flag](../../reference/project-config.md#environmentsproduction) to `true`. This affects some default behav
I'm not sure what you mean by fixed width tbh

2023-04-26 07:35 UTC, Orzelius commented on docs/k8s-plugins/action-types/container.md
> +The `container` action type is an abstraction that can be used with multiple plugins. [See here](../../other-plugins/container.md) for an in-depth guide on the action type itself. Continue reading fo
I'm not sure what you mean by fixed width tbh

2023-04-26 08:19 UTC, merged