0.13 docs update tutorials
garden-io/garden pull request #4127
Opened 2023-04-26 11:22 UTC by vvagaytsev

**What this PR does / why we need it**:
Addresses the tutorials part of #4067.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-05-02 16:56 UTC, vvagaytsev commented on docs/tutorials/your-first-project/1-initialize-a-project.md
> +[//]: # (TODO: `garden create action` is still under construction, update this section when the command is ready)
Agree, the command can wait. I'll change the tutorial to use explicit configuration code snippets for action definitions.

2023-05-08 10:24 UTC, vvagaytsev commented on docs/tutorials/your-first-project/1-initialize-a-project.md
> +[//]: # (TODO: `garden create action` is still under construction, update this section when the command is ready)
Changed this in https://github.com/garden-io/garden/pull/4127/commits/1bc2439daa7c0ed83d226fe6bb25ea7e5e53c101

2023-05-08 10:24 UTC, vvagaytsev commented
@Orzelius @Walther now this is ready for the second review round :)

2023-05-08 10:29 UTC, Orzelius commented
would you mind updating the target branch, there are 5k+ line changes in this pr currently

2023-05-08 10:37 UTC, vvagaytsev commented
> would you mind updating the target branch, there are 5k+ line changes in this pr currently

Ah, sorry, my bad :) I've just updated it, thanks 👍

2023-05-08 12:18 UTC, Orzelius requested changes
some nitty-pickies

2023-05-08 12:18 UTC, Orzelius commented on docs/tutorials/your-first-project/1-initialize-a-project.md
> +# This defines an image to be used and refers the 'backend' Build action defined above
```suggestion
# Reference to the Build action that builds the image to be deployed (defined above)
```

Now when I think this is a bit tricky to explain in a concise way. Best I could come up ^

2023-05-08 12:18 UTC, Orzelius commented on docs/tutorials/your-first-project/1-initialize-a-project.md
> +# This block is necessary to deploy and expose the backend application
```suggestion
# Action type specific config goes under the `spec` block
```

I think this is more useful

2023-05-08 12:18 UTC, Orzelius commented on docs/tutorials/your-first-project/1-initialize-a-project.md
> +Create an empty `frontend.garden.yml` config file in the `frontend` directory and add the following lines:
```suggestion
Create a `frontend.garden.yml` config file in the `frontend` directory and add the following lines:
```

2023-05-08 12:18 UTC, Orzelius commented on docs/tutorials/your-first-project/1-initialize-a-project.md
> +# This defines an image to be used and refers the 'frontend' Build action defined above
I think this can be removed as it's explained above

2023-05-08 12:18 UTC, Orzelius commented on docs/tutorials/your-first-project/1-initialize-a-project.md
> +# Dependency section is used to ensure the deployment order. The frontend will be deployed after the backend.
```suggestion
# Dependency section is used to specify action execution order. The frontend will be deployed after the backend is deployed.
# Dependency for the Build action is implicit.
```

2023-05-08 12:18 UTC, Orzelius commented on docs/tutorials/your-first-project/1-initialize-a-project.md
> +# This block is necessary to deploy and expose the frontend application
I think this can be removed as it's explained above

2023-05-08 12:18 UTC, Orzelius commented on docs/tutorials/your-first-project/1-initialize-a-project.md
> +Before deploying the application, you need to set up a local kubernetes cluster or connect to a remote cluster.
```suggestion
Before deploying, you need to set up a local kubernetes cluster or connect to a remote cluster.
```

2023-05-08 12:18 UTC, Orzelius commented on docs/tutorials/your-first-project/3-deploy-and-test.md
> +--- # the yaml separator is necessary to delimit different actions
No need to repeat the comment imo, just distracts from other more important ones

2023-05-08 12:18 UTC, Orzelius commented on docs/tutorials/your-first-project/3-deploy-and-test.md
> +  - deploy.frontend # <- we want the frontend service to be running and up-to-date for this test
Actually there's no need for this, but it can be reworded to something like

```suggestion
  - deploy.frontend # <- have the frontend service be running and up-to-date before the test
```

2023-05-08 12:18 UTC, Orzelius commented on docs/tutorials/your-first-project/4-configure-your-project.md
> +4. Set up your actions, getting them building and deploying.
```suggestion
4. Configure your actions, get them building and deploying.
```

2023-05-08 12:47 UTC, vvagaytsev commented on docs/tutorials/your-first-project/1-initialize-a-project.md
> +# This block is necessary to deploy and expose the frontend application
Removed in https://github.com/garden-io/garden/pull/4127/commits/e1230b742ace72516a30c9a2565fc9062f184f0a

2023-05-08 12:47 UTC, vvagaytsev commented on docs/tutorials/your-first-project/3-deploy-and-test.md
> +--- # the yaml separator is necessary to delimit different actions
Removed in https://github.com/garden-io/garden/pull/4127/commits/e1230b742ace72516a30c9a2565fc9062f184f0a

2023-05-08 12:48 UTC, vvagaytsev commented
Thanks for the comments and improvement @Orzelius! Now everything has been addressed and applied. Please review again :)

2023-05-08 12:59 UTC, Orzelius approved these changes
All good from me! 🎸

2023-05-08 13:05 UTC, merged