0.13 fix: throw when test or run is not found
garden-io/garden pull request #4146
Opened 2023-05-02 08:33 UTC by Orzelius

2023-05-02 11:23 UTC, Walther submitted a review, later dismissed
Thanks for the quick fix!

2023-05-02 14:19 UTC, edvald requested changes

2023-05-02 14:19 UTC, edvald commented on core/src/commands/run.ts
> +      names,
This approach removes the ability to use wildcards in names, so it won't work as-is. Here's one alternative approach: https://github.com/garden-io/garden/blob/d21b826cf981300778815ebf73260d1f7cfd6857/core/src/commands/sync/sync-start.ts#L112

Overall I'd suggest that we should A) throw if a name _without_ a wildcard is passed in but it does not exist, and B) warn if no actions are matched.

2023-05-03 09:21 UTC, Orzelius commented on core/src/commands/run.ts
> +      names,
Yeah that was an oversight on my part. Implemented as suggested in [3765085](https://github.com/garden-io/garden/pull/4146/commits/37650859eb0d8221ca6d31ecb00405a7c71bc650)

2023-05-03 11:47 UTC, edvald approved these changes
Looks good!

2023-05-03 14:12 UTC, Orzelius commented
I think this is good to go. Integ test failures are unrelated and are being fixed separately.

2023-05-04 07:12 UTC, merged