fix osx install deps script and add pointer about Rosetta
garden-io/garden pull request #4157
Opened 2023-05-03 09:37 UTC by shumailxyz

**What this PR does / why we need it**:
- Fixes the error regarding brew install `kubernetes-helm` as its now renamed to helm. 
- Adds pointer about Rosetta requirement in installation instructions for Apple Silicon macs. In case Rosetta is not installed, user faces: `bad CPU type in executable` while using `garden` in terminal.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-05-03 09:55 UTC, Orzelius approved these changes

2023-05-03 09:57 UTC, Walther requested changes
Thanks for the update!

I'm not 100% sure if we need Rosetta for something - I just got the new work laptop with apple silicon and can run the `garden` binary from a `yarn build` fully natively without Rosetta installed. Let's double-check if we need it

2023-05-03 10:01 UTC, Walther approved these changes

2023-05-03 10:05 UTC, stefreak commented
> Thanks for the update!
> 
> ~I'm not 100% sure if we need Rosetta for something - I just got the new work laptop with apple silicon and can run the `garden` binary from a `yarn build` fully natively without Rosetta installed. Let's double-check if we need it - ideally we should be providing fully native arm builds soon <3~
> 
> EDIT: scratch that, let's keep the native arm support as a separate task for later

@Walther for yarn dev you are absolutely right and it already runs natively (since we moved to node 18). But if you install a released version of garden, it'll require rosetta at the moment, as we do not publish ARM builds.

2023-05-03 10:06 UTC, shumailxyz commented
yeah, it 's only an issue if you install released version. I had fresh laptop, installed using homebrew and ran into error because Rosetta wasn't installed.

2023-05-05 07:42 UTC, vvagaytsev approved these changes
Nice! Thank you! 👍

2023-05-05 14:51 UTC, merged