chore(pulumi): make pulumi backendURL and orgName as non-required fields
garden-io/garden pull request #4164
Opened 2023-05-03 14:15 UTC by srihas-g

**What this PR does / why we need it**:
Initialize Pulumi's backendURL and orgName with default values. Also make them as non-required config options.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-05-03 15:55 UTC, twelvemo requested changes

2023-05-03 15:55 UTC, twelvemo commented on plugins/pulumi/config.ts
> +  orgName: string
Shouldn't `orgName` stay optional too?

2023-05-03 16:32 UTC, stefreak commented on plugins/pulumi/config.ts
> +    orgName: joi.string().default(null).allow(null).description(dedent`
why null? orgName was already optional, without `default(null).allow(null)`

2023-05-03 16:35 UTC, stefreak requested changes

2023-05-03 16:35 UTC, stefreak commented on plugins/pulumi/config.ts
> +  orgName: string
If orgName is null or a string (like defined in joi) it should be
```suggestion
  orgName: string | null
```

but I think it would be better to avoid null if possible, and keep using undefined in case it isn't defined (keep `orgName?: string`

2023-05-03 16:35 UTC, stefreak commented on plugins/pulumi/helpers.ts
> +    return provider.config.orgName
👍 This looks much better than before. The code before looks strange actually 👀

2023-05-03 16:35 UTC, stefreak commented on plugins/pulumi/config.ts
> +    backendURL: joi.string().uri().default("https://api.pulumi.com").description(dedent`
Ooops, good catch! I'd suggest we add tests for the pulumi config validation. That should be pretty easy. Let's pair on this @srihas-g

2023-05-03 16:44 UTC, srihas-g commented on plugins/pulumi/config.ts
> +    backendURL: joi.string().uri().default("https://api.pulumi.com").description(dedent`
I'd love to do it in another PR and get the breaking changes out of main branch first.

2023-05-04 14:47 UTC, stefreak commented on plugins/pulumi/handlers.ts
> -      throw new ConfigurationError("Pulumi: `cacheStatus: true` is not supported for self-managed backends", {
what happened to these checks? Where do they live now?

2023-05-04 14:48 UTC, stefreak commented on plugins/pulumi/handlers.ts
> -      throw new ConfigurationError("Pulumi: `cacheStatus: true` is not supported for self-managed backends", {
I think they are important, because otherwise I remember there were some really cryptic error messages when configuring these things

2023-05-09 08:19 UTC, twelvemo approved these changes
Looks good to me but since I also worked on this one, would also like to see @stefreak 's review.

2023-05-09 09:12 UTC, stefreak requested changes
Cool, good work! I think the example code can be slightly improved to make it easier to read and understand. 

Also I'm confused as to why backendURL in the module definition has been removed; I had a look into the code and the exec function should have no issues running multiple processes with different sets of environment variables concurrently.

2023-05-09 09:12 UTC, stefreak commented on docs/pulumi-plugin/configure-provider.md
> +kind: Project
I find the example slightly confusing:

Instead of declaring defaults for every variable above, and then overriding e.g. using `orgName: null`, I think it would be easier to read if only non-null variables are declared in every environment, and then you add `|| null` in the provider configuration.

2023-05-09 09:12 UTC, stefreak commented on plugins/pulumi/config.ts
> -    backendURL: joi.string().uri().optional().allow(null).description(dedent`
Why do you remove backendURL here? I looked into the code that executes the pulumi command, and we correctly pass env as a dictionary to the exec function, so there should be no conflict with multiple pulumi processes concurrently.

2023-05-09 09:21 UTC, srihas-g commented on plugins/pulumi/config.ts
> -    backendURL: joi.string().uri().optional().allow(null).description(dedent`
We faced some misbehaviour with Pulumi stack select based on tags when multiple backends are in use, hence we are going ahead with one backend for the provider for the entire env approach first and then get back on this one as an added feature.

2023-05-09 09:59 UTC, srihas-g commented on docs/pulumi-plugin/configure-provider.md
> +kind: Project
agreed, updated the example

2023-05-09 10:26 UTC, stefreak approved these changes

2023-05-09 13:25 UTC, stefreak approved these changes

2023-05-09 13:50 UTC, merged