chore: 0.13 analytics improvements
garden-io/garden pull request #4179
Opened 2023-05-05 19:06 UTC by mkhq

**What this PR does / why we need it**:

Adapt the analytics to 0.13 by including project stats for action kinds.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-05-11 16:59 UTC, eysi09 requested changes
Two comments, otherwise looks great! 🙏

2023-05-11 16:59 UTC, eysi09 commented on core/src/analytics/analytics.ts
> +  actionBuildsCount: number
Nitpick but feels like this should be called `buildActionCount`, `deployActionCount`, etc

2023-05-11 16:59 UTC, eysi09 commented on core/src/analytics/analytics.ts
> +    commandIteration: number
I think we should skip this for now since we're changing this behaviour in general:

- Introduce the concept of a parent session (with a `parentSessionId`)
- This would be a persistent session like `garden dev`
- Every time you run a command within that session, via the terminal / Cloud / Desktop, that gets counted as a single session within the parent session. 
- With this, a command can't technically be run twice. Each session is exactly a single command but it can have a parent command. Only persistent commands like `garden dev` can be parent commands.

2023-05-12 06:27 UTC, eysi09 submitted a review, later dismissed

2023-05-12 06:28 UTC, mkhq commented
@eysi09 I've re-enabled the failing nock tests, if this turns out to be an issue still we can re-add the skip.

2023-05-12 08:49 UTC, mkhq commented
> @eysi09 I've re-enabled the failing nock tests, if this turns out to be an issue still we can re-add the skip.

Added the skip back because those tests keep on failing.

2023-05-12 09:03 UTC, eysi09 approved these changes

2023-05-12 10:14 UTC, merged