feat(core): --logs option for deploy command
garden-io/garden pull request #4180
Opened 2023-05-06 13:51 UTC by thsig

**What this PR does / why we need it**:

When used, the `--logs` option streams service logs during deployment, and then keeps the command running until the user exits it.

This is useful for combining deployment with log streaming.

**Special notes for your reviewer**:

We should only be streaming logs from the current time onwards, but the logs monitor currently doesn't support the `since` option. I didn't add it back in since IIRC @eysi09 is working on a branch that addresses that.

2023-05-06 13:52 UTC, thsig commented
Here's a screenshot:

<img width="499" alt="Screenshot 2023-05-06 at 15 44 40" src="https://user-images.githubusercontent.com/382137/236628387-4f52a1b6-a693-46df-8aa0-a74b6650f2e7.png">

2023-05-06 13:55 UTC, eysi09 requested changes
Couple of comments, otherwise looks great!

2023-05-06 13:55 UTC, eysi09 commented on core/src/commands/deploy.ts
> +// import figures from "figures"
Remove?

2023-05-06 13:55 UTC, eysi09 commented on core/test/unit/src/commands/deploy.ts
> +        "logs": false,
Should we test the case were `logs=true`?

2023-05-06 13:55 UTC, eysi09 commented on core/test/unit/src/commands/deploy.ts
> +        "logs": false,
...or are all of these for non-persistent runs?

2023-05-06 19:31 UTC, thsig commented on core/test/unit/src/commands/deploy.ts
> +        "logs": false,
These are all for non-persistent runs—I'm not sure how much value there is in testing this functionality specifically (all the interesting parts happen inside the logs monitor and the plugin handlers under that).

2023-05-07 10:54 UTC, eysi09 approved these changes

2023-05-07 12:43 UTC, merged