chore: get rid of "modules" term
garden-io/garden pull request #4270
Opened 2023-05-15 10:17 UTC by vvagaytsev

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-05-15 16:04 UTC, Orzelius requested changes
some nitties

2023-05-15 16:04 UTC, Orzelius commented on docs/using-garden/actions.md
> +expressions.
```suggestion
Disabled actions are skipped with other action kinds and dependency declarations to them are ignored.
Template strings referencing runtime outputs will fail to resolve when the action is
disabled, so you need to make sure to provide alternate values for them using conditional
expressions.
```

2023-05-15 16:20 UTC, Orzelius submitted a review, later dismissed

2023-05-16 14:47 UTC, vvagaytsev commented
@thsig feel free to push the changes to the existing branch and merge it.

2023-05-16 22:49 UTC, thsig approved these changes

2023-05-17 07:31 UTC, merged