feat(dockerhub): publish rootless containers
garden-io/garden pull request #4274
Opened 2023-05-15 13:59 UTC by stefreak

Add rootless container variant for use in environments where
using the root user is not possible, for example GitLab's Runner Operator

Supersedes #3865

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-05-15 14:41 UTC, stefreak commented
TODO: Sync with @worldofgeese to find out if these rootless images work and help make things easier in a rootless environment.

2023-05-15 16:33 UTC, stefreak commented on docs/reference/dockerhub-containers.md
> +| `acorn-*` or `0.12*`              | Garden CLI version is 0.13 (Codename Bonsai). If the tag name does not contain edge, this is the latest stable release. |
```suggestion
| `acorn-*` or `0.12-*`              | Garden CLI version is 0.12 (Codename Acorn). If the tag name does not contain edge, this is the latest stable release. |
```

2023-05-15 16:40 UTC, stefreak commented on docs/reference/dockerhub-containers.md
> +We publish a number of containers to our official DockerHub account ([hub.docker.com/gardendev](https://hub.docker.com/gardendev)).
Broken link
```suggestion
We publish a number of containers to our official DockerHub account ([hub.docker.com/u/gardendev](https://hub.docker.com/u/gardendev)).
```

2023-05-15 19:02 UTC, stefreak commented on support/alpine.Dockerfile
> +  && git init
Ownership of the git repo in garden static is not quite right yet. 
Getting this error when using the rootless container:

```
✖ Unexpected Git error occurred while running 'git status' from path "/garden/static". Exit code: 128. Error message: fatal: detected dubious ownership in repository at '/garden/static'
To add an exception for this directory, call:

	git config --global --add safe.directory /garden/static
✖ Command "git status" failed with code 128:

   fatal: detected dubious ownership in repository at '/garden/static'
To add an exception for this directory, call:

	git config --global --add safe.directory /garden/static
```

2023-05-16 08:47 UTC, worldofgeese requested changes

2023-05-16 08:47 UTC, worldofgeese commented on docs/README.md
> +* [Garden Containers on DockerHub](./reference/dockerhub-containers.md)
```suggestion
* [Garden Containers on Docker Hub](./reference/dockerhub-containers.md)
```
Docker Hub naming convention is to put a space between "Docker" and "Hub"

https://www.docker.com/products/docker-hub/

2023-05-16 08:47 UTC, worldofgeese commented on docs/reference/dockerhub-containers.md
> +We publish a number of containers to our official DockerHub account ([hub.docker.com/gardendev](https://hub.docker.com/gardendev)).
```suggestion
We publish a number of containers to our official Docker Hub account ([hub.docker.com/gardendev](https://hub.docker.com/u/gardendev)).
```

Space between "Docker" and "Hub"

2023-05-16 08:47 UTC, worldofgeese commented on docs/reference/dockerhub-containers.md
> +| [`gardendev/garden-aws-gcloud-azure`](https://hub.docker.com/r/gardendev/garden-aws-gcloud-azure) | Contains the Garden CLI, the Google Cloud CLI and the AWS CLI v2 |
```suggestion
| [`gardendev/garden-aws-gcloud-azure`](https://hub.docker.com/r/gardendev/garden-aws-gcloud-azure) | Contains the Garden CLI, the Google Cloud CLI, the AWS CLI v2, and the Azure CLI |
```

2023-05-16 08:47 UTC, worldofgeese commented on support/alpine.Dockerfile
> +  && git init
Why does Garden init a git repository at `static`?

2023-05-17 08:29 UTC, TimBeyer approved these changes
👏

2023-05-17 08:57 UTC, merged