improvement(sync-status): show all syncs
garden-io/garden pull request #4333
Opened 2023-05-19 23:21 UTC by thsig

**What this PR does / why we need it**:

We now show a sync status for syncs that aren't currently live (e.g. where the target resource isn't deployed).

2023-05-20 10:05 UTC, eysi09 commented on core/src/plugins/kubernetes/sync.ts
> +        targetDescription: stripAnsi(targetDescription),
This is a silly leftover from my changes. 

Should we just have a `targetDescription` variables and a `targetDescriptionLogMsg` so that we don't have to strip the ANSI characters.

2023-05-20 10:13 UTC, eysi09 requested changes
Works like a charm except the ANSI business. Great work!

2023-05-20 10:13 UTC, eysi09 commented on core/src/plugins/kubernetes/sync.ts
> +        source: sourceDescription,
Looks like are we also applying ANSI codes to the source. We should remove those. 

Otherwise it doesn't print right in the terminal and consumers of this API will get a funny looking string.

2023-05-20 10:13 UTC, eysi09 commented on core/src/plugins/kubernetes/sync.ts
> +        targetDescription: stripAnsi(targetDescription),
This is a silly leftover from my changes.

Should we just have a `targetDescription` variables and a `targetDescriptionLogMsg` so that we don't have to strip the ANSI characters?

2023-05-20 15:03 UTC, eysi09 submitted a review, later dismissed

2023-05-20 15:59 UTC, eysi09 commented on core/src/plugins/kubernetes/sync.ts
> +      // const { source: defaultSource, target: defaultTarget } = orientEndpoints({
Need to remove this, right?

2023-05-20 16:24 UTC, thsig commented
This should be good to go now (needs to be squashed before merging).

2023-05-21 15:48 UTC, edvald approved these changes

2023-05-21 15:48 UTC, merged