Feature/ce 34/bonsai readme
garden-io/garden pull request #4379
Opened 2023-05-22 16:20 UTC by worldofgeese

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-05-22 17:53 UTC, thsig commented
Thoughts on this, @eysi09?

2023-05-22 18:33 UTC, thsig commented
Looks great! There are a couple of dead links in there (have probably been dead for a while—I think we only run the docs check on changed files).

From the [CI run](https://app.circleci.com/pipelines/github/garden-io/garden/17760/workflows/ec107204-a326-4e86-af4f-4a6d1c1b6c67/jobs/308754):
```
  ERROR: 2 dead links found!
  [✖] https://go.garden.io/garden → Status: 404
  [✖] https://docs.garden.io/basics/installation → Status: 404
```

2023-05-22 18:34 UTC, eysi09 commented
This is beautiful! Love the simplicity and the terminal screencap. 

Just one thought, should we add a section called Docs that links to them, similar to what we have in the Community section. 

Beside the link at the top, there's not much that references to docs proper (except implicitly in other links) and you might think that's all there is to it.

2023-05-22 18:34 UTC, eysi09 requested changes
This is beautiful! Love the simplicity and the terminal screencap. 

Just one thought, should we add a section called Docs that links to them? Similar to what we have in the Community section.

Beside the link at the top, there's not much that references to docs proper (except implicitly in other links) and you might think that's all there is to it.

2023-05-22 19:37 UTC, shumailxyz commented on README.md
> +_If you love Garden, please ★ star this repository to show your support :green_heart:. Looking for support? Join our [Discord](https://go.garden.io/garden)._
```suggestion
_If you love Garden, please ★ star this repository to show your support :green_heart:. Looking for support? Join our [Discord](https://go.garden.io/discord)._
```

2023-05-23 08:07 UTC, Orzelius commented on README.md
> -![Stack Graph](docs/stack-graph-drawing.png)
I think the stack graph, preferably a picture should still be present. That was the feature that drew me in at first and I think it's the main selling point of Garden in general.

2023-05-23 08:07 UTC, Orzelius commented on README.md
> +![Garden dev deploy](https://raw.githubusercontent.com/ShankyJS/garden-quickstart-content/d8095ad1a8615edf49e721b8afcd901f3056e127/dev-mode.gif)
I think this should be a bit faster, maybe speed up the deploy bit. Also running something like `test e2e` after the deploy would show more of garden capabilities.

2023-05-23 08:09 UTC, worldofgeese commented on README.md
> +- [License](#license)
I googled a built-in ToC feature and couldn't find one. As I understand it, this is the correct way to do a ToC in GitHub-flavored Markdown. This is a ToC for the document itself. The links below the logo link out.

2023-05-23 08:11 UTC, worldofgeese commented on README.md
> +![Garden dev deploy](https://raw.githubusercontent.com/ShankyJS/garden-quickstart-content/d8095ad1a8615edf49e721b8afcd901f3056e127/dev-mode.gif)
This might be a stretch goal: @ShankyJS created it and it's already merged in the quickstart revamp.

2023-05-23 08:14 UTC, Orzelius commented on README.md
> +- [License](#license)
The screenshot I sent is the built in github toc, it's available for any md doc by clicking on the icon on top left

2023-05-23 08:15 UTC, Orzelius commented on README.md
> +![Garden dev deploy](https://raw.githubusercontent.com/ShankyJS/garden-quickstart-content/d8095ad1a8615edf49e721b8afcd901f3056e127/dev-mode.gif)
With just a deploy it's kinda lame tho, makes it seem like another preview environment provider

2023-05-23 08:17 UTC, worldofgeese commented on README.md
> +- [License](#license)
Sorry: the pic didn't come through on VS Code. I've never once noticed this, which I think is damning of GitHub's implementation. It's totally tucked away visually. I'm not going to die on this hill and am open to clearing out the ToC if you think it detracts from the experience.

2023-05-23 08:22 UTC, worldofgeese commented
> Looks great! There are a couple of dead links in there (have probably been dead for a while—I think we only run the docs check on changed files).
> 
> From the [CI run](https://app.circleci.com/pipelines/github/garden-io/garden/17760/workflows/ec107204-a326-4e86-af4f-4a6d1c1b6c67/jobs/308754):
> 
> ```
>   ERROR: 2 dead links found!
>   [✖] https://go.garden.io/garden → Status: 404
>   [✖] https://docs.garden.io/basics/installation → Status: 404
> ```

I've fixed the first dead link but I can't find the other in the README, https://docs.garden.io/basics/installation

2023-05-23 08:23 UTC, worldofgeese commented on README.md
> +- [License](#license)
Removed in latest commit

2023-05-23 08:29 UTC, shumailxyz commented
> I've fixed the first dead link but I can't find the other in the README, https://docs.garden.io/basics/installation

@worldofgeese here's the dead link


https://github.com/garden-io/garden/blob/a6ec2899ab57a6afbd4e72bde89a7ea2dbfcf1e7/README.md?plain=1#LL41C2-L41C29

2023-05-23 08:39 UTC, worldofgeese commented on README.md
> -![Stack Graph](docs/stack-graph-drawing.png)
Pushing back on this a bit: I'm trying for succinct and direct value. The problem with the Stack Graph is it's not something you can do. Can you suggest a way to communicate the value of the Stack Graph that isn't a very large image and doesn't require a lot of explanation?

"Garden's Stack Graph is a directed acyclic graph (uh oh now we have to explain a DAG). To use the Stack Graph (can't do this because it's inherent to Garden's design)..."

You see what I'm getting at? It's a lot of theory. As a user, I want to know a feature I can make use of. If it uses a DAG, that's not that important to me: what matters is the feature works and I can use it.

2023-05-23 08:41 UTC, worldofgeese commented on README.md
> +![Garden dev deploy](https://raw.githubusercontent.com/ShankyJS/garden-quickstart-content/d8095ad1a8615edf49e721b8afcd901f3056e127/dev-mode.gif)
I don't want to make this a merge blocker for release: can we try and improve it in a later PR?

2023-05-23 08:46 UTC, worldofgeese commented
> > I've fixed the first dead link but I can't find the other in the README, https://docs.garden.io/basics/installation
> 
> @worldofgeese here's the dead link
> 
> https://github.com/garden-io/garden/blob/a6ec2899ab57a6afbd4e72bde89a7ea2dbfcf1e7/README.md?plain=1#LL41C2-L41C29

Fixed, thanks!

2023-05-23 09:26 UTC, Orzelius commented on README.md
> +![Garden dev deploy](https://raw.githubusercontent.com/ShankyJS/garden-quickstart-content/d8095ad1a8615edf49e721b8afcd901f3056e127/dev-mode.gif)
sure

2023-05-23 09:36 UTC, Orzelius commented on README.md
> -![Stack Graph](docs/stack-graph-drawing.png)
> The problem with the Stack Graph is it's not something you can do.

Sure, but the graph allows doing things with garden that would otherwise be impossible or way less efficient. Just listing all those things without mentioning the graph sounds like empty promises or wild dreams to me. Literally all cool and useful functionality of garden that separates us from the competition relies on the Graph.

Maybe something like this:
* The stack graph allows you to declare the dependency structure of your project and track changes to avoid unnecessary builds, deploys and test runs. It's like ci/cd config that you can additionally use for development.

2023-05-23 11:30 UTC, eysi09 commented on README.md
> +Exit with `Ctrl+C` or `exit`.
You should exit by typing `exit`, otherwise you see this warning:

```
Syncs started during this session may still be active when this command terminates. You can run garden sync stop '*' to stop all code syncs. Hint: To stop code syncing when exiting garden dev, use Ctrl-D or the exit command.
→ Run garden util hide-warning dev-syncs-active to disable this warning.```

2023-05-23 11:32 UTC, worldofgeese commented on README.md
> +Exit with `Ctrl+C` or `exit`.
Fixed, thanks!

2023-05-23 11:35 UTC, eysi09 commented on README.md
> -![Stack Graph](docs/stack-graph-drawing.png)
I tend to agree with both points. 

How about we change the "Plugins" section to "How Garden Works". Add one paragraph on the Stack Graph, similar to what @Orzelius wrote above and then add the current "Plugins" stuff below? 

In it's current state, the Plugins section starts a bit abruptly with a "how actions are executed..." which might be confusing without the stack graph context.

2023-05-23 11:41 UTC, eysi09 commented on README.md
> -![Stack Graph](docs/stack-graph-drawing.png)
Something like:

## How Garden Works

Garden users describe their stack with YAML in terms of four actions: Builds, Deploys, Tests, Runs. This allows you to fully codify your workflows, making the reproducible and portable. 

How these actions executed depends on the plugins used. Our Kubernetes plugin is currently the most popular, followed by our Terraform and Pulumi plugins. 

For a deeper dive on the Stack Graph and how Garden works in general, we recommend:

- [How Garden Works](https://docs.garden.io/basics/how-garden-works)
- [A video tour of Garden's directed acyclic graph and getting started](https://www.youtube.com/watch?app=desktop&v=3gMJWGV0WE8)

For a plugin specific docs, checkout:

- [Kubernetes plugin](https://docs.garden.io/guides/remote-kubernetes)
- [Terraform plugin](https://docs.garden.io/terraform-plugin/about)
- [Pulumi plugin](https://docs.garden.io/pulumi-plugin/about)

2023-05-23 11:47 UTC, worldofgeese commented on README.md
> -![Stack Graph](docs/stack-graph-drawing.png)
@eysi09 I have pushed a commit with those changes. Can you review? 😺

2023-05-23 11:49 UTC, eysi09 commented on README.md
> -![Stack Graph](docs/stack-graph-drawing.png)
LGTM! Let's shipit.

2023-05-23 11:49 UTC, eysi09 approved these changes
💯

2023-05-23 11:57 UTC, vvagaytsev approved these changes
🚀

2023-05-23 12:20 UTC, merged