feat(cmd): add get actions command
garden-io/garden pull request #4449
Opened 2023-05-25 15:47 UTC by shumailxyz

**What this PR does / why we need it**:
Add `get actions` command

**Which issue(s) this PR fixes**:

Fixes #4218 

**Special notes for your reviewer**:

2023-05-26 08:56 UTC, Orzelius commented
@shumailxyz if you request review on a wip branch I don't really know if it should we reviewed yet and I get emails about new commits.

2023-05-26 09:11 UTC, shumailxyz commented
@Orzelius My bad. I thought i had removed all reviewers.

2023-05-26 17:17 UTC, shumailxyz commented
@garden-io/core I'd like to request a pre-review of the WIP PR. Still need to add tests and `get runs`, `get builds` and `get tests` command however would be nice if you could already take a quick look. Thanks.

2023-05-29 08:56 UTC, Orzelius reviewed
here's a few comments, hope they help. I take that the get deploy command is still under construction so I didn't dig in too deep, but it definitely should reuse more code from the get actions command.

2023-05-29 08:56 UTC, Orzelius commented on core/src/commands/get/get-actions.ts
> +interface GetActionsCommandResultActionObject {
```suggestion
interface GetActionsCommandResultItem {
```
I think it reads better like this

2023-05-29 08:56 UTC, Orzelius commented on core/src/commands/get/get-actions.ts
> +      .description(`The kind of action.`),
```suggestion
      .description(`Action kind (e.g. Build).`),
```

That's how we refer to it elsewhere in the documentation

2023-05-29 08:56 UTC, Orzelius commented on core/src/commands/get/get-actions.ts
> +    type: joi.string().required().description(`The Type of the action.`),
```suggestion
    type: joi.string().required().description(`Action Type (e.g. 'container').`),
```

2023-05-29 08:56 UTC, Orzelius commented on core/src/commands/get/get-actions.ts
> +        "The name of corresponding module name of an action. Only available if action is derived from module."
```suggestion
        "The name of the module the action is derived from. Only available for converted actions."
```

2023-05-29 08:56 UTC, Orzelius commented on core/src/commands/get/get-actions.ts
> +    `,
I don't think it's clear from this what's the parameter supposed to be. Is it action names, references or something else?

2023-05-29 08:56 UTC, Orzelius commented on core/src/commands/get/get-actions.ts
> +      Show the detailed info for each action, including state, path, dependencies, dependents, associated module and if action is disabled.
```suggestion
      Show the detailed info for each action, including state, path, dependencies, dependents, associated module and if the action is disabled.
```

2023-05-29 08:56 UTC, Orzelius commented on core/src/commands/get/get-actions.ts
> +        break
There's a handy `getActionsByKind()` on the graph class that would suit your needs here.

Maybe you could even add a `getActionsByKinds()` to the graph.

2023-05-29 08:56 UTC, Orzelius commented on core/src/commands/get/get-actions.ts
> +    })
I don't think you should await the `getActionState()` resolution as that would make then resolve all one by one making it slow if many actions states are resolved. There's a point to be made about running into throttling issues if we fire all of them simultaneously but I say we deal with that problem once it comes our way.

Also, maybe the action state should be behind a flag so it's not resolved by default. I don't think it's needed in most cases and it might just make the command unnecessarily slow.

2023-05-29 08:56 UTC, Orzelius commented on core/src/commands/get/get-actions.ts
> +    })
edit: it definitely shouldn't be resolved if `--detail=false`

2023-05-30 11:01 UTC, shumailxyz commented on core/src/commands/get/get-actions.ts
> +    })
Valid point. I'll move state resolution behind a flag e.g. `--with-state`

2023-05-30 11:02 UTC, shumailxyz commented on core/src/commands/get/get-actions.ts
> +        break
its basically the same and calls `getActionsByKind` under the hood with `kind: build`.

2023-05-31 15:28 UTC, Orzelius reviewed
I think there's a bit too much of repetition but other than that well done!

2023-05-31 15:28 UTC, Orzelius commented on core/src/commands/get/get-actions.ts
> +    if (opts["sort"] === "kind") {
I think there should always be a secondary sort by name alphabetically, would make stuff easier to find.

Feel free to skip adding this if you decide it's not important enough though. Stuff like this can be polished indefinitely.

2023-05-31 15:28 UTC, Orzelius commented on core/src/commands/get/get-builds.ts
> +  }
All of this should not be copy pasted across four commands. Only thing different about these is the action Kind. I would just create a single class and extend it four times. That base class should also reuse most of the logic from the get-actions class.

2023-05-31 15:28 UTC, Orzelius commented on core/test/unit/src/commands/get/get-builds.ts
> +describe("GetBuildsCommand", () => {
I think these four test suits should just be a single one looping the same tests. Currently it's not dry enough to my taste. I know loops for tests cases sounds funny at first but I think this is a valid case. I swear we already have a few somewhere in the codebase but I failed to find them.

2023-05-31 22:33 UTC, shumailxyz commented on core/src/commands/get/get-builds.ts
> +  }
Valid point, thanks for pointing. I initially thought that that as most of the stuff is static like description and args etc, it would be better to keep in its own files however now that you commented, i also feel that its quite repetitive so moved to a shared class.

2023-05-31 22:50 UTC, shumailxyz commented on core/src/commands/get/get-actions.ts
> +    if (opts["sort"] === "kind") {
Makes sense. Will add a secondary sort by name.

2023-06-01 12:35 UTC, Orzelius approved these changes
Love it!!

2023-06-01 14:01 UTC, shumailxyz commented on core/src/commands/get/get-builds.ts
> +    super("Build")
yeah, quite minimal 😄 Thanks for the review multiple times :)

2023-06-01 14:08 UTC, vvagaytsev commented on core/src/actions/helpers.ts
> +  return state
This variable can be removed, you can use immediate `return` statements in the `case` blocks and also skip the `break` operators.

2023-06-01 14:28 UTC, vvagaytsev commented on core/src/commands/get/get-actions-subcommand.ts
> +  protected kindLowercaseString: string
These fields could be `private` and `readonly`.

2023-06-01 14:32 UTC, vvagaytsev commented on core/src/commands/get/get-actions-subcommand.ts
> +          }
This makes this class non-abstract :) Because this makes the class aware of all its sub-classes.

I'd prefer to introduce an abstract method here and implement it in every sub-class.

2023-06-01 15:41 UTC, vvagaytsev requested changes
Thanks for implementing such a nice feature! 👍 
I've left a few comments, please check :)

2023-06-01 21:36 UTC, shumailxyz commented on core/src/commands/get/get-actions-subcommand.ts
> +          }
We could actually simplify it further like

```
getSuggestions: ({ configDump }) => {
  return Object.keys(configDump.actionConfigs[this.kind])
}
```

and i would prefer above instead of abstract method and implementing it in each subclass.

2023-06-01 21:54 UTC, shumailxyz commented on core/src/actions/helpers.ts
> +  return state
removed

2023-06-02 07:36 UTC, vvagaytsev commented on core/src/commands/get/get-actions-subcommand.ts
> +          }
Nice! Elegant solution :)

2023-06-02 07:36 UTC, vvagaytsev approved these changes
Thank you! 🚀

2023-06-02 09:35 UTC, merged