Shanky/ce-49-submit-prs-for-quickstart-buttons
garden-io/garden pull request #4556
Opened 2023-06-07 05:46 UTC by ShankyJS

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-06-07 09:13 UTC, eysi09 requested changes

2023-06-07 09:13 UTC, eysi09 commented on README.md
> +Start using Garden right away by using any of the following two options:
We need to fix the sections a bit. 

With these changes it's

- Installation (H2)
- Demo (H2)
- Interactive environments (H3)
- Local Installation (H3)

So it's like interactive environments and local installation are nested under demo. Also "Usage" is missing. 

How about we instead do

-  Installation (H2)
- Demo (H2)
- Interactive Environments (H2)
- Usage (H2)

The goal with the usage section is first and foremost to show how it works at a glance, more so then be a follow up to the installation.

2023-06-07 09:13 UTC, eysi09 commented on README.md
> +- You can also install the prerequisites in your computer and then follow the steps below. 💻
This kind of makes it sound like there's a choice between using interactive environments or installing Garden locally. 

However, interactive environments are for testing things out with an example project whereas you always need to install Garden locally to actually use it on your own projects. 

So let's make sure we don't conflate the two. I thing keeping the sections I suggested above more or less addresses that.

2023-06-07 09:13 UTC, eysi09 commented on README.md
> +If you find any bugs 🐛 or have suggestions to improve our labs please don't hesitate in reaching out through an issue towards this [repository](https://github.com/garden-io/garden-interactive-environ
Change:

"hesitate in reaching out..."

to:

"hesitate to reach out by creating an [issue here](https://github.com/garden-io/garden-interactive-environments/issues) or by asking in [our Discord Community](https://go.garden.io/discord) 🌸

2023-06-08 05:12 UTC, ShankyJS commented on README.md
> +Start using Garden right away by using any of the following two options:
I added this sections structure in latest commit, closing this comment for a new review.

2023-06-08 05:12 UTC, ShankyJS commented on README.md
> +- You can also install the prerequisites in your computer and then follow the steps below. 💻
Re-worked this.

2023-06-08 05:18 UTC, ShankyJS commented on docs/basics/quickstart.md
> +Garden is an all-in-one DevOps platform that enables you to build, test, deploy your applications and infrastructure in a single, unified workflow.
I suggest moving the text "In this quickstart..." to a brand new section called `Usage` the same way the main README is structured.

If this doesn't work, please leave a comment, and I'll take it back. @eysi09 @worldofgeese

2023-06-08 05:19 UTC, ShankyJS commented on docs/basics/quickstart.md
> +## Usage
This would be the new "Usage" section because it's an H2 every of its children is an H3.

cc @eysi09 / @worldofgeese

2023-06-08 05:20 UTC, ShankyJS commented on README.md
> +> Make sure you have Garden installed and Kubernetes running locally (e.g. with Minikube or Docker for Desktop) before deploying the project.
I brought this line here as we don't specify this in the document, which adds good value to it IMO.

cc @eysi09

2023-06-08 05:21 UTC, ShankyJS commented on README.md
> +If you want to try Garden in an interactive cloud-based environment with a playground-like experience, use our new Killercoda and CloudShell environments ✨.
Brand new text optimized with Grammarly and ChatGPT for potential grammar issues; I hope it's ok and less wordy than the first try. 

cc @worldofgeese / @eysi09

2023-06-08 05:22 UTC, ShankyJS commented on README.md
> +If you find any bugs 🐛 or have suggestions to improve our labs please don't hesitate to reach out by creating an [issue here](https://github.com/garden-io/garden-interactive-environments) or by askin
Apply change requested by @eysi09!

2023-06-08 07:24 UTC, worldofgeese approved these changes

2023-06-08 07:24 UTC, worldofgeese commented on README.md
> +If you want to try Garden in an interactive cloud-based environment with a playground-like experience, use our new Killercoda and CloudShell environments ✨.
```suggestion
Preview Garden with our new interactive and install-free cloud-based playgrounds ✨.
```

2023-06-08 07:24 UTC, worldofgeese commented on docs/basics/quickstart.md
> +If you want to try Garden in an interactive cloud-based environment with a playground-like experience, use our new Killercoda and CloudShell environments ✨.
```suggestion
Preview Garden with our new interactive and install-free cloud-based playgrounds ✨.
```

2023-06-08 07:24 UTC, worldofgeese commented on README.md
> +Click on either of the two buttons below ⬇️.
```suggestion
Click a button to start your Killercoda or Google Cloud Shell environment 👇🏼.
```

2023-06-08 07:24 UTC, worldofgeese commented on docs/basics/quickstart.md
> +Click on either of the two buttons below ⬇️.
```suggestion
Click a button to start your Killercoda or Google Cloud Shell environment 👇🏼.
```

2023-06-08 07:36 UTC, worldofgeese requested changes
Just some small changes!

2023-06-08 07:47 UTC, eysi09 reviewed
Great work @ShankyJS and thanks for addressing the comments! 

This is a massive improvement ✨

I had one other small comment + what Tao suggested.

2023-06-08 07:47 UTC, eysi09 commented on docs/basics/quickstart.md
> +## Usage
Makes sense. But I think "Usage" doesn't really apply here.

How about just calling the section "Quickstart"? Or something along those lines.

2023-06-08 11:33 UTC, ShankyJS commented on docs/basics/quickstart.md
> +## Usage
changed!

2023-06-08 11:34 UTC, ShankyJS commented
@worldofgeese / @eysi09 applied all suggestions and changes, this is ready for a final review + merge! 👍🏻

2023-06-08 11:45 UTC, worldofgeese approved these changes

2023-06-08 18:55 UTC, eysi09 approved these changes

2023-06-08 18:55 UTC, merged