improvement(server): output more debug info
garden-io/garden pull request #4613
Opened 2023-06-13 12:25 UTC by edvald

Small improvement to improve working with Desktop.

2023-06-14 11:57 UTC, eysi09 requested changes
LGTM but might be useful to add a comment explaining the different log props and levels (`commandLogLevel` / `terminalLevel` / `level`).

2023-06-14 11:57 UTC, eysi09 commented on core/src/server/commands.ts
> +      new ServerLogger({
Should we add a comment here or above about the reasoning behind these different levels?

2023-08-24 23:49 UTC, edvald commented on core/src/server/commands.ts
> +      new ServerLogger({
I've simplified this after other changes done in the meantime. Pretty trivial now.

2023-08-26 01:26 UTC, eysi09 approved these changes

2023-08-29 03:56 UTC, merged