fix(server): inconsistent key set for Garden instances for concurrent requests
garden-io/garden pull request #4621
Opened 2023-06-13 17:31 UTC by edvald

cc @eysi09, can you take a look to see if this partially addresses #4597?

2023-06-14 12:18 UTC, eysi09 commented
I'm still seeing the same behaviour. 

[Here](https://github.com/garden-io/garden/blob/master/core/src/server/instance-manager.ts#L131) the key `env=dev` (for my example project). 

There will never be an instance with this key because when we add it to the map it'll have the key `env=dev-my-namespace`. 

So we always hit the codepath that creates a new Garden instance. That code path also unsubscribes the listener from the previous instance so we drop any further events from that instance. 

Basically what's described here: #4597.

Note also that `defaultNs` resolves to `${var.dev-env-name}` on my project (see my comment on the code).

2023-06-14 12:19 UTC, eysi09 requested changes

2023-06-14 12:19 UTC, eysi09 commented on core/src/garden.ts
> +    const defaultNs = this.getEnvironmentConfig().defaultNamespace || defaultNamespace
The template string isn't resolved here so I get `defaultNs=${var.dev-env-name}`.

The returned namespace is still `vote-demo-eysi` because of the line below:

``` 
    if (this.namespace !== defaultNs) {
      namespace = this.namespace
    }
```

2023-06-14 12:34 UTC, eysi09 commented
...what I don't really understand is why we first read the key from the instance manager params and then again in the `set` from the Garden instance. 

I would've assumed we'd just re-use the original key we get from params and use that in the `set` method.

2023-06-14 12:58 UTC, eysi09 commented
Some further findings:

When we create the initial DummyGarden for the parent dev command the `gardenKey` we [set on the log context](https://github.com/garden-io/garden/blob/master/core/src/garden.ts#L1855) has a namespace (default) so it becomes `env=default-default`. 

I think that conflicts with this code comment: `// Setting this after resolving the gardenKey above because we don't want the default namespace resolved there`

When we then create a "proper" Garden instance via the instance manager the namespace is missing so the log context gets `gardenKey=env=default`.

2023-06-19 00:13 UTC, edvald commented
Closed in favor of #4649

2023-06-19 00:13 UTC, closed without merging