fix(cloud): emit ns statuses for in-cluster builds
garden-io/garden pull request #4628
Opened 2023-06-14 08:41 UTC by thsig

**What this PR does / why we need it**:

We now emit a `namespaceStatus` event whenever one of our internal helpers for checking the status of a Kubernetes namespace is called. This is done whenever we e.g. perform a Deploy, Test or Run in that namespace, or when we perform an in-cluster Build in that namespace (e.g. via BuildKit or Kaniko).

Here, we also remove namespace statuses from the relevant result types (e.g. `ServiceStatus`, `RunStatus` and `EnvironmentStatus` and the associated schemas). These added unwanted noise to the interfaces and schemas.

Instead, we emit the `namespaceStatus` events on the plugin event broker (`ctx.events`) and re-emit them to `garden.events` in the base router.

**Which issue(s) this PR fixes**:

Previously, automatic environment cleanup would not get triggered for namespaces where only Builds had taken place (i.e. no Deploys, Runs or Tests). This fixes that.

**Special notes for your reviewer**:

I wrote a test case verifying that `namespaceStatus` events get emitted during BuildKit builds, but it kept hanging due to something Mutagen-related. I've verified manually that the events do get emitted (and so long as we're using the standard helpers for getting the Kubernetes namespace status in the BuildKit and Kaniko handlers, we should be good).

We should investigate this further, but I didn't want to get bogged down in debugging a test case that seemed like it might also introduce flakiness into our integ test suite.

2023-06-14 09:04 UTC, vvagaytsev commented
@thsig this fixes #4609, right?

2023-06-14 09:34 UTC, thsig commented
It does, yeah—forgot to mention that in the description.

2023-06-14 16:18 UTC, eysi09 requested changes
Had one small comment. 

Otherwise I feel like we need to re-think this in general but don't want to block the fix. 

But shouldn't this be handled in a consistent manner at the action or router level with events that include plugin specific information so that it extends beyond just K8s?

AEC would then be responsible for applying the clean up for different plugins (or using the CLI to do it).

2023-06-14 16:18 UTC, eysi09 commented on core/src/plugins/kubernetes/init.ts
> +  await getAppNamespaceStatus(k8sCtx, log, k8sCtx.provider)
Wouldn't it be better to just emit the status directly here? 

We could easily refactor or remove this function and that would either break this or produce unwanted side effects.

2023-06-14 17:23 UTC, thsig commented on core/src/plugins/kubernetes/init.ts
> +  await getAppNamespaceStatus(k8sCtx, log, k8sCtx.provider)
Yeah, that's a good point. Will make that change.

2023-06-14 17:30 UTC, thsig commented
> But shouldn't this be handled in a consistent manner at the action or router level ...

In this PR, we're catching `namespaceStatus` events from the plugin event broker in one place in the base router. We could do it for each individual router method, but that seems unnecessarily repetitive.

> ... with events that include plugin specific information so that it extends beyond just K8s?

That totally makes sense—we can always change/extend the `namespaceStatus` events to have a `detail` field, for example.

In general, I understand your reservations about this PR. That said, my thinking was that the `namespaceStatuses` field on action results felt bolted-on and not a good pattern, and that this was another "letting Cloud know about what's going on" event (like the old `log` events). So I felt it was less hacky this way.

Also, both before and after this PR, we're relying on integ tests to ensure that we don't accidentally stop sending the events when certain plugin handlers are called. There's currently no framework-level guarantee that any namespace statuses were generated by the plugin handler.

I do think that going forward, it would be nice to have a plugin-level mechanism to register event types for the router to listen for.

2023-06-14 17:56 UTC, eysi09 commented
Oh I don’t have reservations about the PR per se. Rather this flow in general which needs to be revisited separately imo so we can extend AEC to more plugins.

2023-06-14 17:56 UTC, eysi09 approved these changes

2023-06-15 06:49 UTC, vvagaytsev commented on core/src/plugins/kubernetes/init.ts
> +  ctx.events.emit("namespaceStatus", nsStatus)
It looks like the function `getAppNamesStatus` just delegates to `getNamespaceStatus` without any extra logic. The latter, in turn, also sends the same event. Wouldn't we have duplicate events emitted?

2023-06-15 06:52 UTC, vvagaytsev commented on core/src/router/run.ts
>          // TODO: get this out of the core framework and shift it to the provider
Dangling TODO comment here :)

2023-06-15 06:53 UTC, vvagaytsev commented on core/src/router/test.ts
>          // TODO: get this out of the core framework and shift it to the provider
[Same](https://github.com/garden-io/garden/pull/4628/files#r1230520095) here

2023-06-15 09:36 UTC, thsig commented
Should be good to go now, @vvagaytsev.

2023-06-15 09:51 UTC, vvagaytsev approved these changes
Thank you! I've left one more [comment here](https://github.com/garden-io/garden/pull/4628/files#r1230753446). If the duplicate events make no harm, then all is good!

2023-06-15 11:03 UTC, merged