fix: use included files only for build in tree hash calculation
garden-io/garden pull request #4632
Opened 2023-06-14 12:49 UTC by shumailxyz

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-06-14 16:13 UTC, stefreak commented on core/src/vcs/vcs.ts
> +        }
I'm not 100% sure how to review this because I am very unfamiliar with how this is supposed to work. 
But I feel like this needs a regression test. The minimal example I provided in https://github.com/garden-io/garden/issues/4618 could be used for that

2023-06-14 16:15 UTC, stefreak commented on core/src/vcs/vcs.ts
> +        }
One problem with this approach might be that for Deploy actions without `build`, e.g. `kubernetes` type deploys, we do need to take the included files into account as it may contain changed manifests. 
For the `kubernetes` deploy kind we only should include the files that are specified in the spec.

2023-06-14 16:26 UTC, shumailxyz commented on core/src/vcs/vcs.ts
> +        }
I used the example you provided as reference and wrote a few other garden files to test it.

Regarding your point about kubernetes deploys, those will be included as this the condition already considers explicitly included files into account.

2023-06-15 07:37 UTC, vvagaytsev submitted a review, later dismissed
Lgtm! 👍

2023-06-15 07:43 UTC, Orzelius commented on core/src/vcs/vcs.ts
> +        }
I agree with Steffen, this should be tested. You can add a test to the [already existing suite](https://github.com/garden-io/garden/blob/main/core/test/unit/src/vcs/vcs.ts#L97) for this.

2023-06-15 08:09 UTC, stefreak commented on core/src/vcs/vcs.ts
> +        }
> Regarding your point about kubernetes deploys, those will be included as this the condition already considers explicitly included files into account.
Sounds reasonable– I don't know how this works, but maybe add a test case for a kubernetes or helm deploy that doesn't explicitly set `include`

2023-06-16 10:31 UTC, Orzelius commented on core/test/unit/src/vcs/vcs.ts
> +    const convertObjToArgs = (args: {
I was thinking a change in the call signature of the original `getTreeVersion` function itself. I think it's okay to have plain params if there's not many of them but at soon as they grow long or there's a bool involved I prefer a [destructured object](https://mariusschulz.com/blog/typing-destructured-object-parameters-in-typescript#typing-immediately-destructured-parameters)

<img width="440" alt="image" src="https://github.com/garden-io/garden/assets/33936483/e72ad818-dc40-4974-92fa-adda40514a47">

2023-06-16 10:34 UTC, Orzelius commented on core/test/unit/src/vcs/vcs.ts
> +    const convertObjToArgs = (args: {
@shumailxyz please don't rewrite git history in the review process, it tends to be tricky to see what has changed. Utilize a fixup commit instead. You can squash the fixups into the original commits before the merge if you want to rebase merge or you can do a squash merge.

2023-06-16 11:09 UTC, shumailxyz commented on core/test/unit/src/vcs/vcs.ts
> +    const convertObjToArgs = (args: {
I did start with refactoring the call signature of original function but then switched to adding helper for tests as it was being used at some other places too. I do think that 4 args are not that many though however will still update it considering the bool.

2023-06-16 14:46 UTC, Orzelius approved these changes
well done! figuring out the issue origin must have taught a bit about garden's internal structures

2023-06-18 00:40 UTC, edvald commented on core/src/cli/cli.ts
> +    log.verbose(`garden version: ${getPackageVersion()}`)
This seems a little odd to me to print on every verbose execution. I'd either make this a debug level or reconsider what exactly is printed and where.

2023-06-18 00:59 UTC, edvald requested changes
So, I don't think this is the correct solution. Happy to help out with this btw but wanted to at least flag before this is merged.

I can see this create an issue with e.g. an `exec` `Test` action where the version should be based on files related to the action. That will now _only_ work if users explicitly set the `include` field. So, many existing setups will break with this PR as-is, since users are not required to do that. Many similar scenarios would likely have the same issue.

When `build` is specified on Deploy/Run/Test actions, it could make sense to set the `include` field to `[]` unless either of `include` or `exclude` is explicitly set on the config already. This should be checked _after_ the `configure` plugin handler is called, since those handlers often infer or override include/excludes based on the action spec. I in fact thought this was already the case, perhaps it was just discussed at some point and not implemented. At least I can't find it in the action resolution code.

Lastly, I don't think it makes sense to first scan for the files contained in the action and then to conditionally detach the `contentHash` from the file list. In my view, the list of files should always deterministically map to a `contentHash`, and it makes more sense to affect the `include/exclude`. It's more consistent and also avoids unnecessary I/O.

2023-06-18 01:04 UTC, edvald commented
That all said, thank you for diving into this @shumailxyz! You're pretty deep in the machine there, amongst the dragons :) And not at all far from the right approach either, this is just one of the more delicate parts of the codebase and quite a bit of nuance to deal with.

2023-06-19 10:02 UTC, shumailxyz commented
@edvald Thank you for the feedback. That's a very valid  point and I agree that affecting include/exclude is a better approach. Will update it.

2023-06-19 10:06 UTC, shumailxyz commented on core/src/cli/cli.ts
> +    log.verbose(`garden version: ${getPackageVersion()}`)
This is coming from #4590 and I think it makes sense to print garden version at the start of the execution. There's a point to move it to debug level however I am more inclined towards keeping it at verbose level so if someone runs garden with `-l3` and copies log, the garden version is also copied.

2023-06-19 23:09 UTC, edvald approved these changes

2023-06-20 09:33 UTC, merged