feat(template): allow `this.name` and `this.mode` in action config
garden-io/garden pull request #4646
Opened 2023-06-15 14:19 UTC by vvagaytsev

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4616

**Special notes for your reviewer**:
Still WIP, I need ton add some unit tests

2023-06-18 01:10 UTC, edvald requested changes
Had one comment, but otherwise looks solid, good work 👍

2023-06-18 01:10 UTC, edvald commented on plugins/pulumi/commands.ts
> +  const templateContext = new TemplatableConfigContext(garden, action.getConfig())
Hmm, I think we should keep ActionConfigContext here. The mode and name should both be available at this point.

2023-06-19 07:25 UTC, vvagaytsev commented on plugins/pulumi/commands.ts
> +  const templateContext = new TemplatableConfigContext(garden, action.getConfig())
Thanks! Fixed that in https://github.com/garden-io/garden/pull/4646/commits/d62d10f05ec7f3c9c39d81878fc4c4b41a1b11d2

2023-06-19 07:27 UTC, edvald approved these changes

2023-06-19 07:35 UTC, merged