add homepage Garden recipes
garden-io/garden pull request #4693
Opened 2023-06-22 08:01 UTC by ShankyJS

2023-06-22 08:37 UTC, 10ko commented
Hey @ShankyJS, this is a great start and I like the structure, but I'd wait to merge this until we have the first recipe, since it goes live immediately once it's on `main`. 👍

2023-06-22 08:39 UTC, ShankyJS commented
> Hey @ShankyJS, this is a great start and I like the structure, but I'd wait to merge this until we have the first recipe, since it goes live immediately once it's on `main`. 👍

Hey @10ko yes! I'm already working on the first recipe, just wanted to involve the right stakeholders earlier to see if the structure makes sense! 

Thanks a lot for the comments

2023-06-22 08:52 UTC, 10ko commented
Makes sense, thanks! I am 100% sure some of our users would love a GitLab (and GitHub) guide. Let me know if I can support with that. :)

2023-06-22 10:33 UTC, worldofgeese requested changes

2023-06-22 10:33 UTC, worldofgeese commented on docs/README.md
> +* [Garden Recipes](./tutorials/garden-recipes/README.md)
I would move Garden Recipes to a top-level item (no parent)t . WDYT @eysi09? My gut tells me Recipes is too ambiguous. I want it to offer value right away. Here Namespace puts them at the Feature level. It's not a one for one because we have many more sections.

![image](https://github.com/garden-io/garden/assets/59834693/a82f83a3-31b8-4700-94d2-a0eda8c324ef)

Devbox puts them under Examples

![image](https://github.com/garden-io/garden/assets/59834693/6d0d38ee-9a33-4dff-8da5-1044cf8124d5)

Maybe top-level naming doesn't matter and we could offer more SEO-friendly sub-sections like Namespace does with its "Faster GitHub Actions".

I'm also ok on waiting on a decision if it means getting a Go example merged earlier.

2023-06-22 10:33 UTC, worldofgeese commented on docs/tutorials/garden-recipes/README.md
> +Welcome to Garden Recipes🍳!
```suggestion
```

2023-06-22 10:33 UTC, worldofgeese commented on docs/tutorials/garden-recipes/README.md
> +Welcome to Garden Recipes🍳!
I would remove this as it is just repeating the section title.

2023-06-22 10:33 UTC, worldofgeese commented on docs/tutorials/garden-recipes/README.md
> +Following our Garden Recipes, you'll learn how to streamline your development process, improve efficiency, and quickly build robust applications ✨. Whether working on personal projects or collaborati
```suggestion
Following our Garden Recipes, you'll learn how to streamline your development process, improve efficiency, and quickly build robust applications ✨.
```

I'm a fan of going to value as quickly as possible.

2023-06-22 10:33 UTC, worldofgeese commented on docs/tutorials/garden-recipes/README.md
> +This section provides examples and guides for integrating Garden with popular development tools and platforms🤖.
```suggestion
This section provides examples and guides for integrating Garden with popular development tools and platforms 🤖.
```

Added space between word and emoji.

2023-06-22 10:33 UTC, worldofgeese commented on docs/tutorials/garden-recipes/README.md
> +## Tooling
Should this section instead be called something like Integrations? @eysi09

2023-06-22 10:33 UTC, worldofgeese commented on docs/tutorials/garden-recipes/README.md
> +We value contributions from our community to enhance the Garden Recipes collection, we encourage you to get involved by providing feedback, feature requests, and bug reports.
```suggestion
```

Next two paragraphs are a bit verbose. I'd remove in favor of getting to how they contribute as you do with the third paragraph.

2023-06-22 10:33 UTC, worldofgeese commented on docs/tutorials/garden-recipes/README.md
> +Your input is crucial in shaping the future of Garden Recipes and ensuring its relevance and usefulness to the community.
```suggestion
```

See previous comment.

2023-06-22 10:33 UTC, worldofgeese commented on docs/tutorials/garden-recipes/README.md
> +If you encounter any issues or bugs in the recipes, please report them in our main repository. We can create a rich and valuable resource for the Garden community.
```suggestion
If you encounter any issues or bugs in the recipes, please report them in our main repository. Or [join our Discord](https://go.garden.io/discord) to talk to our devs or get help.
```

2023-06-22 10:33 UTC, worldofgeese commented on docs/tutorials/garden-recipes/languages/README.md
> +Each recipe follows a consistent structure, making it easy to integrate Garden into your favorite language.
Let's tell the developer exactly what they're going to get: 

> our recipes offer clear explanations and code samples.

How about something like, "our recipes offer language-specific, opinionated "Happy Paths". In just 5 minutes you'll slash your build and run test times and enjoy rebuild-free container development with Garden's Code Synchronization."

This tells the developer
- time they can be expected to use from their busy schedule
- they don't need to know a lot about Garden to get started, they just need to follow directions
- in 5 minutes they'll gain coding superpowers

I want to directly quote my [favorite new resource for technical writing](https://diataxis.fr/tutorials-how-to/) because I think it captures what I desire from this. Emphasis my own:

> Diátaxis insists that **[what matters in documentation is the needs of the user](https://diataxis.fr/needs/#needs)**, and it’s by paying attention to this that we can correctly distinguish between tutorials and how-to guides.

> Sometimes the user is at study, and sometimes the user is at work. Documentation has to serve both those needs.

> A tutorial serves the needs of the user who is at study. Its obligation is to provide a successful learning experience. **A how-to guide serves the needs of the user who is at work. Its obligation is to help the user accomplish a task.** These are completely different needs and obligations, and they are why the distinction between tutorials and how-guides matters: tutorials are learning-oriented, and **how-to guides are task-oriented**.

2023-06-23 01:17 UTC, ShankyJS commented on docs/tutorials/garden-recipes/languages/README.md
> +Each recipe follows a consistent structure, making it easy to integrate Garden into your favorite language.
This is fantastic feedback, @worldofgeese. Thank you so much! I applied this change, but more importantly, got the message you where trying to send

2023-06-23 01:34 UTC, ShankyJS commented on docs/README.md
> +* [Garden Recipes](./tutorials/garden-recipes/README.md)
At this moment, we have the following:

````md
H1 Tutorials 🌼
   H2 Your First Project
   H2 Garden Recipes
     H3 Languages
     H3 Tooling/Integration
   H2 Migrating your configuration for Bonsai
````

I like calling them `Garden Recipes` as it's an easy way to promote rather than creating empty single-handed documents without too much context; if we provide a good structure to our users, it will be easier for them to find our content.

I agree with moving it out to a section without a parent, as it will be even easier to find, and I'll move the section right under `Basics.`

Let me know what do you guys think @10ko / @eysi09 / @worldofgeese

2023-06-23 05:54 UTC, ShankyJS commented
@worldofgeese I've added the code and Garden configuration for a simple Go API, 

I used `helmet` to provide more usability with the Helm Deploy action instead of the simple `container.`

I'm unsure if it's worth it, as it adds more complexity to the configuration than a `container` deploy action.

You can find the code [here](https://github.com/garden-io/garden/tree/5296926e31ada2565fb0445fe9b1e72b969d9203/examples/recipes/languages/go)

Working on the document now. 

cc @10ko

2023-06-23 08:29 UTC, worldofgeese commented
> @worldofgeese I've added the code and Garden configuration for a simple Go API,
> 
> I used `helmet` to provide more usability with the Helm Deploy action instead of the simple `container.`
> 
> I'm unsure if it's worth it, as it adds more complexity to the configuration than a `container` deploy action.
> 
> You can find the code [here](https://github.com/garden-io/garden/tree/5296926e31ada2565fb0445fe9b1e72b969d9203/examples/recipes/languages/go)
> 
> Working on the document now.
> 
> cc @10ko

I do like the idea of standardizing on Helm charts as the "Happy Path" since one of the frequent complaints and issues we receive is that the container module, on its own, can't do what users want it to do. The chart and path name, `garden-helmet` is not clear. I would rename to `my-chart` or similar. Using standardized Helm Library Charts like The Helmet allows configuration to be just a matter of key values. I'm open to discussion on this!

Have you tested this, @ShankyJS?

2023-06-23 08:34 UTC, 10ko commented on docs/tutorials/garden-recipes/README.md
> +## Tooling
I would avoid to call it integrations, since could be confused with Cloud Integrations/connections. Maybe we can even be more specific and call it CI/CD tools? Or something along those lines.

2023-06-23 11:26 UTC, eysi09 commented on docs/README.md
> +* [Garden Recipes](./tutorials/garden-recipes/README.md)
Yeah, plus one on making it top level. Also open to better names. I always relate recipes to Ansible / Puppet / Chef kind of tooling.

Even something gardening related? 😬

It's a policy to not go all in on gardening puns and themes, but it can be nice if done tactfully.

2023-06-23 12:50 UTC, ShankyJS commented
Hey @worldofgeese yes, I already tested and deployed this locally and it works just fine. 

The only caveat is that we need a Helm chart to use as "application" chart and then consume the library of "helmet" which will be a couple of extra steps to explain

But it works like a charm! 

Another option would be to host our own base chart, 

Why? Because we could have the total ownership of this Helm Chart, do integrations with 3rd parties as we wish (Datadog for example). 🎉

2023-06-23 13:55 UTC, ShankyJS commented on docs/README.md
> +* [Garden Recipes](./tutorials/garden-recipes/README.md)
What about Garden Seeds? 🌱🤞

2023-06-27 11:02 UTC, ShankyJS commented
Hey, @10ko / @worldofgeese, this is ready to review; here is a little video with the proposed new structure.

https://github.com/garden-io/garden/assets/17713708/cecbf7de-c50c-4488-8fba-e29f1281ad91

2023-06-27 11:06 UTC, ShankyJS commented on docs/garden-recipes/languages/go-recipe.md
> +[Example Repo](https://github.com/garden-io/garden/tree/main/examples/recipes/languages/go)
This is a circular reference; it won't resolve after this is merged. The solution might be to separate PRs 1 for code and 1 for docs. 

This is making that the check-docs check fails in CircleCI @worldofgeese / @10ko

2023-06-27 11:07 UTC, ShankyJS commented on docs/garden-recipes/languages/go-recipe.md
> +To compare your progress, check our [example folder](https://github.com/garden-io/garden/tree/main/examples/recipes/languages/go) for this recipe.
Same as above.

2023-06-27 11:07 UTC, ShankyJS commented on docs/README.md
> +## undefined Misc
I don't know why it decided to be undefined; I didn't change this file at all 🍭.

@worldofgeese

2023-06-27 11:09 UTC, ShankyJS commented on examples/recipes/languages/go/api/api.garden.yml
> +  sync:
@10ko / @worldofgeese, do you guys mind testing to deploy this configuration with the `--sync` option, in Bonsai this fails on me with this error:

````bash
⚠ deploy.api           → Synchronization monitor exited with code 1.
⚠ deploy.api           → Could not connect to sync daemon, retrying (attempt 1/10)..
````

2023-06-27 11:10 UTC, ShankyJS commented on examples/recipes/languages/go/api/api.garden.yml
> +  sync:
Regular deploy works as expected; also when I had this as a `container` module, it used to work as expected, so it might be a layer 8 problem with the config too...

2023-06-27 12:11 UTC, worldofgeese requested changes
Is there any way we can provide the reader of these tutorials with everything they need except their Go code? 

Templating tools like:
- [`algokit init`](https://github.com/algorandfoundation/algokit-cli/blob/main/docs/features/init.md) <- only for Algorand smart contract developers but useful as a reference
- [cookiecutter](https://github.com/cookiecutter/cookiecutter)
- [Copier](https://github.com/copier-org/copier)

offer a way to generate scaffolds the user just needs to answer a few questions to personalize.

I think we can deliver language templates that are ready for developers to plug their own code into and run `garden dev`. That's my dream.

```mermaid
flowchart TD
    A[Garden is gonna give you superpowers] -->|Use template tool| B(Bring your own Go code then run `garden dev`)
```

If users want to then customize the generated templating, or add additional tests, or add an environment variable, we can send them to that section. But let them wield the power *first*.

2023-06-27 13:56 UTC, ShankyJS commented
> Is there any way we can provide the reader of these tutorials with everything they need except their Go code?
> 
> Templating tools like:
> 
> * [`algokit init`](https://github.com/algorandfoundation/algokit-cli/blob/main/docs/features/init.md) <- only for Algorand smart contract developers but useful as a reference
> * [cookiecutter](https://github.com/cookiecutter/cookiecutter)
> * [Copier](https://github.com/copier-org/copier)
> 
> offer a way to generate scaffolds the user just needs to answer a few questions to personalize.
> 
> I think we can deliver language templates that are ready for developers to plug their own code into and run `garden dev`. That's my dream.
> 
> ```mermaid
> flowchart TD
>     A[Garden is gonna give you superpowers] -->|Use template tool| B(Bring your own Go code then run `garden dev`)
> ```
> If users want to then customize the generated templating by adding additional tests, or add an environment variable, we can send them to that section. But let them wield the power _first_.

@worldofgeese / @10ko I'm going to be working on trying to use cookie-cutter, copier, or any other mechanism that could provide our users with these template files in a single command or less.

2023-06-27 15:56 UTC, worldofgeese commented
> @worldofgeese / @10ko I'm going to be working on trying to use cookie-cutter, copier, or any other mechanism that could provide our users with these template files in a single command or less.

@10ko I think this could be a great PoC for the `garden bootstrap go` command we discussed at our sync, WDYT? We'd use a third party OSS tool for the templating, *for now*, then present it at a Show & Tell and write a pitch for adopting as a Garden-native feature?

2023-07-06 09:21 UTC, 10ko commented
Is this ready to go?

2023-07-10 10:15 UTC, ShankyJS commented
> Is this ready to go?

Yes, it is!

2023-07-10 12:41 UTC, worldofgeese requested changes
Great job, @ShankyJS! I've added a number of comments, suggestions and a few grammar fixes to get this to release quality. I'm very excited for our first Garden Seed 🌱

2023-07-10 12:41 UTC, worldofgeese commented on docs/garden-seeds/languages/README.md
> +- [Go seed](./go-seed.md)
Instead of, “Explore the Languages Seeds section and experience the power of Garden in your projects,”: “From the sidebar, pick a language to quickly scaffold your Garden project and experience the power of Code Synchronization, tests, ...” <- I would also link Code Synchronizations, tests, and any other features they'll experience.

And I would change `Go seeds` to something like
```
[Languages]
  [Go]
```

2023-07-10 12:41 UTC, worldofgeese commented on docs/garden-seeds/languages/go-seed.md
> +If you encounter any issues or bugs 🐛 in this seed, don't hesitate to contact our [Discord Community](https://go.garden.io/discord) 🌸.
```suggestion
If you encounter any issues or bugs 🐛 in this seed, don't hesitate to join our [Discord community](https://go.garden.io/discord) 🌸 for access to Garden's dedicated Community Engineers and our AI chatbot 🤖  trained on our docs.
```

2023-07-10 12:41 UTC, worldofgeese commented on docs/garden-seeds/languages/go-seed.md
> +Go projects and compiled languages can run seamlessly on Garden, using our SDLC inner loop with local/remote Kubernetes environments 🍃.
When using acronyms always define the acronym in full with e.g. (SDLC) appended but I would also change the sentence to convey greater meaning since it reads a bit like a string of buzzwords.

```suggestion
Go projects and compiled languages can run seamlessly on Garden, with fast image rebuilds as you type, cached tests and more deployed to any number of local and remote Kubernetes environments 🍃.
```

2023-07-10 12:41 UTC, worldofgeese commented on docs/garden-seeds/languages/go-seed.md
> +This seed deploys a simple Go API using Helm and Garden to template our application and seamlessly deploy it to a local Kubernetes cluster ✅.
Should we also let them know how easy it is for them to drop-in their own Go project?

2023-07-10 12:41 UTC, worldofgeese commented on docs/garden-seeds/languages/go-seed.md
> +[Seed Repo](https://github.com/garden-io/go-seed)
```suggestion
```

I don't think we need this since the repo is repeated down-page.

2023-07-10 12:41 UTC, worldofgeese commented on docs/garden-seeds/languages/go-seed.md
> +This demo uses Garden with Helm to deploy to our Kubernetes cluster; to do so, we will need to create our Helm Chart first.
```suggestion
This demo scaffolds a Helm chart we'll deploy to our Kubernetes cluster.
```

Avoid communicating complexity. We're doing all of this for them.

2023-07-10 12:41 UTC, worldofgeese commented on docs/garden-seeds/languages/go-seed.md
> +2. Install Python3; we need this to run/install Cookiecutter 🍪; most distros/OS already include python3, but if you don't, you can install it by following this [guide](https://docs.python-guide.org/s
```suggestion
2. Ensure Python is available on your system and version 3.7 or higher by running `python --version`. MacOS and most Linux distributions will have Python already installed. Follow the official Python installation [guide](https://docs.python-guide.org/starting/installation/#installation-guides) if not. Python is required to scaffold the language seed.
```

Here I've adopted “ensure” over “install” so it's clear this step is likely not required. I've also given a small hint that both confirms Python is installed on their system and also checks their Python version is the minimum required for Cookiecutter.

2023-07-10 12:41 UTC, worldofgeese commented on docs/garden-seeds/languages/go-seed.md
> +cookiecutter https://github.com/garden-io/go-seed.git
Why is this command repeated?

2023-07-10 12:41 UTC, worldofgeese commented on docs/garden-seeds/languages/go-seed.md
> +If you would like to understand how the configuration is working behind the scenes checkout our [go-seed repository](https://github.com/garden-io/go-seed/blob/main/README.md)
```suggestion
If you would like to dive into the code used for this Garden Seed, check out our [go-seed repository](https://github.com/garden-io/go-seed/blob/main/README.md)
```

2023-07-10 12:41 UTC, worldofgeese commented on docs/garden-seeds/languages/go-seed.md
> +If you want to get your test results with greater detail, use `get test-results unit.`
```suggestion
If you want to get your test results with greater detail, use `get test-results unit.`

To exit the REPL at any time, type `exit`.
```

2023-07-10 12:41 UTC, worldofgeese commented on docs/garden-seeds/languages/go-seed.md
> +Now you can deploy your new API and be proud of your hard work, because this project has `sync` enabled, you can simply modify your `main.go` and watch how your Go code gets rebuilt each time.
```suggestion
Because this project has Code Synchronization already configured, you can simply modify your `main.go` and observe changes live on the synced code path.
```

Maybe we should add something like, “Want to modify the path or use your own Go app? Simply...” We should communicate how and where users can modify the configuration for themselves.

2023-07-10 12:41 UTC, worldofgeese commented on docs/garden-seeds/languages/go-seed.md
> +- If you find any bugs 🐛 or have suggestions to improve our seeds, please don't hesitate to reach out by creating an [issue here](https://github.com/garden-io/garden/issues/new?assignees=&labels=&pro
```suggestion
- If you find any bugs 🐛 or have suggestions to improve our seeds, please don't hesitate to reach out by creating an [issue here](https://github.com/garden-io/garden/issues/new?assignees=&labels=&projects=&template=BUG_REPORT.md&title=) or by asking in our [Discord community](https://go.garden.io/discord)🌸
```

2023-07-10 13:38 UTC, ShankyJS commented on docs/garden-seeds/languages/go-seed.md
> +cookiecutter https://github.com/garden-io/go-seed.git
There would be two sections one for Linux and one for MacOS, commands are the same though

2023-07-10 14:17 UTC, ShankyJS commented on docs/README.md
> +## undefined Misc
@worldofgeese, we are probably going to need some help from @10ko / @eysi09 on this one; this list gets automatically generated by the.`yarn generate-docs` command, and somehow it's killing the misc folder

2023-07-10 15:53 UTC, 10ko reviewed
Looks good, I only have some doubts on where we host the videos and screenshots.

2023-07-10 15:53 UTC, 10ko commented on docs/garden-seeds/about.md
> +In [Languages](./languages/README.md), you'll find various examples and guides tailored to specific coding languages. Whether you're a Pythonista, a Gopher, or working with other programming language
I hope we'll have a Python seed soon if we claim we got them covered. :P

2023-07-10 20:19 UTC, worldofgeese commented on docs/garden-seeds/languages/go.md
> +![Quick diagram with tooling](https://ce-content.s3.fr-par.scw.cloud/golang-garden-recipe.png)
It's Community Engineering's. We have accounts with Scaleway and Civo for all our mad science experiments 🧑‍🔬

2023-07-11 06:15 UTC, ShankyJS commented on docs/README.md
> +## undefined Misc
The emojis are automatically added by Gitbook, it's just that this section is getting undefined somehow

2023-07-11 15:15 UTC, 10ko approved these changes
LGTM

2023-07-12 14:08 UTC, worldofgeese approved these changes

2023-07-12 14:39 UTC, vvagaytsev commented
I've just rebased and force-pushed this. Let's wait for CI completion. And let's use **Squash & Merge** with commit header like `docs: add Garden Seeds main page and go-seed`

2023-07-12 14:59 UTC, vvagaytsev requested changes
The [check-docs](https://app.circleci.com/pipelines/github/garden-io/garden/18992/workflows/8e578139-a064-446c-8b33-7a14dc102857/jobs/344752) CI step fails because the link https://github.com/garden-io/go-seed/blob/main/README.md points to a non-public repository. @ShankyJS @worldofgeese do we plan to make it public?

2023-07-12 18:31 UTC, ShankyJS commented
> The [check-docs](https://app.circleci.com/pipelines/github/garden-io/garden/18992/workflows/8e578139-a064-446c-8b33-7a14dc102857/jobs/344752) CI step fails because the link https://github.com/garden-io/go-seed/blob/main/README.md points to a non-public repository. @ShankyJS @worldofgeese do we plan to make it public?

Hey @vvagaytsev thanks for the heads-up, I already made the repository public so the link should work now, any way to retrigger the test?

2023-07-13 07:45 UTC, vvagaytsev commented
Thanks, @ShankyJS! I've re-triggered the CI pipeline. Let's wait for its completion and merge.

2023-07-13 07:52 UTC, vvagaytsev approved these changes
CI looks good now, thanks! There is one test failures that is irrelevant. It also happens in another branches.

2023-07-13 07:54 UTC, merged