chore(analytics): improve error reporting structure
garden-io/garden pull request #4707
Opened 2023-06-25 21:44 UTC by mkhq

**What this PR does / why we need it**:

Garden errors are aggregated in several steps when executing a graph. This PR simplifies the error reporting in analytics by only including the `lastError`. This is the last error added to the list of errors in the results of a graph execution. The struct reported back in analytics has detailed data on three levels:

- `error`, which refers to the top-most error
- `wrapped`, the first wrapped error in the top-most error
- `leaf`, the first leaf found when recursively iterating through wrapped errors. This is the most specific error and should provide a good indication of the error cause.

In addition to the new structure, we also started on an error context struct which can contain specific fields that would help identify task-types or plugins that typically lead to a failed execution.

Additional care has been taken to avoid reporting back any sensitive data. E.g. we opt-out of including task names which could simplify analysis.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-06-30 08:34 UTC, vvagaytsev requested changes
There are some merge conflicts, let's rebase this.

2023-07-07 09:34 UTC, Orzelius commented on core/test/unit/src/analytics/analytics.ts
> +      expect(event).to.eql({
I think it'd be cleaner if we had only one of these snapshot tests and the other cases just validated only what's needed. That way I'd be dry-er and would decrease line count by a good bit.

2023-07-12 08:08 UTC, vvagaytsev commented on core/src/analytics/analytics.ts
> +    })
It looks like these 3 functions are re-created on every call of `resultErrorProperties`. Should we declare those outside the class?

2023-07-13 05:35 UTC, mkhq commented on core/src/analytics/analytics.ts
> +    })
Broke out into a separate helpers file to clean up this function/file a bit. It's only called once at the end of a command run.

2023-07-13 08:41 UTC, vvagaytsev approved these changes
LGTM, thanks! 👍

2023-07-13 09:15 UTC, merged