chore(test): fix remote source repo link
garden-io/garden pull request #4747
Opened 2023-07-04 15:22 UTC by vvagaytsev

Use main branch that contains the action-based configs and the updated Node vesrion.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-07-04 16:08 UTC, Orzelius requested changes

2023-07-04 16:08 UTC, Orzelius commented on examples/remote-sources/garden.yml
> +    repositoryUrl: https://github.com/garden-io/garden-example-remote-sources-web-services.git#main
This should have worked fine as the 0.13 branch exists and has action configs on the repo
https://github.com/garden-io/garden-example-remote-sources-web-services/tree/0.13

I'd like to have both a branch and a tag based links here as the logic for fetching is completely different and both should be tested

2023-07-05 07:52 UTC, vvagaytsev commented on examples/remote-sources/garden.yml
> +    repositoryUrl: https://github.com/garden-io/garden-example-remote-sources-web-services.git#main
It stopped working with `0.13` branch because it did have undefined versions for Python dependencies. So I updated the `main` branch in the target repo and switched the link to point to the `main` branch. Just to avoid maintaining one more branch in the example repo.

The previous version of this config also used 2 URLs with branches. Do we have different code paths to clone tags and branches? I haven't found any difference yet.

We have function [`parseGitUrl`](https://github.com/garden-io/garden/blob/main/core/src/vcs/git.ts#L51) that checks URL validity and returns URL and "hash" (a hash can be either sha1 commit hash or branch or tag).
If it's not a sha1 hash, we just clone the branch, see https://github.com/garden-io/garden/blob/main/core/src/vcs/git.ts#L537

So, it looks like we handle tag and branch URLs in the same way. Just tested it, and it works with both branches and tags. If it stops working at some point, it will be caused by a breaking change in Git.

We can still have one tag URL here. I'd like to keep this and https://github.com/garden-io/garden/blob/main/e2e/projects/remote-sources-modules/garden.yml aligned. So, I'll make a new tag on the latest revision of the `main` branch in https://github.com/garden-io/garden-example-remote-sources-db-services.git and will change the URL of `db-services` here.

2023-07-05 07:59 UTC, vvagaytsev commented on examples/remote-sources/garden.yml
> +    repositoryUrl: https://github.com/garden-io/garden-example-remote-sources-web-services.git#main
Changed the second link to point to a Git tag in https://github.com/garden-io/garden/pull/4747/commits/e56ee90d8cfceb760881b052a800008ec67bdf7c

2023-07-05 08:40 UTC, Orzelius commented on examples/remote-sources/garden.yml
> +    repositoryUrl: https://github.com/garden-io/garden-example-remote-sources-web-services.git#main
ahh yep, I mixed up the commit SHA and tag cloning logic, my bad. Do we test the SHA clone anywhere?

2023-07-05 09:31 UTC, vvagaytsev commented on examples/remote-sources/garden.yml
> +    repositoryUrl: https://github.com/garden-io/garden-example-remote-sources-web-services.git#main
Added SHA1 URLs in https://github.com/garden-io/garden/pull/4747/commits/f41daea7b1d8be8caa90f532245f68c17a8a72b0

2023-07-05 10:20 UTC, Orzelius approved these changes
thanks

2023-07-05 10:31 UTC, shumailxyz approved these changes
Awesome 💯  Thank you.

2023-07-05 10:40 UTC, merged