feat: otel collector integration
garden-io/garden pull request #4769
Opened 2023-07-07 12:46 UTC by TimBeyer

**What this PR does / why we need it**:
This PR enables us to locally deploy an [otel collector](https://github.com/open-telemetry/opentelemetry-collector) by configuring it as a provider.

The provider once configured finds an open port, creates a configuration file on the fly and then spawns the collector on the local machine. It then reconfigures the existing otel exporter to target the new collector, which then proceeds to export the data to the desired destination.

An example project config could look like this:

```
apiVersion: garden.io/v0
kind: Project
name: otel-collector-test
environments:
  - name: local
    defaultNamespace: ${var.dev-env-name}
providers:
  - name: local-kubernetes
    environments: [local]
    namespace: ${environment.namespace}
  - name: otel-collector
    exporters:
      - name: otlphttp
        enabled: true
        endpoint: http://localhost:4318
      - name: newrelic
        enabled: true
        apiKey: ${secrets.NR_API_KEY}
      - name: honeycomb
        enabled: true
        apiKey: ${secrets.HONEYCOMB_API_KEY}
        dataset: ${secrets.HONEYCOMB_DATASET}
      - name: datadog
        enabled: true
        site: ${secrets.DD_EXPORTER_SITE}
        apiKey: ${secrets.DD_EXPORTER_API_KEY}
variables:
  dev-env-name: ${project.name}-testing-${local.username}
```

Currently supported are a generic `otlphttp` type for any HTTP OTLP endpoint, and configs for `newrelic`, `honeycomb` and `datadog`.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-07-07 13:35 UTC, TimBeyer commented on core/src/util/process.ts
> +    logger.silly(logLine)
If `streamLogs` is used we now send all logs from subprocesses also to the CLI log output using the silly loglevel.
This is quite useful in order to debug issues with tools we call from garden.

2023-07-10 09:56 UTC, Orzelius requested changes
I think the formatter might have been misconfigured. There are many styling changes which seem to be unrelated and make it hard to review

2023-07-13 08:59 UTC, Orzelius reviewed
Thank you! Incredibly clean and easy to read code! I've posted some comments and am wondering about the lack of tests and docs, but other than that it looks sweet. Sorry for the long wait for the review, I just forgot about the pr.

2023-07-13 08:59 UTC, Orzelius commented on core/src/garden.ts
> +      let allResources = flatten(
This change doesn't seem to be needed

2023-07-13 08:59 UTC, Orzelius commented on core/src/plugins/otel-collector/config/logging.ts
> +export type LoggingExporterVerbosityLevel = "detailed" | "normal" | "basic"
"basic" doesn't sound like a verbosity level to me. Is it some terminology coming from elsewhere that I'm unaware of? Why not the usual "info", "verbose" and "trace" or "all"?

2023-07-13 08:59 UTC, Orzelius commented on core/src/plugins/otel-collector/otel-collector.ts
> +  Otel Collector
Will the docs be added later?

2023-07-13 08:59 UTC, Orzelius commented on core/src/plugins/otel-collector/otel-collector.ts
> +  return { ready: false, outputs: {} }
Is the hardcoded `ready: false` intentional?

2023-07-13 08:59 UTC, Orzelius commented on core/src/plugins/otel-collector/otel-collector.ts
> +  }
I think the error should be logged as well

2023-07-13 08:59 UTC, Orzelius commented on docs/reference/providers/otel-collector.md
> +        verbosity: normal
Will the docs come later?

2023-07-13 09:03 UTC, TimBeyer commented on core/src/garden.ts
> +      let allResources = flatten(
You're right. I have no idea where this change came from.
Shouldn't our linter have `prefer-const` enabled and catch this?

2023-07-13 09:18 UTC, Orzelius commented on core/src/garden.ts
> +      let allResources = flatten(
Seems like it's not configured to do so properly

2023-07-13 09:32 UTC, TimBeyer commented on core/src/plugins/otel-collector/otel-collector.ts
> +  return { ready: false, outputs: {} }
I believe it is. If I recall this correctly, garden would check first if the environment is ready, and if so it would not call `prepareEnvironment` again.
We need to call `prepareEnvironment` every time, so we always say it's not ready.

Even worse is that if you just once leave out this hook, the status is assumed to be complete with cache enabled, and the cached state is written to the filesystem making it that without a `--force` the provider will never initialize again.

We also found that returning `disableCache: true` in `getEnvironmentStatus` does not actually disable the cache and will still proceed caching the state.

This it is required to return `ready: false` here and then later on return `disableCache: true` from the `prepareEnvironment` handler.

2023-07-13 09:38 UTC, TimBeyer commented on docs/reference/providers/otel-collector.md
> +        verbosity: normal
The problem here is that `oneOf` and `anyOf` schemas [aren't correctly converted into docs yet](https://github.com/garden-io/garden/blob/de50fcc7ccfa29b520facbe83bee8fdb31caea8b/core/src/docs/json-schema.ts#L37-L45).

I think we should fix this soon since it makes the docs incomplete, but since it's not strictly related and once fixed the docs will show up for this as well, I decided to not make it part of this PR.

2023-07-13 10:30 UTC, shumailxyz commented
Great work @TimBeyer 💯 

Just read through the PR. Wondering the same what @Orzelius mentioned about lack of tests and docs.

2023-07-13 14:41 UTC, TimBeyer commented
@shumailxyz @Orzelius I thought about how to test this but couldn't come up with a good way.
If we unit test this we need to mock almost everything that makes this work in the first place leading to not very solid tests.
Probably e2e tests would be best, but then we'd have to create an OTLP HTTP endpoint and verify that we get all the data, which is difficult since we're sending quite a lot of data that can also change at any time if new spans are added.
The schemas for the config generation could be tested, but they are very simple and the typesystem already makes sure that inputs and outputs are correct.
That just leaves the `ReconfigurableExporter` and the function to find a string in a childprocess output.
I can add tests for those if you prefer.
Also if you have a good idea for how to tests the overall feature without having to mock a lot of things and that will always work even if we change the exact things we trace, I'm happy to take a look at that too.

2023-07-13 14:45 UTC, Orzelius commented
I think a e2e test is the way to go here. It would serve as a smoke test for if we make a fatal mistake that would kill the functionality completely and would double as an example configuration for when we need to do further work on the functionality.

We already have some clumsy e2e tests that do a lot, but that's the business we're in

2023-07-13 16:31 UTC, stefreak commented on core/src/util/process.ts
> +    logger.silly(logLine)
This is slightly weird now, as we also send the messages emitted as `log` event to `ctx.events` to our logger with `verbose` log level.
Do we need duplicate logs both on silly and verbose?

2023-07-13 16:32 UTC, stefreak commented on core/src/util/util.ts
> +    gracefulExit(code)
🚀 Nice that's much better

2023-07-13 17:08 UTC, TimBeyer commented on core/src/util/process.ts
> +    logger.silly(logLine)
The way I understood it is that ctx.events only goes to cloud and isn't actually logged. That's why I added the extra log statement so it shows up in core as well.

2023-07-14 08:48 UTC, stefreak commented on core/src/util/process.ts
> +    logger.silly(logLine)
The action router also logs these: https://github.com/garden-io/garden/blob/main/core/src/router/build.ts#L44C12-L44C12

Do you see the logs only once or twice in manual testing?

2023-07-14 08:49 UTC, stefreak commented on core/src/util/process.ts
> +    logger.silly(logLine)
It's a little surprising maybe, but I added that log statement there so that we always send logs to both Cloud and the CLI

2023-07-14 08:51 UTC, stefreak commented on core/src/util/process.ts
> +    logger.silly(logLine)
For tests and tasks it does that too, but there only if the interactive flag is false: https://github.com/garden-io/garden/blob/main/core/src/router/test.ts#L49

That's because logs get streamed to stdout in that case

2023-07-14 09:01 UTC, TimBeyer commented on core/src/util/process.ts
> +    logger.silly(logLine)
I see the logs only once

2023-07-14 09:03 UTC, stefreak commented on core/src/util/process.ts
> +    logger.silly(logLine)
Interesting, that's strange can we have a look at this together?

2023-07-14 12:03 UTC, TimBeyer commented
@shumailxyz @Orzelius Added some e2e smoke tests for the feature.

2023-07-14 14:14 UTC, TimBeyer commented on core/src/util/process.ts
> +    logger.silly(logLine)
I fixed this so we shouldn't see duplicate logs from the places where you already added the logging

2023-07-17 08:38 UTC, Orzelius reviewed
Looks good, but what about docs 👉👈?

2023-07-17 10:16 UTC, Orzelius approved these changes
@TimBeyer and I decided that the provider reference docs should suffice. This is good to merge from my side. cc @garden-io/core

2023-07-17 11:51 UTC, merged