feat(cli): add cloud secrets update command
garden-io/garden pull request #4804
Opened 2023-07-11 18:20 UTC by shumailxyz

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-07-17 10:32 UTC, Orzelius requested changes
I think the documentation should also mention that secrets will be created if they don't exist.

If you want to make the creation of secrets default behavior the command should be upsert not update. If you want to keep it update I think that the creation of new secrets should be behind a flag, something like `--upsert`.

Although we decided that we won't be testing this e2e with cloud I still think this code should be split into smaller testable parts and unit tests should be written to ensure quality and make future developments easier.

2023-07-17 10:32 UTC, Orzelius commented on core/src/cloud/api.ts
> +      retry: retry === true ? true : false, // defaults to false unless true is explicitly passed
There must be a cleaner way to write this 🤔

How about
```suggestion
      retry: !!retry
```

2023-09-22 08:53 UTC, eysi09 reviewed
Great work! 

Left a few comments but overall looks good.

2023-09-22 08:53 UTC, eysi09 commented on core/src/commands/cloud/secrets/secrets-update.ts
> +  let tmp = sortBy(allSecrets, "name")
Kind of a nitpick but I'd prefer something more descriptive like `sortedSecrets` instead of `tmp`

2023-09-22 08:53 UTC, eysi09 commented on core/src/commands/cloud/secrets/secrets-update.ts
> +  tmp = tmp.filter((secret) => Object.keys(secretsToUpdateArgs).includes(secret.name))
How about chaining all these together so that you don't have to constantly re-assign the `tmp` variable?

Something like:

```
const filteredSecrets = sortBy(allSecrets, "name")
  .filter((s) => envName ? s.environment.name === envName : true)
  .filter((s) => userId ? ...)
  .filter((s) => ...)
```

2023-09-22 08:53 UTC, eysi09 commented on core/src/commands/cloud/secrets/secrets-update.ts
> +    help: "Set this flag to upsert secrets instead of update i.e. existing secrets are updated while missing secrets are created.",
```suggestion
    help: "Set this flag to upsert secrets instead of updating them. I.e., existing secrets will be updated while missing secrets will be created.",
```

2023-09-22 08:53 UTC, eysi09 commented on core/src/commands/cloud/secrets/secrets-update.ts
> +    help: deline`Update the secret(s) by providing the ID(s) of secrets.
```suggestion
    help: deline`Update secret(s) by secret ID(s).
```

2023-09-22 08:53 UTC, eysi09 commented on core/test/unit/src/commands/cloud/secrets/secrets-update.ts
> +describe("SecretsUpdateCommand", () => {
Maybe out of scope for now since this PR is already pretty old but moving forward I think we should be testing the cloud commands with `nock` and just examining the request body. 

That way we can just create the Garden command instance, test all the different args and opts and examine what the POST body looks like. For this case we can also mock the get request.

I'm typically not a fan of mocking but these kind of tests are an exception.

2023-09-22 13:27 UTC, shumailxyz commented on core/src/commands/cloud/secrets/secrets-update.ts
> +  tmp = tmp.filter((secret) => Object.keys(secretsToUpdateArgs).includes(secret.name))
Sure, updated in https://github.com/garden-io/garden/pull/4804/commits/5b7c5a057f86a0ba4307de8c5b57448efe6597e7

2023-09-22 13:28 UTC, shumailxyz commented on core/test/unit/src/commands/cloud/secrets/secrets-update.ts
> +describe("SecretsUpdateCommand", () => {
yeah makes sense. May be we can create some kind of package that provides mock for our api client and can be reused whenever required

2023-09-25 14:05 UTC, eysi09 approved these changes
Thanks for addressing the PR comments. Looks good to me!

2023-09-26 14:05 UTC, merged