fix(serve): connect to Cloud if process is started outside of project dir
garden-io/garden pull request #4822
Opened 2023-07-13 12:02 UTC by edvald

This came up in the Desktop client because it'd start the serve command outside of any project root, and thus not connect to Cloud at all for the live view etc. to work.

cc @eysi09

2023-07-19 14:03 UTC, vvagaytsev commented
@eysi09 is this ready to do? LGTM, but I might miss some context.

2023-07-19 19:00 UTC, eysi09 commented
> @eysi09 is this ready to do? LGTM, but I might miss some context.

I'm not sure. Maybe I'm missing something, but when we connect to Cloud we need to do that in the context of some specific project. What would that be in the case where Garden is started outside of a given project?

2023-09-11 13:14 UTC, trymbill commented
@eysi09 and I just verified this works now for Desktop. So LGTM! 👍

2023-09-11 15:23 UTC, vvagaytsev approved these changes

2023-09-18 10:09 UTC, eysi09 commented
Just to follow up. 

I think we just need to make sure we only set the `localServerPort` for the `dev` or `serve` command. So when registering a session for, say, a `deploy` command, we need to make sure that the local server port isn't set in the payload. 

This hasn't been an issue until the change in this issue was introduced. Basically the added `registerSession` call appears to sometime set a server port when it shouldn't.

2023-10-05 11:04 UTC, eysi09 requested changes

2023-10-05 11:04 UTC, eysi09 commented on core/src/server/instance-manager.ts
> +        localServerPort: ["dev", "serve"].includes(garden.commandInfo.name) ? this.serveCommand.server.port : undefined,
This is called in more places and we need to update it all of them. 

Can I also suggest that in the `registerSession` function we set the `localServerPort` type to `number | null` so that it's explicit and we won't forget to add it at other call sites.

2023-10-05 11:34 UTC, shumailxyz commented on core/src/server/instance-manager.ts
> +        localServerPort: ["dev", "serve"].includes(garden.commandInfo.name) ? this.serveCommand.server.port : undefined,
I think we don't need this on other places. We basically have 3 calls of `registerSession` including this one. The other 2 calls are in `base.ts` and  `serve.ts`.

The `base.ts` call already has a check and skips the registration in case of dev/serve.
https://github.com/garden-io/garden/blob/8490aacf9f1e29278212f91ac3f3af31eab38b88/core/src/commands/base.ts#L311-L315

And in [`serve.ts`](https://github.com/garden-io/garden/blob/8490aacf9f1e29278212f91ac3f3af31eab38b88/core/src/commands/serve.ts#L179), we do not need this check as it only registers session for dev/serve.

2023-10-05 18:03 UTC, eysi09 commented on core/src/server/instance-manager.ts
> +        localServerPort: ["dev", "serve"].includes(garden.commandInfo.name) ? this.serveCommand.server.port : undefined,
Aha ok. Makes sense.

2023-10-06 07:44 UTC, eysi09 approved these changes

2023-10-06 09:29 UTC, merged