feat(config): better error messages around schema validation
garden-io/garden pull request #4889
Opened 2023-07-25 01:05 UTC by edvald

This attaches the YAML parse results to configs when loading, and leverages that when rendering validation error messages.

```yaml
...
3  | spec:
4  |   foo: 123
-------^
"foo" should be a string
```

This should be a useful step for an IDE highlighting integration as well.

2023-07-25 07:41 UTC, vvagaytsev requested changes
There are some test failures, please take a look.

2023-07-25 12:21 UTC, TimBeyer commented
Does this work as expected with YAML files that contain multiple docs?
When I was trying this out you needed to do something like

```ts
const lineCounter = new LineCounter()
const parser = new Parser(lineCounter.addNewLine)

const tokens = parser.parse(content)
const docsGenerator = new Composer().compose(tokens)

const docs = Array.from(docsGenerator) as Document.Parsed<ParsedNode>[]
```

to get the docs and then use `lineCounter.linePos` to get the correct line in the input file.

2023-07-25 12:24 UTC, edvald commented
I hadn't tested that specifically, good catch. Not sure I fully follow your code there though. Happy to take commits on this PR btw, it's very much a draft still, bunch of broken tests etc.

2023-07-31 11:09 UTC, thsig commented
Btw, I think it's acceptable if we just show the YAML doc that the error came from, even it it's a sub-doc of a larger one—we just need to help the user quickly pinpoint the source location.

2023-08-21 09:57 UTC, vvagaytsev commented on core/src/config/validation.ts
> +  const errorDetails = error.details.map((e) => {
This could be extracted as a separate function that does the error rendering.
Also, there are some index-based array operations. Would it be safer to wrap them in a `try/catch` just in case?

2023-08-21 09:58 UTC, vvagaytsev commented on core/src/tasks/resolve-provider.ts
> +        return true
Does this statement always break the loop after the first iteration? Was it done intentionally? It looks like the returned `boolean` value is never used, do we need it?

2023-08-21 10:25 UTC, vvagaytsev commented
I left a few comments and questions, please check.
Otherwise looks good, thank you! 👍

2023-08-24 23:08 UTC, edvald commented on core/src/config/validation.ts
> +  const errorDetails = error.details.map((e) => {
A try/catch definitely makes sense. Will refactor a bit.

2023-08-24 23:10 UTC, edvald commented on core/src/tasks/resolve-provider.ts
> +        return true
That's intentional. The boolean needs to be there, linter complains if we only return it to break.

2023-08-24 23:39 UTC, edvald commented on core/src/config/validation.ts
> +  const errorDetails = error.details.map((e) => {
Done 👍

2023-09-04 11:38 UTC, vvagaytsev commented on core/src/tasks/resolve-provider.ts
> +        return true
Ok, got it, thanks! It may make sense to leave a short comment on that :)

2023-09-04 11:38 UTC, vvagaytsev submitted a review, later dismissed
LGTM! 👍  Thanks for the great improvement! 💯

2023-09-21 12:38 UTC, edvald commented
Just did that actually, good timing :) Just grappling with my merge commit now.

2023-09-21 12:51 UTC, edvald commented
Ok, should be ready now, pending tests passing.

2023-09-25 13:06 UTC, vvagaytsev commented
Now there are more conflicts to be resolved.

2023-09-25 15:41 UTC, edvald commented
Updated again.

2023-09-26 07:07 UTC, vvagaytsev commented on core/src/template-string/template-string.ts
> +  resolved: any
It looks like these parameters are never rendered. Do we need this specific kind of error? Or should we just use `ConfigurationError` class instead?
@stefreak @TimBeyer wdyt?

2023-09-26 08:34 UTC, edvald commented on core/src/template-string/template-string.ts
> +  resolved: any
I opted to keep this even though the typed detail object was removed, since we are likely to use this (and potentially more) later for e.g. a language server implementation.

2023-09-26 13:17 UTC, vvagaytsev approved these changes
Thank you! 💯

2023-09-26 13:51 UTC, merged