fix(k8s): regression in globs in k8s manifest files
garden-io/garden pull request #4903
Opened 2023-07-31 08:54 UTC by vvagaytsev

**What this PR does / why we need it**:
The regression was introduced in #4516. After that PR, it was possible to silently skip all non-existing files specified in in `spec.files` of a Deploy action of type `kubernetes`.

In `0.13.6` that would fail with error like this:
```console
ENOENT: no such file or directory, open '~/garden/core/test/data/test-projects/kubernetes-type/with-build-action/deployment-action1.yaml'
```

This PR implements some explicit checks for path existence and makes the output a bit more readable:
```console
Invalid manifest file path(s) in Deploy action 'with-build-action'. Cannot find manifest file(s) at ~/garden/core/test/data/test-projects/kubernetes-type/.garden/build/exec-build/deployment-action1.yaml
```

Issues #4505 and #4506 still exist. That's why the deployment can fail even with the existing manifest file. The build directory appears to be empty. It will be fixed in a separate PR.

**Which issue(s) this PR fixes**:

Fixes #4900

**Special notes for your reviewer**:
You can find more detail and explanation in the commit messages.

2023-07-31 10:54 UTC, thsig requested changes
Great stuff! Really appreciate the added test cases.

I had one suggestion to improve the new error message, otherwise we're good to go here.

2023-07-31 10:54 UTC, thsig commented on core/src/plugins/kubernetes/kubernetes-type/common.ts
> +      message: `Invalid manifest file path(s) in ${action.kind} action '${
Since we're adding a nice error message here, let's go the extra mile and include the missing (relative) paths in the error message.

2023-07-31 11:11 UTC, vvagaytsev commented on core/src/plugins/kubernetes/kubernetes-type/common.ts
> +      message: `Invalid manifest file path(s) in ${action.kind} action '${
Changed that in dad43954aff3ab8a554e1973e8c950a3da1ce866.

2023-08-01 11:10 UTC, Walther approved these changes
Looks good, thanks for the fix! ✨

2023-08-01 11:23 UTC, merged