chore(analytics): include project and user metadata when running commands with noProject
garden-io/garden pull request #4915
Opened 2023-08-02 18:25 UTC by mkhq

**What this PR does / why we need it**:

Optionally includes project and user metadata when running a command that works outside the project root.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-09-06 14:55 UTC, vvagaytsev commented on core/src/cloud/api.ts
> +    userProfile: CloudUserProfile | undefined = undefined
It might be nicer to have a parameter object instead of 5 positional args here.

2023-10-04 18:06 UTC, eysi09 requested changes
Great stuff! 

I had a couple of comments but otherwise looks good.

2023-10-04 18:06 UTC, eysi09 commented on core/src/analytics/analytics.ts
> +    if (garden instanceof DummyGarden) {
Can we extract this to a separate function and update the control flow so that it doesn't have all these nested if statements?

We can instead return early with something like:

```
if (!projectConfig) {
  return
}

// proceed...
```

2025-05-26 12:01 UTC, vvagaytsev commented
Closing as not planned for now. We'll re-think this and create a new PR if necessary.

2025-05-26 12:01 UTC, closed without merging