WIP: ephemeral cluster provider
garden-io/garden pull request #4927
Opened 2023-08-08 08:59 UTC by shumailxyz

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-09-08 12:51 UTC, worldofgeese requested changes

2023-09-08 12:51 UTC, worldofgeese commented on docs/basics/ephemeral-clusters.md
> +Once your ephemeral cluster is created, the Kubeconfig file for that cluster is stored on your local computer. The path to the Kubeconfig file is shown in the logs when you deploy your project using
Kubeconfig is with a lowercase "k" [according to Kubernetes's docs](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/).

2023-09-11 14:18 UTC, 10ko commented on docs/basics/ephemeral-clusters.md
> +The ingress URLs are not publicly accessible and require authentication via GitHub. To preview an ingress URL, you must authenticate with GitHub and authorize the "Garden Ephemeral Environment Previe
I think we can directly mention you need to be authenticated to app.garden.io, let's not mention what kind of OAuth providers we use, also because we might change these in the future.

2023-09-12 15:21 UTC, vvagaytsev commented on core/src/plugins/kubernetes/init.ts
> +  if (!clusterInit && remoteCluster && provider.name !== EPHEMERAL_KUBERNETES_PROVIDER_NAME) {
Here we can use negated `isProviderEphemeralKubernetes` helper instead of the explicit value comparison.

2023-09-12 15:25 UTC, 10ko submitted a review, later dismissed
Woop woop! I added a bunch of corrections and questions, mostly around the docs! Thanks for the PR @shumailxyz !!

2023-09-12 15:25 UTC, 10ko commented on docs/basics/ephemeral-clusters.md
> +The ephemeral Kubernetes clusters are provided for free to all users. The ephemeral clusters are designed for short-term use and allow you to run and test your applications with Garden on Kubernetes
Let's move this part above.

2023-09-12 15:25 UTC, 10ko commented on docs/basics/ephemeral-clusters.md
> +With the ephemeral-kubernetes provider configured, you can now deploy your project using the Garden CLI by running the following command:
```suggestion
Once the provider is configured, you can deploy your project using the Garden CLI by running the following command:
```

2023-09-12 15:25 UTC, 10ko commented on docs/basics/ephemeral-clusters.md
> +The CLI will automatically provision an ephemeral Kubernetes cluster for your project and deploy your application to it.
```suggestion
Garden will automatically provision an Ephemeral Kubernetes Cluster for your project and deploy your application to it.
```

2023-09-12 15:25 UTC, 10ko commented on docs/basics/ephemeral-clusters.md
> +If you want to refer to the hostname that is assigned dynamically when the cluster is created, you can refer to that using the output `${providers.ephemeral-kubernetes.outputs.default-hostname}`. Thi
```suggestion
If you want to refer to the hostname that is assigned dynamically when the cluster is created, you can refer to that using the output `${providers.ephemeral-kubernetes.outputs.default-hostname}`. This can be useful if, for example, you want to expose an ingress on a subdomain of the default hostname. e.g. You want to expose `api` on `api.<default-hostname>`.
```

2023-09-12 15:25 UTC, 10ko commented on docs/basics/ephemeral-clusters.md
> +For instance, if you wish to expose an API service on a subdomain like api.<default-hostname>, you can easily achieve this in your Garden configuration. Here's an example of how to configure your Gar
Same here.

2023-09-12 15:25 UTC, 10ko commented on docs/basics/ephemeral-clusters.md
> +```
```suggestion
```yaml
```

2023-09-12 15:25 UTC, 10ko commented on docs/basics/ephemeral-clusters.md
> +Once your ephemeral cluster is created, the kubeconfig file for that cluster is stored on your local computer. The path to the kubeconfig file is shown in the logs when you deploy your project using
```suggestion
Once your ephemeral cluster is created, the kubeconfig file for that cluster is stored on your local machine. The path to the kubeconfig file is shown in the logs when you deploy your project using Garden and looks like following:
```

2023-09-12 15:25 UTC, 10ko commented on docs/basics/ephemeral-clusters.md
> +This kubeconfig file allows you to interact with the cluster using kubectl or other Kubernetes tools.
```suggestion
This kubeconfig file allows you to interact with the cluster using `kubectl` or other Kubernetes tools.
```

2023-09-12 15:25 UTC, 10ko commented on docs/basics/ephemeral-clusters.md
> +- Local docker builds are currently not supported. Only the in-cluster builds using Kaniko are supported however that is configured by default for the ephemeral-kubernetes provider.
```suggestion
- Local docker builds are currently not supported. In-cluster building with Kaniko is the only supported building method and it is configured by default at the provider level.
```

2023-09-12 15:25 UTC, 10ko commented on docs/basics/ephemeral-clusters.md
> +<!-- todo add example link once example is merged: https://github.com/garden-io/garden/tree/main/examples/ephemeral-cluster-demo -->
We should be able to add this link right?

2023-09-13 08:31 UTC, shumailxyz commented on core/src/plugins/kubernetes/init.ts
> +  if (!clusterInit && remoteCluster && provider.name !== EPHEMERAL_KUBERNETES_PROVIDER_NAME) {
Good catch. I missed this one somehow.

2023-09-13 09:37 UTC, shumailxyz commented on core/src/plugins/kubernetes/container/handlers.ts
> +            `You are using ${EPHEMERAL_KUBERNETES_PROVIDER_NAME} provider and and have disabled ingress controller setup by specifying setupIngressController=false in the provider configuration. Eith
Let's remove this. I was thinking earlier that what if someone goes through setting up DNS and use their hostname, but now that i think, that won't be possible for ephemeral clusters in current setup.

2023-09-13 09:47 UTC, twelvemo commented on docs/basics/ephemeral-clusters.md
> +If you need to destroy the cluster before its maximum lifetime of 4 hours expires, you can do so by visiting [Garden Cloud](https://app.garden.io) and selecting the option to destroy the ephemeral cl
I think that makes sense, but i think we can release the first iteration without additional features around managing clusters. I like the idea of deleting clusters after a short time maybe 30 min of inactivity.

2023-09-13 09:49 UTC, twelvemo commented on core/src/plugins/kubernetes/container/handlers.ts
> +            `You are using ${EPHEMERAL_KUBERNETES_PROVIDER_NAME} provider and and have disabled ingress controller setup by specifying setupIngressController=false in the provider configuration. Eith
I agree and it is also not tied to installing our ingress controller or not.

2023-09-13 09:54 UTC, shumailxyz commented on docs/basics/ephemeral-clusters.md
> +<!-- todo add example link once example is merged: https://github.com/garden-io/garden/tree/main/examples/ephemeral-cluster-demo -->
After it's merged because otherwise the CI step check-docs will fail due to a dead link.

2023-09-13 09:58 UTC, shumailxyz commented
@10ko Thanks for all the suggestions. I couldn't directly apply suggestions because I had some local changes to docs but manually used those.

2023-09-13 09:59 UTC, shumailxyz commented on core/src/plugins/kubernetes/container/handlers.ts
> +            `You are using ${EPHEMERAL_KUBERNETES_PROVIDER_NAME} provider and and have disabled ingress controller setup by specifying setupIngressController=false in the provider configuration. Eith
Yeah i removed that.

2023-09-13 09:59 UTC, shumailxyz commented on core/src/plugins/kubernetes/init.ts
> +  if (!clusterInit && remoteCluster && provider.name !== EPHEMERAL_KUBERNETES_PROVIDER_NAME) {
Updated in https://github.com/garden-io/garden/pull/4927/commits/4090b954c0f26d646b8a13d2c11ea2ca166392a0#diff-3db0d3360208391d7411863de1ff45345be4ed5e47ae2038ff0b53ed85ad1d44R236

2023-09-13 10:07 UTC, shumailxyz commented on examples/ephemeral-cluster-demo/README.md
> +For information about ephemeral Kubernetes clusters, check out the docs: <!-- todo: add link to docs for ephemeral clusters -->
Same issue. CI will fail at check-docs step due to dead link

2023-09-13 10:10 UTC, shumailxyz commented on docs/basics/ephemeral-clusters.md
> +## Usage quota and managing clusters
I think it's better to inform user first about the usage quota and then proceed with docs around configuration, deploying, ingresses etc. Feels more intuitive to me. I had this section after ingresses previously but moved above on @worldofgeese suggestion and liked the idea.

2023-09-13 10:25 UTC, twelvemo requested changes
Looks really good! Just one small nitpick and a couple of comments on the existing threads from my side.

2023-09-13 10:25 UTC, twelvemo commented on core/test/unit/src/plugins/kubernetes/ephemeral.ts
> +  it("should throw an error in configure provider if user is not in", async () => {
```suggestion
  it("should throw an error in configure provider if user is not logged in", async () => {
```

2023-09-13 10:51 UTC, worldofgeese commented on docs/basics/ephemeral-clusters.md
> +## Usage quota and managing clusters
Yes, we don't want folks getting surprised by this IMO.

2023-09-13 11:10 UTC, 10ko commented
Good to go for me, at least as a first version, we can iterate on it. I'll leave it to the others to approve, so all requests are taken into consideration.

2023-09-13 12:14 UTC, twelvemo approved these changes

2023-09-13 13:41 UTC, merged