docs: added docs for config resolution flow
garden-io/garden pull request #4978
Opened 2023-08-23 22:24 UTC by thsig

**What this PR does / why we need it**:

This should be useful for contributors when debugging config resolution issues or adding features relating to templating (at least to get a high-level orientation and figure out where to start).

2023-08-24 08:10 UTC, vvagaytsev reviewed
Cancelling the stale review

2023-08-24 08:11 UTC, vvagaytsev commented on core/src/graph/config-resolution-overview.md
> +See `core/src/template-string/parser.pegjs` for details on the syntax and expression evaluation logic. When Core is built, this file is passed to [PEG.js](https://pegjs.org) which generates an effici
PegJS is quite outdated, and it has a successor - [Peggy](https://github.com/peggyjs/peggy). We'll switch to Peggy  in #4889

2023-08-24 08:38 UTC, vvagaytsev commented on core/src/graph/config-resolution-overview.md
> +## Phase 1 of action resolution: Preprocessing during config graph construction
Maybe we can have H2-header like `Action resolution phases` here, and 2 H3-headers below:
* `Phase 1: Preprocessing during config graph construction`
* `Phase 2: Full resolution in solver just before task execution`

2023-08-24 08:38 UTC, vvagaytsev commented on core/src/graph/config-resolution-overview.md
> +For example: `ProjectConfigContext`, `ActionConfigContext` and `ActionSpecContext` (the last being more specific, as the spec is only fully resolved in phase 2 of action resolution).
We can add a link to the _phase 2 action resolution_ paragraph here.

2023-08-24 08:40 UTC, vvagaytsev commented on core/src/graph/config-resolution-overview.md
> +These classes are also used to generate the reference docs for what template keys are available where, so they're an excellent place to start when figuring out why e.g. a certain key isn't available
```suggestion
**Debugging hint!** These classes are also used to generate the reference docs for what template keys are available where, so they're an excellent place to start when figuring out why e.g. a certain key isn't available at a certain phase of config resolution.
```

2023-08-24 08:40 UTC, vvagaytsev commented on core/src/graph/config-resolution-overview.md
> +These classes are also used to generate the reference docs for what template keys are available where, so they're an excellent place to start when figuring out why e.g. a certain key isn't available
This can also be moved to the end of the section.

2023-08-24 09:04 UTC, vvagaytsev commented on core/src/graph/config-resolution-overview.md
> +* The solver will then fully resolve any required actions in dependency order (phase 2 of action resolution), so that the outputs of dependency actions are made available for full template resolution
It might be good to add a link to the solver guide here.

2023-08-24 09:13 UTC, vvagaytsev reviewed
Thank you! 👍 
I've left a few comments, please check.

2023-08-24 21:18 UTC, thsig commented
Should be good to go now—I addressed most of the comments (and skipped some of them).

Thanks for reading through this!

2023-08-26 01:29 UTC, eysi09 commented
This is great! I see myself looking this up multiple times. 

Out of scope for this PR but I'm wondering if we should collect all these in a single place, e.g. a top-level dir called `contributing` as opposed to co-locating with code. 

(I know co-locating is a good thing in general, but maybe high level architectural docs like this are an exception.)

2023-08-28 11:27 UTC, thsig commented
> This is great! I see myself looking this up multiple times.
> 
> Out of scope for this PR but I'm wondering if we should collect all these in a single place, e.g. a top-level dir called `contributing` as opposed to co-locating with code.
> 
> (I know co-locating is a good thing in general, but maybe high level architectural docs like this are an exception.)

Good idea! I'll do that.

2023-08-28 11:51 UTC, thsig commented
I read this through again and made a couple of edits and clarifications. Should be good to go.

2023-08-28 12:54 UTC, worldofgeese commented on contributor-docs/config-resolution.md
> +  * or `${actions.build.api.deployment-image-id}` -> `some-registry.io/my-org/api:v-abf3f8dca`.
```suggestion
  * or `${actions.build.api.outputs.deployment-image-id}` -> `some-registry.io/my-org/api:v-abf3f8dca`.
```

https://docs.garden.io/reference/action-types/build/container#usd-actions.build.less-than-name-greater-than.outputs.deployment-image-id

2023-08-28 13:04 UTC, worldofgeese requested changes
I made one suggestion but this otherwise looks like a *fantastic* resource for folks looking to understand config resolution.

2023-08-28 13:05 UTC, worldofgeese approved these changes

2023-08-28 16:03 UTC, merged