K8s deploy config templates example (WIP)
garden-io/garden pull request #5005
Opened 2023-09-02 23:48 UTC by eysi09

**What this PR does / why we need it**:

Depends on #4992 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-09-08 10:16 UTC, worldofgeese requested changes
I've confirmed this example runs locally. Asked for a few changes.

2023-09-11 15:51 UTC, eysi09 commented on examples/k8s-deploy-config-templates/README.md
> +        - "${inputs.enableIngress ? 'manifests/ingress.yaml' : null }" # <--- The "inputs" are defined in the JSON schema referenced in the 'inputsSchemaPath' field
I don't that think that works inside inline code like this. Or am I missing something?

I can just remove this part of the sample config though if you think that's better.

2023-09-11 15:53 UTC, eysi09 commented on examples/k8s-deploy-config-templates/web/README.md
Nope, I'll remove it.

2023-09-12 06:43 UTC, worldofgeese approved these changes
This looks ready to fly 🕊️ to me! Thanks for addressing.

2023-09-12 07:11 UTC, merged