Fix/k8s action type aec
garden-io/garden pull request #5122
Opened 2023-09-21 11:49 UTC by vvagaytsev

**What this PR does / why we need it**:
A follow-up fix for #4846 to address @stefreak 's [comment on the AEC](https://github.com/garden-io/garden/pull/4846#issuecomment-1695938718).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-09-21 11:51 UTC, shumailxyz commented on core/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +      if (manifestHash === "paused-by-aec") {
should we may be create a constant for this like [we do in case of helm](https://github.com/garden-io/garden/blob/feat-update-secret-cmd/core/src/plugins/kubernetes/helm/status.ts#L28)?

2023-09-21 11:52 UTC, shumailxyz commented on core/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +      if (manifestHash === "paused-by-aec") {
also, consider adding a todo to remove it once we implement the generic manifests comparison

2023-09-21 11:54 UTC, vvagaytsev commented on core/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +      if (manifestHash === "paused-by-aec") {
Makes sense, thank you!

2023-09-21 12:04 UTC, vvagaytsev commented on core/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +      if (manifestHash === "paused-by-aec") {
Addressed the items above in the recent commits, please check.

2023-09-21 12:26 UTC, twelvemo requested changes
Overall looks good, but i think we might be using the wrong annotation key.

2023-09-21 12:26 UTC, twelvemo commented on core/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +      const manifestHash = resource.metadata?.annotations?.[k8sManifestHashAnnotationKey]
Isn't `k8sManifestHashAnnotationKey = "manifest-hash"` but we want to look for the annotation key `"aec-status"` here? The value of an annotation with the key `"manifest-hash"` would never be `"paused-by-aec"` right?

2023-09-21 12:27 UTC, shumailxyz commented on core/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +      const manifestHash = resource.metadata?.annotations?.[k8sManifestHashAnnotationKey]
I think aec overrides the value of `manifest-hash` annotation

2023-09-21 12:32 UTC, twelvemo commented on core/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +      const manifestHash = resource.metadata?.annotations?.[k8sManifestHashAnnotationKey]
Oh i see, yes you are right of course. I was just getting confused because for helm we look for another annotation key.

2023-09-21 12:32 UTC, shumailxyz commented on core/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +      const manifestHash = resource.metadata?.annotations?.[k8sManifestHashAnnotationKey]
yes, for helm it's different.

2023-09-21 12:34 UTC, shumailxyz approved these changes

2023-09-21 12:35 UTC, shumailxyz commented
`e2e-run-actions` is failing but i think it's a flake

2023-09-21 12:35 UTC, twelvemo approved these changes
Super quick turnaround!

2023-09-21 12:36 UTC, vvagaytsev commented on core/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +      const manifestHash = resource.metadata?.annotations?.[k8sManifestHashAnnotationKey]
Hmm.. It looks like Cloud sets `garden.io/manifest-hash` to `paused-by-aec`, see https://github.com/garden-io/garden-platform/blob/main/workflow-runner/src/runners/cleanup-runner/index.ts#L258-L260

The `garden.io/aec-status` seems to be used only if the resource in question is managed by Helm: https://github.com/garden-io/garden-platform/blob/main/workflow-runner/src/runners/cleanup-runner/index.ts#L262-L268

2023-09-21 13:23 UTC, stefreak commented on core/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +      if (manifestHash === "paused-by-aec") {
Some people are using another value here, it would be good if we either also supported a generic value like just "paused", or if we check for the length of the string (=if it's not a hash)

See also: https://github.com/garden-io/garden/issues/3438#issuecomment-1349264690

2023-09-21 13:28 UTC, stefreak commented on core/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +      if (manifestHash === "paused-by-aec") {
Should we maybe add a test for this behaviour, so we don't miss it next time? It was quite time-consuming to make sure that we do not regress here. A test might save a lot of time in the future when we make changes to this functionality again. Also it'd ensure that this change actually works

2023-09-25 10:08 UTC, stefreak submitted a review, later dismissed
Great work! 👍 

I think we need to still make sure that `deploy -f` always deploys even when the deploy is `ready` already; But that can be done in a separate PR.

2023-09-25 10:26 UTC, shumailxyz commented
@vvagaytsev Some of the tests are failing. I wonder if those are due to the manifest hash check you added.

2023-09-25 10:29 UTC, vvagaytsev commented
@shumailxyz thanks! I see, that's because of the annotation change. The tests share the same in-cluster resource. After the new test is executed, I'll ensure that everything is reverted back to the normal state.

@stefreak thanks! Yes, let's address the `--force` flag in a separate PR/

2023-09-25 11:12 UTC, stefreak commented on core/test/integ/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +        await kubernetesDeploy(deployParams)
I understand if that's a bigger change and you want to do it separately; But would it be better to run `kubernetesDeploy` in a `beforeEach` in a group for all the tests that rely on it being deployed?

2023-09-25 11:13 UTC, stefreak commented on core/test/integ/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +        await kubernetesDeploy(deployParams)
seeing `try {} finally {}` in a test is strange when mocha provides `before` and `after` primitives for these kinds of things

2023-09-25 11:26 UTC, vvagaytsev commented on core/test/integ/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +        await kubernetesDeploy(deployParams)
That requires more changes and re-grouping of the tests. We can do it later if we have more tests that modify remote resources that should be re-deployed on the test completion.

2023-09-25 11:50 UTC, vvagaytsev commented on core/test/integ/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +        await kubernetesDeploy(deployParams)
I added a dedicated config for this test case in 75c1b2461f9df6e98e2599f358e522564bdf642b.
Now we don't need to restore the remote resource state used by the other tests.

2023-09-25 14:26 UTC, stefreak submitted a review, later dismissed
👍

2023-09-25 14:28 UTC, shumailxyz commented on core/test/integ/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +      // and that qill slow down the test execution.
```suggestion
      // and that will slow down the test execution.
```

2023-09-25 14:29 UTC, shumailxyz submitted a review, later dismissed
Awesome 💯 

Just a typo that i found.

2023-09-25 14:33 UTC, shumailxyz approved these changes

2023-09-25 15:39 UTC, merged