improvement(k8s): remove old system garden and improve local-k8s startup time
garden-io/garden pull request #5136
Opened 2023-09-26 10:04 UTC by vvagaytsev

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-09-28 08:41 UTC, stefreak commented on static/kubernetes/nginx-kind-old.yaml
> +          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0
missing sha256 hash. it's important to add it to every single image we reference from the garden binary or the static directory, to make sure that docker containers that ship with garden do not change after the garden binary shipped (which increases security by preventing supply-chain attacks).

2023-09-28 10:54 UTC, vvagaytsev commented on static/kubernetes/nginx-kind-old.yaml
> +          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0
Thanks! I fixed that in e665126a9edeee78ac8b08ccbd00b2b9fa0ec1e1.

2023-10-11 07:26 UTC, stefreak commented on core/src/plugins/kubernetes/commands/cluster-init.ts
> +  description: "[DEPRECATED] Initialize or update cluster-wide Garden services.",
The docs need to be still updated to reflect that this command is not needed anymore.

2023-10-16 10:44 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local/local.ts
> +  const systemNamespace = await getSystemNamespace(ctx, provider, log)
@twelvemo do we need to calculate the `systemNamespace` here? We do not use this variable in the code but use `config.gardenSystemNamespace` instead.

2023-10-16 10:47 UTC, vvagaytsev commented on core/src/plugins/kubernetes/local/local.ts
> +  const systemNamespace = await getSystemNamespace(ctx, provider, log)
Ah, we need that to ensure the system namespace existence.

2023-10-16 10:49 UTC, vvagaytsev commented on core/src/plugins/kubernetes/integrations/nginx.ts
> +    return "missing"
Does the error here always mean that the helm release is missing? Should we keep it `unknown` as before?

2023-10-16 11:08 UTC, twelvemo commented on core/src/plugins/kubernetes/integrations/nginx.ts
> +    return "missing"
I would say it should always implies missing, because we only reach this line if the helm command failed. Helm has a couple of statuses itself which we cover before. So we should only print this line if helm could not find the release at all.

2023-10-16 11:18 UTC, vvagaytsev commented on core/src/plugins/kubernetes/integrations/nginx.ts
> +    return "missing"
Ok, thanks for the clarification!

2023-10-16 14:51 UTC, twelvemo commented on core/src/plugins/kubernetes/ephemeral/config.ts
> +  await getSystemNamespace(ctx, ctx.provider, log)
We need to make sure for this provider again that the namespace actually exists.

2023-10-16 14:59 UTC, vvagaytsev commented on core/src/plugins/kubernetes/ephemeral/config.ts
> +  baseConfig.resources = defaultResources
Good catch, thank you! 👍

2023-10-23 07:17 UTC, twelvemo commented on static/kubernetes/nginx-ingress-class.yaml
Do we still need this file? I think we have a function for deploying the `ingressClass` now.

2023-10-23 07:19 UTC, twelvemo commented on static/kubernetes/nginx-kind.yaml
We should be able to get rid of this file as well.

2023-10-23 07:28 UTC, twelvemo commented on core/src/plugins/kubernetes/commands/uninstall-garden-services.ts
> +    await ingressControllerUninstall(k8sCtx, log)
```suggestion
     if (k8sCtx.provider.config.setupIngressController === "nginx") {
      await ingressControllerUninstall(k8sCtx, log)
    }
```
We should only remove it if it was installed by Garden or this specific Garden project in the first place.

2023-10-23 10:32 UTC, vvagaytsev commented on static/kubernetes/nginx-ingress-class.yaml
Yes, we have had the function called `ingressClassCreate` since 13720e91c881e15dd496f8218c9e6ea7182e18e0. But it has not been used yet. I changed that in 7fdd8fa1ba1ff9b2656e0d60e052609c73ba5324, please take a look.

The file [`nginx-ingress-class.yaml`](https://github.com/garden-io/garden/pull/5136/files/9399f5d744c2b74792ed98cd70b9af57f48a9a6f#diff-64fb5b2e763ad016dab2de57687b03c7125ffa0ff7ec5cafe31ca002403a2f5e) was used only in microk8s ingress controller installation in [`local.ts`](https://github.com/garden-io/garden/pull/5136/commits/13720e91c881e15dd496f8218c9e6ea7182e18e0#diff-b2d8fd1b3e1cf8d96418cb3bf6a6a15efa3c4521bdb47de856aefaf4927adb7cL111).

Do we need to create the `IngressClass` explicitly only for microk8s? OR for any other cluster types as well?

2023-10-23 10:37 UTC, vvagaytsev commented on static/kubernetes/nginx-kind.yaml
Good catch! Removed this in b172ef6f86344832b08ee55a9c630c8b422f6fc7.

2023-10-23 10:38 UTC, vvagaytsev commented on core/src/plugins/kubernetes/commands/uninstall-garden-services.ts
> +    await ingressControllerUninstall(k8sCtx, log)
Right! Good catch, thank you!

2023-10-23 10:54 UTC, twelvemo commented on static/kubernetes/nginx-ingress-class.yaml
> Do we need to create the IngressClass explicitly only for microk8s? OR for any other cluster types as well?

You are right, we don't need to do that at all. If we use the helm chart, the `ingressClass` is deployed via the helm chart.
For microk8s and minikube, the addons already include the nginx `ingressClass`. This probably changed since the last time this was revisited.

And for kind clusters, we use the custom manifests that also include the `ingressClass`.  So we can get rid of  the `ingressClassCreate` function and remove it from microk8s nginx setup.

2023-10-27 19:31 UTC, vvagaytsev commented
Now this is ready for review. There is still one unresolved comment by @stefreak. Let's do a full review round, and then address all comments at once :)

2023-11-01 09:37 UTC, stefreak requested changes
Great job 👍 
Let's hope that we can merge the PR to remove the .git repository in the static directory soon.

Moving all docker image references to `constants.ts` and declaring them using the type `DockerImageWithDigest` is important to me, the other comments are optional.

2023-11-01 09:37 UTC, stefreak commented on core/src/plugins/kubernetes/nginx/default-backend.ts
> +const GARDEN_DEFAULT_BACKEND_IMAGE =
I believe it would be good if we declare all Docker images in `constants.ts` and use the `DockerImageWithDigest` type to ensure that we don't miss the sha256 when updating the image in the future.

2023-11-01 10:08 UTC, twelvemo commented on core/src/plugins/kubernetes/nginx/ingress-controller.ts
> +    await helmNginxInstall(ctx, log, getK3sNginxHelmValues)
Really like that idea!

2023-11-03 11:09 UTC, vvagaytsev commented on docs/k8s-plugins/advanced/rbac-config.md
> -  # Allow port forward to build-sync services
That was cherry-picked from the original PR. I don't know why it was changed. @edvald do you remember why it was changed?

2023-11-03 11:14 UTC, edvald commented on docs/k8s-plugins/advanced/rbac-config.md
> -  # Allow port forward to build-sync services
I do. There were several rules there that we no longer need by default, since we’re not using the `garden-system` namespace as much. Probably good to review this closely, but looking at it again quickly it seems like the changes still make sense.

2023-11-03 11:54 UTC, vvagaytsev commented on core/src/plugins/kubernetes/nginx/default-backend.ts
> +const GARDEN_DEFAULT_BACKEND_IMAGE =
Done in 23774d16a10b43a5fe70c2569790418c1da0336e.

2023-11-03 12:09 UTC, stefreak commented on core/src/plugins/kubernetes/nginx/default-backend.ts
> +const GARDEN_DEFAULT_BACKEND_IMAGE =
@vvagaytsev There are still some image digests hidden in some of the manifests, e.g. core/src/plugins/kubernetes/nginx/nginx-kind-manifests.ts – maybe you can uncover more using the search

2023-11-07 16:47 UTC, vvagaytsev commented on core/src/plugins/kubernetes/nginx/default-backend.ts
> +const GARDEN_DEFAULT_BACKEND_IMAGE =
Thanks! I did the full-text search and fixed the remained code places in 57d56af93a35c7e394bcbb4b026d2feeea43f6a5.

2023-11-07 17:36 UTC, stefreak commented on core/src/plugins/kubernetes/nginx/default-backend.ts
> +const GARDEN_DEFAULT_BACKEND_IMAGE =
Love this!

2023-11-07 17:37 UTC, stefreak approved these changes
LGTM :shipit: 
![image](https://github.com/garden-io/garden/assets/139624/84aa3d2e-8e0e-4459-9ac5-0b66511c4bb5)

2023-11-08 16:31 UTC, vvagaytsev commented on core/src/plugins/kubernetes/nginx/ingress-controller.ts
> +    await helmNginxInstall(ctx, log, getK3sNginxHelmValues)
@stefreak I've made the refactoring in https://github.com/garden-io/garden/compare/57d56af93a35c7e394bcbb4b026d2feeea43f6a5..2ea6202c39cf8afd185a6cb26311bb80ca5e3ade

Please review it again :)

2023-11-08 16:31 UTC, vvagaytsev commented on core/src/plugins/kubernetes/commands/cluster-init.ts
> +  description: "[DEPRECATED] Initialize or update cluster-wide Garden services.",
Sure, I'll update the docs soon.

2023-11-09 08:23 UTC, stefreak submitted a review, later dismissed
Great additional changes! 👍 

I already meant to approve in my last review, but I accidentally only commented. But here's the approval again :)

2023-11-09 08:43 UTC, stefreak commented on core/src/plugins/kubernetes/nginx/ingress-controller.ts
> +    await helmNginxInstall(ctx, log, getK3sNginxHelmValues)
Looked good to me already, looks even better now :) 👍

2023-11-09 08:51 UTC, stefreak commented on core/src/plugins/kubernetes/commands/cluster-init.ts
> +  description: "[DEPRECATED] Initialize or update cluster-wide Garden services.",
Should we also emit a deprecation warning of we want to officially deprecate this command?

2023-11-09 10:36 UTC, vvagaytsev commented on core/src/plugins/kubernetes/commands/cluster-init.ts
> +  description: "[DEPRECATED] Initialize or update cluster-wide Garden services.",
Yes, I think so. I'l push a few more commits and will ask for another approval :)

2023-11-09 11:37 UTC, vvagaytsev commented on core/src/plugins/kubernetes/commands/cluster-init.ts
> +  description: "[DEPRECATED] Initialize or update cluster-wide Garden services.",
Added a deprecation warning in 509d490a8f790dc4a3732ee4e5e1ec464a0c7f40.

2023-11-09 11:42 UTC, vvagaytsev commented on core/src/plugins/kubernetes/commands/cluster-init.ts
> +  description: "[DEPRECATED] Initialize or update cluster-wide Garden services.",
> The docs need to be still updated to reflect that this command is not needed anymore.

@stefreak this command is still functional, we'll remove it in `0.14`. So, is it fine to keep the documentation as it is for now? Wdyt? Feel free to suggest/push a documentation update to this PR if necessary :)

2023-11-09 12:53 UTC, stefreak commented on core/src/plugins/kubernetes/commands/cluster-init.ts
> +  description: "[DEPRECATED] Initialize or update cluster-wide Garden services.",
OK 👍

2023-11-09 13:22 UTC, merged