docs: add dashboard cta to welcome page
garden-io/garden pull request #5156
Opened 2023-09-28 10:55 UTC by eysi09

**What this PR does / why we need it**:

Add a call-to-action for the new Garden Web Dashboard to the docs Welcome page. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-09-29 14:42 UTC, worldofgeese requested changes
Very minor hard-break fix suggestion and I also added the Garden Web Dashboard walkthrough GIF. On the Welcome page it's nested inside the info block: unsure if GitBook supports this?

2023-09-29 14:45 UTC, worldofgeese commented on docs/getting-started/quickstart.md
> +An interactive quickstart is also available by logging in to the Garden Web Dashboard. With the dashboard you can see the status of your builds and deployments, stream logs in real-time, and manage e
```suggestion
An interactive quickstart is also available by logging in to the Garden Web Dashboard. With the dashboard you can access command history, stream logs in real-time, view the status of your builds, tests, and deploys, visualize your dependency graph, and manage your free ephemeral clusters. To get started, [launch the Garden Web Dashboard](https://app.garden.io).
```

2023-09-30 08:41 UTC, eysi09 commented
Thanks for the suggestions! I've accepted both of them. We can merge this to main and see what it looks like on the `edge` branch and update the gif if needed.

2023-09-30 09:11 UTC, worldofgeese approved these changes

2023-09-30 09:45 UTC, merged