Docs remote k8s dev
garden-io/garden pull request #5214
Opened 2023-10-09 11:00 UTC by worldofgeese

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-10-10 08:20 UTC, worldofgeese commented
@valeriegarden, Eysi suggested citing case studies for each journey. WDYT?

2023-11-02 11:35 UTC, mkhq commented on docs/use-cases/local-development-remote-clusters.md
> +## Key features
Another key feature here would be Code Synchronization (https://docs.garden.io/guides/code-synchronization).

2023-11-20 12:36 UTC, eysi09 requested changes
Had a few comments but overall this looks great!

The "This needs some rework" comment is obviously not very actionable so perhaps we just follow up in person on that one.

2023-11-20 12:36 UTC, eysi09 commented on docs/README.md
> +* [Portable CI Pipelines that Run Anywhere](./use-cases/portable-ci-pipelines.md)
Isn't "Portable" and "Run Anywhere" a tautology? 

Also, what you think about skipping "CI" and just calling it "Fast pipelines that run anywhere"?

Because if you're running this "pipeline" from your laptop to start your dev env than it's not really CI.

2023-11-20 12:36 UTC, eysi09 commented on docs/use-cases/portable-ci-pipelines.md
> +Similarly, when developers run the test from their laptop against same environment as the CI pipeline uses, Garden will also skip running it in CI. Since the test runs in a remote environment and Gar
Let's skip "same environment" for now since we're doing work to enable caching across environments.

2023-11-20 12:36 UTC, eysi09 commented on docs/use-cases/portable-ci-pipelines.md
> +## Prerequisites
Should we skip this and the "Troubleshooting" section for now and have the "Next Steps" be a link to the "Quickstart" guide. 

Once we build out the actual journey we can re-introduce.

2023-11-20 12:36 UTC, eysi09 commented on docs/use-cases/portable-ci-pipelines.md
> +
Should we add "across all stages of software delivery" or "during development, in CI and in QA" or something similar to the end of the first sentence (can be its own sentence). 

Just to be make it clear "where" teams use these features.

2023-11-20 12:36 UTC, eysi09 commented on docs/use-cases/portable-ci-pipelines.md
> +## Key features
This needs some rework.

2023-11-20 12:36 UTC, eysi09 commented on docs/use-cases/local-development-remote-clusters.md
> +## Key features
Plus one!

2023-11-20 12:36 UTC, eysi09 commented on docs/use-cases/local-development-remote-clusters.md
> +## Key features
Also integration/api/e2e testing _as you develop_. Might be missing links for that.

2023-11-20 12:36 UTC, eysi09 commented on docs/use-cases/jumpstart-idp.md
> +Imagine vending self-contained, standardized stacks to your developers that help get them off the ground in seconds not days. This stack might contain a database, Kubernetes manifests defining an API
Instead of:

This stack might contain a database, Kubernetes manifests defining an API, and a Helm chart containing the frontend.

How about:

The stack might contain a pre-configured Helm chart for a database, Terraform modules for infrastructure, Kubernetes manifests for services, and more, that teams can compose together to suit their needs.

2023-11-24 11:39 UTC, worldofgeese commented on docs/use-cases/portable-ci-pipelines.md
> +## Key features
@eysi09, can you be more specific?

2023-11-24 11:46 UTC, worldofgeese commented on docs/README.md
> +* [Portable CI Pipelines that Run Anywhere](./use-cases/portable-ci-pipelines.md)
@eysi09 normally I'd agree but I think we're trying to juice the SEO here.

2023-12-04 11:24 UTC, eysi09 submitted a review, later dismissed

2023-12-04 15:24 UTC, eysi09 approved these changes

2023-12-04 15:53 UTC, merged