fix(cloud): ensure cloud project id is set on garden class
garden-io/garden pull request #5306
Opened 2023-10-26 23:54 UTC by eysi09

**What this PR does / why we need it**:

This commit fixes a regression introduced with:
https://github.com/garden-io/garden/pull/5291

That commit was just a tiny tweak to a couple of lines of code to improve error messages but actually ended up breaking the core <> cloud interaction for the community tier dashboard.

The underlying reason is the fact that this particular code was quite convoluted and not tested well enough.

So this commit refactors the cloud init logic to make it more readable and adds a handful of tests to prevent these kind of regressions from happening again.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-10-27 00:46 UTC, eysi09 commented on core/src/garden.ts
> +    // In general the project ID should be read from the cloud project but we
This feels odd but without this the tests for the analytics break.

2023-10-27 09:21 UTC, shumailxyz commented
Note: This must be merged before we do a release.

2023-10-27 12:41 UTC, shumailxyz commented
@eysi09 The tests are failing.

2023-10-31 18:37 UTC, eysi09 commented
Tests are passing now.

2023-10-31 21:01 UTC, mkhq requested changes

2023-10-31 21:01 UTC, mkhq commented on core/src/garden.ts
> +  if (isCommunityEdition) {
If the project ID is set in the config we should give precedence to that.

2023-11-01 08:55 UTC, eysi09 commented on core/src/cloud/api.ts
> +  async getProjectById(projectId: string) {
The types were wrong. It's never `undefined`, it always returns a `CloudProject`. 

So if we don't specify them but rather have the compiler infer them it won't break again this next time we update this function.

2023-11-01 09:01 UTC, eysi09 commented on core/src/garden.ts
> +  if (projectIdFromConfig && isCommunityEdition) {
Yeah I wasn't sure about this one. 

The reason I decided to fail fast is because before this change, Garden could actually use the wrong ID to fetch secrets on the community version which would just fail with confusing errors. 

If we allow it, it feels like we're creating more foot guns for now. 

There's nothing that documents the ability to set the ID and change the name and in general it feels like a complex hack we shouldn't point users to.

There's plenty of examples though of Garden configs with IDs, so I can imagine users on the community edition will bump into those and start adding them to their config when they don't really need it. And they'll be confused as to why some of their projects use IDs and others don't and what the overall purpose is. 

So I'd rather just fail fast or _for now_, and tell you, "Hey, you only need the ID on a commercial edition".

2023-11-01 09:03 UTC, eysi09 commented on core/src/garden.ts
> +  if (isCommunityEdition) {
See my comment above. 

If you agree we can keep this as is, otherwise I need to update this.

2023-11-01 09:04 UTC, eysi09 commented on core/src/garden.ts
> +  if (projectIdFromConfig && isCommunityEdition) {
....this also makes it one fewer code branches to worry about below.

2023-11-01 13:31 UTC, mkhq approved these changes

2023-11-01 13:42 UTC, mkhq commented on core/src/garden.ts
> +  if (projectIdFromConfig && isCommunityEdition) {
Ok, sounds good, lets keep this logic for now.

2023-11-01 15:22 UTC, merged