chore: restructuring util/util.ts (part 1)
garden-io/garden pull request #5435
Opened 2023-11-17 14:03 UTC by vvagaytsev

**What this PR does / why we need it**:
This is the continuation of the util-refactoring PR series started in #5431.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-11-17 14:06 UTC, vvagaytsev commented on core/test/unit/src/util/garden-cloud.ts
> +        // TODO: should we care about http/https here? Do we always get only https:// urls?
@mkhq @eysi09 any ideas here? Should we consider introducing a type for domains? (Maybe it's an overkill.) Can we get it as a template variable at some point?

Now we also accept garbage strings like `"aaabbbcc"`, for such ones this function will return `"Garden Enterprise"`.

2023-11-17 16:16 UTC, eysi09 requested changes

2023-11-17 16:16 UTC, eysi09 commented on core/src/util/garden-cloud.ts
> +/*
Can we just call this file `cloud.ts`, it's consistent with other cloud related filenames.

2023-11-17 16:16 UTC, eysi09 commented on core/test/unit/src/util/garden-cloud.ts
> +        // TODO: should we care about http/https here? Do we always get only https:// urls?
Can we use the URL library to construct a URL from the string and just read the hostname so that we don't need to worry about the protocol. 

It could just throw if the name isn't a valid hostname. It'd be a runtime error but we'd have runtime issues anyway if the hostname is bad.

2023-11-17 16:35 UTC, vvagaytsev commented on core/src/util/garden-cloud.ts
> +/*
Done in 28bd58bbe50d94e15346443fb6b1f0e11c8d7597.

2023-11-17 16:41 UTC, vvagaytsev commented on core/test/unit/src/util/garden-cloud.ts
> +        // TODO: should we care about http/https here? Do we always get only https:// urls?
@eysi09 thanks for the suggestion, sounds good!

I made a quickfix in d0e32f5365d5eaf0b7f356f949f9e924ff4090d5. That minimizes the semantic changes made in this PR.

Let's make a separate PR with improved URL validation and examination.

2023-11-20 12:37 UTC, eysi09 submitted a review, later dismissed

2023-11-23 17:41 UTC, eysi09 approved these changes

2023-11-23 18:04 UTC, merged