improvement(api): send action type to cloud
garden-io/garden pull request #5447
Opened 2023-11-20 13:19 UTC by eysi09

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-11-21 16:16 UTC, eysi09 commented on core/src/graph/actions.ts
> +      const depConfig = configsByKey[depKey]
Just FYI @thsig, this won't work. 

If the action depends on a module it won't be in that map and `depConfig` will be `undefined`. 

That's why the CI tests are failing.

2024-10-10 13:47 UTC, eysi09 commented on core/test/integ/src/plugins/kubernetes/kubernetes-type/handlers.ts
> +    garden.mergeModuleConfigs([withNamespace(nsModuleConfig, nsName)])
In the previous version these tests were actually not working right because when setting the module config here we replaced the actual module configs from the test projects. 

With this change we now merge the module config we're setting dynamically with the existing configs so that nothing gets overwritten.

2024-10-10 13:56 UTC, vvagaytsev approved these changes

2024-10-10 13:57 UTC, vvagaytsev requested changes

2024-10-10 13:57 UTC, vvagaytsev commented on core/src/util/testing.ts
> -  setWorkflowConfigs(workflowConfigs: WorkflowConfig[]) {
This caused multiple build errors in the tests.

2024-10-10 14:02 UTC, eysi09 commented on core/src/util/testing.ts
> -  setWorkflowConfigs(workflowConfigs: WorkflowConfig[]) {
Yeah my bad, it looked like nothing was depending on it but turns the LSP was just borking. Added it back.

2024-10-10 14:03 UTC, vvagaytsev approved these changes
👍

2024-10-10 14:46 UTC, merged