refactor(k8s): use faux SSH command to switch away from Mutagen fork (rebased)
garden-io/garden pull request #5551
Opened 2023-12-12 11:06 UTC by vvagaytsev

Garden currently uses a custom fork of Mutagen for its kubectl exec transport. This is the last remaining blocker to get Garden back on the official Mutagen releases.

At the moment, Mutagen doesn't support custom transports, but it does allow a custom ssh executable to be specified, which presents an opportunity for using a faux SSH command that calls down to kubectl exec using parameters smuggled through the SSH hostname specification. In this case, they are smuggled in a Base64-encoded JSON object (with some slight encoding tweaks to pass through Mutagen's local path detection heuristic).

The faux SSH implementation added in this commit will almost certainly be useable (with minor tweaks) as a custom transport implementation once support exists in Mutagen.

This commit is merely a DRAFT because it does not include a mechanism for distribution of this faux SSH command or computation of its storage location to specify via MUTAGEN_SSH_PATH.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2023-12-15 13:54 UTC, vvagaytsev commented
@xenoscopic I rebased #3102 on top of the latest main and tried out the faux SSH transport.

I used the path to the faux SSH executable binary as a value of `MUTAGEN_SSH_PATH`, was that correct? So the command I used was:
```console
# I compiled the `ssh.go` and moved it to `bin/` sub-directory
MUTAGEN_SSH_PATH="~/Repositories/garden/core/src/mutagen/faux-ssh/ssh/bin" gdev deploy --sync
```

That command failed with the error:
```console
Error: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to create agent command: unable to set up SSH invocation: unable to identify 'ssh' command: unable to query file metadata: stat /Users/vladimirvagaytsev/Repositories/garden/core/src/mutagen/faux-ssh/ssh/ssh: not a directory
```

I tried it with the latest Mutagen 0.17.4 and got the same error. I also tried to grant `777` permissions to the faux SSH binary itself and its parent directory, but that did not help.

Could you give any clue on that, please? Thank you!

2023-12-19 16:19 UTC, xenoscopic commented
Hey @vvagaytsev, sorry for the slow response - I believe the issue here is that you'll want to set `MUTAGEN_SSH_PATH` to the directory containing the faux `ssh` executable, not the path of the executable itself.

2023-12-20 08:48 UTC, vvagaytsev commented
Thank you @xenoscopic! Now it works!

2024-02-09 16:51 UTC, eysi09 requested changes
Had a handful of minor comments but otherwise looks great!

2024-02-09 16:51 UTC, eysi09 commented on core/src/mutagen.ts
> +  const warnMessage = `This version of Garden uses a new file syncing machinery.
Let's just use a normal `.` instead of `!!!`. 

Also, we need to actually explain _how_ you stop Mutagen processes.

Finally, we should avoid using the term Mutagen. Most Garden don't know (and shouldn't have to know) what Mutagen is. Instead we can say that you need to stop active syncs and explain how that's done.

2024-02-09 16:51 UTC, eysi09 commented on core/src/mutagen.ts
> +export const isNativeMutagenEnabled = () => !gardenEnv.GARDEN_ENABLE_LEGACY_SYNC
Do we need this function? 

The following is equally clear (if not clearer):

```
export const mutagenVersion = gardenEnv.GARDEN_ENABLE_LEGACY_SYNC ? mutagenVersionLegacy : mutagenVersionNative
```

This could also be wrapped into a function like `getMutagenVersion()`.

2024-02-09 16:51 UTC, eysi09 commented on core/src/mutagen.ts
> +async function getMutagenSshPath(log: Log): Promise<string | undefined> {
Can we add a doc string to this function explaining the different return values?

2024-02-09 16:51 UTC, eysi09 commented on core/src/mutagen.ts
> +    return undefined
This is a bit of a nitpick but I think we should return `null` instead of `undefined` here.

2024-02-12 08:34 UTC, vvagaytsev commented on core/src/mutagen.ts
> +async function getMutagenSshPath(log: Log): Promise<string | undefined> {
Added the comment in d835e425aca0824501f3b99ca4e93f0b9d15da50.

2024-02-12 08:44 UTC, vvagaytsev commented on core/src/mutagen.ts
> +    return undefined
That will cause some change in the interface `MutagenEnvValues` and the contract of the function `getMutagenEnv`.

Maybe, it's better to always require to pass sshPath explicitly be declaring it as `sshPath: string | null` instead of `sshPath?: string`. But we need to pass it only in a single place. The other calls to `getMutagenEnv` will have `null` or `undefined` value. That looks a bit awkward. That was the reason why the `sshPath` was introduced as an optional value of the `MutagenEnvValues`.

To be honest, I don't see a big semantic difference between `null` and `undefined` in this context. The `sshPath` must be defined only when we use the new sync machinery. Otherwise, it's not defined. So, it's undefined :)

2024-02-12 09:09 UTC, vvagaytsev commented on core/src/mutagen.ts
> +export const isNativeMutagenEnabled = () => !gardenEnv.GARDEN_ENABLE_LEGACY_SYNC
Inlined it in 03218996421ef18d831b637d50a9e35aca7d73c8. Also flipped some if-statements to avoid negated conditions, for better readability :)

2024-02-12 11:25 UTC, vvagaytsev commented on core/src/mutagen.ts
> +  const warnMessage = `This version of Garden uses a new file syncing machinery.
I made it simpler in 3350bbe7594e8ef94adaace8a524f383cecad611 :)
That would be the easiest way to shutdown the old sync machinery. Maybe we should put a similar instruction to the self-update command.

2024-02-12 11:25 UTC, vvagaytsev commented on core/src/mutagen.ts
> +export const isNativeMutagenEnabled = () => !gardenEnv.GARDEN_ENABLE_LEGACY_SYNC
The Mutagen version can be resolved statically. We can keep it as it is.

2024-02-12 20:02 UTC, vvagaytsev commented on core/src/mutagen.ts
> +              log.warn(
Thanks for the comments @eysi09! I'll make sure to address those tomorrow. Doc link would be the best option 👍 

Regarding the error throwing, it will be thrown after 5 retries anyway, it will not restart anything. So, it makes sense to do it immediately. Good point!

2024-02-13 09:06 UTC, vvagaytsev commented on core/src/mutagen.ts
> +              log.warn(
Changed this in 5873c505837fc520ee77ea23e26023e06b7f5ae3 and 24fa50899d1e2e41c9702b240ccf9032e381ba19.

I'll create a new PR to update the sync guide.

2024-02-16 14:16 UTC, vvagaytsev commented on core/src/mutagen.ts
> +              log.warn(
Added a troubleshooting section in d06e241d971796e60aa4d48ad2f4c18069105150.

2024-02-16 14:32 UTC, thsig commented on core/src/mutagen.ts
> +              log.warn(
> It looks like the underlying syncing machinery was switched
I'd suggest using slightly less colourful prose here, maybe something like:
> It looks like you've changed to a different version of the sync daemon [...] and therefore the sync daemon needs to be restarted.

2024-02-16 18:30 UTC, eysi09 requested changes

2024-02-16 18:30 UTC, eysi09 commented on core/src/mutagen.ts
> +                  makeDocsLink("misc/troubleshooting#restarting-sync-daemon")
This link is wrong and should point to the correction section of the code synchronization guide.

2024-02-19 08:59 UTC, vvagaytsev commented on core/src/mutagen.ts
> +                  makeDocsLink("misc/troubleshooting#restarting-sync-daemon")
Thanks! Fixed that in a81a033e48e5533836c3eb9055f2c6ce6dde34bc.

2024-02-19 08:59 UTC, vvagaytsev commented on core/src/mutagen.ts
> +              log.warn(
Thanks! I updated the message in a81a033e48e5533836c3eb9055f2c6ce6dde34bc.

2024-02-19 11:16 UTC, thsig approved these changes

2024-02-19 13:27 UTC, merged

2024-02-19 13:31 UTC, vvagaytsev commented
A follow-up PR is #5744.