feat(sync): deprecate non-interactive `sync start` and `stop` commands
garden-io/garden pull request #5747
Opened 2024-02-19 16:15 UTC by vvagaytsev

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2024-02-20 08:07 UTC, vvagaytsev commented
This PR addresses the [comment from #5733](https://github.com/garden-io/garden/pull/5733#issuecomment-1947426312).

2024-02-21 23:28 UTC, eysi09 requested changes

2024-02-21 23:28 UTC, eysi09 commented on core/src/commands/sync/sync-stop.ts
> +    if (!params.parentCommand) {
I think we should skip this.

We don't want users starting syncs outside of the dev console but the sync stop command can still make sense, e.g. if you need to manually stop them after a process crash.

2024-03-04 08:58 UTC, vvagaytsev commented on core/src/commands/sync/sync-stop.ts
> +    if (!params.parentCommand) {
Thanks! I removed this change.

2024-03-04 09:19 UTC, eysi09 approved these changes

2024-03-04 10:16 UTC, merged