feat(container): experimental cloudbuilder support
garden-io/garden pull request #5928
Opened 2024-04-11 15:28 UTC by stefreak

Experimental cloudbuilder support for test customers.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2024-04-11 16:09 UTC, stefreak commented on core/src/plugins/container/cloudbuilder.ts
> +        message: `Only allowed to call withBuilder if Cloud Builder is available. Must call shouldBuildInCloudBuilder before calling withBuilder.`,
```suggestion
        message: `Only allowed to call withBuilder if Cloud Builder is available. Must call isConfiguredAndAvailable before calling withBuilder.`,
```

2024-04-11 20:55 UTC, thsig reviewed
Great stuff! Just commenting for how since this is still marked as a draft.

2024-04-12 07:40 UTC, stefreak commented on core/src/cli/params.ts
> +  "cloudbuilder": new BooleanParameter({
I'll change this to an environment variable instead. It's slightly less nice, but it's also simpler and also does the job

2024-04-12 08:52 UTC, stefreak commented on core/src/plugins/container/cloudbuilder.ts
> +  async isConfiguredAndAvailable(ctx: PluginContext, action: Resolved<ContainerBuildAction>) {
Will solve this in separate PR. Created a linear issue

2024-04-12 08:53 UTC, stefreak commented on core/src/plugins/container/cloudbuilder.ts
> +const cloudBuilderAvailability = new LRUCache<CloudBuilderAvailability>({
Oh thanks for raising that. I'll use the same library we use in platform

2024-04-12 10:23 UTC, thsig submitted a review, later dismissed

2024-04-12 10:46 UTC, thsig submitted a review, later dismissed

2024-04-12 13:33 UTC, edvald commented on core/src/plugins/container/container.ts
> +      cloudbuilder: joi
```suggestion
      gardenCloudBuilder: joi
```

2024-04-12 17:53 UTC, stefreak commented on core/src/plugins/container/build.ts
> +    if (BUILDKIT_LAYER_REGEX.test(logLine)) {
This doesn't quite work in some cases:

```
✔ build.api-types           → Accelerated by Garden Cloud Builder (12/4 layers cached)
✔ build.api-types           → Done (took 5.6 sec)
ℹ build.frontend-dev        → Building frontend-dev (type container) at version v-d37aa82d25...
ℹ build.frontend-dev        → Building frontend-dev:v-59705ca12f...
✔ build.frontend            → Accelerated by Garden Cloud Builder (35/19 layers cached)
✔ build.frontend            → Done (took 5.8 sec)
```

We can either improve the logic, or remove it entirely, WDYT?

2024-04-15 11:55 UTC, stefreak commented on core/src/plugins/container/build.ts
> +    if (BUILDKIT_LAYER_REGEX.test(logLine)) {
fixed the regex. now the numbers look correct

2024-04-15 11:57 UTC, vvagaytsev commented on core/src/plugins/container/build.ts
> +    if (BUILDKIT_LAYER_REGEX.test(logLine)) {
Should we also use `\s` instead of ` `?

2024-04-15 12:31 UTC, vvagaytsev commented on core/src/plugins/container/build.ts
>      cwd: action.getBuildPath(),
Nit: `action.getBuild0Path()` can be replaced with `buildPath` that is already defined in [L112](https://github.com/garden-io/garden/pull/5928/files#diff-9908a5a1399edfb110bb66a430136f2b9c0a6350a1f48d19ccc8b859fd212173R112).

2024-04-15 12:39 UTC, vvagaytsev commented on core/src/plugins/container/cloudbuilder.ts
> +})
We might want to make this configurable in the future.
That's definitely not necessary in the first version. We can just put a TODO comment as a reminder.

2024-04-15 13:28 UTC, vvagaytsev commented on core/src/plugins/container/cloudbuilder.ts
> +  }
Should we use [`gardenEnv`](https://github.com/garden-io/garden/blob/main/core/src/constants.ts#L64) instead? It allows to have a type-safe boolean flag with a default value.

2024-04-15 13:43 UTC, vvagaytsev requested changes

2024-04-15 13:43 UTC, vvagaytsev commented on core/src/plugins/container/cloudbuilder.ts
> +  }
There it can be done like this:
```
GARDEN_CLOUDBUILDER: env.get("GARDEN_CLOUDBUILDER").required(false).default("false").asBool(),
```

2024-04-15 13:45 UTC, vvagaytsev commented on core/src/plugins/container/cloudbuilder.ts
> +  }
Should we use `GARDEN_CLOUD_BUILDER` for better readability? Somewhere use do use PascalCased `CloudBuilder` and camelCased `cloudBuilder`. It might be nicer to align the naming :)

2024-04-15 14:18 UTC, vvagaytsev commented on core/src/util/ext-tools.ts
> +  public name: string
We can also declare it as `readonly` to ensure it s immutability.

2024-04-15 14:20 UTC, vvagaytsev commented on core/src/util/ext-tools.ts
> +  public spec: PluginToolSpec
[Same](https://github.com/garden-io/garden/pull/5928/files#r1565878772) here, let's prevent mutability of the publicly exposed class fields that are not assumed to be writable.

2024-04-15 14:24 UTC, vvagaytsev commented on core/src/util/process.ts
>      })
Should we simplify this to be just `proc.on("exit", resolve)` like in the line above?

2024-04-15 14:28 UTC, vvagaytsev reviewed
Thank you! 💯 LGTM! 👍 
I left some comments, please ping me when it's ready for the re-review :)

2024-04-15 14:32 UTC, stefreak commented on core/src/util/ext-tools.ts
> +  public name: string
Great idea! It was soooo confusing that we mutated the `toolPath` in the concrete `PluginTool` class.

2024-04-15 14:36 UTC, stefreak commented on core/src/plugins/container/cloudbuilder.ts
> +  }
Thanks, changed this 👍

2024-04-15 14:39 UTC, stefreak commented on core/src/util/process.ts
>      })
We can do that, but that'd change the behaviour; Right now the `Promise` resolves to `void` and in your variant it'd resolve to whatever the `exit` event handler receives as first argument (Likely the exit code). I only added the `error` here as I noticed that in case of an error the Promise would never be resolved or rejected. The `error` event will pass the error itself to `reject` as first argument.

2024-04-15 14:55 UTC, vvagaytsev commented on core/src/plugins/container/cloudbuilder.ts
> +  // The env variable GARDEN_CLOUD_BUILDER can be used to override the cloudbuilder.enabled config setting.
The setting name seems to be `gardenCloudBuilder.enabled`.

2024-04-15 14:56 UTC, vvagaytsev commented on core/src/plugins/container/cloudbuilder.ts
> +export const cloudbuilder = {
Let's rename this to `cloudBuilder`.

2024-04-15 14:59 UTC, vvagaytsev commented on core/src/util/process.ts
>      })
Ah, right! Thanks for the explanation :)

2024-04-15 15:28 UTC, vvagaytsev approved these changes

2024-04-15 15:29 UTC, vvagaytsev commented
Thank you! 👍 The comments above are not critical and can be addressed in a follow-up PR.

2024-04-16 09:19 UTC, merged