Add an allowFailure field to WorkflowStepSpec
garden-io/garden pull request #6114
Opened 2024-05-31 04:18 UTC by alex-kattathra-johnson

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #6077

**Special notes for your reviewer**:

2024-05-31 13:31 UTC, stefreak commented
@alex-kattathra-johnson there seems to be a typescript error:
```
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  ../core/test/unit/src/commands/workflow.ts(74,43): error TS2322: Type 'true' is not assignable to type 'false'.
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  ../core/test/unit/src/commands/workflow.ts(75,32): error TS2322: Type 'true' is not assignable to type 'false'.
cli ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄  4:26:04 AM - Project '../sdk/tsconfig.json' can't be built because its dependency '../core' has errors
```
You'll need NodeJS 22.2 on your machine, and then you can run `npm install` and then `npm run check-all` to find typescript errors

Let us know on Discord in the #dev channel ifyou need any support setting your dev environment up. You can find the Discord link and further information about how to contribute here: https://github.com/garden-io/garden/blob/main/docs/contributing/README.md

2024-05-31 20:20 UTC, alex-kattathra-johnson commented
@stefreak: Got the errors resolved and the builds successful. Thank you!

2024-06-03 13:34 UTC, stefreak commented on core/test/unit/src/commands/workflow.ts
> +        steps: [{ script: "echo fail!; exit 1", allowFailure: true }],
@alex-kattathra-johnson thank you so much for the effort! Looking pretty good to me so far.

Looking at the code and the test cases I have one question: what behaviour would you expect for subsequent steps?

The behaviour of the current implementation would be that subsequent steps only run with `when: always` or `when: onError`, so configuring `allowFailure` does not have an effect on subsequent steps, only on the overall workflow success. If that's what we want, maybe it would be good to add a few words to the docs to clarify.

Can you also add test cases for subsequent steps, and update the docs at https://github.com/garden-io/garden/blob/main/docs/using-garden/workflows.md to mention the new `allowFailure` option?

Thank you so much! Great work ❤️

2024-06-03 13:35 UTC, stefreak commented on core/src/commands/workflow.ts
> +        shouldError = shouldError || !step.allowFailure
The comment was meant for the `continue` line, so let's keep them together
```suggestion
        shouldError = shouldError || !step.allowFailure
        // There may be succeeding steps with `when: onError` or `when: always`, so we continue.
```

2024-06-03 13:36 UTC, stefreak commented on core/src/commands/workflow.ts
> +        shouldError = shouldError || !step.allowFailure
It is more verbose, but I'd find this slightly more readable:
```suggestion
        if (!step.allowFailure) {
            shouldError = true
        }
```

2024-06-06 20:37 UTC, alex-kattathra-johnson commented
@stefreak : I've updated the PR based on the discussion from the issue. Could you please do another review when a chance is afforded?

2024-06-13 12:48 UTC, twelvemo requested changes
Great job on this! I think adding an `allowFailure` flag on a step is a great idea, however after a longer discussion @stefreak and I figured that in the current format the distinction between `onFailure` and `onError` is a bit difficult to understand. This is not due to your implementation, which is great. Some more suggestions on how to proceed in another comment soon.

2024-06-13 12:52 UTC, stefreak requested changes
@alex-kattathra-johnson Wow, great job, really amazing how you drilled down into the workflow code, and your code looks like it behaves exactly as proposed by @salotz in #6077

During deeper review @twelvemo and me took the time to think again about the user perspective, and while initially I thought adding `onFailure` is a good idea, it turns out to make workflows harder to explain and workflow code harder to read.

Our proposal is the following:
1. Let's go back to the older version of the PR where you only added `allowFailure` (And possibly rename that to `continueOnError`. Let's keep the added tests from the current version 👍 
2. Let's open an issue and postpone the `onFailure` handler to another PR; What we think might be ideal is something like the following, but implementation of that is too complex to shove it into this PR.
```
kind: Workflow
name: test
steps:
 - name: allowed_to_fail 
   script: this_will_fail
   continueOnError: true
 - if: ${steps.allowed_to_fail.outcome == "error"} 
   script: echo "Step 1 failed, let's clean it up"
```

2024-06-13 12:52 UTC, stefreak commented on core/src/commands/workflow.ts
>        // TODO: If any of the errors are not instanceof GardenError, we need to log the explanation (with bug report information, etc.)
In the code below, we get all the `stepErrors` and construct an error message explaining to the user why the workflow failed.

In the code above however, we always add the error to `stepErrors`, even if the workflow was allowed to continue.

2024-06-13 12:52 UTC, stefreak commented on core/src/config/workflow.ts
> +      .boolean()
We should add a default: 
```suggestion
      .boolean()
      .default(false)
```

2024-06-13 12:52 UTC, stefreak commented on core/src/config/workflow.ts
> +    allowFailure: joi
During deep review together with @twelvemo we noticed that it might be easier to explain / understand for a user if the flag name focuses on the behaviour in regards to the subsequent steps; We'd propose the name `continueOnError` with default being false.

2024-06-13 12:54 UTC, stefreak commented on core/src/commands/workflow.ts
>        // TODO: If any of the errors are not instanceof GardenError, we need to log the explanation (with bug report information, etc.)
For the next version of this PR: if `continueOnError` was `true`, then if we don't add the step error to `stepErrors`, then the error message will still be correct should there be any other error.

Otherwise users might be confused, as they are trying to solve an error that wasn't actually causing the workflow to fail.

2024-06-13 16:12 UTC, alex-kattathra-johnson commented
Sliced the PR with the Occam's razor! :)

2024-06-17 12:47 UTC, twelvemo approved these changes
Looks good! Thanks for taking the time to rework it again!

2024-06-18 13:20 UTC, stefreak approved these changes
@twelvemo and me made some additional changes to the logging and error handling behaviour. Looks good to go now, if the tests pass

2024-06-18 17:51 UTC, stefreak approved these changes

2024-06-18 18:30 UTC, merged