chore(cloudbuilder): add runtime information to build status events
garden-io/garden pull request #6153
Opened 2024-06-07 11:33 UTC by stefreak

Add runtime information to build status events, so we can display them
in the Cloud UI

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2024-06-10 10:24 UTC, 10ko approved these changes
Looks good to me, can @vvagaytsev or someone else (perhaps @eysi09 since you worked on this previusly) also take a look?

My only concern is the term "actual" might be slightly confusing but to be honest I cannot find a better term out of the top of my head, so if we agree on that, I am totally ok with it. :)

2024-06-10 10:35 UTC, twelvemo requested changes

2024-06-10 10:35 UTC, twelvemo commented on core/src/plugins/container/cloudbuilder.ts
> +      const unavailable = await getAvailability(ctx, action)
Does it really make sense to call `getAvailability` again here? It is also called by `cloudBuilder.isConfiguredAndAvailable`. The inconsistent state seems rather unlikely.

2024-06-10 11:09 UTC, stefreak commented on core/src/plugins/container/cloudbuilder.ts
> +      const unavailable = await getAvailability(ctx, action)
I agree this is confusing; It's needed to get `unavailable.reason`.

The availability will be cached in the LRUCache, because as you said we call it right before. The same thing happens when the plugin calls `withBuilder`; it calls `isConfiguredAndAvailable` before, for decision-making, and then `withBuilder` calls `getAvailability` again to retrieve the credentials from the availability response.

To make sure that we call `getAvailability` only once and pass the result as a parameter to `withBuilder` would require a thorough refactoring of the build handlers in the Kubernetes and container plugins.

2024-06-10 11:13 UTC, stefreak commented on core/src/plugins/container/cloudbuilder.ts
> +      const unavailable = await getAvailability(ctx, action)
Usually, we even call `isConfiguredAndAvailable` before `getActionRuntime` e.g. here: https://github.com/garden-io/garden/pull/6153/files#diff-9908a5a1399edfb110bb66a430136f2b9c0a6350a1f48d19ccc8b859fd212173R100

2024-06-10 11:41 UTC, twelvemo commented on core/src/plugins/container/cloudbuilder.ts
> +      const unavailable = await getAvailability(ctx, action)
I see, that makes sense. This is okay for me 👍

2024-06-10 11:41 UTC, twelvemo approved these changes

2024-06-11 09:14 UTC, eysi09 approved these changes
This looks good to me. Great work!

I think it's great in general to include the "runtime" with the action payload and we can add it for more kinds when we need them.

2024-06-11 09:50 UTC, merged