fix: reproduce symlinks in build staging correctly on windows
garden-io/garden pull request #6433
Opened 2024-09-12 18:17 UTC by stefreak

Unfortunately I mixed those up due to the confusing data structures in https://github.com/garden-io/garden/pull/6430

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2024-09-12 18:23 UTC, stefreak commented on core/src/build-staging/helpers.ts
> +          sourceStats.target?.isDirectory() ? "dir" : "file",
probably would have been less confusing if these parameters were named `fromStats` and `toStats` or something like that

2024-09-13 10:43 UTC, vvagaytsev commented on core/src/build-staging/helpers.ts
> +          sourceStats.target?.isDirectory() ? "dir" : "file",
Feel free to rename params to avoid confusion.

2024-09-13 10:45 UTC, vvagaytsev requested changes
There is a lint error. It complains about unused local variable `targetStats` from the params object defined in [L159](https://github.com/garden-io/garden/pull/6433/files#diff-35d7acac46ec199eb991f6b1296b6ae1d7a11ec53e57668afcb91a194a9cea00R159).

Do we need that variable here?

2024-09-17 16:49 UTC, stefreak commented
@vvagaytsev thanks, fixed the issue now, and refactored the code to make the variable names more clear.

2024-09-17 16:51 UTC, stefreak commented
@vvagaytsev the parameter has been added in #6430, but it was only due to the misleading name; It was actually correct to use `sourceStats.target` so the `sourceStats` parameter is indeed not necessary.

2024-09-17 16:51 UTC, vvagaytsev approved these changes
Thanks! 👍

2024-09-17 18:43 UTC, merged