improvement: make sure artifacts are always fetched
garden-io/garden pull request #6532
Opened 2024-10-11 09:25 UTC by 10ko

**What this PR does / why we need it**:

When executing `Run` or `Test` actions of type `exec`, we now always try to export the artifacts.
More specifically, we make sure to fetch artifacts in the case of:
- A `spec.command` failing with a non-zero exit code.
  - In this case we will only log an errror in case of failure while fetching artifacts.
- A `spec.command` throwing unexpectedly.
  - Same as above, only a warning.

In case the `spec.command` runs successfully and the fetching fails, we maintain the current behaviour of throwing an error.

This PR closes #6524

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2024-10-11 11:58 UTC, vvagaytsev commented on core/src/plugins/exec/test.ts
> +  if (runCommandErrors.length === 0) {
A minor non-blocking nit :)

This `if`-condition can be inverted, and the `else`-block can be then unwrapped. Thus, we'll have an error-check and throw immediately if any errors are there, and the errorless code branch will be outside a long `if`-block.

2024-10-11 11:58 UTC, vvagaytsev submitted a review, later dismissed
👍

2024-10-11 12:02 UTC, 10ko commented
Sorry I should have made it a draft. These changes do not account to all the use-cases unfortunately, since if the run command returns a non-zero exit code, it will not throw. So I am amending the code as we speak.

2024-10-11 12:31 UTC, 10ko commented
Good to go now, @vvagaytsev

2024-10-16 06:14 UTC, stefreak requested changes

2024-10-16 06:14 UTC, stefreak commented on core/src/plugins/exec/test.ts
> +  if (runCommandErrors.length === 0) {
@10ko you forgot to invert the condition (also at https://github.com/garden-io/garden/pull/6532/files#diff-fa98144b93cb2ad5871e8c16c14184f17a93eac35549d003bd0e239a134af471R59) 
```suggestion
  if (runCommandErrors.length) {
```

2024-10-16 06:14 UTC, stefreak commented on core/src/plugins/exec/run.ts
> +  const runCommandErrors: unknown[] = []
If there's always one element in the array, I think it's cleaner to use `let` here:
```suggestion
  let runCommandError: unknown | undefined
```

2024-10-17 09:24 UTC, 10ko commented on core/src/plugins/exec/run.ts
> +  const runCommandErrors: unknown[] = []
`runCommandErrors` is never reassigned, it will give you a type error if you use `let`.

2024-10-17 12:10 UTC, stefreak commented on core/src/plugins/exec/run.ts
> +  const runCommandErrors: unknown[] = []
it's never reassigned because you push an element to the array, but why use an array in the first place if it'll never have more than one element?

2024-10-17 12:12 UTC, 10ko commented on core/src/plugins/exec/run.ts
> +  const runCommandErrors: unknown[] = []
aaah, that's what you meant. Sorry didn't understand you from your first comment. Sure thing, that makes sense.

2024-10-17 12:21 UTC, stefreak commented on core/src/plugins/exec/run.ts
> +  const runCommandErrors: unknown[] = []
@10ko I've pushed a commit with the change I had in mind, does it look good to you?

2024-10-17 12:23 UTC, stefreak approved these changes
feel free to merge if you think my commit is ok 👍

2024-10-17 13:06 UTC, merged

2024-10-18 11:16 UTC, stefreak commented on core/src/plugins/exec/run.ts
> +  const runCommandErrors: unknown[] = []
No worries :D